### ISSUE TITLE
Build instructions don't work for me.

### ISSUE THREAD

**Issue by zackp30** [veloce/lichobile#10]
```
➤➤➤ android update project --target android-19 -p app -s
Error: app is not a valid project (AndroidManifest.xml not found).
```

**Comment by kuc** [comment]
I think that you must first run all commands from "Build the web application" part.

**Comment by veloce** [comment]
Sorry the readme is a bit outdated. I'm going to change the build tools soon and it should be more straightforward after.

**Comment by zackp30** [comment]
Ahh, thanks! :smile:

**Comment by mehdisadeghi** [comment]
I also tried a lot to find out how to run the project but after installing cordova and some other npm stuff I failed to get into something meaningful. So, just to say that I'm watching for your updates as well.

**Comment by zackp30** [comment]
@mehdisadeghi yeah, oops, should keep it open.

**Comment by veloce** [comment]
I updated the readme: see it in branch 1.3.x. It should contain all instructions to setup the project.
