### ISSUE TITLE
Puzzles stuck in Offline mode when data connection changes from WiFi to 4G

### ISSUE THREAD

**Issue by ssb22** [veloce/lichobile#1001]
On a Samsung Galaxy S9 running Android 9, when I started to solve a puzzle while connected to WiFi, and, with the puzzle still open, walked out of the WiFi area and the phone connected to 4G data, then finished the puzzle, then tapped the bottom-left Progress icon, the app told me I was offline, even though the phone's Chrome app was still able to reload lichess.org without trouble.  Quitting and restarting the app made it recognise it was online again, but I was not awarded any rating points for the puzzle I had solved while "offline".  (The puzzle had been loaded via the "Continue training" button and I didn't remember having seen it before.)

**Comment by kernc** [comment]
Duplicate of https://github.com/veloce/lichobile/issues/945.

**Comment by ssb22** [comment]
I'm not 100% convinced this is a duplicate, because #945 appears to be about a WiFi-only situation, whereas #1001 is about changing from WiFi to 4G mid-session.  Maybe the two issues have the same root cause, but without root-causing them I wouldn't know if they're duplicate.  But you know more than me ;-)

**Comment by landry314** [comment]
Well, is it still a problem, @ssb22 ? #945 was closed. Should this be closed too?

**Comment by ssb22** [comment]
Thanks, I have not been able to reproduce the issue with Version 7.2.0 of the Lichess app (although the device has now been upgraded to Android 10 but I don't expect that to be relevant).  I think this issue can be closed for now (unless anyone else still has this problem in which case it can be reopened I guess).
