### ISSUE TITLE
New Mobile App LOGO

### ISSUE THREAD

**Issue by debpedrano** [veloce/lichobile#1002]
Good day, I am a graphic designer and i have a design here that fits on your project. Just reply on this issue if you want the design.

**Comment by DarthFlappy** [comment]
I have the felling that you have not looked at lichess.org or https://lichess.org/about I recommend that you close this and waist the owner's time.

**Comment by dsjoerg** [comment]
Everything on this site is done for free but if you want to donate something please submit a PR!
