### ISSUE TITLE
Pawn wrongly eats another pawn (teleportation)

### ISSUE THREAD

**Issue by Reidea** [veloce/lichobile#1003]
I'm submitting a bug report.

[Video](https://youtu.be/HD0AwdDWp5w)

[Video: Steps to reproduce](https://youtu.be/NA1-j1nmDRM)

Device: Samsung Galaxy M20, Android 9, lichess v6.1.4 (Download from Google Play: lichess • Free Online Chess)

**Comment by niklasf** [comment]
This is a legal move and called "en passant". You can [learn about it on Lichess](https://lichess.org/learn#/15) or in the [Wikipedia article](https://en.wikipedia.org/wiki/En_passant).

**Comment by jubichan** [comment]
This happened to me too, and I thought it was a bug! Had no clue about this move 😅 well, the more you know!
