### ISSUE TITLE
Puzzle issue

### ISSUE THREAD

**Issue by Sssamatppap** [veloce/lichobile#1008]
Hello,

I have found a bug about mobile puzzles. If I use training mode on the website (by computer), and after I would like to continue that on my mobile app, I will get back the first puzzle from the website, what I already solved. These "re-puzzles" success don't change anything in your puzzle rating.

My phone is Samsung Galaxy J7 (2016) and the OS is Android 8.1.

**Comment by DarthFlappy** [comment]
Known issue, see #813

**Comment by DarthFlappy** [comment]
https://github.com/veloce/lichobile/pull/960 may be more helpful

**Comment by Sssamatppap** [comment]
Okey, thanks.
