### ISSUE TITLE
Back button issue

### ISSUE THREAD

**Issue by HBiSoft** [veloce/lichobile#1009]
**I'm submitting a bug report**

**Current behavior:**

Whenever I press the back button, the application is closed (no matter where I am inside the application).

**Expected behavior:**

When I press the back button it should go to the previous page. When I'm busy playing a game and I accidentally press the back button it should not exit out of the application.

**Steps to reproduce:**

Open a tournament, for example, then press the back button. Like I mentioned above, it doesn't matter on what page I am inside of the application.

**Environment information**

- Samsung J7 Pro
- Android 9
- Lichess 6.1.4

---
I think it's also worth mentioning - Yesterday I updated the app for the first time in about 4 months. This wasn't an issue before I updated.

**Comment by veloce** [comment]
I can reproduce this bug too (even though it does not happen all the time). Currently investigating.

**Comment by veloce** [comment]
The cause is probably: https://github.com/apache/cordova-android/issues/687

**Comment by freefal** [comment]
PR that I believe resolves this issue here: https://github.com/veloce/lichobile/pull/1022

**Comment by HBiSoft** [comment]
Fixed in the new update.
