### ISSUE TITLE
Blocked a player and cant follow him now.

### ISSUE THREAD

**Issue by hakarit** [veloce/lichobile#1010]
Hi there! 
Ich blocked a player by missclick and now i cant follow him anymore and i dont see him in my follower list. 
Is this a bug, or my fault?
Couldnt find a solution so. 

Mfg hakarit

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by ornicar** [comment]
unblock them

**Comment by veloce** [comment]
I'll try to fix this problem in the next release. In the meantime you can either retrieve the player from the app players search screen and unblock him. Or you could go to the website and see the list of blocked players.
