### ISSUE TITLE
Enpassant Bug ???

### ISSUE THREAD

**Issue by zeon2017** [veloce/lichobile#1013]
# Bug report

**Current behavior:**

Unable to use the chess move Enpassant, either the move is missing or bugged

**Expected behavior:**

If the pawn is pushed without attacking the opponent pawn, Enpassant move should me available to use

**Steps to reproduce:**

Try using the legal chess move Enpassant, where the opponent pushes to the next square instead of attacking a pawn using his pawn, Enpassant should come into play.

**Environment information**
- Moto G, 1 GB ram 
- Android 5.1
- Current version on date.

**Comment by ProgramFOX** [comment]
Working alright on my app. What position or move sequence did you have and were unable to move en passant?
