### ISSUE TITLE
Players' names clickable in zen mode

### ISSUE THREAD

**Issue by NKlug** [veloce/lichobile#1017]
**I'm submitting a bug report** 

# Bug report

**Current behavior:**
In zen mode, although the players' names and ratings are invisible, the fields are still clickable and show the "ratings" popup on click. Does not feel like intended to me.

**Expected behavior:**

The fields with the invisible names and ratings are not clickable

**Steps to reproduce:**

Enter a game in zen mode and click where the players' names are supposed to be.

**Environment information**

- One Plus 7 Pro
- Android 9
- lichess version 6.1.4

**Comment by Raffa2005** [comment]
I think that's a great feature that the name is still clickable in Zen-Mode. I sometimes use it if my opponent suggests draw in a difficult position. I hope it won't be changed
