### ISSUE TITLE
2018 iPad Pro aspect ratio

### ISSUE THREAD

**Issue by jarbus** [veloce/lichobile#1019]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**
Black Bars and lower resolution on iPad Pro 2018

**Expected behavior:**
Full screen with sharper lines

**Environment information**

iPadOS Beta 5, iPad Pro 2018, Lichess version 6.0.0

**Comment by Calinou** [comment]
@jarbus Was this fixed in a recent update? It'd be good to write a comment so we can be sure :slightly_smiling_face:

**Comment by jarbus** [comment]
> @jarbus Was this fixed in a recent update? It'd be good to write a comment so we can be sure 🙂

Indeed it was! Apologies for not commenting and I appreciate the work done on the app :)
