### ISSUE TITLE
Proper home page

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#102]
We need to get rid of the 'start board' home. It's confusing and useless.

We can replace it with:

* a tour
* a nice login page with also 'create a game', and 'play offline' buttons
* ... ideas?

**Comment by clarkerubber** [comment]
I'd have it follow suit with the lichess site. Perhaps populate it with a
list of currently available games with a couple of buttons below for
"Create a game" and "Play offline".

Login page might be a bit pushy on the "make an account please" front, and
a tour would lose its appeal pretty quickly.

**Comment by Evropi** [comment]
My suggestion has always been (as per #93) to show the sidebar menu sliding in, and display it.

Having the sidebar slide in establishes how the app is controlled (primarily via the sidebar, that is), and also offers immediate access to the all important sign-in, create a game, and offline play fuctions.

The animation must be there for my proposal to work, and I don't know if it can be executed on-demand when it loads.

**Comment by clarkerubber** [comment]
Even with the slide-in, the landing/homepage doesn't do anything. It's
still space that could be better occupied.

**Comment by Evropi** [comment]
I wouldn't want to replicate the same information or actions though. Furthermore, it's generally not good to have special one-time landing screens like that, especially if it's unclear how you can get to them again. It throws off a first time user forever, which is why I'm very concerned about including such pages.

If you were to have a 'home page', it would have to be something completely different. The only thing I can think of that fits these conditions is some form of help. Also, it has been established by that point how to do the main actions in the app, so the user should have no trouble picking up how to open that menu again (and slide-in is a very established mechanism of control).

**Comment by clarkerubber** [comment]
It's simple, the landing page replicates the Play page of the lichess
website, and you arrive at it similarly on the mobile app: List have a
button on the left slide in called "Play", which takes you to the homepage.
This homepage contains a list of available games, and two buttons: one to
play online, and the other to play OTB.

This will remove the New Game menu from the list of currently in play
games, but I think that the separate is acceptable, and it will bring the
OTB and Online play options closer together in one place: the landing page.

**Comment by Evropi** [comment]
The first paragraph makes the proposal more sensible.

However, removing the New game menu from the sidebar might be harmful. *Where would you start a new game from* while playing another, or while looking over a correspondence game? These are questions that must be considered.

**Comment by veloce** [comment]
I'm for a simple (but nicely designed) page with buttons to create a game, to play offline, and an invitation to login. Those who are connected are redirected to the most urgent game.

This page is indeed a landing page for those who are anonymous. And you won't find it again, except if you press back button on certain situations.

I find the sliding menu on opening weird. It's not what you expect of a menu (to fill the gap for a missing screen).

**Comment by veloce** [comment]
I reckon you were right from the beginning @Evropi . We'll show the opened menu for user who aren't signed in. It's the best idea since the home page is just a landing page indeed that should not be seen more than once, so why bother. 

To be done for 1.2.

**Comment by veloce** [comment]
Fixed in ead55a32f6457154f3389be93ce06e972da19b39
