### ISSUE TITLE
Update Android Settings Game behavior

### ISSUE THREAD

**Issue by KCErb** [veloce/lichobile#1020]
**I'm submitting a bug report**

# Bug report

**Current behavior:**

When I try to update any "game behavior" settings in android I get a simple toast "Error. Bad request". I can confirm by visiting lichess.org (or by hitting the back arrow and coming back into the game behavior menu) that the setting is not propagated to the backend.

**Expected behavior:**

Updating game behavior settings on the app should update them on the server.

**Steps to reproduce:**

1. Select the hamburger menu in the top left on Android (7.0 NRD90M).
2. Scroll to bottom, selecting "Settings".
3. Select "Game behavior"
4. Update any setting.
5. You'll see a toast "Error. Bad Request" but the UI will update as if the update was successful.
6. If you check the setting on lichess.org or if you select the left-pointing arrow in the top-left corner and re-enter the "Settings > Game behavior" area you'll see that the setting is the same as before.

**Environment information**

- phone hardware: Redmi, Redmi Note 4
- phone operating system version: MIUI Global 10.2 | Stable. 10.2.3.0(NCFMIXM)
- android version: 7.0 NRD()M
- android security patch level: 2018-12-01
- version of lichess mobile: 6.1.4

**Comment by freefal** [comment]
Thanks for the clear bug report.

This is resolved here: https://github.com/veloce/lichobile/pull/1021.

It will get merged into the main repo and then published in the next release.

**Comment by KCErb** [comment]
Awesome, thanks!
