### ISSUE TITLE
California piece set on the site, but not in the app.

### ISSUE THREAD

**Issue by pullup** [veloce/lichobile#1026]
**I'm submitting a ...**  (keep the relevant one):
**- feature request**
# Feature request

Add the California piece set to app please so that everything can look the same between devices <3

**Comment by Brottweiler** [comment]
I noticed this set is missing and also a couple of others; `gioco` and `icpieces`.

Then I noticed that there is a set called `alpha` in the app that I can't find on the site.

**Comment by SteveEricJordan** [comment]
Yes, please add california to the app, exactly the one i´m using is missing in the app.
