### ISSUE TITLE
Integrate offline games better

### ISSUE THREAD

**Issue by tobiasvl** [veloce/lichobile#103]
Currently, offline games are completely separate from online games that are played on the server, but it would be nice if those were unified somehow, so you could have more than one at the same time, etc.

Suggestion: Store more than one offline game at a time, and list offline games together with the online games, visually distinct somehow.

If #99 is implemented, pause the clock automatically while the game is not open.

**Comment by clarkerubber** [comment]
This would likely be carried out using the Import functionality of the site
once the game completes.

**Comment by veloce** [comment]
Now you have a PGN share button, so I'm closing this.
