### ISSUE TITLE
App v6.2.0 crashes when analyzing with Stockfish

### ISSUE THREAD

**Issue by Harschism** [veloce/lichobile#1032]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**
The iOS lichess app (v6.2.0) crashes when I try to analyze a game with the internal Stockfish engine.

**Environment information**

- phone hardware: iPhone 6S+ and iPhone SE
- phone operating system version: iOS 12.4.1
- version of lichess mobile v6.2.0

**Comment by bonobo1** [comment]
This happens on Android as well.
Problem description:
After a game click on 'Learn from your mistakes'.
Making the wrong move will result in an endless loop for evaluating the move.
Phone: Samsung Galaxy S7 edge
Android 8.0.0

**Comment by Whiner54** [comment]
I’m using an iPad Pro 9.7”.
I have the same issue when I am analyzing moves.
This started right after v6.2.0 as well.

**Comment by Whiner54** [comment]
This is not fixed. The game still locks up randomly while analyzing a game. It happens as soon as a move is selected.
