### ISSUE TITLE
Please remove the notification bell sound

### ISSUE THREAD

**Issue by MDScar** [veloce/lichobile#1043]
**I'm submitting a ...**  (keep the relevant one):
- feature request

# Feature request

- Please remove the annoying notification bell sound which occurs on the Android app after I play a move.  I like the subtle classic chess move sound, but the new notification bell is annoying -- so much so that I was forced to downgrade my app version.
- This request should be implemented because the sound is both annoying and the use case is silly -- why on Earth would any user need a notification sound after the user himself takes an action?  It might make sense if the notification sound occured when the opponent moved, but even then this current default bell is so annoying I would want it disabled entirely if the sound could not be customized or there was no way in-app to reduce its loudness.  The simple classic chess piece move sounds would be enough for me.

**Comment by landry314** [comment]
I absolutely agree. I had to disable sounds altogether because of this loud and annoying confirmation chime.

**Comment by veloce** [comment]
It's the same sound as in the website, and it is only in corres. games thus I won't disable it. I lowered it to be less annoying.

**Comment by MDScar** [comment]
Thanks, veloce.  But, with this sound in the game, I will be forced to remain at version 6.1.3

Love the app, generally though. All of your efforts are greatly appreciated!

**Comment by veloce** [comment]
So I guess you use move confirmation on every game, right? What time control do you play with, by curiosity?

**Comment by veloce** [comment]
I realize that this feature can be used with real time games too. So you're right that it should work well with both usage (correspondence and real time). I'll see what I can do about it (about the delay too).

**Comment by MDScar** [comment]
Hi, @veloce

I do use move confirmation on all of my games.  Rapid games are probably my most played.

There might be ways to tweak the UI so that misclicks are more easily avoided, but.... I'm not sure that's possible.  I decided to accept more lose-on-time outcomes rather than lose-on-misclicks.
