### ISSUE TITLE
Move submission appears notably less responsive

### ISSUE THREAD

**Issue by MDScar** [veloce/lichobile#1047]
**I'm submitting a ...**  (keep the relevant one):
- feature request

# Feature request

EVALUATE VER 6.2.0 MOVE PROCESSING

In upgrading from ver 6.1.3 to 6.2.0 on Android, there came a number of UI tweaks.  One change is that there is a "Loading" spinner after each move now.

It's possible that this spinner simply more accurately reflects the background processing required for every move, but the length of the delay feels longer than in previous versions.

If there have been client-side changes that cause the Android app to process moves more slowly, please create tickets to optimize the code.

Whether moves actually are being processed more slowly or not, the modal Spinner element is not ideal.  Such a spinner could exist a s a small element next to the player clock or something, rather than being a modal.

**Comment by veloce** [comment]
Well move confirmation is designed at first for correspondence (and why not slow games) so I don't think this delay is problematic. The added value to this change is the server confirmation that the move was received and processed (when you hear the sound and the modal disappear). Before you could have a network problem and think the move was sent where it was not.

**Comment by MDScar** [comment]
@veloce The spinner modal is unnecessarily distracting.  To be brutally honest, dimming the screen and obstructing the view of the board after EVERY MOVE is bad UI design.
