### ISSUE TITLE
Add Some Indication After A Game If The Other Player Has Moved On

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1052]
- Feature Request

In the Lichess Android app, after a game has finished, it is unclear whether or not the other user has started a new game or closed the app or is still looking at the game or in the chat.

If I want to communicate to the other player about the game after it has finished, I risk wasting my time writing a message he will never see. What I do currently is I tap on the menu then see if the "Rematch" button is grayed out. If it isn't then the player is still around and I write a message. Still, he could leave before my message is done and, still, I would be wasting time.

I suggest an indication is placed in the chat window that says if the player is still around. Maybe it could be italic text inline which says "The other player is no longer here" or something else like an indicator or a change of color or something...

By the way, implementing issue #942 would help solve this as well because the other player would still get what is written in the chat even though he has left. It would be in his inbox.

**Comment by freefal** [comment]
The icon next to your opponent's name will turn green when he's in the game and gray when he is not.

**Comment by landry314** [comment]
would you look at that!

well, maybe grey would be better as another color like red... grey is an overlooked color...
