### ISSUE TITLE
Traning synchronization problem

### ISSUE THREAD

**Issue by bisherbas** [veloce/lichobile#1061]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

I have the app installed both on my iPad and Android phone OnePlus 5T. My progress on one device is not reflected on the other one. Therefore, if I switch from my phone to my iPad, I end up redoing all of the same trainings which I had already completed on my phone. In other words two devices are not synced.

**Expected behavior:**

Two devices should be synced for training

**Steps to reproduce:**

1. Make some training progress on smartphone
2. Switch to iPad and same puzzles are showing instead of the latest one showing on the phone

**Environment information**

OnePlus 5T, Oxygen OS 9.0
iPad 6, iOS 13.1
Lichess v6.2.0

**Other information:**

None.

**Comment by veloce** [comment]
Sorry but device synchronisation is just not a feature right now. And we don't have any plan to implement it in a next future.

**Comment by bisherbas** [comment]
Oh, ok
 Thanks
