### ISSUE TITLE
Please continue supporting old devices.

### ISSUE THREAD

**Issue by misha-franz** [veloce/lichobile#1064]
Please keep releasing android4.4-release.apk.

**Comment by AdityaMH** [comment]
My Kitkat phone don't support latest 4.4 release either.

**Comment by Delgan** [comment]
The unavailability on Android 4.4 seems recent. Could this possibly be reverted or is it required in order to bring new features?

**Comment by AdityaMH** [comment]
Not new features, but add support again for android kitkat in latest version.

**Comment by AdityaMH** [comment]
so where i can found that file?
