### ISSUE TITLE
imported games player names are missing

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#1067]
> when I choose User Menu>Profile>Games>Games Played >Imported Games in the latest version of the app, the names of both the Black and White players in every game listed shows up as  "Anonymous".
> When I choose an actual game, the real names are there, but it is impossible to know who the player is from the games list. The same problem does not exist when I log on to lichess with a browser. Look forward to a fix soon.

**Comment by freefal** [comment]
PR here: https://github.com/veloce/lichobile/pull/1069
