### ISSUE TITLE
Can't start a game when in anonymous mode

### ISSUE THREAD

**Issue by arimourao** [veloce/lichobile#1071]
- bug report

**Current behavior:**

Can't start a game when in anonymous mode through the "Create a game" button in the drawer.
The spinner supposedly to show the pairing, shows that it is seeking a rated game under the user defined options, which is impossible when anonymous. Just an "Error" message pops up, like in the ss attached. 

The only way to start a new game is through the "Quick setup" tab in home page.
  
**Expected behavior:**

It should pair with an another casual game

- phone hardware: Motorola X2
- phone operating system version: Android 8
- version of lichess mobile: 6.3.0

![index(2)](https://user-images.githubusercontent.com/7979806/67254995-485e1180-f456-11e9-8377-20e05e6e9c28.jpg)

**Comment by ornicar** [comment]
I logged off, created a 2+2 game (ensuring I don't get paired in an existing pool), and proceeded to play a game.

v6.3.0
samsung galaxy a8
android 9

**Comment by arimourao** [comment]
I noticed a recent update fixed this bug. Thanks.
