### ISSUE TITLE
v6.3.0  Enable local comp eval 

### ISSUE THREAD

**Issue by RedAir0** [veloce/lichobile#1073]
LiChess Android version 6.3.0 :
the following options disappeared in the 'study' / settings tab:

Enable local computer evaluation
Infinite analysis
Analysis lines
Processor Cores

**Comment by jas14** [comment]
I believe this is being brought back in 7.0.0, see 802f2699ab7740c5cf92c93be8417b1806172fc1 and the attached screenshot:

![infinite_analysis](https://user-images.githubusercontent.com/569991/71328097-e877fb80-24d6-11ea-9800-4d83e814c0f6.png)

**Comment by veloce** [comment]
Some studies have local eval disabled.
