### ISSUE TITLE
Play with real money

### ISSUE THREAD

**Issue by Ehsynli** [veloce/lichobile#1080]
**I'm submitting a ...**  (keep the relevant one):

# Feature request

- We can add money (USD or sth) to our accounts and play for real money.
- As we know Chess is not making masters earn more. They will come here to earn money online.
- Even low Rating players can pay for playing with GrandMasters

**Comment by freefal** [comment]
The trouble with playing for money is cheating. Lichess already battles a great deal of cheating despite the lack of any obvious reward for doing so. Adding money, will make the problem much worse.
