### ISSUE TITLE
En passant capture of the Queen (possibly pieces other than pawn) 

### ISSUE THREAD

**Issue by cobnex** [veloce/lichobile#1081]
I'm reporting a bug I noticed when playing against the computer on mobile app. 

There was a En Passant capture of a Queen. The En Passant should only be allowed for the capture of pawns. 

I believe there is no verification of the type of piece that moved two squares from the starting line of pawns. 

I attached screenshots with the moves so it can be easier to reproduce.

**Comment by cobnex** [comment]
![IMG_20191112_132148](https://user-images.githubusercontent.com/57653705/68644578-65b36680-0550-11ea-81a2-3de2f5ae1322.jpg)

**Comment by cobnex** [comment]
![IMG_20191112_132214](https://user-images.githubusercontent.com/57653705/68644608-8085db00-0550-11ea-9c03-ba76a405fc2a.jpg)

**Comment by cobnex** [comment]
![IMG_20191112_132243](https://user-images.githubusercontent.com/57653705/68644620-8ed3f700-0550-11ea-9e03-585e2b4c3e96.jpg)

**Comment by niklasf** [comment]
FEN: r4rk1/pp1bbppp/8/nNq5/3ppPn1/7N/PPPPQ2P/R1B1KB1R w KQ -

Couldn't reproduce.

**Comment by cobnex** [comment]
Yeah, me neither, I tried to reproduce in several ways and wasn't able to see it again. I'll close y the case and reopen in case I see it again.
