### ISSUE TITLE
Feature Request: Play Chess With the Cam

### ISSUE THREAD

**Issue by WolfgangFahl** [veloce/lichobile#1088]
**I'm submitting a feature request**  

# Feature request
Playing chess using a physical board and recognizing the pieces with the cam should be supported.

See http://wiki.bitplan.com/index.php/PlayChessWithAWebCam/Papers for different attempts that haven been made out there as well as http://wiki.bitplan.com/index.php/PlayChessWithAWebCam 

for the prototype i am working on.
My code is in alpha but I'm willing to share my results. 

**Assumptions**
It's assumed that a hobbiest chess player:

- will follow the [chess rules](https://en.wikipedia.org/wiki/Rules_of_chess) and roughly follow the [FIDE tournament rules]( https://www.fide.com/FIDE/handbook/Standards_of_Chess_Equipment_and_tournament_venue.pdf).

-  play at a regular speed
- own a decent chessboard e.g. a tournament board and tournament pieces
- own a high resolution webcam or smartphone with cam
-  have access to the internet 
- use a display device with a resolution that will be able to display the relevant information:
--   camera picture of own/opponents board
--   standardized picture of chess position
--   optional: FEN, PGN and time
--   optional: camera picture of other player / own camera picture
--   Lighting conditions can be kept stable and checked for suitabiltiy in advance

Please note that these needs also apply for most of the chess robot usecase

**Comment by WolfgangFahl** [comment]
see https://stackoverflow.com/questions/54983696/can-i-transfer-data-between-a-cordova-android-app-an-embedded-device-chess-bo

**Comment by ornicar** [comment]
Pretty much all the asumptions above are wrong.

**Comment by WolfgangFahl** [comment]
I assume you mean "statistically wrong" that is  the assumptions are only true in a small number of usecases. How could we find out the real distribution?

**Comment by ornicar** [comment]
This is well outside the scope of lichobile.
