### ISSUE TITLE
No notifications on iOS

### ISSUE THREAD

**Issue by run-after** [veloce/lichobile#1096]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

No longer receiving notifications on iOS app

**Expected behavior:**

Received notifications whenever it’s my tooth or game over or draw etc

**Steps to reproduce:**
Playing?

**Environment information**

- phone hardware - iphone se
- phone operating system version - 13.1.3
- version of lichess - 6.3.0

**Comment by jonathanhurd** [comment]
Same deal, iPhone 11, iOS 13.1.3, lichess 6.3.0

**Comment by thisbailiwick** [comment]
I was noticing this too, but I did just get one. Can't say I've changed anything setting wise since day before yesterday when I was trying to fix this.
iPhone 8 Plus
iOS 13.2.3
Lichess 6.3.0
