### ISSUE TITLE
Can’t open players profiles from search results

### ISSUE THREAD

**Issue by hluup** [veloce/lichobile#1099]
**I'm submitting a:**
- bug report

# Bug report

**Current behavior:**
When clicking a username in players search results, app closes unexpectedly.

**Expected behavior:**
When clicking a username in players search results I should be taken to the corresponding profile.

**Steps to reproduce:**
* Click players
* Click on a magnifying glass 
* Search for any name
* Click on a name amongst the results

**Environment information**
* iPhone 7 & iPad (5th generation)
* iOS 13.1.3 & iPadOS 13.3
* lichess 6.3.0

**Comment by jas14** [comment]
Cannot repro on Android, lichobile v6.3.0

**Comment by hluup** [comment]
Seems to be iOS specific.

**Comment by veloce** [comment]
Cannot reproduce.
