### ISSUE TITLE
Castling impossible

### ISSUE THREAD

**Issue by Anonjmous** [veloce/lichobile#1102]
Hi, 

Can you tell me if this looks regular to you?

https://lichess.org/training/100541

Please, notice that the f5 bishop covers the b1 square. 

Thanks for your help/answer.

Best regards.

**Comment by niklasf** [comment]
The *king* cannot pass through attacked squares, the rook can. You can practice the rules here: https://lichess.org/learn#/14/9

**Comment by Anonjmous** [comment]
Thank you.
I checked before, but nothing was written about that.

Have a nice day.

Le sam. 28 déc. 2019 14:51, Thibault Duplessis <notifications@github.com> a
écrit :
