### ISSUE TITLE
On iPhone, chat messages no longer visible after send

### ISSUE THREAD

**Issue by adaddeo** [veloce/lichobile#1103]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**
After sending a message, the chat screen no longer becomes mostly blocked and not visible.

**Expected behavior:**
After sending a message, the chat screen should show the sent message (and any previous messages).

**Steps to reproduce:**
Within a game:
1. Open the messenger screen
2. Enter text into the input (I used the string "test")
3. Click the send icon
4. Screen becomes blocked

**Environment information**
- phone hardware: 11 pro max
- phone operating system version: iOS 13.3
- version of lichess mobile: 6.3

![signal-2019-12-28-125410](https://user-images.githubusercontent.com/1143517/71548509-d41f7d00-2974-11ea-8921-c4e3ef391279.png)
![signal-2019-12-28-125433](https://user-images.githubusercontent.com/1143517/71548510-d4b81380-2974-11ea-849b-14e83b76c3c9.png)

**Comment by slayernn** [comment]
Worst chat in app ever
