### ISSUE TITLE
App crashes when i search players

### ISSUE THREAD

**Issue by slayernn** [veloce/lichobile#1107]
Bug Report
Can’t normally search profiles, app crashes.

1 Go to players
2 Set online/all
3 search “mark”
4 view profiles before crash
On my phone crashed after 2-3 viewed profiles (markp, marks)

phone hardware : iPhone 6s A1688
phone operating system version : iOS 13.2.3/13.3
version of lichess mobile : 6.3.0 and older

**Comment by GiovanniSalmeri** [comment]
I confirm the same bug with iPhone XR, iOS 13.3, latest version of lichess mobile.
In this configuration the app crashes immediately, doesn't allow to view any profile.

**Comment by hluup** [comment]
Same bug as this? #1099

**Comment by slayernn** [comment]
> Same bug as this? #1099
I think yes
