### ISSUE TITLE
Remove links to browsers in kid mode

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#1110]
on some devices it might be the only way to open a browser, because it has been disallowed everywhere else.

Remove links like "More on lichess" when kid mode is enabled.

**Comment by lakinwecker** [comment]
Better yet, remove the built-in browser.  I've never understood it's point even in non-kid mode

**Comment by lakinwecker** [comment]
What I mean by this is that we should configure it so that all external links should be opened in the phone browser.
