### ISSUE TITLE
activating kid mode gives only error message

### ISSUE THREAD

**Issue by david-hil** [veloce/lichobile#1114]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**
When trying to activate kid mode you get a toast saying "Error.". Seemingly, nothing changes. When I open the settings again, the toggle is off again.

**Expected behavior:**

Clicking on kid mode should activate the kid mode, as described in the text above the toggle switch

**Steps to reproduce:**

Open user menu -> settings -> kid mode. Click on the switch. Observe nothing changing besides the "Error." toast.

**Environment information**

- phone hardware: Huawei Mate 10 lite
- phone operating system version: Android 8.0.0
- version of lichess mobile: 6.3.0

**Other information:**

It works fine on the website, so the issue seems to be the app

**Comment by veloce** [comment]
that's a BC break which is currently fixed on master, but you'll have to wait for the new release
