### ISSUE TITLE
Hello, after app update home page is not working correctly. The screen stuck on loading and i can't choose random rated game. Im using xiaomi mi mix 2.

### ISSUE THREAD

**Issue by forteuropa** [veloce/lichobile#1123]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by veloce** [comment]
You can try to clear the app cache.

**Comment by forteuropa** [comment]
Yes that helped, thanks.

На пт, 7.02.2020 г., 12:05 ч. Vincent Velociter <notifications@github.com>
написа:
