### ISSUE TITLE
New games are not loaded

### ISSUE THREAD

**Issue by arnulfholm** [veloce/lichobile#1127]
I'm submitting a bug report
# Bug report

**Current behavior:**
When I start a game, I can hear the "game ready" sound, but I only see the board. There are no pieces on the board. And on the top the loading circles keeps loading. 

**Expected behavior:**
I'm expecting to be able to play the game.

**Steps to reproduce:**
1. Create new game
2. That is it

**Environment information**
iPhone 8
iOS 13.3.1 (didn't work on 13.3.0, so upgrading to see if that would help)
v7.0.0
![IMG_6030](https://user-images.githubusercontent.com/1655093/74023579-45087a80-49a0-11ea-8a43-25ef0931f1e0.png)

**Comment by arnulfholm** [comment]
Found the error. 
It happens when vibration is toggled on.
Settings -> Sounds -> Vibrate on game events

**Comment by veloce** [comment]
Wha! Thanks for finding this.

**Comment by veloce** [comment]
Fixed: https://github.com/veloce/lichobile/commit/ac6127507bb792eccb05181f3bde6bf5473c54ad
