### ISSUE TITLE
Opponents moved but it is not seen in mobile

### ISSUE THREAD

**Issue by luqmanrom** [veloce/lichobile#113]
I attached this two pictures. I thought I won by time, but it was actually i did not get the last opponent move on my mobile. I am not sure why. Internet connection was fine. I had clear checkmate sequence though. But I lost due to the bugs :(

![screen shot 2015-02-18 at 12 51 40 am](https://cloud.githubusercontent.com/assets/6434819/6243497/5e5313a4-b708-11e4-8547-96aa8f0218be.png)

![screenshot_2015-02-18-00-46-14](https://cloud.githubusercontent.com/assets/6434819/6243510/7d667538-b708-11e4-80e6-5c6ef3147567.png)

**Comment by veloce** [comment]
Not sure to understand what's going on here. I don't see a position difference between mobile and desktop. So what was the last opponent move?

**Comment by clarkerubber** [comment]
The difference is the discrepancy in the clocks.

On Thu, Feb 19, 2015 at 2:58 AM, Vincent Velociter <notifications@github.com

**Comment by luqmanrom** [comment]
Yes. Notice the clocks. Thanks. You guys doing great job anyways!

**Comment by ornicar** [comment]
Looks like the clock event was not applied. May or may not be fixed by https://github.com/veloce/lichobile/commit/51737d604cd2bc2c6fe4eb7cf2145149448c114c

Please report if it happens again after we release 1.0.2.
