### ISSUE TITLE
Can’t push the button

### ISSUE THREAD

**Issue by rostovsales** [veloce/lichobile#1133]
Than opponent goes offline i can’t get the win by pushing button. Than i push the modal window just close
video with problem https://vimeo.com/390499083/description

iphone6s

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by ZeChArtiahSaher** [comment]
Can confirm, this bug occurs on iphone 6s ios 12.1.4 as well with all modal windows. Can't resign, add time, control analysis settings, etc...
