### ISSUE TITLE
Share Game URL ios

### ISSUE THREAD

**Issue by d8reptile** [veloce/lichobile#1134]
**I'm submitting a bug report

# Bug report

**Current behavior: After completing a game and attempting to share the game URL on iOS, pressing the share game url does nothing**

**Expected behavior: the game url should be created with the ability to share or copy**

**Steps to reproduce: complete game -> menu -> share -> share game url**

**Environment information**

iPhone 11, current iOS 
This started happening after most recent lichess update where the icon graphic changed. Version 7.0.0

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by freefal** [comment]
Confirmed.

**Comment by yatzy** [comment]
Also happens on Android

**Comment by veloce** [comment]
yes, fixed https://github.com/veloce/lichobile/commit/5f1074e3f6b2ee49fbdb0eebe451975925d58075
