### ISSUE TITLE
Recent update has broken suggested moves in analysis mode

### ISSUE THREAD

**Issue by aleith** [veloce/lichobile#1135]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**In *analysis mode* the iOS app fails to show best move arrows (blue and green suggestion arrows) and the calculated player advantage score (+/-n or #n). This is not working at all since I updated to Lichess v7.0.0**

**Stockfish generates best move suggestions indicated with blue (current player) and green (previous players better move) arrows. Stockfish calculates score advantage to either player**

Without the bug you will see these arrows in any situation during the game play in analysis mode. Even at checkmate or stalemate you will see the score, but no blue arrow for next best move for current players move. 

Occasionally these arrows appear when one is in analysts mode, but it never lasts for more than one move at a time. And seems to be related to start position of the puzzle if one has come from a puzzle (usually this is where I use analysais mode the most to see what I’ve missed when I get a puzzle wrong and then after I’ve found the correct solution but don’t understand it). 

**Steps to reproduce:**

From a completed puzzle or past game click the analysis button below the playing board. 

**Environment information**

- iPhone XS Max
- iOS 
- version 7.0.0

**Other information:**

In previous versions of the iOS app I noticed that under certain particular circumstances move suggestions would not appear. These were usually when a move was played that put the opponents king was in check. Then only legal move squares would appear, not best move suggestions. This may be a clue as to why it isn’t working much at all now.

**Comment by freefal** [comment]
I tried this on v7.0.1 of the app on the iPhone 8 and could not reproduce.

**Comment by aleith** [comment]
I realised that the new install reset the setting that switches this function on and off. The settings are available from the "cog" icon at the bottom of analysis mode screen. The setting in question is "Toggle local evaluation".

For some reason the arrows do occasionally get drawn on the board when local evaluation is turned off.  

The great news is this version fixed an annoying issue/bug that suggested moves didn't appear when a  King was in check. Now it draws best move(s) arrows!
