### ISSUE TITLE
Duplicate push notifications

### ISSUE THREAD

**Issue by lazerwalker** [veloce/lichobile#1139]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

When an opponent makes a move, I get two identical push notifications in quick succession on the same device

**Expected behavior:**

I should only get one push notif per move!

**Steps to reproduce:**

Have notifications enabled. Start a game with someone. Have them make a move.

**Environment information**

- iPhone 11 Pro
- iOS 13.3.1
- v7.0.0

**Other information:**

Let me know if there's identifying information I can provide about my account if that's helpful to debug.

**Comment by bsamseth** [comment]
I can confirm this also happens on the latest release (as of Feb. 12 2020).

* iPhone X
* iOS 13.3.1
* __v7.0.1__

In addition to duplicate notifications, the red badge on the app icon shows more than it should. For instance, right now it says 6 (it should say 1).

**Comment by bsamseth** [comment]
I also want to mention that I've noticed that the red notification counter badge has been steadily rising each time I get a new notification. I'm at 42 (still only one "real" notification).

**Comment by veloce** [comment]
Fixed in 7.0.3
