### ISSUE TITLE
Share URL button not working

### ISSUE THREAD

**Issue by mqll** [veloce/lichobile#1140]
**I'm submitting a ...**  
-# Bug report

**Current Behavior**

The “Share Game URL” button is not working. Nothing happens when the button is pressed 

**Expected behavior:**

Previously (the previous version of the app) the button brought up the iPhone sharing screen where you can directly text, airdrop, mail, Facebook, etc or simply copy the url to share elsewhere. 

**Steps to reproduce:**

Open any game in the app, whether just recently played or an older one

Press the hamburger button on the bottom left of the screen

Press the “Share” button

The “Share game URL” and “Share PGN” pop up

Press “Share game URL” 

**Environment**

- iPhone 8 Plus
- iOS 13.3.1
- lichess 7.0.1

**Comment by freefal** [comment]
Thanks for reporting this. It has been fixed and will be release shortly as
v7.0.2

**Comment by mqll** [comment]
Excellent. The app is terrific. I love the redesign
