### ISSUE TITLE
Claim victory prompt annoying text layout 

### ISSUE THREAD

**Issue by jerweb63** [veloce/lichobile#1142]
I’m reporting a bug. 

phone hardware: iPhone 6s

phone operating system version: iOS 13.3.1

version of lichess mobile : 7.0.1

steps to reproduce:
Opponent disconnects from game. 

description of the observed behavior:
After a certain time, you get a dialogue window with the option to either “Claim victory” or “Call draw”. However the notification on the window is all running together like, theOtherPlayerHasLeftTheGameYouCanForceResi...

description of the expected behavior:
Notification text should be legible without all words running together.

**Comment by veloce** [comment]
Already fixed.

**Comment by jerweb63** [comment]
Thanks again:)
