### ISSUE TITLE
New Version 7 Still Not in Play Store

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1143]
I've been updating from the website because my Play Store still hasn't gotten version 7. Is it suppose to be there yet?

**Comment by veloce** [comment]
Eventually it will. But it's the same as downloading it from here if you are impatient.

**Comment by landry314** [comment]
yeah it is the same signature it seems which is strange to me. f-droid apps have different signatures. i assumed google compiled it with their own signature but i am quite ignorant about it.

**Comment by Ka-hu** [comment]
It's still not updated, play store shows me: 

Current Version: 6.3.0
Updated: **February 29**, 2020  

Version 7 was released on Feb 5, so I guess you should check in the play store about what happened.

**Comment by landry314** [comment]
My play store says version 6.3.0 updated on Sept 26, 2019

**Comment by Ka-hu** [comment]
Interesting. The desktop browser shows February 29: [Screenshot](https://i.imgur.com/nPxFMPd.png). I checked on the phone, and indeed it shows Sept 26, 2019.

Anyway, it should be updated by now, I guess. The current version is 7.0.4, and it's 23 days old as of today.

**Comment by SVVredeburg** [comment]
It is the same here, now April 5th. On both desktop and phone (Android 9.0 Play Store) I can't get anything newer than 6.3.0. Surely it can't take two months since 7.0.0, might there be anything wrong at the Google side perhaps?

**Comment by SVVredeburg** [comment]
Still no sign of improvement, perhaps time to reopen the issue? This way no-one can profit from the past and upcoming bug fixes and feature requests. I mean, I did download the APK file myself, but not everyone at my chess club will be able to do so.

**Comment by Ka-hu** [comment]
You are right, this issue should be reopened. Obviously there is some problem with the play store release.

**Comment by landry314** [comment]
Thank you!
