### ISSUE TITLE
Puzzle bug

### ISSUE THREAD

**Issue by Giualinao** [veloce/lichobile#1147]
Hello, first I have a problem with repeated puzzles, and I don't become/lose rating in this case.

Now I have problem that i lose now 500-600 rating points in one day (I played too much because I was frustrated), because puzzles are not good valued, every time when I make mistake, I lose 20-30 points, like that my rating is on high level (I was 2500+, now I am under 2000). When I win, I become often 1-5 points, rarely more then this 

I just want to this be fixed and to play puzzles normally. After all i am disappointed that I lose something that I build for a long time.

Fix it, please

**Comment by musicosinletra** [comment]
I have the same problem. I need a solution, there is a finite number of puzzles. Please, I need a solution soon. Thanks.

**Comment by jas14** [comment]
@musicosinletra as with games, your rating is inclined to gravitate to the average. If you're playing puzzles that are much harder than your rating, you will gain many points when solving correctly, and lose few when you don't solve correctly. Conversely, when you play puzzles that are much easier than your rating, you will gain few points when solving correctly, and lose many when you don't solve correctly. That's how the system is intended to function.

As for the finite number of puzzles - from my understanding, there are currently many, many more puzzles than you could hope to complete, and Lichess often adds more. If you have a problem with puzzle generation, you may open it on https://github.com/ornicar//lila - that's where we get the puzzles from.
