### ISSUE TITLE
Broken share game pgn or url

### ISSUE THREAD

**Issue by jerweb63** [veloce/lichobile#1148]
Bug report: Some things are broken with sharing game PGN or URL

Phone hardware: iPhone 6S

Phone operating system version: iOS 13.3.1

Version of lichess mobile beta: 7.0.1

Steps to reproduce:

Open a game from game history or with a game just completed and click on Share. 

Description of the observed behavior:

After playing a game, I wished to share the pgn. Clicked on Share and was presented with two options: Share game URL and Share PGN. Clicking on Share game URL does nothing, and tapping Share PGN opens the game in an Analysis Board. From inside the Analysis board, I tried selecting Share & export. Once again, Share game URL does nothing. Share raw PGN also does nothings. Selecting Share Annotated PGN opens a Board Editor. 

Description of the expected behavior:

Should be resulting in the usual options for iOS, such as share to Messenger, email, Notes, Facebook, etc...

The option to share FEN seems to work correctly however. 

**Note: Similar problems were observed ,although not totally the same, on my IPad Air 2 under with the same soft versions.

**Comment by veloce** [comment]
Fixed in https://github.com/veloce/lichobile/releases/tag/v7.0.2

**Comment by jerweb63** [comment]
Great job. Thanks for your hard work and effort.
