### ISSUE TITLE
Can't install lichess beta on iOS 8

### ISSUE THREAD

**Issue by derekchiang** [veloce/lichobile#116]
Not sure if this is a known issue, but I can't install lichess beta on my iPhone 6 which runs iOS 8.  It simply says "Unable to download app".

**Comment by veloce** [comment]
It's normal: only phones that are in the provisioning profile can download the app.

**Comment by derekchiang** [comment]
What is a provisioning profile?  So is there a way for me to download the app?

**Comment by ornicar** [comment]
It will be released very soon.
