### ISSUE TITLE
Feature request: add "share as gif option in app

### ISSUE THREAD

**Issue by shuvashish76** [veloce/lichobile#1162]
Just like the web version, add share the game as gif option in the app too.

![photo_2020-03-24_13-54-29](https://user-images.githubusercontent.com/48226312/77404252-72d24300-6dd7-11ea-85d0-ac832b246f65.jpg)
![photo_2020-03-24_13-54-44](https://user-images.githubusercontent.com/48226312/77404265-7665ca00-6dd7-11ea-8dfe-eaad1c028eac.jpg)

**Comment by Aditya-ds-1806** [comment]
Is this going to happen at all?

**Comment by Aditya-ds-1806** [comment]
Is this going to happen at all?

**Comment by Aditya-ds-1806** [comment]
Is this going to happen at all?
