### ISSUE TITLE
No points awarded following victory

### ISSUE THREAD

**Issue by shbrainard** [veloce/lichobile#1166]
**I'm submitting a ...**  (keep the relevant one):
- bug report
 

# Bug report

**Current behavior:**

I played this game:

https://lichess.org/jYRZhtjQOHh6

I won on time, and no points were awarded.

**Expected behavior:**

I should have won points.

**Steps to reproduce:**

Again, link: https://lichess.org/jYRZhtjQOHh6

Compare to any other game where you can see points awarded: https://lichess.org/SgsYj4gncMOm

I was 1783 before the game, and remained so following the victory.

**Environment information**

- iPhone SE
- iOS 13.3..1
- v7.0.3

**Other information:**

# Feature request

**Comment by shuvashish76** [comment]
That's a casual game. I guess you never played a casual game before...😄

**Comment by ilyes42** [comment]
My friend, there's no error in the app, what you played was a casual game, there are two types of games "casual" or "rated". casual means you just play for fun, doesn't affect your rating, whether you win lose or draw.

**Comment by shbrainard** [comment]
So weird, thanks for the clarification!

It's true, I don't think I've ever played a Casual game before, I've always just clicked "Quick pairing > 3+0 Blitz" and it's been rated by the default.  Not sure why it switched to Casual, but I'll keep an eye out for that in the future.

Thanks again!
