### ISSUE TITLE
Tournament err

### ISSUE THREAD

**Issue by almani1979** [veloce/lichobile#1167]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by almani1979** [comment]
Server dosn't pair player 
After waiting for while , some people lost games because didn't move !!!

**Comment by skoshe** [comment]
Sometimes when player is idle, suddenly the game appears from nowhere, forcing to play. If aborted, lichess server then blocks you.
Stockfish is also down.
