### ISSUE TITLE
Bug:  Cannot add comments (annotate) in study mode.  

### ISSUE THREAD

**Issue by JerryHobby** [veloce/lichobile#1169]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

Using Lichess app in iPad in landscape mode.  In the study area, I can click on COMMENT, but cannot add text there.  It works on the website but not in the app.

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by freefal** [comment]
Studies are read-only on the app for now.
