### ISSUE TITLE
[Feature Request] Add New Time Controls

### ISSUE THREAD

**Issue by freefal** [veloce/lichobile#1176]
Add the 30+0 and 30+20 time controls that were recently added to the homepage of the website.

**Comment by ornicar** [comment]
```
+ 10+5
+ 15+10
+ 30+0
+ 30+20
- 15+15
```

**Comment by freefal** [comment]
It looks like this change should happen dynamically here (https://github.com/veloce/lichobile/blob/master/src/xhr.ts#L115)

If wonder if `d.lobby.pools` isn't being populated or if it is being cached somewhere?

**Comment by freefal** [comment]
This is solving itself as caches time out.
