### ISSUE TITLE
Lichess tournaments links not redirect to open on lichess app - IOS

### ISSUE THREAD

**Issue by abdozyan** [veloce/lichobile#1179]
I'm submitting a bug report

**Current behavior:**

When i have tournament link and try to open the url , it opens in safari and never redirect to open in the lichess app for iphone

**Expected behavior:**

I expect when i click tournament link to take me to the lichess app and direct me to the tournament page, since most of times i cannot find the tournament listed in the tournaments list inside the app

**Steps to reproduce:**

open any lichess tournament link in Safari browser

**Environment information**

-Iphone 11 Pro max
- phone operating system version ios 13.4.1
- version of lichess 7.0.5

**Comment by Kostik8** [comment]
Actually there is completely no way to join any private/closed tournament on iOS app.

**Comment by abdozyan** [comment]
Understood, But the problem that i have a very bad experience with lichess app as a IOS user, because most of the time me and my friends organize many private tournaments along the day on a a daily basis, most of the times  cannot find these tournaments in the tournaments list on lichess app and also i tried to join the tournament s using the web and then open the app on hope that i will find it somewhere but unfortunately i couldn't, so i fail to join the tournament or i have to use my pc, so i believe you may arrange for a mitigation that allow ios users to search for a specific tournament  or list the already joined tournaments  so i can resume playing from ios

**Comment by JavascriptLearner815** [comment]
why doesn't anyone make a device that can work for the things on all types? each device type has its own advantages and disadvantages.

**Comment by abdozyan** [comment]
Seems the solution is to go and buy some cheap android phone so I can open private tournaments on the app

**Comment by veloce** [comment]
Fixed now
