### ISSUE TITLE
15+10 changed to rapid

### ISSUE THREAD

**Issue by Nicktz** [veloce/lichobile#1184]
The 15+10 game definition has now changed to rapid (previously classical)- which means my ratings have been transferred to 30min, which I never play. Please fix this and allow ratings to be transferred back to 15.min

**Comment by freefal** [comment]
The 15+15 pool, which is a classical time control, was changed to be 15+10,
which is a rapid time control, and some longer classical time controls were
added. Best would be to play some games at 15+10 to establish your rapid
rating.

**Comment by Nicktz** [comment]
Why move the ratings away? Takes time to build up the ratings- cannot see
why this cannot be transferred?
