### ISSUE TITLE
Problem with lichess mobile "Training"

### ISSUE THREAD

**Issue by Raffa2005** [veloce/lichobile#1190]
**I'm submitting a ...** :
- bug report

# Bug report

**Current behavior:**

If you make some tactics-training on the lichess website (lichess.org) on the pc and then switch to mobile, you will have to repeat all of the exercises you just did. 

**Expected behavior:**
The lichess website should sync automatically with the lichess mobile app, so that if you solve one exercise you wouldn't have to re-do it in the app.

**Steps to reproduce:**
1. Open the lichess website on the pc
2. Go to the tactics-training section
3. Solve some exercise (for example 5)
4. Switch to the mobile app
5. Go to the "training" section
6. -> now you see that you have the same exercises as on the website

**Environment information**

- phone hardware: Redmi 5+
- phone operating system version: Android 8.1.0 Oreo
- version of lichess mobile: 6.3.0 (the current one in playstore)

**Other information:**
IMPORTANT:
The website DOES sync in a way with the mobile app. If you re-do the exercises as I explained, you will NOT gain/lose ELO(which is good), however you still have to re-do them or "skip" them by resigning.

**Comment by francescoluciano** [comment]
Same problem for me!

- phone hardware: Honor 4x
- phone operating system version: Android 6.0
-- version of lichess mobile: 7.0.4

**Comment by Raffa2005** [comment]
Bug fixed after update on lichess v.7.0.4
