### ISSUE TITLE
Deep links not working

### ISSUE THREAD

**Issue by ojb500** [veloce/lichobile#1196]
# Bug report

**Current behavior:**

Following a deeplink to a user's profile leads to a persistent loading spinner and the message "lichess.org is unreachable. Request timeout", although lichess seems to still be online, and it's still possible to get to the user's profile via the friends list or player search.

Game links also don't seem to work reliably, and sometimes leave the UI in a strange state.

Deeplinks to a particular position in the analysis board or board editor ( https://lichess.org/analysis/1k6/1r6/2K5/Q7/8/8/8/8_w_-_- ) lead only to the app home screen.

**Steps to reproduce:**

I took my phone and opened Chrome at the deeplink test page, which I uploaded here https://rotherham.cc/deepLinkTest.html

Follow the first link, to the game: https://lichess.org/2360tJXP/black

Result: 
![image](https://user-images.githubusercontent.com/1455381/80050059-81ae3180-850c-11ea-8657-d1989a386367.png)

Now go back to the test page in Chrome and follow the link to freefal's profile: https://lichess.org/@/freefal

Result: 
![image](https://user-images.githubusercontent.com/1455381/80050032-73f8ac00-850c-11ea-940b-4df47c71661e.png)

**Environment information**

Pixel 3 XL
Android 10
App version 7.0.4
Chrome 81.0.4044.117

**Other information:**

I know of another Android user seeing this problem since getting the 7.0.4 update quite recently, but don't have their full phone spec to hand. If I get more info I'll update.

**Comment by veloce** [comment]
Thanks for the detailed but report. I'll have a look asap.

**Comment by princek94** [comment]
I am facing same issue with the links. Below is my phone specs:

![IMG_20200424_095139](https://user-images.githubusercontent.com/64242969/80175089-426a0880-8612-11ea-85c8-e0d89f9e4bff.jpg)

**Comment by ojb500** [comment]
Also seen on a Samsung Galaxy A3 (2017)
Android 8.0.0
app 7.0.4

**Comment by jamesdalmau** [comment]
Also seen on Samsung Galaxy S9 
Model number SM-G960F/DS
Android version 10
Kernel version 4.9.118-18339707
Security patch level 1 April 2020
Lichess version 7.0.4

**Comment by codeskraps** [comment]
Did you fix the issue? The issue persist on my site. I can not join any correspondence chess game.

**Comment by jamesdalmau** [comment]
Why was this closed? I still have the exact same problem. Clicking this link: https://lichess.org/Sd0eHkmu/black gives the following result
![Screenshot_20200506-122443_lichess](https://user-images.githubusercontent.com/10828987/81133543-47757300-8f95-11ea-8940-8e10d6a4f5e8.jpg)

**Comment by freefal** [comment]
@veloce is fixing this in his master branch and it will appear in the next
release.
