### ISSUE TITLE
Can't issue challenge to other players

### ISSUE THREAD

**Issue by Seandersont** [veloce/lichobile#1199]
# Bug report

**Current behavior:**

Mobile app is freezing, I can't challenge anymore, when I click challenge, it spins for a second, then the screen goes black. I can press back a couple of times to get the screen back to normal, but if I click on the top right button to see what games I have available, it becomes buggy and doesn't show anything.

**Expected behavior:**

I should be able to click challenge and have that challenge show up for me on my home menu, even before it is accepted.

**Steps to reproduce:**

Various buttons give me issues since the update

**Environment information**

Galaxy s9+
android 10 kernel 4.9.186-17655189
7.0.4

**Other information:**

Tried reinstalling, and restarting the phone. Also tried to send an invite on the website, and am unsure if it worked or not.

**Comment by vinittheanalyst** [comment]
I am facing the same problem..
