### ISSUE TITLE
Login doesn't seem to work

### ISSUE THREAD

**Issue by flugsio** [veloce/lichobile#12]
Pressing the menu-icon, then LOGIN-button. The startview glides back and wifi-icon in statusbar sends/receives for a bit. I'm expecting to see a login form of some sort.

Now nothing happens when pressing menu-icon, starting games still work though. If I start a game and then go back then the menu-icon is working again to show the sidebar.

Samsung I9100 Galaxy S II
Android 4.1.2
lichess 1.0.0 (beta2)
connected via wifi (playing with computer works)

**Comment by ornicar** [comment]
That may fix it https://github.com/veloce/lichobile/commit/29bb0e290a33e6eddda47b53771c6c3f13014eb9

**Comment by flugsio** [comment]
Solved in beta4
