### ISSUE TITLE
Enforce a maximum delay between the 2 clicks to validate castling move 

### ISSUE THREAD

**Issue by Kraymer** [veloce/lichobile#1206]
# Feature request

I observed that the vast majority of the few missclicks i do in my games are related to castling move, ie I clicked the king then I click the rook inadvertently and the castling happens.  
I suspect it is not specific to me.

**Current behavior:**

Castling is done by clicking the king then the rook. If a long time elapsed between the two clicks, castling still happens.

**Expected behavior:**

I first thought of adding a preference to "fix" that and then figure an UX adjustment would fix most missclicks :  don't validate the castling move if more than X seconds elapsed between the king and the rook clicks.

**Comment by veloce** [comment]
Instead of a delay (too problematic) I added the same option as in the website, so you can disable the castling by moving to the rook.

**Comment by Kraymer** [comment]
Great, thanks ! How can I be informed when the release is shipped ?

**Comment by veloce** [comment]
You can subscribe to this repository releases.

**Comment by Kraymer** [comment]
Merci ! déso j'avais zappé ce fonctionnement de github ;)
