### ISSUE TITLE
Full screen logo on app start shows extra black pixels

### ISSUE THREAD

**Issue by Incog5** [veloce/lichobile#1208]
# Bug report

**Current behavior:**
![Screenshot_20200429-122144_lichess](https://user-images.githubusercontent.com/14378320/80563289-d540e380-8a14-11ea-87e2-5ef6ac103d12.jpg)
 
With the new logo, I notice a few extra black pixels , upper left, thought my screen was defective.

**Steps to reproduce
Launch the app and pay attention to startup logo

**Environment information**
- Samsung Galaxy S8+
- Android 9
- Lichess 7.0.4

**Comment by niklasf** [comment]
Already fixed via https://github.com/veloce/lichobile/pull/1177/commits/1e02cd2e70eb3a46c5ef7bc4279c6547907dd71f, but not yet released.
