### ISSUE TITLE
The app does not open match links from WhatsApp.

### ISSUE THREAD

**Issue by CRomero1988** [veloce/lichobile#1219]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

_The empty board appears with a series of symbols at the top of the screen._

**Expected behavior:**

_The game should appear on the screen without any problem._

**Environment information**

- phone hardware
_ALICE_TL23_VC_
- phone operating system version
_Android 5.0.1._
- version of lichess mobile
_7.0.4._

**Other information:**
_It usually happens when the links of the games are opened from WhatsApp._

![bug](https://user-images.githubusercontent.com/64718957/80898355-0bf25480-8cc8-11ea-9e29-27332a5dd3d9.jpg)

**Comment by pranavh** [comment]
The app does not open links from anywhere: I tried Google Keep and Gmail, same result. I opened an issue too #1217

**Comment by veloce** [comment]
Fixed.
