### ISSUE TITLE
Duplicate names in friends list in app

### ISSUE THREAD

**Issue by tmmlaarhoven** [veloce/lichobile#1220]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

In the android app, sometimes when opening the friends list, some names appear multiple times (so far I observed names appearing twice and three times).

**Expected behavior:**

Each name should appear only once.

**Steps to reproduce:**

I'm not sure how to reproduce this, but it happens quite often, when just using the app and occasionally opening the friends list.

**Environment information**

- phone hardware: OnePlus 3T
- phone operating system version: Android/OxygenOS 9.0.6
- version of lichess mobile: 7.0.4

**Other information:**

Some screenshots:

![image](https://user-images.githubusercontent.com/11218275/80920425-ae402580-8d24-11ea-819e-b381d95f2a0a.png)

![image](https://user-images.githubusercontent.com/11218275/80920428-b39d7000-8d24-11ea-9707-a12b4c0bc346.png)

**Comment by jlpb97** [comment]
![Screenshot_2020-05-06-13-00-38-824_org lichess mobileapp](https://user-images.githubusercontent.com/44595095/81206503-33804000-8f9a-11ea-8661-f37444a115ab.jpg)

Same here

**Comment by dvdme** [comment]
I also see this behaviour some times.

Environment information

phone hardware: Xiaomi Mi A3
phone operating system version: Android One 9
version of lichess mobile: 7.0.4

**Comment by veloce** [comment]
Fixed (probably) in 386e1d39

**Comment by tmmlaarhoven** [comment]
@veloce With the current version (v7.2.0) on Android, I still got the same issue just now.
