### ISSUE TITLE
Android app won't scroll down

### ISSUE THREAD

**Issue by Pereper** [veloce/lichobile#1225]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

So since the app was updated to its current version (7.0.4), I've been unable to scroll down on its main page, so I'm unable to see the puzzle of the day, any of the tournaments going on or the news feed. Additionally, on the analysis board of any game the board will, by default, be in the "small" setting and in that state it will actually not appear at all until I "enlarge" it, at which point it will appear, but it still will not allow me to scroll down to see the entirety of the move list. I'd tinker with the app settings but it won't let me scroll down on those either.

**Expected behavior:**

I would expect the app's interface to scroll down properly at all times and allow access to all its features.

**Steps to reproduce:**

I basically open the app and find it already behaving as described.

**Environment information**

- Samsung Galaxy S7 Edge
- Android 8.0.0
- Since lichess 7.0.0 and on up to lichess 7.0.5

**Comment by baroca** [comment]
I had the same problem and in my case an outdated version of android web view was the cause.
You can install it from the play store: https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by Pereper** [comment]
> I had the same problem and in my case an outdated version of android web view was the cause.
> You can install it from the play store: https://play.google.com/store/apps/details?id=com.google.android.webview

Well that solved it for me too. Thank you very much!

**Comment by PiR43** [comment]
Same problem for me install com.google.android.webview was not enough I need also unactive com.android.webview (who was the default webview engine used on my ROM).
