### ISSUE TITLE
Opening game links with the app

### ISSUE THREAD

**Issue by tmmlaarhoven** [veloce/lichobile#1226]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

When trying to open a game link in the lichess app (Android), it seems the app gets stuck in some kind of loop without loading the game. 

**Expected behavior:**

The game should just be opened in the app.

**Steps to reproduce:**

The way I can repeatedly get this bug to appear is to load e.g. the game https://lichess.org/n9d43jXt. In particular this link was posted in the lichess discord, and if I click it in the discord app, select "Open with lichess app" (rather than opening in a mobile browser) I get the behavior described above and screenshotted below.

**Environment information**

OnePlus 3T, Android/OxygenOS 9.0.6, Lichess App v7.0.4.

**Other information:**

Below are screenshots of the behavior in the app. The top bar shows an increasing number of back-arrows, suggesting it is getting stuck in a wrong loop and nesting arrow after arrow on the screen.

![image](https://user-images.githubusercontent.com/11218275/81213222-e9dc2900-8f8a-11ea-8959-90ac33e71b18.png)

![image](https://user-images.githubusercontent.com/11218275/81213247-f19bcd80-8f8a-11ea-9089-e7901f09c065.png)

![image](https://user-images.githubusercontent.com/11218275/81213259-f82a4500-8f8a-11ea-9fc2-a090aa4a8375.png)

**Comment by dvdme** [comment]
I also have the exact same behaviour described here. 

**Environment information**

Xiaomi Mi A3, Android One 9, Lichess App v7.0.4.
Xiaomi Mi A2, Andriod One 10, Lichess App v7.0.4.

**Other information:**

On my Xiaomi Mi A2 I still had Lichess App v6.3.0 installed while I was testing this. Lichess App v6.3.0 did not had this behaviour, opening links worked fine. However, after updating to Lichess App v7.0.4 it started to happen on this phone too.

Screenshot of my Xiaomi Mi A3:

![mi-a3](https://user-images.githubusercontent.com/3511881/81275659-e0fe5c80-9049-11ea-854d-171b1dbc7161.jpeg)

Screenshot of my Xiaomi Mi A2:

![mi-a2](https://user-images.githubusercontent.com/3511881/81277325-2cb20580-904c-11ea-8417-f8a14bad3618.jpg)

**Comment by ddugovic** [comment]
Reportedly also reproducible on a Oneplus 6T device.

**Comment by colin-higgins** [comment]
I've been seeing this problem for at least a week now. 
Players in my tournament reported the problem on a variety of android and iOS devices.

**Comment by veloce** [comment]
Already reported and fixed. Please wait for the release. If you can't wait, please rollback to 6.3.0, which you can download in the release page, in the meantime.
