### ISSUE TITLE
Feature request: Add all board themes + piece sets that are on lichess website

### ISSUE THREAD

**Issue by Ejstn** [veloce/lichobile#1230]
I propose to add all board themes + chess pieces that are on the lichess website but are missing in mobile application.

Namely: there are **24 board themes on web but 12 on mobile**, there are **22 piece sets on web and 16 on mobile**.

My argument / use case is I would like to set the same theme + pieces on web and on mobile, so if I change between web and mobile it is more convenient / seamless.

**Comment by LichessUser** [comment]
I agree, they should add all the theme, I am bored with the themes on app

**Comment by LichessUser** [comment]
I l
![IMG_20200512_091118](https://user-images.githubusercontent.com/64771561/81640643-af680580-943c-11ea-88a8-529e5b5f5cd4.jpg)
ove this one
