### ISSUE TITLE
To add a new theme from lichess website

### ISSUE THREAD

**Issue by LichessUser** [veloce/lichobile#1231]
![IMG_20200512_091118](https://user-images.githubusercontent.com/64771561/81638047-8a23c900-9435-11ea-9169-c397dd10b350.jpg)

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

This theme is really cool, I want this theme on the lichess app as it does not has any good pieces and board sets, so please add this theme to the app.

**Comment by greatwolf** [comment]
Is this referring to the board or the piece set or both? What's the name of them?

**Comment by LichessUser** [comment]
How to see the names of the pieces?

**Comment by greatwolf** [comment]
click on piece set or board themes and just mouse over it should show the name.

**Comment by LichessUser** [comment]
Any way to show it on mobile, I don't have a pc

**Comment by LichessUser** [comment]
> click on piece set or board themes and just mouse over it should show the name.

These are the board and pieces I am talking about
![IMG_20200513_021945](https://user-images.githubusercontent.com/64771561/81744106-648fd180-94c0-11ea-87e5-06415907fa12.jpg)
![IMG_20200513_021916](https://user-images.githubusercontent.com/64771561/81744149-740f1a80-94c0-11ea-98b9-01d5dbd11831.jpg)

**Comment by LichessUser** [comment]
> Is this referring to the board or the piece set or both? What's the name of them?

Board name:- Wood4
Pieces name:- Cardinal

Please add these to the lichess app.
Thank you

**Comment by LichessUser** [comment]
Or you can tell me way to add these board and pieces myself

**Comment by LichessUser** [comment]
Can you do anything for me Me GreatWolf regarding this?

**Comment by veloce** [comment]
Hello, I'm planning to add all board themes in the next release.

**Comment by veloce** [comment]
For missing piece theme, I'll accept PRs.

**Comment by LichessUser** [comment]
Sir when will the next update come?, And what is meant by pRS?

**Comment by LichessUser** [comment]
> For missing piece theme, I'll accept PRs.
Please add all the pieces too, which are available on website.
It would be really helpful.
Thank you

**Comment by LichessUser** [comment]
> For missing piece theme, I'll accept PRs.

Please add all the pieces too, which are available on website.
It would be really helpful.
Thank you

**Comment by LichessUser** [comment]
Or do I have to create a pull request for it?

**Comment by LichessUser** [comment]
Add leather board theme also, looks cool
