### ISSUE TITLE
iOS App Crashes

### ISSUE THREAD

**Issue by daid999** [veloce/lichobile#1234]
I'm submitting a bug report. 

Current behaviour:
I open the iOS app to make a correspondence game move but the correspondence button (top right) is unresponsive when pressed. I then click the nav bar ‘burger’ button and press my profile name at which point the app will black screen and crash. 

Expected behaviour:
Open the app, click on correspondence icon to take turn and that match should open as normal. The app should not black screen when any nav bar buttons are pressed. 

Steps to reproduce:
Start a correspondence match. Take your first turn. Close the app and wait for the notification that it is your turn to move. DO NOT PRESS NOTIFICATION TO ENTER APP. Instead, open the app using the app icon. Press correspondence button (no effect). Press nav bar button followed by your profile name (app crash). 

Environment information:
iPhone Xs 
iOS 13.3.1
v7.0.5

**Comment by glechapelain** [comment]
Hi!

I'm same!

I do get notifications, but that's about it: clicking the app brings up an unresponsive black screen of sadness.

I can take a look, but I don't have a cable thunderdome-to-USB to pair up the macbook and the iPhone.

(I also know close to nothing about Apple development but am keen to learn.)

**Comment by veloce** [comment]
Fixed in next version.

**Comment by glechapelain** [comment]
Hi!


Thank you, it has worked for a short time.   Now, when I play: and hit `confirm'.. I see a infinite circling loop of sadness on confirm and the application is irresponsive again :(
