### ISSUE TITLE
Setup docs once app is running

### ISSUE THREAD

**Issue by tholman** [veloce/lichobile#1235]
Not sure the right place to put this, so will drop it here.

I'm looking to setup locally. I've got the app running (docs lead me to that point fairly clear), and have lila running as well... but struggling to get my local lichomobile to talk with the app/endpoints, so can't login/play with any games .

Thinking I've missed something somewhere.

**Comment by freefal** [comment]
Make sure https://github.com/veloce/lichobile/blob/master/appconfig.dev.json is pointing at the instance of Lila you want to talk to.

**Comment by tholman** [comment]
Ooh, that seems to have done it. I've got a feeling I had the order wrong originally. 🙏🙏🙏

**Comment by tholman** [comment]
Hmmm, next problem was that my websocket is refusing connections due to some settings. Also exploring if there is an order that I need to go in for it to be fine. Going by

```
{
  "apiEndPoint": "http://localhost:9663",
  "socketEndPoint": "ws://localhost:9664"
}
```

As the defaults via setting them up. Does that seem right?

**Comment by veloce** [comment]
Hi! I assume you want to use a local instance of lila? Then you shouldn't do it like that, but follow this guide instead:
https://github.com/ornicar/lila/wiki/Lichess-Development-Onboarding

I also wrote a guide some time ago (probably incomplete) for mobile development with a local lila: https://github.com/veloce/lichobile/wiki/Setting-a-lichess-dev-server-for-the-app

**Comment by tholman** [comment]
Right, following both of these got lila running on `localhost:9663` and I'm thinking lila-ws on `localhost:9664` ... there's nothing in there about setting up the lichobile configs to what they should be, so was guessing at those. 

The endpoint is working correctly/allowing me to create users/games, but then the ws server doesn't seem to be working, so playing the games breaks after a move.

.. happy to update some docs, but just trying to get it all working locally first :)
