### ISSUE TITLE
Castling breaks android app gameplay

### ISSUE THREAD

**Issue by edtayl** [veloce/lichobile#1236]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**
Whenever i castle in android app the game stops and an additional move is played automatically. No further play is possible. This is when playing stockfish offline.

**Expected behavior:**
Should be able to castle then proceed normally with game

Should be able to castle normally
**Steps to reproduce:**
Play stockfish offline in android app. Castle. 

**Environment information**
Android samsung galaxy phone app

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by veloce** [comment]
Not able to reproduce and you didn't specify required info.
