### ISSUE TITLE
Fix lag of cardinal chess pieces

### ISSUE THREAD

**Issue by LichessUser** [veloce/lichobile#1241]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

Hey veloce, thanks for adding cardinal piece set in the lichess app, after updating it to 7.1.1, I am having some issues with the pieces, whenever I move the pieces, they look like laggy. Please fix this issue

**Comment by LichessUser** [comment]
It usually happens when we download external board themes such as LEATHER, WOOD4, etc.
Please fix this issue, and also remove that transparent black Circle when we drag a piece.

**Comment by LichessUser** [comment]
See this video for more info

**Comment by veloce** [comment]
If it lags there's not much I can do. It's certainly due to your phone's hardware not powerful enough (as is mine so I know that it can lag). Sorry but you need to use another theme then.

**Comment by LichessUser** [comment]
> If it lags there's not much I can do. It's certainly due to your phone's hardware not powerful enough (as is mine so I know that it can lag). Sorry but you need to use another theme then.

Yes, my device is a low end device having only 2gb ram, but I checked on my friend's phone, have 4gb RAM and an excellent processor, that cardinal pieces was lagging on his device too. The lag was same in both, mine and my friend's device.
I think other players having high end devices also facing this issue.
Please try to find the solution Veloce.
Thank you

**Comment by veloce** [comment]
I fixed it by removing the filter, as I always favor low end devices. Thanks @greatwolf for the insight!

**Comment by LichessUser** [comment]
Then please release the new version soon
