### ISSUE TITLE
Add Replay Feature 

### ISSUE THREAD

**Issue by HeyitsClay** [veloce/lichobile#1248]
On the browser version of the site there is options to auto play previous games. I'd love to see this added to the mobile app, I really enjoy watching games this way. 
![Screenshot_20200519-161805_Chrome](https://user-images.githubusercontent.com/65625777/82387617-5e33b500-99ec-11ea-871a-c644eb62c576.jpg)

**Comment by veloce** [comment]
Yes I plan to add this along with the "share as gif".

**Comment by veloce** [comment]
Closed in https://github.com/veloce/lichobile/commit/349a328aab94a44f2968dbb8a99f48123991cb26
