### ISSUE TITLE
Mobile App tournaments games does not appear

### ISSUE THREAD

**Issue by bsjw** [veloce/lichobile#1251]
Hi,

I am a new joiner to Lichess and just tried joining a tournament room with no rating requirements etc using mobile app and was able to register for the tournament. However after the countdown ended and the tournament started, i was not paired any games for the next 1 hour while all the games started for the other places and they have started playing many games. Please advise if there is an issue with the mobile app starting games in tournaments. Thank you.

**Comment by freefal** [comment]
None that we know of. Tournaments usually work quite well on the app. Let
us know if this is a consistent issue. One quick fix would be to go back to
the home screen and then come back to the tournament page to refresh (but
you shouldn't need to do this).

**Comment by LichessUser** [comment]
Did you click the withdraw button after the tournament started?

**Comment by bsjw** [comment]
Hi,

I have tried again in another tournament and was able to have the auto pop up of games. 

Thanks 

Best Regards,
Benjamin 

> On 21 May 2020, at 11:05 PM, Lichess user <notifications@github.com> wrote:
> 

﻿
Did you click the withdraw button after the tournament started?
