### ISSUE TITLE
Bug report: duplicated friends on the friends list

### ISSUE THREAD

**Issue by kamil98** [veloce/lichobile#1268]
**Describe the bug**
Sometimes after clicking on the friends icon some of my friends are listed more than once.

**Expected behavior**
Every online friend should appear exactly once on that list.

**Screenshots**
![image](https://user-images.githubusercontent.com/15572959/83406150-502f5c80-a40e-11ea-95a7-4480998a5475.png)

*Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS13.5
 - Version 7.1.0

**Comment by seanysean** [comment]
Reported here: #1220
