### ISSUE TITLE
Add a sound alarm when time is low

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#127]
... and maybe a visual alarm too

**Comment by Calinou** [comment]
Can it be disabled in the settings?

**Comment by veloce** [comment]
Yes but only in the website preferences.

**Comment by Calinou** [comment]
So, how do you disable it in the mobile app?

**Comment by veloce** [comment]
You can't. For now settings in mobile app remain simple on purpose. Either you have sounds or no sound at all. I think being able to disable it is already sufficient. I use my time with more urgent stuff.
