### ISSUE TITLE
Reset analysis in correspondence game 

### ISSUE THREAD

**Issue by borishere** [veloce/lichobile#1273]
Currently there is no button to quickly get back to the current position of the game. You may have different branches of moves in your analysis and you have to manually find the last move of current game position if you want to reset analysis moves.

I would like to have an additional button for it.

**Comment by veloce** [comment]
The current position is circled with red in the move list, you can tap on it.

**Comment by borishere** [comment]
> The current position is circled with red in the move list, you can tap on it.

Thanks, I know it. But circled move is small and not easy to tap. Better make some kind of reset button in interface.
