### ISSUE TITLE
[Feature] Searching users and adding Friends

### ISSUE THREAD

**Issue by joshsweaney** [veloce/lichobile#1286]
There is currently no way to add a user as a friend from their profile page.

The ability to search for users is hidden behind the "@Community" menu item.

I think both of these things are issues that need addressing. A typical use case of the app, would be hearing that your friend is on Lichess, asking for their username, and wanting to quickly search for them and add them as a friend. You may not want to start a game right away, but adding as a friend will let you remember their name and start one later. The design of this work flow in the app isn't great at the moment.

I would make searching for users clearer, and also add a "Add Friend" toggle above the existing "Follow" toggle.

**Comment by veloce** [comment]
Follow is the same as adding a friend, and you can search players under the "Players" menu item.
