### ISSUE TITLE
iOS scroll bug

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1289]
Since release of 7.0 version both mobile apps don't have smooth scroll as it was before. Still not sure why it wasn't fixed, maybe it have some technical reasons I'm not aware of. 
Lack of scrolling acceleration makes app uncomfortable to use, scrolling long menus takes more time than it has to be.

My device: iPhone 5s and 6, iOS 12.4.7.

**Comment by veloce** [comment]
@Baikalcadillac do you still have the issue with version 7.4.0? I'm using a ipad and don't have the issue (neither on iphone emulators).

**Comment by Baikalcadillac** [comment]
@veloce yes. Menus can be scrolled, but the problem is you can't scroll long lists with one swipe (as it was before moving to ionic capacitor, I suppose). Scrolling to the end of long menu/list takes two/three "swipes", because it's scrolls small distance at once, from the point when you've clicked to the point when you stopped moving your finger. 
It's hard to explain, I was thinking it's because of outdated iOS version, but other apps are working fine.

**Comment by Baikalcadillac** [comment]
Fix isn't applied to move list while watching games on Lichess TV, scroll momentum doesn't work on iOS 12 (on iOS 14 works as intended).
