### ISSUE TITLE
Analysis board

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#129]

**Comment by garawaa** [comment]
plz add move times chart in landdscafe mode insteed of move list.

**Comment by JoelMon** [comment]
Vote for this feature.

**Comment by shirepirate** [comment]
yes, please add this feature. a must for correspondence games

**Comment by veloce** [comment]
TODO:

- [ ] check highlight
- [ ] promotion
- [ ] landscape view

**Comment by veloce** [comment]
Finally :)
