### ISSUE TITLE
App Crash with board-editor + analysisboard because impossible position (Android)

### ISSUE THREAD

**Issue by stevevonrein** [veloce/lichobile#1291]
**Description**
For my version (Android version 5.1, Lenovo TB3-710I, App-version: 7.2.0) it's possible to create a position, where a king could get captured and let the analysisboard anlyse that impossible position.

**To Reproduce**
(I hope it's clear after that):
1. Open the 'board-editor' (under tools, where you create your own position)
2. Place the Black King and a White Rook so that **Black King is attacked by the White Rook** and make sure it's **white's turn**
3. Click on 'analyse' (what shouldn't be allowed)
4. If Stockfish is active, the app should crash after a view seconds. If Stockfish isn't activated, you can capture the king with the rook (and that should never happen), can move on until you switch Stockfish on.

**Disclaimer**
I don't use the english version of the app, but I hope it's clear what I mean with 'board-editor'

**Comment by veloce** [comment]
I think it's clear. Thanks for the bug report!
