### ISSUE TITLE
Limit chat unread chat count cache size

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1297]
After long time playing/watching Lichess TV, downloading different board themes and backgrounds app fills with cache, that can exceed app size. For now the only way to clear it is complete reinstall.
For iOS it can be checked in Settings, General, iPhone storage and then choosing Lichess.

**Comment by veloce** [comment]
If you can do it from ios menu I don't need to implem that in the app. The only thing that I see that can fill up the cache are the chat unread counts. I'll see if I can have a more clever approach here to limit the size it takes.

**Comment by Baikalcadillac** [comment]
Since app consumes relatively small amount of space it's not critical. 
Also what I've noticed is that after each update it's clearing app data before the download.
