### ISSUE TITLE
Never get a game

### ISSUE THREAD

**Issue by ThetruthICC** [veloce/lichobile#13]
I tried to play another human, and set the time control to 3 0. After selecting my game I see a screen with

Waiting for opponent
3100 players and the number keeps changing.
X and Cancel button

After 10 minutes I have yet to get a game. If I go to my mobile browser and select 3 0 I get a game fairly quickly.

**Comment by veloce** [comment]
There's certainly a problem. We'll investigate.

**Comment by veloce** [comment]
Were you anonymous or logged in?
