### ISSUE TITLE
Draw arrows and circles on the app

### ISSUE THREAD

**Issue by LichessUser** [veloce/lichobile#1300]
Guys, is there any way to draw arrows and circles on the lichess app?, it would be excellent for mobile users if this feature comes to the app.
it would be fun to draw arrows on the app.
Thank you.

**Comment by Mahyar-Sahraei** [comment]
You must use a mouse but as far as i know the right click will result in a back function and wont let you draw arrows. I think an extra button should be useful, for example if it is activated, you draw arrows instead of making moves

**Comment by LichessUser** [comment]
Yes Mahyar, Correct!!
There should be an extra button in the bottom of the screen to draw arrows and circles. It will provide us PC like feeling.
Can you guys create a pull request for it?
@greatwolf, @freefal

**Comment by imagination972** [comment]
We need this badly! Whenever I'm on the phone I miss this feature so much. It should be very easy to implement that. We just need a button to activate the drawing. Hope devs see that.

**Comment by ornicar** [comment]
> It should be very easy to implement that

Show us.
