### ISSUE TITLE
Missing a lot of translated strings

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1313]
This applies to **ukrainian** translations.

Currently in app instead of translated words there are these lines:
NbFollowers, NbFriendsOnline, NbSecondsToPlayFirstMove.

When will the translation be updated?

**Comment by veloce** [comment]
I think if you see that it must happen in all languages. Thanks for reporting.

**Comment by veloce** [comment]
So I confirm it's not translated in your language. Now it fallbacks correctly to english.

**Comment by Baikalcadillac** [comment]
Thanks!
Also worth mentioning that since the last translation update many missing strings were translated/corrected. Web version already have most of them (some are still pending), would be nice to have them in app too.
