### ISSUE TITLE
Delay In Starting Next Puzzle In Spotty Data Connections

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1314]
I do puzzles on the subway a lot and the data connection goes in and out as we come in and out of stations. This is quite annoying because if I try to start the NEXT puzzle in my ALREADY downloaded cache of 50 puzzles then it immediately looks for a data connection which is quite weak and fading... the three dots move as it searches for the servers. I am waiting for like 10 seconds until the connection finally drops in the tunnel THEN it lets me do the next puzzle.

I suggest the algorithm be changed to immediately open the next puzzle in the cache and allow us to start it THEN to search for the next puzzle to download to refill the cache. I feel this would be the expected behavior.

It really doesn't make sense to force the user to wait for the cache of puzzles to fill BEFORE letting the user start the next puzzle which is 50 puzzles away from the current one!

This could be fixed by shifting a few lines of code earlier I would imagine. It doesn't seem too hard. I haven't seen the code though.

**Comment by veloce** [comment]
It is not supposed to work like that. I'm not sure to have understood everything, but it looks like a regression. Thanks for reporting.

**Comment by veloce** [comment]
@landry314 do you use the last version of the app?

**Comment by landry314** [comment]
i'm always using the most current version! i use the app every day.

**Comment by landry314** [comment]
This no longer works. It has regressed to the older problem. When I am on an underground subway and coming in and out of signal I need to go into airplane mode for the puzzles to work because Lichess keeps looking for a signal and delaying giving me the next puzzle even though it has many puzzles downloaded.
