### ISSUE TITLE
Tournament ranking when watching games

### ISSUE THREAD

**Issue by tmmlaarhoven** [veloce/lichobile#1326]
When watching e.g. Magnus Carlsen play in the Titled Arena, the most convenient way to make sure to catch his games in the app is to go to his profile and click the TV to see his games. That way however it's impossible to keep track of his progress in the arena, without leaving the mode of viewing his games.

Would it be an idea, when watching a game between two players in an arena, to add their rankings to the user info above and below the board? So instead of just showing the name, title, rating etc., adding the ranking in the tournament here?

As I'm mostly interested to see how Magnus is doing in the event, that would be enough to see if he's doing well, and if his current opponent is a competitor for the lead in the tournament. (If I want to know the full rankings I can then still switch views.)

**Comment by veloce** [comment]
It's actually a regression. Will fix it, thanks for reporting.
