### ISSUE TITLE
[feature] Add option to download some (configurable?) puzzles for offline play

### ISSUE THREAD

**Issue by swapnildinkar** [veloce/lichobile#1334]
**Describe the solution you'd like**
The app has an option where user can specify if puzzles need to be downloaded so that they can be later played if offline.

**Additional context**
Currently, the only thing that can be played offline is with computer, and it would be ideal if puzzles are also made available offline.

**Comment by veloce** [comment]
I don't know what version are you using but this has been implemented for quite some time now.
