### ISSUE TITLE
Illegal castle 

### ISSUE THREAD

**Issue by kefahB** [veloce/lichobile#1336]
Hi, 

I found this bug in this buzzle.  

![25068D45-B59E-427D-9D0C-4630F3DD35DE](https://user-images.githubusercontent.com/18148534/90195489-d6323100-ddc9-11ea-8f09-157785c242f0.png)
![CEA4E10B-7222-40BC-A814-2911043C4A30](https://user-images.githubusercontent.com/18148534/90195492-d92d2180-ddc9-11ea-903c-ef60e251f255.png)

**Comment by dsjoerg** [comment]
It is not illegal!

See https://en.wikipedia.org/wiki/Castling

"Castling may only be done if the king has never moved, the rook involved has never moved, the squares between the king and the rook involved are unoccupied, the king is not in check, and the king does not cross over or end on a square attacked by an enemy piece."

In this position the _king_ is not crossing over a square attacked by an enemy piece.  The rook is, but that is immaterial.
