### ISSUE TITLE
Shows nan+undefined in turnament TV

### ISSUE THREAD

**Issue by axelwas07** [veloce/lichobile#1338]
**Describe the bug**
It shuld display the time the clock starts at

![Screenshot_20200819-181436_lichess](https://user-images.githubusercontent.com/63060013/90662440-a4e1b700-e248-11ea-8189-6974b06dafcd.jpg)

 - Device: samsung galaxy a41
 - OS: android

Sorry for so little info. i don't more info that i have writen here

**Comment by ornicar** [comment]
next lila deploy will fix it
