### ISSUE TITLE
multiple premoves

### ISSUE THREAD

**Issue by tidypy** [veloce/lichobile#1342]
**Is your feature request related to a problem? Please describe.**
Problem = Clickjackers for rating pts.

**Describe the solution you'd like**
Solution = click drag toggle or long press  swipe.  
,  basically id like to swipe a piece up the board like the king or pawn and it will premove all the way to promotion,  or to that spot.  

Also Enable 3-4 move premoves,   

**Describe alternatives you've considered**
Tablet users have no choice we must tap twice to move pieces

**Additional context**

**Comment by ornicar** [comment]
Won't happen.
