### ISSUE TITLE
left handed mode

### ISSUE THREAD

**Issue by tidypy** [veloce/lichobile#1343]
**Is your feature request related to a problem? Please describe.**
Tablet users left hand covers the chessboard,  can't play bullet hand covers squares

**Describe the solution you'd like**
Under board display settings,   ADD. --> Display board on right, or display moves annotation on right, or say ``lefthand mode.`` 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ornicar** [comment]
It's more convenient for the board to be on the left side if you're left-handed, and it's already there.

**Comment by tidypy** [comment]
Your opinion of convenience is irrelevant, an option is required.
By your logic it is more convenient to be on the left side if left handed.
70-90 % of people are RIGHT HANDED.  So the app is less convenient for
70-90% of your tablet users.
Create the option is the root issue request.

Thank you kindly;
