### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by fva9** [veloce/lichobile#1346]
**Describe the bug**
Can't watch/observe matches in tournaments. 

**To Reproduce**
1. Go to tournament
2. Click on match down the page
3. Match dont launch, "resource not found" 

**Expected behavior**
Observe match

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei p20 Lite]

**Additional context**
It stopped working like 2 weeks ago. I didnt move or delete any files. Sorry for my bad English, hope someone will help how to solve this problem.

**Comment by ManuPranav08** [comment]
Same issue here
