### ISSUE TITLE
Misplaced icons on iOS 14.0

### ISSUE THREAD

**Issue by MathPlayer** [veloce/lichobile#1383]
**Describe the bug**
The UI layout is broken around most icons in iOS 14.

**To Reproduce**
* Check main page updates after the quick game setup.
* Check user profile ratings.

**Expected behavior**
Icons are not overlapping text.

**Screenshots**
![image](https://user-images.githubusercontent.com/1119787/93667470-83156300-fa86-11ea-8f37-9541a2c975b4.jpeg)
![image](https://user-images.githubusercontent.com/1119787/93667475-8ad50780-fa86-11ea-90a2-f1a55d631d24.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.0
 - using the mobile app version v7.5.0 (spotted in the settings page)

**Comment by KTS66** [comment]
I have the same issue.
iPad mini (5th generation)
14.0.1

**Comment by joshuak94** [comment]
Can i ask why this was closed? I've also been having this issue for a couple weeks.

**Comment by kraktus** [comment]
The issue is fixed but probably an update isn't available yet

**Comment by joshuak94** [comment]
Ah great, thank you.

**Comment by ianpan870102** [comment]
A similar issue has been reopened here: https://github.com/veloce/lichobile/issues/1423

**Comment by MathPlayer** [comment]
Personally, I received the update and the icons are not misplaces anymore.
I believe #1423 and this issue are duplicates.
