### ISSUE TITLE
Wrong winner

### ISSUE THREAD

**Issue by EternalAzure** [veloce/lichobile#1390]
When I won a 3+0 blitz game by timeout, my opponent was announced winner (by timeout). I lost elo to him and games data base shows him as winner. But when I examine that game, I have 19 seconds on a clock while he has 0.

I have encountered this bug only when both players are low on time (red background). Game was played on Android mobile app.

![Screenshot_20200929-153341~2](https://user-images.githubusercontent.com/46266019/94560665-a4870380-026b-11eb-9eaa-7b27b9336d4c.png)

![Screenshot_20200929-153346](https://user-images.githubusercontent.com/46266019/94560685-ab157b00-026b-11eb-82aa-6e9c2c869b22.png)

**Smartphone:**
 - Device: [Google Pixel 1]
 - OS: [Android: QP1A.191005.007.A3]

**Comment by papb** [comment]
From the screenshot, you didn't win. That game was a draw.

When a game is a draw, the one with highest rating loses a little rating, and the other gains a little rating.

**Comment by EternalAzure** [comment]
I see 

> From the screenshot, you didn't win. That game was a draw.
> 
> When a game is a draw, the one with highest rating loses a little rating, and the other gains a little rating.

Oh, I see
