### ISSUE TITLE
Repeating puzzles and rating problem.

### ISSUE THREAD

**Issue by aamirrasheed81** [veloce/lichobile#1391]
I keep getting the same puzzle when pressing the refresh button on the app. Also, my puzzle rating does not change after solving puzzles on the app, which is the expected behavior when solving puzzles you already saw, but I can't manage to get new ones.

**Comment by pranavKunapuli** [comment]
I am also observing this same behavior. Some of the repeated puzzle IDs I have seen are 61063, 61067, 61068, etc.

**Comment by ptfreak** [comment]
I'm experiencing the same issue. Puzzles repeat after I start with the puzzle of the day.

**Comment by rainwolf** [comment]
Same here, for me the list starts with 61054, 61055, and so on

**Comment by steve-abrams** [comment]
Same. I also experience repeating starting at 61054.

**Comment by rainwolf** [comment]
Once I hit 61054 on desktop in the browser, the problem seemed to solve itself. I don't know if it will work, but you can try loading that specific puzzle in the browser and solve it there. https://lichess.org/training/61054

**Comment by OrangeEye** [comment]
I've got similar problems, when I use the "continue training" button. But the little refresh icon at the bottom works fine. I've get new puzzles and my rating change in the app and also in the browser.

**Comment by cviscione** [comment]
Same problem with puzzle 61054 on android app.
