### ISSUE TITLE
Opponent won with no time 

### ISSUE THREAD

**Issue by Aaronthenovice** [veloce/lichobile#1393]
I was playing bullet and the opponent ran out of time but still made the finishing move. I would have played better moves if I knew you were allowed to win with no time left.

**Comment by Aaronthenovice** [comment]
https://lichess.org/zJP3tdrN/black

Played two of the the last moves with 0.4 seconds and the last move Rf8# despite having lost on time.

**Comment by freefal** [comment]
Your opponent had less than 0.05s, which rounded to 0.0s, but he still had
some time. In general don't stop playing until the result modal pops up.
