### ISSUE TITLE
Zen mode configurable as a per game setting

### ISSUE THREAD

**Issue by cleary** [veloce/lichobile#1399]
Hi @ornicar - firstly a big thankyou for this amazing project

My feature request is to make Zen mode applicable on a per game basis - my problem is, I play two sorts of games:
1. rated blitz -> I use zen mode
2. unrated correspondence -> I don't use zen mode, and like to chat as I play  

without fail, I will have it on the wrong mode when I go to play a blitz game, and I don't have the dexterity to get into settings to change it without losing a stack of time (I usually notice after I've played my first move) plus I've often seen the rating already and my head games have already begun

**Describe the solution you'd like**
I'd like to be able to apply a global default to Zen mode, so that any new games I start use that mode
But I'd like to be able to change the global default on a per game basis (via the context menu?) 

It would fix my issue by being able to set the global default for zen mode to on, and then allow me to turn it off for each casual game I play

**Describe alternatives you've considered**
seeing a sports psychologist to try and improve my head issues (joke) :P

**Additional context**
![Screenshot_20201022_165759](https://user-images.githubusercontent.com/2577966/96830852-cac54b00-1487-11eb-8dff-5df2baefcc74.png)

**Comment by veloce** [comment]
Fixed in aed2dea728ae92f5b39866fd3f6781c4fff3d78d
