### ISSUE TITLE
Requests extraordinary permissions

### ISSUE THREAD

**Issue by Evropi** [veloce/lichobile#14]
@ornicar asked I file a report about the permissions the app asks for on installation. Lichobile asks for phone number/ID and voice recording permissions, and these don't seem useful to lichobile.

Device: Samsung GT-S7275R (Galaxy Ace 3 LTR model)
OS Version: Android 4.2.2 w/ TouchWiz, never rooted.
Kernel version: 3.4.0-2715021
Beta build 2

**Comment by veloce** [comment]
Unfortunately I'm using cordova plugins to play sounds that requests also these permissions. I'll see if I can be more granular about it. It's possible that there's nothing to do about it though.

**Comment by ornicar** [comment]
voice recording is pretty hardcore.

**Comment by veloce** [comment]
I can disable voice recording permission but this is done in cordova generated files. I lack a system to do this permanently. Until this is fixed you may still see those permissions in beta release but we'll make sure it's not in prod release.

**Comment by veloce** [comment]
Normally fixed in recent builds

**Comment by Evropi** [comment]
It still requests basic phone data, which includes phone number. Here's a couple of screenshots from the beta 6 package installation process:
https://cdn.mediacru.sh/A/AslSpjkREeCZ.png
https://cdn.mediacru.sh/8/84EU4Li-J0jl.png

**Comment by ornicar** [comment]
I agree the phone number is not acceptable. Even if it means sitting on analytics, it has to go.

**Comment by veloce** [comment]
@ornicar have you tested last beta (1.0.6) ? Normally it should ask for it anymore.

**Comment by veloce** [comment]
Tested myself it's ok

**Comment by ornicar** [comment]
aw cool :dancers:
