### ISSUE TITLE
Any support for DGT boards???

### ISSUE THREAD

**Issue by entuccio** [veloce/lichobile#1400]
Would be great if the iOS app would connect directly with a Bluetooth DGT chessboard.

Have you planned to develop this feature? Thanks

**Comment by ornicar** [comment]
The website has it, you can use it in a mobile browser: https://lichess.org/dgt

**Comment by entuccio** [comment]
Thank you for your answer. Anyway, How I can connect the DGT Bluetooth via mobile phone ? I can't install LiveCloud there.
