### ISSUE TITLE
Game links not working

### ISSUE THREAD

**Issue by GSPP** [veloce/lichobile#1407]
Opening a link to a lichess game in some other app (such as a chat app) takes you to the start page in the app. It should take you to the game.

Example link: https://lichess.org/EMcS1tGM#39

Tested on Android EMUI 10, Huawei P20 mate lite.

**Comment by jas14** [comment]
Cannot reproduce on OxygenOS 10.3.6 (OnePlus 6), Android v10.

**Comment by GSPP** [comment]
I can no longer reproduce, either. I have tested clicking on a link in Chrome and in Signal. Works fine now... I will reopen if this resurfaces.

**Comment by GSPP** [comment]
The following link cannot be opened: https://lichess.org/Qrj20Qkw/white#53

I rebooted my phone to make sure all state is reset. The link fails to open in both Signal and in Pushbullet.

**Comment by GSPP** [comment]
For some reason, when I open this link from the Github website in Chrome, it works. Please try sending this link to yourself in an app like Signal or Pushbullet in order to reproduce. I have no explanation for why this is.

**Comment by jas14** [comment]
I just sent this to myself via Signal and it still works for me. Same OS and platform
