### ISSUE TITLE
Wrong checkmate red aura

### ISSUE THREAD

**Issue by Krock21rus** [veloce/lichobile#1410]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

Last move was automove
![Screenshot_20201103-132601](https://user-images.githubusercontent.com/14953722/97974345-7f406480-1dd8-11eb-8c1b-4ed91af6bbd1.jpg)

**Comment by freefal** [comment]
Is this reproducible? If so, could you send a game link?

**Comment by Krock21rus** [comment]
https://lichess.org/pMmTQDwH

But you should play jew game to reproduce it
I am almost 100% sure it is reproducable

**Comment by jas14** [comment]
Duplicate of #1012
