### ISSUE TITLE
Making a move doesn't reduce the number in the top right games notification badge (Pixel 5)

### ISSUE THREAD

**Issue by troutio** [veloce/lichobile#1417]
The mini chessboard button top right has a notification badge which shows how many moves I have to make (I usually play several concurrent correspondence games). When I make a move, I'd expect this number to decrease by one. Since I moved to my new phone (Pixel 5) this does not occur - the number only reduces if I tap the badge again and and go back out to the game selection screen.

**To Reproduce**
1. Notice that I have an outstanding move (badge number reads x)
2. Click on the mini chessboard button (top right).
3. Make a move
4. Notice that the badge number on the mini chessboard button is still x.
5. Tap on the mini chessboard button again.
6. Badge number correctly shows x-1.

**Expected behavior**
The number should reduce immediately on playing the move. It did this on my previous phone.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11

**Comment by sean-krail** [comment]
I’m also experiencing this issue on iOS 14.2 (iPhone 7 Plus).
