### ISSUE TITLE
Icons overlaps with text

### ISSUE THREAD

**Issue by arnulfholm** [veloce/lichobile#1423]
**Describe the bug**
Icons are many times overlapping with text. It seems to be a problem all over the application.

**To Reproduce**
1. Start a new game, say Bullet 1 0
2. Look at the bullet icon in the header. It overlaps the 1 in 1 0

**Expected behavior**
It should be some padding/ margin  between  the two

**Screenshots**
![lichess](https://user-images.githubusercontent.com/1655093/100196930-e34ada00-2ef9-11eb-8089-9551de664de8.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro (it also happens on iPhone 8)
 - OS: iOS 14.1
 - Lichess version v7.5.0
- Language: Norwegian

**Comment by ianpan870102** [comment]
Similar issue on latest iOS and latest Lichess app

![image](https://user-images.githubusercontent.com/36686900/100438292-e8b44a00-30dc-11eb-9fe3-a918781021a6.png)

This issue is similar: https://github.com/veloce/lichobile/issues/1383
