### ISSUE TITLE
Movement Bug lichess

### ISSUE THREAD

**Issue by Vichospam** [veloce/lichobile#1427]
The movements : d4, I move to d5 then he eat dxc5 and then 
I move to d5. He can eat but he move to cxd6 and the pawn disappears, please see the screenshot
Phone: Mate 10 pro, android 10

![Screenshot_20201128_141019_org lichess mobileapp](https://user-images.githubusercontent.com/75177536/100521926-b7dc1f80-3185-11eb-87d2-4c515742620c.jpg)
![Screenshot_20201128_141028_org lichess mobileapp](https://user-images.githubusercontent.com/75177536/100521930-c0345a80-3185-11eb-930d-94806fa2815e.jpg)

**Comment by freefal** [comment]
https://en.wikipedia.org/wiki/En_passant
