### ISSUE TITLE
Game link with color doesn't work

### ISSUE THREAD

**Issue by jakubdabek** [veloce/lichobile#1436]
**Describe the bug**
Link to game analysis opens the initial app view instead of the specific game.

**To Reproduce**
1. Click on a game link (e.g. https://lichess.org/cMWykxtt/white - this is how you get the links when you specify which side is displayed where)
2. Choose `lichess` in the `Open with` dialogue
3. See that the initial app screen opens

**Expected behavior**
The game is opened in the app

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8 SM-G950F 
 - OS: Android 9
 - App Version v7.5.0

**Additional context**
Links without the color (e.g. https://lichess.org/cMWykxtt) do work, so do other links (training etc.)

**Comment by steviestickman** [comment]
This also happens on my Phone.

Phone: Galaxy A70
OS: Android 10
App Version: V7.5.0

With the first link it opens the homescreen.

    https://lichess.org/FLA6l3qu/white

With the second link it opens the game

    https://lichess.org/FLA6l3qu

**Comment by veloce** [comment]
Thanks for reporting, will fix.
