### ISSUE TITLE
Puzzles not working

### ISSUE THREAD

**Issue by code5010** [veloce/lichobile#1451]
**Describe the bug**

When attempting puzzles you are prompted to sign in when attempting to check the rating graph even though already signed in, signing in does nothing. The view solution button is nonfunctional and you are unable to progress to the next puzzle

**To Reproduce**
1. Go to 'Puzzles'
2. Click on 'View solution or rating graph'
3. See error

**Expected behavior**
I expected to see rating after clicking the rating graph and the analysis section/next puzzle button after clicking show solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/76076941/102875858-fe7e0c00-4409-11eb-9d83-b3225accbf69.png) this is before clicking show solution.
 ![image](https://user-images.githubusercontent.com/76076941/102875807-ec9c6900-4409-11eb-9239-6ceebf824f20.png) this is after clicking show solution.

![image](https://user-images.githubusercontent.com/76076941/102875887-09d13780-440a-11eb-8051-27dcd2e484f2.png)
This is after clicking the rating graph.

**Smartphone:**
 - Device: [iPhone7]
 - OS: [iOS14.2]
 - Browser [Safari]
 - Version [14]

**Comment by illuminat281090** [comment]
One more comment to non func puzzles 

https://user-images.githubusercontent.com/24498981/102894406-b8599480-446b-11eb-8750-682f31730708.mp4

**Comment by jas14** [comment]
I imagine this is related to puzzles v2: https://github.com/ornicar/lila/pull/7678

**Comment by RubenMiranda79** [comment]
I have the same problem  with lichess app since this morning (and I have the same smartphone).

**Comment by benrubinsycle** [comment]
Same issue here on android

**Comment by melikechan** [comment]
Yes, when I tried to see my rating on puzzles, it gave the same error.

**Comment by omills** [comment]
I am experiencing something similar. It prompts me to sign in when I attempt to check my puzzle score history. Sometimes after solving a puzzle it says "resource not found". Started today I think. iPhone 12 mini.

**Comment by hatep** [comment]
Same behaviour on the Android app for OnePlus3, OxygenOS 9.0.6 (based on Android 9).

**Comment by ornicar** [comment]
I fixed the rating graph. It's just empty now. Rating history is no longer available.

If you have another issue and the puzzle ID is lower than 200,000, then touch the reload button at the bottom of the screen.

**Comment by shrey2708** [comment]
Same thing on my Redmi K20 pro
