### ISSUE TITLE
Unable to do puzzles

### ISSUE THREAD

**Issue by insidebitrunner** [veloce/lichobile#1458]
**Describe the bug**
When I open the app, then click on puzzles, it produced a screen with no chess pie and gives me a message ",unable to reach lichess.org ". I am not logged in.
**To Reproduce**

**Expected behavior**
a new puzzle to show up and complet

Tablet (please complete the following information):**
 - lenova tab 4
 - android 8.1
 - version 7.6.0
 - 

**Additional context**

**Comment by ornicar** [comment]
fix will land tomorrow
