### ISSUE TITLE
iOS: Notifications do not clear after action taken. 

### ISSUE THREAD

**Issue by hallmansm** [veloce/lichobile#1465]
On iOS 14.2
iPhone 11 Pro

Notification badge numbers are correct (for instance, when opponent moves in correspondence game). 

When I make all my moves and close the app, the notification numbers are not cleared. In order to clear the numbers, I have to force-close the app, then open the app, then close the app.

**Comment by bkif4** [comment]
I’ve the same problem ! Thank you @hallmansm for the report
Please correct this little problem 😉

**Comment by atomoton** [comment]
duplicate of https://github.com/veloce/lichobile/issues/1228
