### ISSUE TITLE
Migrate to ESLint from TSLint?

### ISSUE THREAD

**Issue by jas14** [veloce/lichobile#1467]
Palantir, the maintainer of TSLint, [announced](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in Feb 2019 that TSLint is deprecated in favor of ESLint. The latter will have better continued support, so it may be worth switching.

**Comment by veloce** [comment]
Yep that would be nice 👍

**Comment by jas14** [comment]
[Branch](https://github.com/jas14/lichobile/compare/typed-tests...jas14:eslint) is up. it's based on #1464, so I'll wait for that
