### ISSUE TITLE
Ping warning text have no spaces between words

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1469]
Steps to reproduce: tap on "?" button at the top of the side menu near username.

![photo_2020-12-27_20-11-19](https://user-images.githubusercontent.com/67504540/103177314-eda61e00-4881-11eb-8e3f-282be0ee5f39.jpg)

**Comment by jas14** [comment]
The relevant file hasn't been touched in about a month. Some questions:
- What platform are you using?
- What version of the app do you have?
- What locale do you have the app set to?
- (If different) What locale is your phone set to?

**Comment by Baikalcadillac** [comment]
I'm using iOS 12.5 (iPhone 6) and iOS 14.3 (iPhone X). Lichess 7.6.0 with english language, but russian language and Ukraine region on both devices.

**Comment by Baikalcadillac** [comment]
It’s fixed, at least for me. I guess issue can be closed now
