### ISSUE TITLE
Pawn could eat imaginary pawn diagonal

### ISSUE THREAD

**Issue by schreluc** [veloce/lichobile#1482]
I jumped with my pawn two blocks and another pawn could eat my pawn as he would jumped only 1 block. See the screenshots
![Screenshot_2021-01-04-15-48-34-084_org lichess mobileapp](https://user-images.githubusercontent.com/45065103/103547784-2444ef80-4ea5-11eb-96a2-777159f95c62.jpg)
![Screenshot_2021-01-04-15-48-41-791_org lichess mobileapp](https://user-images.githubusercontent.com/45065103/103547796-2909a380-4ea5-11eb-85d2-9b28d50079bf.jpg)
![Screenshot_2021-01-04-15-48-50-230_org lichess mobileapp](https://user-images.githubusercontent.com/45065103/103547805-2c049400-4ea5-11eb-92ec-6a73552231bb.jpg)

**Comment by freefal** [comment]
This is called en passant (https://en.wikipedia.org/wiki/En_passant) and is a legal chess move.

**Comment by schreluc** [comment]
Oke thanks, never heard of it :O

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
