### ISSUE TITLE
Galaxy Tab S5e (SM-T720) there are any user information about opponents on gaming screen

### ISSUE THREAD

**Issue by vs5991748** [veloce/lichobile#1488]
![Screenshot_20210109-233729_lichess](https://user-images.githubusercontent.com/12272236/104109983-f6640e80-52db-11eb-8a10-39b4346d4bb6.jpg)

**Comment by freefal** [comment]
Ensure that in Settings —> Game Display that Zen Mode is set to Off

**Comment by vs5991748** [comment]
Very thank you )
