### ISSUE TITLE
Push notifications for correspondence games

### ISSUE THREAD

**Issue by frankcalise** [veloce/lichobile#149]
Allow for a user to enable notifications when it is his/her turn in a correspondence game.

Maybe something more short term / temporary could just be a daily reminder if there is a way to check pending correspondence game turns.

Has there been any digging on a plugin for push notifications? I found [PushPlugin](https://github.com/phonegap-build/PushPlugin)

**Comment by veloce** [comment]
It's planned.. but require work in both server and client. Not the most urgent.

**Comment by brianhlin** [comment]
Any word on this? It makes correspondence chess mostly unusable for me.

**Comment by Evropi** [comment]
This isn't up to [Vincent](https://github.com/veloce/lichobile) but up to [Thibault](https://github.com/ornicar/lila), on the server side. Other things are happening at the moment... I wouldn't hold your breath for push notifications just yet.

**Comment by ornicar** [comment]
A lot of players are requesting this.

**Comment by fabienengels** [comment]
The only reason I keep playing on chess.com on my mobile, as soon as it's available, bye bye chess.com.

**Comment by kylerberry** [comment]
@veloce would you accept PR's for this issue?

**Comment by veloce** [comment]
Well, thanks for asking but I don't see a lot of things to do for that issue in lichobile @kylerberry 

The main part of the job is server side, this is where the logic of when send a push, talk to android and apple APIs is done, etc... 

The client side code should be pretty light. Actually the hardest part client side should be the management of new certificates for iOS, and this is not a lichobile issue but a [tarifa](tarifa.tools) one. 
I'll receive the help of @peutetre to implement it in tarifa, the toolchain I use to build the apps.

That being said, if you want to help and send PR for other parts of the app, you're welcome :)

**Comment by peutetre** [comment]
tarifa@0.12.0 should be released early next week so that we can start to take care of push notifications in https://github.com/TarifaTools/tarifa/milestones/0.13.0

**Comment by ornicar** [comment]
I'm ready to do serverside work.

**Comment by ZurabWeb** [comment]
@veloce Yeah, I'm willing to help with server side as well. Let us know what's needed.

**Comment by jjasghar** [comment]
I'd like to say this would be awesome to have. Thanks for creating a great app and every use of it has been a delight.

**Comment by Unihedro** [comment]
@veloce ornicar/lila#1306 has the intel you'll need, it's your turn :P

**Comment by veloce** [comment]
Finally done :dancer:

**Comment by ornicar** [comment]
hurray :dancers:

**Comment by mikeokner** [comment]
Really looking forward to this! What's the release time frame look like for 2.4? Looks like all the milestones have been completed.

**Comment by Unihedro** [comment]
The latest version of the android app already has this.

**Comment by mikeokner** [comment]
Looks like the Google Play store was updated on Jan 3 but Apple's app store and this repo both show the latest release as 2.3 back in November.

**Comment by larister** [comment]
There have been a few updates on iOS since, but I can't find notifications. Love this app, so any update would be hugely appreciated
