### ISSUE TITLE
Switch from "compat" messaging to WebSocket-based messaging

### ISSUE THREAD

**Issue by jas14** [veloce/lichobile#1491]
**Is your feature request related to a problem? Please describe.**

The current mobile messaging system feels more like email than chat. lila has already implemented WebSocket-powered chat server-side, and uses it on the desktop site. Notable differences:
- Plain HTTP requests (reload required) vs WebSocket (real-time chat)
- Subject line required in current implementation for new messages

**Describe the solution you'd like**

For better parity with the desktop site and for improved ease of use, I'd like the mobile app to be able to do real-time messaging without a subject line.

**Describe alternatives you've considered**

Minimally, I'd like to add a placeholder for the body of the new message. There's a placeholder for the subject line but not the body, and it's difficult to see the separator between subject and body, which is confusing and has lead me and friends to fill out the entire message in the subject line. See screenshot.

<img src="https://user-images.githubusercontent.com/569991/104332935-af823e80-54be-11eb-817f-bbb50aded10c.png" width="300" />

As a short-term step to at least remove the subject line requirement, we might be able to use the official [Lichess messaging API](https://lichess.org/api#operation/inboxUsername), as the screen for replying to an existing thread already does.

<img src="https://user-images.githubusercontent.com/569991/104333185-f53f0700-54be-11eb-9c88-2950868a4772.png" width="300" />

**Additional context**

Here's the lila desktop version, which is what I'd like to more or less see on mobile (with different styles, probably):
<img src="https://user-images.githubusercontent.com/569991/104333278-0d168b00-54bf-11eb-9a1b-b06365d649d0.png" width="300" />

**Comment by veloce** [comment]
Yes that would be a nice to have of course. But I don't plan to do it myself in a near future, as I have other priorities.

**Comment by jas14** [comment]
I'll probably open a branch myself and see what I can do :)

**Comment by veloce** [comment]
If you do that, you can reuse some of the code of [the msg module of lila](https://github.com/ornicar/lila/tree/master/ui/msg). It would be nice to have the same responsive design that fits both phones and tablets.
