### ISSUE TITLE
Error in puzzles 

### ISSUE THREAD

**Issue by cdkHub** [veloce/lichobile#1496]
When I do a puzzle I get an Error box. 

**To Reproduce**
1. Go to Puzzles
2. Play and solve or not 
3. If you retry the puzzle you get the error message 
4. 

**Expected behavior**
Everything seems to work fine (except for the graph, which has been posted). The only problem seems to be the error message. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 14.3
 - Browser app
 - Version 7.6.0
![865C9E16-83F3-4ED8-8FBD-5D01863CD704](https://user-images.githubusercontent.com/77423723/104538811-97a7d900-55ea-11eb-84ca-df0af45886fe.png)

**Additional context**

**Comment by veloce** [comment]
Reported server side issue. Should be fixed with server update.

**Comment by cdkHub** [comment]
Yes, I noticed this morning that it was fixed. Nice job! Thank you.
