### ISSUE TITLE
Error when trying to launch game vs computer on mobile "Invalid FEN"

### ISSUE THREAD

**Issue by pssnyder** [veloce/lichobile#1500]
**Describe the bug**
While trying to launch a game vs a computer opponent, I receive an error on the screen and the game will not start. The error reads, "Error: Invalid FEN" but I'm not loading an FEN or doing analysis so not sure what is wrong.

**To Reproduce**
1. Go to home screen
2. Click on play with the computer
3. Leave all settings default accept change time clock to 10|3 increment

**Screenshots**
![Screenshot_20210114-152427](https://user-images.githubusercontent.com/2072916/104645851-a7243200-567d-11eb-8a4c-56b6435987b9.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - App Version: Lichess 7.6.1

**Comment by pssnyder** [comment]
Realized what it was asking for was a board position input since nothing defaulted into that box. Error was confusing though.

**Comment by carstenhag** [comment]
I am having the same issue and don't know how to fix it. 
I'm on V8.0.0

![Screenshot_2023-06-26-00-03-44-04_86d667449b00b848f46d695606363a65](https://github.com/lichess-org/lichobile/assets/3776997/329e5c53-1a2b-42e3-8e8f-14b1f35c3b02)
