### ISSUE TITLE
opening puzzle links with the mobile app is broken. 

### ISSUE THREAD

**Issue by zinovic** [veloce/lichobile#1502]
**Describe the bug**
When clicking a puzzle link from a discord chat, and opening it with the mobile app (android) it will give a random puzzle instead of the one sent. Opening this same link on a browser works correctly. 

**To Reproduce**
1. Send a puzzle link over discord, eg. https://lichess.org/training/7HlKU
2. The link embed works correctly, a small preview on the correct puzzle shows up. 
3. Click the link and click to open with the lichess app. 
4. It will give a random puzzle. if using the open with browser it works correctly.

**Expected behavior**
For the puzzle link to lead to the correct puzzle in the lichess app. 

**Smartphone (please complete the following information):**
 - Device: Pixel 1, also tried on an S8
 - OS: [android 10,  S8 in on android 9]
 - Discord version 53.8 (1367)

**Additional context**

**Comment by jas14** [comment]
Two problems:
1. there's an [assumption](https://github.com/veloce/lichobile/blob/7047a850167a81cc221aaa1a996a99f954b2a547/src/ui/training/training.ts#L35) that the puzzle ID will be a number, not a string (which is true of puzzles v1 IIRC)
2. there's no [puzzle API endpoint](https://github.com/ornicar/lila/blob/ddf0a0a43a739e10db1c3c8d1a79a74b7481dbcf/app/controllers/Puzzle.scala) yet (that I can see) on lila that can retrieve a puzzle as JSON by string ID
