### ISSUE TITLE
Define custom server URL

### ISSUE THREAD

**Issue by gu1ll0me** [veloce/lichobile#1506]
We would like to self-host our own Lichess server at work and use this mobile app to connect to it. It is or it could be possible to set the server URL in-app?

**Comment by veloce** [comment]
It's not documented indeed, but you can by defining a new env.
Just copy the `appconfig.dev.json` file to another file: `appconfig.<my_env>.json`. You can change the server url here. And then build the application using the `APP_CONFIG` environment variable that must match the `<my_env>` part of your file.
Example for `appconfig.local.json`, run `APP_CONFIG=local npm run build`.
