### ISSUE TITLE
iOS Study Changes Don't Save

### ISSUE THREAD

**Issue by laitinen** [veloce/lichobile#1510]
**Describe the bug**
On iOS, when I add variations to a study I've previously created, these changes don't save after I navigate away from the study.

**To Reproduce**
1. Create a study in your browser. Use the default settings. Insert 1.e4 e5.
2. Navigate to the study within the iOS app. Insert 2.Nf3 Nf6.
3. Navigate away.
4. Navigate back to study on either your browser or iOS. The study only shows 1.e4 e5. 

**Expected behavior**
The study should reflect the latest changes, including the knight moves.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.3
 - Lichess version 7.6.0

**OS X Browser**
- Chrome 87.0.4280.88 (arm64)

**Comment by veloce** [comment]
Studies are read only in the app, that's why.
