### ISSUE TITLE
Tournament chat shouldn't scroll down when receiving a new message

### ISSUE THREAD

**Issue by mlhtnc** [veloce/lichobile#1513]
**Is your feature request related to a problem? Please describe.**
When you reveive a message in tournament chat, it scrolls down and you can't even read messages. You need to scroll up again and after receiving another message, again it goes down. It is getting frustrating quickly.

**Describe the solution you'd like**
IMO, it is better not scrolling down when you get a new message. Maybe a scroll down button might be helpful if you go too much upper.

**Comment by lipis** [comment]
We can do what YouTube live chat does or Twitch..
