### ISSUE TITLE
Buttons for opening explorer etc. difficult to reach 

### ISSUE THREAD

**Issue by jerweb63** [veloce/lichobile#1514]
Accessibility Issue iOS version 

I'm very frustrated when I
try to click on the micro sized icons for the opening book, analysis, etc. They are so tiny and cramped together which makes them hard to use, as you must really attempt to accurately touch them. The problem is intensified when if one has unsteady or larger than average hands, or both for that matter. 

**Describe the solution you'd like**

I strongly feel that this accessibility problem could be solved by placing the functionality of these icons / buttons into a fold out or slide down menu which would allow much more surface for touching. At the least space them further apart and increase their sizes. 

**Additional context**

![B3943E96-E961-46A7-A9D0-2A0AC41E84C3](https://user-images.githubusercontent.com/8494662/105077181-69b01200-5a8c-11eb-9a54-d8a6e3b71752.jpeg)

**Comment by veloce** [comment]
I'll try to think about it. Do you know that you can also swipe left/right to change tabs?

**Comment by jerweb63** [comment]
Hello Vincent,

I did not know that you could just swipe. This works very well indeed! 


Thanks

**Comment by jerweb63** [comment]
Did not know of the option to swipe to the desired window. This is good enough for me.
