### ISSUE TITLE
Indicate with a icon if the move was best, excelent, good, imprecision, error or a opening move automatically when use stockfish

### ISSUE THREAD

**Issue by COD3BREAK3R** [veloce/lichobile#1515]
I apologize for my English because I will use google translate.

There is a feature that is not yet implemented in lichess that does exist in chess.com which is great and it is about indicating with an icon in the corner of the moved piece if that move was good, bad, from a book, etc.
I would very much like them to implement it and it would be amazing. Thanks

![Screenshot_2021-01-21-14-03-40-243_com chess](https://user-images.githubusercontent.com/51484063/105401266-fd502280-5bf3-11eb-8703-b08a1aaa1c33.png)

![Screenshot_2021-01-21-14-03-29-861_com chess](https://user-images.githubusercontent.com/51484063/105401288-0640f400-5bf4-11eb-8f6b-414352ce0bd6.png)

I know what lichess has the function that when performing a computer analysis it indicates in each move with a comment how it was but it is more comfortable the way chess.com shows it, also the movements outside the original game are not commented. that there is the option of practicing with the computer and that when making a move it says if it was good or bad, but it automatically moves the pieces after one play which does not allow me to make another move on my own so that the engine can evaluate it if I wish stay on the same side, it is also not as specific as chess.com indicating if the play was opening, good, excellent, the best, and so on.

I also add that I would like the function of indicating threats to remain permanently active so that I don't have to be in each play that wants to see the threats by pressing the button. thanks to the team for creating this app.

**Comment by COD3BREAK3R** [comment]
Great, thanks for including it @veloce, I have detected a bug that I would like to share:

![Screenshot_2021-03-11-15-31-02-857_com opera browser](https://user-images.githubusercontent.com/51484063/110851925-b12e6f80-827f-11eb-9969-3f298aa5838d.png)
As can be seen in the screenshot, if the king castles and it is an error, part of the icon remains off the screen


It would be great if, in addition to indicating the errors, the module showed how good the move made is or if it is a book opening as in chesscom.

I suggest taking the chesscom color scheme as a base, as I find it somewhat confusing that an error is marked in blue since in chesscom it indicates that it was a brilliant move. if there were all these options it would be incredible.

![Screenshot_2021-03-11-15-35-18-998_com chess](https://user-images.githubusercontent.com/51484063/110852316-34e85c00-8280-11eb-880a-19451d200f21.png)

**Comment by veloce** [comment]
This is the mobile app repo, and you are submitted a bug in the website. This is not the right place to do it. Plus I think this issue has already been fixed in the website.

**Comment by COD3BREAK3R** [comment]
> This is the mobile app repo, and you are submitted a bug in the website. This is not the right place to do it. Plus I think this issue has already been fixed in the website.

Thanks for adding the motion annotations in the Android Lichess app. Unfortunately the problem mentioned on the website also exists in the app. Here is a screenshot.

![Screenshot_2021-03-17-20-28-26-161_org lichess mobileapp](https://user-images.githubusercontent.com/51484063/111556353-bcdad400-8760-11eb-8b9e-8249af028fc6.png)

I would like to see annotations for each move outside of the original game executed on the analysis board in the future, because only annotations are shown for the original moves made in the game.

I add that the change from one place to another of the annotation icon is not smooth on my device, I have a xiaomi redmi note 4, if this animation could be disabled in a future update it would be good.
