### ISSUE TITLE
Lifetime score problem on mobile app

### ISSUE THREAD

**Issue by muratuner** [veloce/lichobile#1519]
Some matches after lifetime scores not cripted, not shown on my mobile app. Why?
Thanks now for your all supportings.

**Comment by muratuner** [comment]
> Some matches after lifetime scores not cripted, not shown on my mobile app. Why?
> Thanks now for your all supportings.

For example https://lichess.org/t7Iu9Nqn

**Comment by freefal** [comment]
This seems to be a server issue. Unfortunately this issue was too old for thibault to debug (https://github.com/ornicar/lila/issues/8282), I suppose because he doesn't have logs that old. If this happens again, please report directly against the server repo (https://github.com/ornicar/lila/issues)
