### ISSUE TITLE
Graph button in a puzzle asks me to log in, but I already was.

### ISSUE THREAD

**Issue by Pablo-No** [veloce/lichobile#1521]
**Describe the bug**
Graph button in a puzzle asks me to log in, but I already was.

**To Reproduce**
1. Go to any puzzle
2. Click on the graph icon

**Expected behavior**
I would have spected to see some stadistics.

**Screenshots**
After solving the puzzle:
![Paso 1](https://user-images.githubusercontent.com/65043486/105717825-e0339080-5f20-11eb-877f-f7e7ac7dc3a4.jpg)
After clicking on the graph icon:
![Paso 2](https://user-images.githubusercontent.com/65043486/105717858-e9246200-5f20-11eb-9bba-401c032ca632.jpg)
After clicking on the log in button:
![Paso 3](https://user-images.githubusercontent.com/65043486/105717908-f5a8ba80-5f20-11eb-9e70-9fcfd635ec8d.jpg)
Here you can see I already was logged in:
![Sesión](https://user-images.githubusercontent.com/65043486/105717933-ffcab900-5f20-11eb-9df2-a81b75328ef4.jpg)

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: Android 10 QKQ1.200512.002
 - Browser I was using the app, I don't know what else to say.
 - Version 7.6.1

**Additional context**
I tried to log in in that screen but I couldn't.

**Comment by freefal** [comment]
Is this still an issue in the latest version of the app?

**Comment by freefal** [comment]
FYI, the latest version available is 7.8.1

**Comment by Pablo-No** [comment]
No, it hasn't happened anymore.
