### ISSUE TITLE
UI bug, no graph when game analysis is done

### ISSUE THREAD

**Issue by soegaard** [veloce/lichobile#1526]
After playing a game I often click the "Analysis" tab and request a game analysis.
Some animation is displayed while the game analysis is computed.
When the analysis is done - the analysis isn't displayed (see attached screenshot).
Clicking another tab and clicking back solves the problem.

If it helps, it has worked in the past but broke after an update (several months ago).
![IMG_1CDE22CD2904-1](https://user-images.githubusercontent.com/461765/106309584-9faa7e80-6262-11eb-9c6c-14ac37f800ea.jpeg)

Note: Original reported here https://github.com/ornicar/lila/issues/8040 but

> Hi, you should move this issue to https://github.com/veloce/lichobile , 
> the repository for the app, not the web see #7857 And check if it wasn't already reported.
> Otherwise good report, this happened me too.

**Comment by johtso** [comment]
I'm also experiencing this bug on Android.

**Comment by wrigjl** [comment]
Also affects iPadOS 14.4
