### ISSUE TITLE
Crashing the app with an exercise from the Soviet Chess Primer

### ISSUE THREAD

**Issue by csaavedra** [veloce/lichobile#1528]
Exercise 18 from chapter 1, "Mate in one move, in 47 different ways", can cause the app to crash.

Here is the FEN generated by lichess board editor:

```
1n2b3/P2P1P1P/6K1/2QBkNR1/5N2/3P2P1/1R6/B7 w KQkq - 0 1
```
Go to the analysis board and then "practice with the computer", and boom!

![IMG_20210130_150301_428](https://user-images.githubusercontent.com/2523171/106357496-0b4a2580-630f-11eb-8451-967ed9c0959d.jpg)

**Comment by veloce** [comment]
Your FEN is actually problematic as it enables castle on both sides, where castle should be disabled.
This fen would work: 
```
1n2b3/P2P1P1P/6K1/2QBkNR1/5N2/3P2P1/1R6/B7 w - - 0 1
```

The app should make sure you can't analyse with such an invalid fen though, I'll try to fix that soon. Thanks for reporting.

**Comment by csaavedra** [comment]
Just to make it clear -- I generated the FEN from the Lichess board editor after entering the position piece by piece, in order to share it here. But just entering the position in the editor, and then going to "analyze" and then "practice with the computer" crashes the app. I suppose it's possible that the FEN is used internally to feed the engine? In that case there would be two possible bugs:

1. the FEN generated from the editor is buggy, as it shouldn't allow casting.
2. What you described -- forbidding analysis of such a buggy FEN.
