### ISSUE TITLE
decrease "next move" and "previous move" button accidental holds by implementing a hold delay

### ISSUE THREAD

**Issue by atomoton** [veloce/lichobile#1530]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I mean to only move one move forward or backward, but the button registers a finger "hold" and it skips multiple moves. The buttons I mean are highlighted here: 
![image](https://user-images.githubusercontent.com/16313135/106398077-e91fd880-63de-11eb-9363-35c3c2cedaf1.png)
This is in both the game view and/or the analysis view.

**Describe the solution you'd like**
If there was a hold delay of 1.5-2s on these buttons, it would make it a lot easier to do multiple fast taps, without inadvertently skipping moves. It would also still allow the very rapid "scanning" that you can get by holding the button, but it would be more intentional.

**Describe alternatives you've considered**

- could be a setting to change the buttons to be single step only (ie. like this: 
![image](https://user-images.githubusercontent.com/16313135/106398154-3dc35380-63df-11eb-87e9-7313558ece41.png)
) (sorry for my bad MS Paint)

**Additional context**
Thanks everybody for your work on this app!

**Comment by veloce** [comment]
Yes I'll do that.

**Comment by BrendanEMahon** [comment]
Connected to this, the bottom bar should be large IMO.  Making it easier to push the next and previous buttons when intended and reducing clicks that jump you to a specific move later in the game (when you click above the forward arrow unintentionally).

**Comment by atomoton** [comment]
just got the update: thank you so much this is much nicer
