### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by gitteruser** [veloce/lichobile#1531]
**Describe the bug**
Before this bug I have the use of app "HTTPbot". Some experiments with cors.
Then I opened lichess tried to start blitz, but the modal was displaying "??" Instead of online games number. Then I get sight of log out and tap to login, paste my login and pass and finally catch this bug after tap on button.

![image](https://user-images.githubusercontent.com/57964250/106512115-39cc2a00-64e2-11eb-88d4-ff7999aa2454.jpeg)

The same massage and no connection with two WiFi spots and cellular

_Sorry for my English_

**Comment by niklasf** [comment]
This was a server issue at the time. We're working to bring it back fully. There's nothing that can be fixed in the app itself.
