### ISSUE TITLE
App can't connect to Lichess server

### ISSUE THREAD

**Issue by Dampfie93** [veloce/lichobile#1536]
**Describe the bug**
Compiled .APK can't access regular [lichess.org](url) server. Is this normal?
Seems like it's connecting to the [lichess.dev](url) server.

**To Reproduce**
compile apk as README.md
install apk on mobile

**Smartphone**
 - Android 10

**Comment by Dampfie93** [comment]
Fixed!

scripts/inject-conf.js does what it supposed to do. Injects a config.
change into:
```
// dev | release
const mode = process.env.APP_MODE || 'release'

if (!['dev', 'release'].includes(mode)) {
  console.error("APP_MODE possible value: 'dev' | 'release'")
  process.exit(1)
}


// dev | prod | custom
const confKey = process.env.APP_CONFIG || 'release'
```
and create file `appconfig.prod.json` with [lichess.org](url) instead of [lichess.dev](url)

**Comment by veloce** [comment]
That's right, you figured it out. Sorry if the documentation is not clear about that. I should try to find the time to update the README (or I'll accept a PR that would improve the doc of course).
