### ISSUE TITLE
"Infinite analysis" can't be toggled

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1540]
iPhone X, Lichess 7.7.2

![photo_2021-02-07_18-05-04](https://user-images.githubusercontent.com/67504540/107152162-07ea1600-696f-11eb-8bfa-f22d750e88ae.jpg)

**Comment by veloce** [comment]
Sorry for the regression. Will fix, but in the meantime you can use the new "+" button after analysis is complete for a position.
