### ISSUE TITLE
Wrong ranking system 

### ISSUE THREAD

**Issue by NaOHann** [veloce/lichobile#1545]
A checkmate is shown on the dialogue but the score system remark it as a tie. 
![779A1F09-74AC-4300-8011-17787123B543](https://user-images.githubusercontent.com/61576335/107333087-f419ed80-6aef-11eb-86e5-00cd71b90b7c.png)

**Comment by Guki29** [comment]
![Screenshot_20210209-085517~2](https://user-images.githubusercontent.com/78787791/107333791-3cb4b500-6ab6-11eb-8761-f3e4220a49f7.png)

Same Problem

**Comment by kraktus** [comment]
Must have been caused by this issue: https://lichess.org/forum/lichess-feedback/bug-with-game-completion-today-between-724-and-804#1
