### ISSUE TITLE
Strategy mode

### ISSUE THREAD

**Issue by wolfiex** [veloce/lichobile#1547]
It would be useful to be able to enable a strategy mode whilst waiting for your opponent. 

A dummy copy of the board where you can explore different senarios a few moves ahead by being able to move both pieces on the board, without actually doing so in the game. 

Aesthettically this can be done by changing the opacity and colours as to show the difference.

**Comment by freefal** [comment]
In a live game, you should be calculating in your head, not playing out lines. In a correspondence game, you can bring up the analysis board and play out lines already.
