### ISSUE TITLE
Shield Arenas icon is missing

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1548]
Shield Arenas have default time control icon instead of shield.

![photo_2021-02-10_17-44-14](https://user-images.githubusercontent.com/67504540/107533591-c1432880-6bc7-11eb-9796-e321e99713b9.jpg)

![blitz](https://user-images.githubusercontent.com/67504540/107533605-c56f4600-6bc7-11eb-8c4b-4056ba659494.png)

**Comment by freefal** [comment]
Pull request to resolve is here: https://github.com/veloce/lichobile/pull/1566

**Comment by Baikalcadillac** [comment]
![BC2ACDA8-0BA5-4C0B-B0C3-A3EB15945D08](https://user-images.githubusercontent.com/67504540/130363390-d25b35e8-4960-4422-b412-a659a270e640.jpeg)

Seems like three-check still have this bug

**Comment by jas14** [comment]
@Baikalcadillac I believe that's expected behavior, the shield appears on the website for all variant shield tournaments:

<img width="294" alt="Screen Shot 2021-08-23 at 8 16 16 AM" src="https://user-images.githubusercontent.com/569991/130445440-0782be0c-6a27-4d2b-9576-0d49a007f01f.png">
