### ISSUE TITLE
Game chats in app don't allow to scroll up. Wiko Y80 with Android 9

### ISSUE THREAD

**Issue by oopsmouseslip** [veloce/lichobile#1553]
When reading the chat in the lichess app, scrolling up is impossible. The chat will jump back down to the last messages posted. Scrolling up and holding does not work.
This happens in both tournament chats and game chats. 
This has happened on both my Wiko Y80 with Android 9 and my old Samsung J3, also Android.

Yes, the chat is rarely interesting. But it can be, and this bug is really annoying.

**Comment by veloce** [comment]
duplicate
