### ISSUE TITLE
Piece changed during game (black bishop to white knight)

### ISSUE THREAD

**Issue by michael1241** [veloce/lichobile#1554]
**Describe the bug**

**To Reproduce**
Unknown

**Expected behavior**
Constant pieces

**Screenshots**
![image](https://user-images.githubusercontent.com/28427681/107857156-90abfa80-6e24-11eb-84bd-2bcf1ac01536.png)
![image](https://user-images.githubusercontent.com/28427681/107857157-930e5480-6e24-11eb-91f2-60534542a3a6.png)

**Smartphone (please complete the following information):**
iOS app version 7.3.0

**Additional context**
https://lichess.org/tYi3fmrd game link

**Comment by michael1241** [comment]
User comment:
Right before the issue, the app had the loading icon for about half a second iirc. I’m also less confident about it being a black bishop now due to the same color square as other bishop.

**Comment by freefal** [comment]
Something odd is indeed going on there, but without steps to reproduce I don't think we can realistically fix the issue. If something similar happens in a reproducible manner, please report again.
