### ISSUE TITLE
Why Does StockFish Level 8 Make Bad Moves?

### ISSUE THREAD

**Issue by goodcyrus** [veloce/lichobile#1555]
**Describe the bug**
After solving a puzzle, I use "continue game from here" and play against stockfish level 8 albeit with a few points advantage.  Stockfish repeatedly makes terrible novice mistakes and loses easily.  This happens all the time.  I can make a video showing this.

**To Reproduce**
1. Go to puzzles, solve puzzle.
2. Click on 'Analysis'
3. Choose "continue from here with computer"
4. Choose local computer (android)
5. use level 8
6. See Stockfish making a LOT of novice mistakes and sacrifices.
7. The analysis of the game may show the errors Stockfish 8 made!!!

**Expected behavior**
This has started happening in the past few weeks.  I play against level 8 so I learn from a master chess player but all these errors ruins the game and makes the wins too easy.

**Screenshots**

**Smartphone (please complete the following information):**
Android 9 on Samsung Galaxy S8 using lichess app.

**Additional context**
example
[Event "Casual Game"]
[Site "https://lichess.org"]
[Date "2/13/2021, 1:03:47 PM"]
[White "goodvirus"]
[Black "Black"]
[Result "1-0"]
[PlyCount "105"]
[FEN "r2q1rk1/1p1nbpp1/p1p4p/3pN3/3Pb3/PB3Q2/1PPB1PPP/R3R1K1 w - - 0 15"]
[Variant "Standard"]
[Termination "mate"]

29. Rxe4 g5 30. Nxd7 f5 31. Nxf8 fxe4 32. Qf5 Qxf8 33. Bxd5+ cxd5 34. Qxd5+ Kh8 35. Qxb7 Rd8 36. Qxe4 Qf6 37. g4 Kg7 38. Re1 Kf8 39. Bb4 Bxb4 40. axb4 Kg7 41. Qe7+ Qxe7 42. Rxe7+ Kg6 43. c3 Rd6 44. h3 Kf6 45. Rh7 Kg6 46. Rh8 Rf6 47. d5 Rf4 48. Rc8 Kf7 49. c4 Ke7 50. Rh8 Rxc4 51. Rxh6 Kf7 52. Rh5 Rc2 53. Rxg5 Ke7 54. Rg8 Kf7 55. Ra8 Rc4 56. Rxa6 Re4 57. Kg2 Re5 58. d6 Rd5 59. b5 Rc5 60. d7 Kg7 61. d8=Q Re5 62. Qc7+ Kf8 63. Ra8+ Re8 64. Qd6+ Kg7 65. Ra7+ Kg8 66. Qg6+ Kf8 67. Qf7# 1-0

ANOTHER 

[Event "Casual Game"]
[Site "https://lichess.org"]
[Date "2/13/2021, 2:00:55 AM"]
[White "White"]
[Black "goodvirus"]
[Result "0-1"]
[PlyCount "130"]
[FEN "2r1k3/3R1p2/4p2p/1pB1Pp2/3R3r/1P6/P1P5/1K6 b - - 0 33"]
[Variant "Standard"]
[Termination "mate"]

66. Rxd4 Re7+ 67. Kd8 Re8+ 68. Kxe8 Bxd4 69. Ke7 Bb6 70. h5 a4 71. bxa4 bxa4 72. h4 Bd4 73. h3 Bc3 74. h2 Bb4+ 75. Ke8 c3 76. h1=Q+ Kc2 77. Qe4+ Kd1 78. Qxb4 cxb4 79. f4 Ke2 80. Rc4 a5 81. Rxb4 Kf3 82. Kf8 a6 83. Ra4 Kg4 84. Kg7 Kh5 85. Rxa6 Kg4 86. Ra4 Kh3 87. Re4 Kg4 88. Kg6 Kh4 89. Rxe5 Kh3 90. Kg5 Kg2 91. Re3 Kf2 92. Kg4 Kg2 93. Re5 Kg1 94. f3 Kf2 95. Re2+ Kf1 96. Kg3 Kg1 97. f2+ Kf1 98. Re1# 0-1

**Comment by veloce** [comment]
you forgot to provide the app version

**Comment by veloce** [comment]
I can reproduce too, thanks for reporting

**Comment by papb** [comment]
Hello, looks like ae0826f changed the level 8 elo from 3000 to 2850, why does this solve the problem? Just curious. Thanks for the great work in this app!

**Comment by veloce** [comment]
because stockfish max elo is 2850 when you set the limit strength option, so I guess that 3000 had the effect to take the default which is 1350... I played one game at level 8 and I didn't see any big mistake, that's why I think it solved the issue.

**Comment by goodcyrus** [comment]
Something went wrong with puzzles in the last update.  No more graph of you
rating history.  Puzzles became too easy as if I'm not logged in and
elementary puzzles are presented to me without regard to my rating.
Continue from here seems to be playing at 1400 level. Some good moves and
30% terrible moves.  Just my observations.   Hope it helps and thanks to
all the great people who created and are improving this app and that site.
I have some suggestions in case anyone is interested.

**Comment by tillchess** [comment]
> because stockfish max elo is 2850 when you set the limit strength option, so I guess that 3000 had the effect to take the default which is 1350... I played one game at level 8 and I didn't see any big mistake, that's why I think it solved the issue.

Which Stockfish is used on iOS and on Android?
