### ISSUE TITLE
Inbox keeps showing 1 unread message.

### ISSUE THREAD

**Issue by Dobrevmotorsport** [veloce/lichobile#1561]
Although I deleted all of my Lichess inbox, it keeps showing "Inbox (1)", but I simply don't have any unread messages.
That was the case with my previous device Motorola G6 Play, that is the case with my current Xiaomi Mi T10 Lite device - OS Android 10QKQ1.200628.002!

https://www.dropbox.com/s/sxt098r8renuxko/Screenshot_2021-02-17-10-27-24-477_org.lichess.mobileapp.jpg?dl=0

**Comment by freefal** [comment]
@ornicar - I can confirm this issue. For me, the server is responding to this request (https://github.com/veloce/lichobile/blob/master/src/ui/inbox/inboxXhr.ts#L9) with `4` despite my not having any unread messages. Would you mind taking a look when you have a moment?
