### ISSUE TITLE
Bug in zen mode on Android

### ISSUE THREAD

**Issue by basso01** [veloce/lichobile#1568]
**Describe the bug**
I played games with zen mode on Android and the movements were uncoordinated, I did several "mouse sleep".

**To Reproduce**
1 - Enable Zen mode in settings
2 - Play a game
3 - The houses were inaccurate to click, with flaws
4 - I returned to normal mode
5 - I played without Zen mode and everything was fine

**Smartphone (please complete the following information):**
 - Device: Motorola G7 Power
 - OS: Android

**Comment by veloce** [comment]
Fixed in version 7.7.2, please update
