### ISSUE TITLE
The computer gets stuck and doesn't play its move

### ISSUE THREAD

**Issue by MrRCK** [veloce/lichobile#1570]
I was playing anti chess level 6 in the android lichess app and the computer (black) didn't play its next move. I waited for about 5 minutes or so. I had to resign in the end.

Here's the game: https://lichess.org/p80XImI9

**Comment by veloce** [comment]
looks more like a server side issue to me, this should not be posted here, this is only the mobile app repo

**Comment by MrRCK** [comment]
Thank you, I wasn't aware of that.
