### ISSUE TITLE
Android version requirement ?

### ISSUE THREAD

**Issue by aleste81** [veloce/lichobile#1571]
Hi, I see we can download android apk from the recent 7.8.1 release to the old 4.7.0, but it is not clear which Android version is needed.
I thought using my old tablet Galaxy Tab 10.1 to launch Lichess, but it is Android 4.0.4 and it says 
"there is a problem parsing the package".

**Comment by veloce** [comment]
android 4 is no longer supported, sorry

**Comment by aleste81** [comment]
so I guess android 5 is ok ?
can I launch the old version with 4 ?
