### ISSUE TITLE
Long term premoves

### ISSUE THREAD

**Issue by eyal282** [veloce/lichobile#1572]
**Is your feature request related to a problem? Please describe.**
Chess.com uses a very good method of premoving. You can premove as many moves as you want which can save you if you need to do something like a ladder mate or convert a devestatingly winning position into more time on your clock to avoid losing. [...]

**Describe the solution you'd like**
Premoving will be possible as many times as you want. Settings menu will have a button that can be resized to terminate all premoves.

**Describe alternatives you've considered**
Losing. Not gonna ever download chess.com. Open Source is superior in every way.

**Comment by fynsta** [comment]
That's an feature request for [ornicar/lila](https://github.com/ornicar/lila) and not for this repository. Also, there it has been declined repeatedly, see [this issue](https://github.com/ornicar/lila/issues/3890)

**Comment by papb** [comment]
What about #1490?

**Comment by fynsta** [comment]
Those are in only in correspondence games and they work a bit differently. But those could be built in because they already exist in the lila Repository
