### ISSUE TITLE
Engine eval taking 5+ secs to load

### ISSUE THREAD

**Issue by Leonardshelby27** [veloce/lichobile#1577]
Since downloading Stockfish 13, all my browsers take over 5 seconds to load an engine evaluation of a new position, even when I'm using a browser that is not using Stockfish 13! This has been noticeable from the day I installed Stockfish 13 (which I can only use with Chrome Beta) but I had been assuming it would go away. Wtf is going on??

**Comment by veloce** [comment]
This is the app repo, not the website. Issues regarding websites should be filed in ornicar/lila repo.
