### ISSUE TITLE
Display bug for analysis

### ISSUE THREAD

**Issue by wrigjl** [veloce/lichobile#1579]
iPadOS 14.4

when I request an analysis, I get the hour glass and then a few seconds later I hear the “ding” of the completed analysis, but the time/analysis window only shows the time. If I click the notation tab and come back to the analysis tab, the analysis graph shows up.

**Comment by jas14** [comment]
Probable duplicate of #1526.

**Comment by wrigjl** [comment]
It totally is... I missed 1526 in my search
