### ISSUE TITLE
Illegal move with pawn in A4

### ISSUE THREAD

**Issue by miloleoelia** [veloce/lichobile#1580]
After I moved my black pawn in C4 adversary capture my pawn in C3. This is an illegal move.

**Phone hardware**
Redmi note 8 M1908C3JG

**Phone operating system version**
Android 10 QKQ1.200114.002

**MIUI version**
MIUI Global 12.0.3 Stable

**Version of lichess mobile**
7.8.1

**Steps to reproduce**
Chessboard with black pawn in A4 and white pawn in B4, try to capture with black pawn. This bug is present also in offline mode.

**Description of the observed behavior**
You can capture the white pawn even though you shouldn't

**Description of the expected behavior**
You can't capture the white pawn

https://user-images.githubusercontent.com/20434282/109524526-eaf9bc00-7ab0-11eb-9c34-fe66858cf5ca.mp4

**Comment by fynsta** [comment]
[En Passant](https://en.wikipedia.org/wiki/En_passant), it's a legal move... Don't worry, you're not the first one

**Comment by miloleoelia** [comment]
Okay, sorry, I didn't know about it. Thank you for your reply.
