### ISSUE TITLE
Adding time to opponent's clock

### ISSUE THREAD

**Issue by Diwaditya** [veloce/lichobile#1585]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm not able add 15 sec to my opponent's clock when he is low on time... The "➕" icon to add time is not visible in the mobile site.

**Describe the solution you'd like**
A good solution would be to decrease the size of the clock and add the ➕ icon. 

**Describe alternatives you've considered**

**Additional context**
See how PyChess manages to add the ➕ icon...
![Screenshot_20210305-184317_Samsung Internet](https://user-images.githubusercontent.com/79149430/110120383-fb78a200-7de2-11eb-9b06-edd53cd62b04.jpg)

**Comment by jas14** [comment]
If you didn't know, this is already available: When you are playing a non-correspondence game, if you tap the menu icon in the lower-left corner, the pop-up contains an option to add 15 seconds.

**Comment by Diwaditya** [comment]
@jas14 Screenshot please.

**Comment by jas14** [comment]
here you are:

https://user-images.githubusercontent.com/569991/110145457-72904500-7da7-11eb-84cf-7d9382ea1365.mov

**Comment by jas14** [comment]
@Diwaditya correct, we don't intend to have exact UI parity with the website
