### ISSUE TITLE
King in a puzzle check is not red.

### ISSUE THREAD

**Issue by eyal282** [veloce/lichobile#1597]
![Screenshot_20210314-154018_lichess](https://user-images.githubusercontent.com/39803639/111071108-47ab9c80-84dd-11eb-87d5-95e9486b529c.jpg)
Being checked in a puzzle doesn't turn the king red

**To Reproduce**
1. Go to 'Lichess Mobile'
2. Click on 'Puzzles'
3. Wait for a puzzle that checks you.
4. Bug found

**Expected behavior**
All checked kings are red with the given setting enabled.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy A12.
 - OS: unsure. Latest.
 - Version: Latest.

**Comment by jas14** [comment]
Can repro on Android, OxygenOS 10.3.8, app version 7.9.0 by visiting:

https://lichess.org/training/555521547
