### ISSUE TITLE
When castling results in a check, king square does not turn red like it usually does

### ISSUE THREAD

**Issue by trhaynes** [veloce/lichobile#1605]
**Describe the bug**
If I castle and that puts the opponent king in check, the square doesn't turn red like it usually does when in check

**To Reproduce**
1. Example game: https://lichess.org/ydzTw40T
2. When I review the game, the square does turn red. But when playing the first time, it doesn't. See screenshot below

**Expected behavior**
Usually the king square goes red when the king is in check

**Screenshots**
![IMG_5853](https://user-images.githubusercontent.com/294560/111571330-c9146080-8763-11eb-926a-a2b4dfa82031.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.4
 - Version v7.9.0

**Comment by jas14** [comment]
Can repro on Android, OxygenOS 10.3.8, app version 7.9.0.
