### ISSUE TITLE
I received 45 extra seconds in a bullet game.

### ISSUE THREAD

**Issue by Julian-creator** [veloce/lichobile#1612]
When I played a bullet game, on my 36th move  my time changed from 26.5 to 1:11.5.

https://lichess.org/RwsHWKpS/white

**Comment by jas14** [comment]
There is a feature that allows you to grant your opponent additional time, in increments of 15 seconds. Since the difference is exactly 45 seconds, I'm 99% sure Black gave White 3 x 15 additional seconds in that game.
