### ISSUE TITLE
Not able to eat queen with pawn

### ISSUE THREAD

**Issue by debuti** [veloce/lichobile#1615]
**Describe the bug**
In a regular match against the CPU the following situation happened
![Screenshot_2021-03-21-21-43-02-005_org lichess mobileapp](https://user-images.githubusercontent.com/243249/111920619-4277c000-8a90-11eb-8e9a-19dea9e6b8c2.jpg)

I cannot move the pawn an eat the black queen, it happened two times in a row

**To Reproduce**
Steps to reproduce
1. Open new match against CPU 
2. Manage to have the oponent queen in front of the pawns
3. Try to eat the queen

**Expected behavior**
The queen is eaten by the pawn.

**Comment by freefal** [comment]
Your pawn is pinned to the king by the rook (if it moved your king would be in check), and so capturing the queen is not a legal move.
