### ISSUE TITLE
App crash when opened

### ISSUE THREAD

**Issue by kotem13** [veloce/lichobile#1620]
**Describe the bug**
The app instantly crashes when you open it.
If you uninstall+reinstall the app or if you clear all of the app's data, the next time you open the app, it works that one time.
After you close the app, opening it again will instantly crash it. It crashes again and again until reinstall/data clear.

**To Reproduce**
1. Uninstall if needed.
2. Reinstall.
3. Open once, everything works normally; close.
4. Try to open again -> instant crash

**Expected behavior**
No crashing

**Smartphone:**
 - Device: Xiaomi Mi 8
 - OS: Android 10
 - Browser: AndroidWebView¿?
 - Version: 7.9.0 (lichess app version)

**Additional context**
The issue stays no matter how many times i restart the phone or uninstall+reinstall the app.

The log outputs this:

name: chess.mobileapp  >>> org.lichess.mobileapp <<<
uid: 10425
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
  <...like 20 hex nums...>

backtrace:
      #00 pc 00000000034529dc  /data/app/com.google.android.webview-_W7IH64Aj6Fa8UhMBDNXvQ==/base.apk!libmonochrome.so (offset 0x2d3000) (BuildId: 95f822edbc9f6b7eae5123e2b88ce8cf430204b4)

**Comment by veloce** [comment]
Are you able to use android studio in order to debug this?

**Comment by kotem13** [comment]
This started happening to me with the app from google play, not a dev build or anything like that.

I believe prod builds cannot be debugged, right?
I will try to get dev build working so I can try to debug the issue.

**Comment by lennonstan240** [comment]
I had this happen last night, not just for Lichess, many apps. I found a reddit thread that said the problem could be solved by uninstalling android webview, did that and I've not had any app crashes since. 

https://www.reddit.com/r/oneplus/comments/mb062y/many_apps_force_closing_solution_8t/

may be unrelated of course but this worked for me.

**Comment by kotem13** [comment]
Yesterday no update for the AndroidWebView appeared for me, but today there's a new one.

Installing the update has corrected the issue.

Also, Stan is right, today a few more apps have started doing weird stuff. Updating also solves issues for these.
