### ISSUE TITLE
Disable chat button with pop up

### ISSUE THREAD

**Issue by DaniSpringer** [veloce/lichobile#1624]
If chat is disabled, then instead of opening a full screen page to tell me that, just have a toast like “white is victorious” upon tapping on the chat button on the iOS app

**Comment by DaniSpringer** [comment]
Anyone here?

**Comment by jas14** [comment]
Not sure this is generically possible, as chats aren't full-on disabled; for a given user, they're either writeable or read-only. If they're read-only, they may 1) already have messages and 2) may continue to receive messages, so it's still useful to show the chat.
