### ISSUE TITLE
Movetime and Depth in offline Stockfish play

### ISSUE THREAD

**Issue by tillchess** [veloce/lichobile#1626]
Saw in Engine.ts that a certain movetime is used in offline Stockfish play with the formula 

```
const maxMoveTime = 5000
function moveTime(level: number) {
  return level * maxMoveTime / 8
}

```
vs low Depth in offline Computer play

```
const levelToDepth: Record<number, number> = {
  1: 5,
  2: 5,
  3: 5,
  4: 5,
  5: 5,
  6: 8,
  7: 13,
  8: 22
}
```

My point is: having these low depths the movetime isn't taking into account by Stockfish anyway because the Depth is reached quickly before movetime runs out.
An alternative Approach is just to use depth as a limiter or a higher depth and a shorter movetime?!.

**Comment by veloce** [comment]
Not sure to understand your point here. The thing is that we want to limit the depth for lower levels, no matter what the move time is, and we want to ensure at the same time that the computer doesn't spend too much time thinking at the highest level.

**Comment by tillchess** [comment]
Got it.
