### ISSUE TITLE
Which Stockfish versions are used ?

### ISSUE THREAD

**Issue by tillchess** [veloce/lichobile#1627]
Which Stockfish version is used on iOS currently?

This multivariant one?

 https://github.com/ddugovic/Stockfish

On Android it's Stockfish.js maybe ?

 https://github.com/niklasf/stockfish.js/tree/ddugovic/src

**Comment by veloce** [comment]
On iOS it's the multivariant one yes: https://github.com/ddugovic/Stockfish 
The version used is indicated on analysis tab (it's a date).

On android it's stockfish 13 for standard and 960 chess. Project source: https://github.com/veloce/capacitor-stockfish
It's using the original stockfish source code pointing to the sf_13 release tag.
For other variants it's using the same multivariant version as iOS.

The reason it's different on iOS (it doesn't have the standard stockfish 13), is a technical one: I could not manage to embed 2 stockfish versions as static librairies. They conflict with each other and this make the app crash.

**Comment by veloce** [comment]
I forgot to tell you @tillchess that there are 2 flavors of Stockfish 13 for android, one with NNUE enabled, and one without.
The version available on google play store is the classical one.
The version with NNUE can be found here: https://github.com/veloce/lichobile/releases. Note that it's only available for devices with an ARM 64bit CPU.
