### ISSUE TITLE
Bug during the game after move of my opponent the game was a draw without asking, without doing 3 same moves or any other rule

### ISSUE THREAD

**Issue by dragonflydoji** [veloce/lichobile#1628]
At move 34 for the Black the game was automatically draw and I don't know why. I am Dragonflydoji, with white in clear advantage, I don't know how it is possible it is a draw.

Go to: https://lichess.org/vecvq3Ox

Please have a look and give my points for the winning, as the game il clearly won and I didn't ask for a draw.

You can verify from this screenshot of the chat:

![Screenshot_20210326-224143_lichess](https://user-images.githubusercontent.com/81445877/112695480-7550f800-8e84-11eb-8cd2-46f3a83818bc.jpg)

Thanks

**Comment by jas14** [comment]
@dragonflydoji , this actually isn't a bug, it's [threefold repetition](https://en.wikipedia.org/wiki/Threefold_repetition). The same position occurred three times within a game (see https://lichess.org/vecvq3Ox#60, https://lichess.org/vecvq3Ox#64, https://lichess.org/vecvq3Ox#68) so your opponent had the right to claim a draw.
