### ISSUE TITLE
Read and write messages from mobile

### ISSUE THREAD

**Issue by LaPingvino** [veloce/lichobile#163]
same as tournament, tentative future?

**Comment by veloce** [comment]
You mean private messages ? It is planned, in a near future I believe :)

**Comment by LaPingvino** [comment]
Yes, exactly :)

**Comment by veloce** [comment]
@ornicar what do you think about having PM in mobile app? IMO it's a nice to have.

**Comment by ornicar** [comment]
I've never seen it requested, as opposed to push notifications, (offline) training, and tournaments.

**Comment by veloce** [comment]
Fair enough
