### ISSUE TITLE
Notications: Vibrate on Game Events: only on opponents turn.

### ISSUE THREAD

**Issue by misterbeebee** [veloce/lichobile#1639]
I am requesting an option for the Vibrate on Game Events feature to only vibrate on opponent's move.

I don't need a vibration to remind me that I am moving, but in fast games I want the vibration as a backup in case I don't see/hear the opponent's move.

This is especially important if the opponent premoves and the indicators for my move and their move are at the same time, and the clock is small.

Thank you

**Comment by veloce** [comment]
Seems logical yes.

**Comment by misterbeebee** [comment]
Thank you!

I hope this change doesn't make anyone unhappy.
