### ISSUE TITLE
the mouse does not work in the mobile app

### ISSUE THREAD

**Issue by pacogomez1964** [veloce/lichobile#1641]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by veloce** [comment]
The app was not meant to be used with a mouse. You have the website for that.

**Comment by pacogomez1964** [comment]
Being able to use the mouse in the app improves the accessibility of the
game, in addition to the fact that the Malloria tablet support is already
prepared to be used in a pc format, this improvement, which is already
included in the most used places in online gaming, would be greatly
appreciated.
