### ISSUE TITLE
Login bug in the lichess android app (Website works) 

### ISSUE THREAD

**Issue by Bauernmord** [veloce/lichobile#1647]
Bug-description:

Login interface of the lichess app doesn't work anymore. If i type in my username + Pw it says "wrong username or password" or sometimes "something went wrong" 
If i type in the exact same username+Pw on the website it works perfectly fine so it must be an error concerning the app.

**To Reproduce**
1. Go to login on lichess app
2. Add username + Pw
3. Message: "something went wrong"

**Expected behavior**
Successful login on the website

Smartphone:
 - Device: Huawei P30 lite
 - OS: Emui 9.1.0 (newest version) 
 - newest lichess app version

**Additional context**
I already head desync. problems with the app starting a couple weeks before login became impossible. It started with not counting my tactics point followed by delaying to show my past matches. 

Standard procedures (reinstalling the app, deleting cache and app data... ) didn't solve the issue.

**Comment by freefal** [comment]
I can't reproduce this. Logging out and in works fine for me.

**Comment by jas14** [comment]
@Bauernmord are you still encountering this issue? If so, can you double-check there are no spaces at the beginning or end of the username or password fields? (See #1806)

**Comment by Bauernmord** [comment]
It works now.
I think i had connectivity issues with the app.

Kind regards
Andreas

Joe Stein ***@***.***> schrieb am Mi., 18. Aug. 2021, 00:12:
