### ISSUE TITLE
Changing piece set renders incorrect king in puzzle

### ISSUE THREAD

**Issue by joshdavis739** [veloce/lichobile#1650]
**Describe the bug**

When in a puzzle, changing the piece set will not update the king icon next to 'Your turn'.

**To Reproduce**

1. Load up a puzzle.
2. Click the hamburger menu and open the settings.
3. Select 'Piece set'.
4. Change your piece set.
5. Click back a couple of times to go back to the puzzle.

The piece set on the board will have updated, but the king icon next to 'Your turn' will not have updated.

**Expected behavior**

I would expect the king icon to update to the new piece set.

**Screenshots**

![Screenshot_20210414-204803_lichess](https://user-images.githubusercontent.com/40396856/114773047-73cd6e00-9d66-11eb-85a8-6522bae4daa4.jpg)
![Screenshot_20210414-204821_lichess](https://user-images.githubusercontent.com/40396856/114773062-77f98b80-9d66-11eb-8289-6a2b1b96c139.jpg)
![Screenshot_20210414-204827_lichess](https://user-images.githubusercontent.com/40396856/114773069-79c34f00-9d66-11eb-8af5-845bcd723d25.jpg)
![Screenshot_20210414-204836_lichess](https://user-images.githubusercontent.com/40396856/114773074-7af47c00-9d66-11eb-9e4c-55a456360a80.jpg)
![Screenshot_20210414-204841_lichess](https://user-images.githubusercontent.com/40396856/114773085-7d56d600-9d66-11eb-948e-4f3e5024cc0b.jpg)

**Smartphone (please complete the following information):**

 - Device: Galaxy S7 Edge
 - OS: Android 8.0.0
 - Browser: Stock Chrome, version 89.0.4389.105
- Version: android app, 7.10.0

**Comment by jas14** [comment]
Thanks for the detailed report. I can also reproduce this on my OnePlus 6, OxygenOS 10.3.9, Lichobile v7.10.0.
