### ISSUE TITLE
Puzzles can have multiple solutions 

### ISSUE THREAD

**Issue by foley2k2** [veloce/lichobile#1664]
Here's one:
https://lichess.org/training/433789613

Both the rook and queen can be used to checkmate.
It doesn't matter which is moved if it wins the game.

There are probably other puzzles like this. To fix, it may be a good idea to check the last move of each puzzle for alternates.

**Comment by jas14** [comment]
Thanks for writing in, but that's not correct for this puzzle. After Rh5+, White can respond with Bh3. You can use the analysis board to confirm this.

**Comment by foley2k2** [comment]
Thanks, just started actually doing puzzles, still working through the
1500s, so could easily miss something.

**Comment by icegood** [comment]
strange example. Rook move is an obvious error. 

Rh5 + ? Bh3!
