### ISSUE TITLE
PGN export bug with black to move

### ISSUE THREAD

**Issue by tmmlaarhoven** [veloce/lichobile#1667]
**The bug**
The PGN export starting from positions where black moves first is incorrectly formatted. If the moves are Nc6 Nf3 Nf6 for instance, the PGN export should have moves 1... Nc6 2. Nf3 Nf6, but instead the export shows 2. Nc6 Nf3 3. Nf6.

**To Reproduce**
1. Go to 'Board editor' in app
2. Click on gear in bottom left and select 'Black to play'
3. Click 'Analysis board' icon on bottom
4. Make some moves
5. Use 'Share & export', and copy to clipboard to get the incorrectly formatted PGN

**Screenshots**
![image](https://user-images.githubusercontent.com/11218275/116922455-b2639380-ac55-11eb-97f9-4595c3a77876.png)
![image](https://user-images.githubusercontent.com/11218275/116922471-b98aa180-ac55-11eb-9e7b-31cbeeca694b.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 3
 - OS: Android

**Comment by jas14** [comment]
I can repro this in development. Looks like an issue communicating to chessground, or an issue with chessground itself.

**Comment by tmmlaarhoven** [comment]
(This seems to be an issue specific about the app by the way - if you do the same steps on the site directly you do get the right format for the PGN.)
