### ISSUE TITLE
Pawn promotion suggestion in Analysis board changes color when it's the opposite color's turn to move

### ISSUE THREAD

**Issue by vvdevadass** [veloce/lichobile#1676]
I noticed the bug while analyzing the puzzle 94449327.

The below bug occurs at [move 40 of this game](https://lichess.org/9sVANEDz/black#79) in the Lichess mobile Android app.
The promotion suggestion which is a black Queen here changes to White Queen when it's white's turn to move in the app. 
I don't see the same behavior in the Firefox browser on mobile or PC.

Observed behavior:
Pawn promotion suggestion in Analysis board changes color when it's the opposite color's turn to move.
Expected behavior:
Pawn promotion suggestion in Analysis board should stay the same color.

Phone model: OnePlus 6
OS: OxygenOS 10.3.9 / Android version 10

Attached snapshots.

Suggestion shows a Black Queen on Black's move 40 as seen in this snapshot:
![Screenshot_20210509-234810](https://user-images.githubusercontent.com/50523278/117583273-ef32fd00-b123-11eb-936b-c317ccd908f1.jpg)
Suggestion changes to White Queen on white's move 41 as seen in this snapshot:
![Screenshot_20210509-234830](https://user-images.githubusercontent.com/50523278/117583274-f0642a00-b123-11eb-8421-3dbf3582ef8a.jpg)

**Comment by jas14** [comment]
Thanks for the detailed report!
