### ISSUE TITLE
Update WebSocket API

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#168]

**Comment by ornicar** [comment]
note to self https://github.com/ornicar/lila/commit/dca9db83689adcb137711d1cf41b3a5cdaf33c27

**Comment by veloce** [comment]
Noted: and I'm renaming the issue

**Comment by ornicar** [comment]
The server now delivers both old and new events. When do you reckon I can drop BC?

**Comment by veloce** [comment]
I suppose you can plan something like a month after v2.0 release. Your call ;) We can test again the `status` xhr to see if it works.
