### ISSUE TITLE
Menu pop-up at end of the game

### ISSUE THREAD

**Issue by AmbroiseS** [veloce/lichobile#1687]
It's not technically a bug 
It's just pretty infuriating to me especially in bullet to have the menu pop-up over the game when the game ends
(Which can introduce many sorts of misclicks when you are out of time and trying to be fast in bullet)
Also i like to reflect on the game not just restart directly

Maybe I am the only one to think like that, I'd like to hear what other think 🙂

**Comment by jas14** [comment]
This is a duplicate of #1683.

**Comment by AmbroiseS** [comment]
Sorry I missed it
I will close the issue
