### ISSUE TITLE
Queenside castling not allowed in imported game

### ISSUE THREAD

**Issue by giordy** [veloce/lichobile#1690]
**Describe the bug**

I imported this PGN game, described in a chess book (I used Chessify to generate the PGN from the image of the board:

```
[Event "?"]
[FEN "r1bq1rk1/pp1n1ppp/2p1p3/8/2PPpB2/P3P2P/1P3PP1/R2QKB1R w - - 0 1"]
[SetUp "1"]
[Date "2021.05.20"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[Site "https://chessify.page.link/main"]
*
```

After moving the White Queen from the first rank, it is not possible to perform Queen side castling.

**To Reproduce**
1. Import the PGN
2. move Qd2 f5
3. Attempt 0-0-0 for white
4. It doesn't allow it

**Expected behavior**
Queen side castling for white should be allowed

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11

**Comment by jas14** [comment]
@giordy this isn't a bug with the app; the issue is that the initial FEN in the PGN you have provided indicates that there is no castling ability (the 3rd space-separated field is blank). Please refer to e.g. https://www.chessprogramming.org/Forsyth-Edwards_Notation for more details

**Comment by giordy** [comment]
@jas14 you're totally correct, now I also learned something new :)

Sorry for the unnecessary issue, I'll close it.
