### ISSUE TITLE
No time but results draw

### ISSUE THREAD

**Issue by Anxoba** [veloce/lichobile#1693]
The oponente has no time but the result was draw

[Event "Rated Bullet game"]
[Site "https://lichess.org/hfAWkdX2"]
[Date "2021.05.21"]
[White "Anxoba"]
[Black "Trojanites"]
[Result "1/2-1/2"]
[UTCDate "2021.05.21"]
[UTCTime "17:39:03"]
[WhiteElo "1101"]
[BlackElo "1093"]
[WhiteRatingDiff "+0"]
[BlackRatingDiff "+0"]
[Variant "Standard"]
[TimeControl "120+1"]
[ECO "B01"]
[Opening "Scandinavian Defense"]
[Termination "Time forfeit"]
[Annotator "lichess.org"]

1. e4 { [%clk 0:02:00] } 1... d5 { [%clk 0:02:00] } { B01 Scandinavian Defense } 2. e5 { [%clk 0:01:56] } 2... f6 { [%clk 0:01:58] } 3. d4 { [%clk 0:01:55] } 3... Nc6 { [%clk 0:01:56] } 4. Nf3 { [%clk 0:01:55] } 4... Bg4 { [%clk 0:01:55] } 5. Nbd2 { [%clk 0:01:52] } 5... fxe5 { [%clk 0:01:53] } 6. dxe5 { [%clk 0:01:45] } 6... Nxe5 { [%clk 0:01:53] } 7. h3 { [%clk 0:01:43] } 7... Nxf3+ { [%clk 0:01:44] } 8. Nxf3 { [%clk 0:01:42] } 8... Bf5 { [%clk 0:01:37] } 9. Bd3 { [%clk 0:01:41] } 9... e6 { [%clk 0:01:30] } 10. Bxf5 { [%clk 0:01:41] } 10... exf5 { [%clk 0:01:30] } 11. Qe2+ { [%clk 0:01:41] } 11... Qe7 { [%clk 0:01:29] } 12. Qxe7+ { [%clk 0:01:36] } 12... Bxe7 { [%clk 0:01:30] } 13. Bf4 { [%clk 0:01:30] } 13... O-O-O { [%clk 0:01:30] } 14. Ne5 { [%clk 0:01:26] } 14... Rf8 { [%clk 0:01:07] } 15. O-O-O { [%clk 0:01:21] } 15... Nf6 { [%clk 0:01:02] } 16. Bg5 { [%clk 0:01:13] } 16... c6 { [%clk 0:01:01] } 17. Bxf6 { [%clk 0:01:12] } 17... Bxf6 { [%clk 0:01:01] } 18. Rhe1 { [%clk 0:01:07] } 18... Re8 { [%clk 0:00:59] } 19. Nd3 { [%clk 0:01:02] } 19... Rxe1 { [%clk 0:00:56] } 20. Rxe1 { [%clk 0:01:02] } 20... Rd8 { [%clk 0:00:49] } 21. Nf4 { [%clk 0:01:01] } 21... Bg5 { [%clk 0:00:46] } 22. Kb1 { [%clk 0:01:00] } 22... Bxf4 { [%clk 0:00:45] } 23. g3 { [%clk 0:00:59] } 23... Bd2 { [%clk 0:00:44] } 24. Re7 { [%clk 0:00:59] } 24... Rd7 { [%clk 0:00:44] } 25. Re6 { [%clk 0:00:57] } 25... g6 { [%clk 0:00:42] } 26. g4 { [%clk 0:00:56] } 26... Be1 { [%clk 0:00:36] } 27. f4 { [%clk 0:00:55] } 27... Bg3 { [%clk 0:00:34] } 28. gxf5 { [%clk 0:00:53] } 28... gxf5 { [%clk 0:00:33] } 29. Rf6 { [%clk 0:00:51] } 29... Bxf4 { [%clk 0:00:31] } 30. Rxf5 { [%clk 0:00:51] } 30... Bd2 { [%clk 0:00:24] } 31. Rf8+ { [%clk 0:00:48] } 31... Kc7 { [%clk 0:00:23] } 32. Rf2 { [%clk 0:00:48] } 32... Be3 { [%clk 0:00:23] } 33. Rf3 { [%clk 0:00:48] } 33... Re7 { [%clk 0:00:23] } 34. h4 { [%clk 0:00:45] } 34... h6 { [%clk 0:00:22] } 35. h5 { [%clk 0:00:45] } 35... Re5 { [%clk 0:00:21] } 36. Rh3 { [%clk 0:00:44] } 36... a5 { [%clk 0:00:20] } 37. c3 { [%clk 0:00:43] } 37... b5 { [%clk 0:00:20] } 38. b3 { [%clk 0:00:42] } 38... b4 { [%clk 0:00:18] } 39. Kc2 { [%clk 0:00:39] } 39... bxc3 { [%clk 0:00:18] } 40. Kxc3 { [%clk 0:00:37] } 40... d4+ { [%clk 0:00:18] } 41. Kd3 { [%clk 0:00:37] } 41... c5 { [%clk 0:00:16] } 42. a3 { [%clk 0:00:35] } 42... Re6 { [%clk 0:00:13] } 43. Rf3 { [%clk 0:00:34] } 43... Rb6 { [%clk 0:00:12] } 44. Kc4 { [%clk 0:00:30] } 44... a4 { [%clk 0:00:10] } 45. bxa4 { [%clk 0:00:28] } 45... Rb1 { [%clk 0:00:08] } 46. Kxc5 { [%clk 0:00:27] } 46... Rc1+ { [%clk 0:00:08] } 47. Kd5 { [%clk 0:00:27] } 47... Ra1 { [%clk 0:00:07] } 48. Rf7+ { [%clk 0:00:28] } 48... Kb6 { [%clk 0:00:07] } 49. Rf6+ { [%clk 0:00:28] } 49... Ka5 { [%clk 0:00:07] } 50. Rxh6 { [%clk 0:00:27] } 50... Bxh6 { [%clk 0:00:05] } 51. Kxd4 { [%clk 0:00:25] } 51... Rxa3 { [%clk 0:00:05] } 52. Kc4 { [%clk 0:00:26] } 52... Rxa4+ { [%clk 0:00:05] } 53. Kc5 { [%clk 0:00:26] } 53... Rh4 { [%clk 0:00:04] } 54. Kd6 { [%clk 0:00:25] } 54... Rxh5 { [%clk 0:00:05] } 55. Ke6 { [%clk 0:00:26] } 55... Rg5 { [%clk 0:00:04] } 56. Kf6 { [%clk 0:00:27] } 56... Kb5 { [%clk 0:00:03] } 57. Ke6 { [%clk 0:00:26] } 57... Kc5 { [%clk 0:00:03] } 58. Kf6 { [%clk 0:00:26] } 58... Kd5 { [%clk 0:00:02] } 59. Kf7 { [%clk 0:00:26] } 59... Ke5 { [%clk 0:00:02] } 60. Ke7 { [%clk 0:00:26] } 60... Rg6 { [%clk 0:00:01] } 61. Kf7 { [%clk 0:00:25] } {  wins on time. } 1/2-1/2

Please consider change the result

**Comment by jas14** [comment]
@Anxoba , this is not a bug; it's a rule of play.

[USCF](http://www.uschess.org/docs/gov/chessrules/US_Chess_Rule_Book-%20Online_Only_Edition_v7.1-1.2.11-7.19.19.pdf) says:

> 14E. The game is drawn **even when a player exceeds the time limit** if one of the following conditions exists as of the most recently determined legal move:
> 14E1. Lone king. **Opponent has only a lone king.**

The [FIDE rule book](https://www.fide.com/FIDE/handbook/LawsOfChess.pdf) has several similar provisions for drawing the game if a player cannot checkmate the other by any legal series of moves.

In any case, this is a server-side decision. If you disagree with this rule, you can open a discussion on [the lichess discord](https://discord.gg/hy5jqSs), or open an issue on https://github.com/ornicar/lila.

**Comment by Anxoba** [comment]
Thank you very much for tour quick answer. I understand It. I didn't know
It.
Happy to learning thanking to you.
Best regards
Anxoba
