### ISSUE TITLE
Display Toast When Game Is Over

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1704]
Game ends suddenly and this leads to confusion. Sometimes I accidentally mated and I'm sitting there waiting for a move. Sometime the clock ran out and I didn't realize and I'm waiting for nothing...

I posted this at the end of the closed issue #1683 but I think notifications don't work for closed issues or something.

**Comment by jas14** [comment]
@landry314 fixed in 16edfa3c0ceade40fd15309674d8ca95d6d9dd22 , it'll be out in the next version!
