### ISSUE TITLE
Show game end dialog automatically

### ISSUE THREAD

**Issue by Kolos65** [veloce/lichobile#1707]
First I was planning to report a bug, but than I saw _"- don't show game end dialog automatically"_ in the latest release. I am not familiar with the reasons behind this change, but I strongly support putting back the gameover dialog, since I constantly get confused at the end of bullet games and stare at a finished game's board for 30 sec until I recognise that the time ran out.

**Comment by jas14** [comment]
@Kolos65 thanks for your feedback, the toast is coming back in the next version (see #1704). Closing this issue as I believe the toast resolves it, feel free to re-open (or open another issue) if you'd like to see something different.
