### ISSUE TITLE
New Cellphone, lichess fails to launch

### ISSUE THREAD

**Issue by SamoGanzas** [veloce/lichobile#1709]
**Describe the bug**
Hello. I've installed lichess on my new phone and it fails to launch. Whenever i click the App it shows the lichess logo and then gets stuck on a white screen. I've already reinstalled it and it status the same. 

**To Reproduce**
1. Go to Apps
2. Click on Lichess
3. See error

**Expected behavior**
Lichess launching as normal. 

**Screenshots**
![Screenshot_20210602-202515](https://user-images.githubusercontent.com/85254775/120540813-02fb1780-c3e1-11eb-8c8a-25967bac04b3.jpg)

![Screenshot_20210602-202814](https://user-images.githubusercontent.com/85254775/120540904-1e662280-c3e1-11eb-84f1-1b25357d4fc9.jpg)

.

**Smartphone (please complete the following information):**
 - Device: LE X527
 - OS: Android 6.0.1.
 - Version lichess 7.11.1

**Comment by freefal** [comment]
Your new phone appears to be running Android 6, which is quite old. Your best bet is to upgrade Android to the most recent version available for your phone and make sure you have the latest version of Chrome installed.

**Comment by SamoGanzas** [comment]
Thank you. I've Chrome updated, and no prompt for update in the system. Guess I'll just play on PC. 
Thanks once again.
