### ISSUE TITLE
move confirmation on correspondence games

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#171]
I just did it for the website: https://github.com/ornicar/lila/commit/3f3906a783a06cb7cdd5d2334836bd4ff99cfe38#diff-1c3a7da4b196677c3bbe565cc2b971d8L40

I think it would be even more useful on mobile.

**Comment by veloce** [comment]
Yep, sure. For the UI I don't know how though. A regular confirm would hide the move just played... so maybe a custom confirm popup at the bottom.

**Comment by ornicar** [comment]
Note that there exists a lichess setting about it, check your preferences page.

**Comment by veloce** [comment]
Yep I kept that setting on purpose. People can only disable it in website, which is fine.
