### ISSUE TITLE
[BUG]: Wrong pawn move & attack 

### ISSUE THREAD

**Issue by SUPERustam** [veloce/lichobile#1721]
**Describe the bug**
Wrong move and attack pawn.

Link to bug game: https://lichess.org/TNXPcDBH/white (move `16. b4 axb3`)

**To Reproduce**
Link to bug game: https://lichess.org/TNXPcDBH/white (move `16. b4 axb3`)

**Expected behavior**
I expected that pawn don't move to `b3` and don't eat my pawn (`b4`)

**Screenshots**
![image](https://user-images.githubusercontent.com/64551202/121865957-29855080-cd07-11eb-8a6b-e889418faabc.png)
![image](https://user-images.githubusercontent.com/64551202/121865998-330eb880-cd07-11eb-889b-4fc9d5f1e72e.png)

**Smartphone**
 - Device: iPhone 7 128gb
 - OS: IOS 14.6
 - Browser: Official Mobile app from App Store
 - Version v7.11.2

**Additional context**
If screenshots don't open, use these links: 
https://ibb.co/F0rQcS3
https://ibb.co/L1vgF67

**Comment by jas14** [comment]
This is not a bug, it's a [rule of the game](https://en.wikipedia.org/wiki/En_passant).

**Comment by SUPERustam** [comment]
Thank you, i am noob in this game:)
