### ISSUE TITLE
Redirect from browser to app by clicking puzzle gives error

### ISSUE THREAD

**Issue by 95111** [veloce/lichobile#1728]
**Description of the bug**
When logged in on Lichess.org (on mobile) using a browser (my example is Brave) you should click on the daily puzzle on the homepage at the bottom. Then you will get redirected to the app (with the error).

**To Reproduce**
1. Open Lichess.org on your browser (my example is brave) when logged in
2. Scroll down to "Puzzle of the day"
3. Click on "Puzzle of the day"
4. See the error, by getting the message from the app "Resource not found"
(video link down below)

**Expected behavior**
You exspect, that the browser redirects you to the app without that error and instead gives you the puzzle of the day to solve.

**Video of the behavior**
https://user-images.githubusercontent.com/59793489/122194500-ca097b00-ce95-11eb-991a-631215eca0f4.mp4

**Smartphone:**
 - Device: Razer Phone 2 [EU]
 - OS: Android 9
 - Browser: Brave
 (I was using the newest version of everything mentioned)

**Additional context**
This is one of my first issues that I'm writing on GitHub. If there are any unclear instructions or other things you would like to see improved, I would be thankful if you tell me your improvements.

**Comment by jas14** [comment]
Can reproduce. We need to make exceptions for special V2 URLs, e.g /training/daily, /training/mix, etc, otherwise we treat "daily" as a puzzle ID. Not sure if we should just wait until Puzzles V2 for this.

**Comment by 95111** [comment]
> Can reproduce. We need to make exceptions for special V2 URLs, e.g /training/daily, /training/mix, etc, otherwise we treat "daily" as a puzzle ID. Not sure if we should just wait until Puzzles V2 for this.

Obviously I'm not a active developer on this project, so I'm not able to imagine the effort that would go into this. But as far as I know there is no official "release date" for Puzzles V2, right? So maybe it would be a better approch (seen in the future) to fix it.

**Comment by jas14** [comment]
Leaving a technical note for whoever picks this up (possibly me, possibly you @95111 if you have any interest 😉): we'll need to copy the [list of puzzle theme keys](https://github.com/ornicar/lila/blob/a2e63d82bdcc8597ca8d6decfaf905a6a1e2e977/modules/puzzle/src/main/PuzzleTheme.scala#L14-L79) into the mobile app and I suppose exclude those from deep links. Not sure how to present this to the user, maybe a toast saying we don't support puzzle themes yet?

**Comment by 95111** [comment]
> Leaving a technical note for whoever picks this up (possibly me, possibly you @95111 if you have any interest 😉): we'll need to copy the [list of puzzle theme keys](https://github.com/ornicar/lila/blob/a2e63d82bdcc8597ca8d6decfaf905a6a1e2e977/modules/puzzle/src/main/PuzzleTheme.scala#L14-L79) into the mobile app and I suppose exclude those from deep links. Not sure how to present this to the user, maybe a toast saying we don't support puzzle themes yet?

Seems like a good idea although you can't really count on me with that problem. I'm a beginner in the world of programming & I'm not really familiar with the project structures of both lichess & lichobile.
