### ISSUE TITLE
No games in Correspondence tab

### ISSUE THREAD

**Issue by kimoloka** [veloce/lichobile#1733]
**Describe the bug**
On the home screen, there are two tabs: Quick Pairing and Correspondence. Usually, I select a game from the list of games in Correspondence. But in the past few days, there are no games in the Correspondence tab. This only happens on my Samsung phone. On the website there is usually a long list of requested games in the Correspondence tab. 

**To Reproduce**
1. Go to Home
2. Click on 'Correspondence'
4. See error: No list of games

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment]
Hi @kimoloka , thanks for the report.

This was a server-side backwards-compatibility issue and was resolved in https://github.com/ornicar/lila/commit/46f08c22c05ed22dd9cdc794f1da63ed1804f3bf, which was deployed about 18 hours ago. I'm going to close this issue as I believe it should be resolved by the above, but please re-open the issue if you're still having this problem.
