### ISSUE TITLE
Scrolling list of games on iPad is horrible

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#174]
Need to fix the scroll somehow for all devices

**Comment by veloce** [comment]
Won't fix for now. Waiting for future cordova-ios version and wkwebview.

**Comment by peutetre** [comment]
Did you tried `-webkit-overflow-scrolling: touch;`?

**Comment by veloce** [comment]
It's iScroll for now (since ios devices can't repaint during scroll). This is the only page where it happens since it's an infinite scroll and the dom is pretty heavy.
I tested on a old iPad, so the main reason is insufficient hardware for such intensive scroll. I'm not sure native scroll and wkwebview would fix the issue but it can't be worse

**Comment by peutetre** [comment]
you may also have a look at https://github.com/cubiq/iscroll/blob/master/build/iscroll-infinite.js
