### ISSUE TITLE
I think there are two equally good solutions in training task 72618088 #9y8Ix

### ISSUE THREAD

**Issue by sl5net** [veloce/lichobile#1743]
I think there are two equally good solutions in https://lichess.org/training/9y8Ix

best moves are:
g3>g2,c6>b5,b5>b4

best moves are not:
g3>g2,c6>b5,g2>g1,b5>b4

but I don't see any disadvantage in the second variant. In variant two, the horse is a little further away because it takes the farmer on the edge. Could be an advantage. I think both solutions should be valid?

**Comment by jas14** [comment]
@sl5net thanks for the feedback but we don't make the puzzles. They're partially derived from Stockfish-determined centipawn advantages, so please first analyse the position with Stockfish and/or no computer assistance first. If you still are still quite convinced the puzzle has many equally good solutions, please open an issue on GitHub.com/ornicar/lila.
