### ISSUE TITLE
Links open to browser on mobile, not app

### ISSUE THREAD

**Issue by chewie01100** [veloce/lichobile#1745]
I have Lichess on my mobile. When friends share matches via a link, it used to open to the app, now it opens to the browser. This is annoying, as the mobile browser version is inferior to the app version.

**Comment by jas14** [comment]
Probably introduced by https://github.com/veloce/lichobile/pull/1706 and a misconfigured apple-app-site-association. Fixing the latter will be faster than creating a release to remove the `/white` perspective path segment.

**Comment by jas14** [comment]
apple-app-site-association resolved, this should be all set. Thanks for the report @chewie01100 !

**Comment by jas14** [comment]
For anyone continuing to experience this issue on v7.11.x: you will need to either uninstall and reinstall the app, or update the app (once applicable), to fix the deep link map on your device.
