### ISSUE TITLE
Change of highlighting color of the board squares

### ISSUE THREAD

**Issue by Ticat25882** [veloce/lichobile#1752]
Could you make the highlighting of the squares change according to the board theme chosen in the mobile app? Just like the website. Since in some themes the highlighting is not clearly distinguishable. Here is an example of the mobile app compared to the website.

![Screenshot_20210702-153119_lichess](https://user-images.githubusercontent.com/86854211/124323052-9b0a2f00-db4e-11eb-91ef-857fa9f86681.jpg)

![Screenshot_20210702-152947_Samsung Internet](https://user-images.githubusercontent.com/86854211/124323075-a65d5a80-db4e-11eb-8337-1b26f4c8cd72.jpg)

Android Version: 11
App version: 7.11.3

**Comment by jas14** [comment]
Thanks for the detailed report @Ticat25882 . Looks like we have to special-case certain board themes [like lila does](https://github.com/ornicar/lila/blob/b08b7b079a9bd4eabf976cb67b9015d7ab56a176/ui/common/css/vendor/chessground/_chessground.scss#L42-L46).
