### ISSUE TITLE
Not possible to get information about time situation even in the analysis.

### ISSUE THREAD

**Issue by baack** [veloce/lichobile#1759]
**Describe the bug**
Not possible to get information about time situation even in the analysis.

**To Reproduce**
1. Play a game
2. The game is finished, but moving back-forward with move does not change time on screen, not even after the game finished
3. Enter analysis and once again - moving back-forward with move does not change time on screen

**Expected behavior**
The time is changed according the time situation on the exact move, like in web version of Licess. At least in analysis but preferable after the game too (when the game finished and uses did not entered analysis yet).

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 8.1

**Comment by jas14** [comment]
The time shown on the clock doesn't change on the website when you navigate backwards and forwards through the game, even after the game has ended.

I can't reproduce the issue where the time on the screen doesn't change in analysis mode - do you mind providing a couple screenshots or a short screen capture?

**Comment by baack** [comment]
> The time shown on the clock doesn't change on the website when you navigate backwards and forwards through the game, even after the game has ended.

* When I open any game URL in browser and navigate backward/forward though the moves - the time changes accordingly.
* When I open the same game URL in Lichess APP and navigate backward/forward though the moves - the time is always the same (that it was at the end of the game).

There is even no way to check what time left for player when some particular move was made.
Check yourself.

**Comment by jas14** [comment]
@baack ah yes - on the website, if you view _someone else's_ game, you'll see the time changes as you navigate, but if you view _your own_ game, you'll see this:

<img width="855" alt="Screen Shot 2021-07-06 at 9 56 24 AM" src="https://user-images.githubusercontent.com/569991/124612609-78269600-de40-11eb-8d26-75df6da46c6b.png">

Note the large clocks on the right - those do not change.

Now, on the _mobile app_, if you view anyone's game (including your own) _before going into analysis_, you'll see something similar to the above. Once you go into analysis mode, you'll see this - note the small time indicators _do_ change:

https://user-images.githubusercontent.com/569991/124619288-837cc000-de46-11eb-99ff-9deb3af1587d.mov

**Comment by baack** [comment]
Thanks for detailed reply.
The problem is I have no clock in analysis at all. Maybe it's screen-size depended bug? Or because I'm not logged in? Also I see no nicknames in analysis when I played without logging in (expected to be both "Anonymous").
Please check the after-game analysis on your device after playing quick game without login (you will be instantly paired with another Anonymous).

**Comment by jas14** [comment]
Got it, now I see. I can reproduce this issue as a logged-out user. I imagine the entire player info bar is being hidden for anonymous players, which includes the time indicator.

**Comment by jas14** [comment]
@veloce I see this behavior was intentionally introduced in 35d80f1d2885f47fa1d6f9c6d542ad9e6b2b3f6c - do you remember the context? If you think hiding everything but the clock in the player bar is acceptable, I can do that - example:
![Screen Shot 2021-07-06 at 8 00 10 PM](https://user-images.githubusercontent.com/569991/124680636-c796b180-de94-11eb-9d85-9b263d295ebb.png)

**Comment by veloce** [comment]
Sorry @jas14 I don't remember the context. I think you can do that yes. Is it possible that the clock information for past games is not available to anon. users though?

**Comment by baack** [comment]
> Is it possible that the clock information for past games is not available to anon. users though?

Not possible, the clock information is shown when I open the same games via share link on the lichess.org.

------------------

Maybe there is a room for an an additional improvement - to show the time situation without entering analysis in the after-game. Like the game finished and browsing back-forward changes the time. And on the final move - the time is the same it was when the game ended. I see no reasons why not?

**Comment by baack** [comment]
@jas14 please take a look at minor regression related: #1874.

**Comment by free5lot** [comment]
Please revert this bug fix because it introduced way bigger problems due to breaking clicking layout of the board in account-less post-game analysis (see #1875).
