### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by bade387** [veloce/lichobile#1766]
At the start screen, the lichess logo appears with a white background, this background is uncomfortable for the eye, especially in the case of low lighting.
I suggest changing this white background to another color that's more comfortable for the player's eye.
Thank you for your understanding.

**Comment by jas14** [comment]
@bade387 is this a duplicate of #1366?

**Comment by bade387** [comment]
@jas14 Actually, I didn't pay attention to that.
If that's against the instructions, please let me know.

**Comment by jas14** [comment]
It's helpful for us to merge reports of the same issue. If the images attached to that issue would solve your problem, please give it a +1 / "thumbs up" and you can close this issue.
