### ISSUE TITLE
Login Bug 

### ISSUE THREAD

**Issue by wgibbs6198** [veloce/lichobile#1787]
**Describe the bug**

Login does not work for mobile app, but does work on web browser. 

**To Reproduce**
1. Go to Login
2. Fill out information 
3. Click on login
4. See error - "Invalid Username or Password"

**Expected behavior**

Login correctly, it logins in just fine if I access it via web browser. 

**Screenshots**

![Screenshot_20210727-112015_lichess](https://user-images.githubusercontent.com/88048468/127198010-b3fb52ec-cd80-4111-98d1-7770ee23515c.jpg)

![Screenshot_20210727-121152_Chrome](https://user-images.githubusercontent.com/88048468/127198208-148de1c2-e37b-4fc4-a18a-0b7a55754548.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: Android 
 - Browser: mobile app
 - Version: 10

**Additional context**

Login DOES work on web browser, but DOES NOT work on mobile app.

**Comment by jas14** [comment]
@wgibbs6198 can you double-check that no spaces were accidentally entered at the beginning or end of the the username or password fields? See: #1806, #1807

**Comment by wgibbs6198** [comment]
That's it, it was a dumb space. Thank you very much!!
