### ISSUE TITLE
Takeback bugged

### ISSUE THREAD

**Issue by Kaento** [veloce/lichobile#1794]
My game had a takeback and it showed my opponent not having moved yet and his time ticking down but in the end I lost
![Screenshot_20210807-154739](https://user-images.githubusercontent.com/20619562/128615913-33d8ffaa-f347-4db3-ab7b-6584d32f40da.png)

**Comment by jas14** [comment]
I'm closing this issue as a duplicate of #1607, but thank you for the report - it's useful to know this is still happening.
