### ISSUE TITLE
Left-sided game clock

### ISSUE THREAD

**Issue by rajsinghUSA** [veloce/lichobile#1798]
Please include a switch for a left-sided game clock on the Android app, so right-handed mobile players can see the clock in bullet chess.  Thank you!

**Comment by jas14** [comment]
This already exists in the left hand menu -> Settings -> Clock

![Screenshot_20210810-213919_86d667449b00b848f46d695606363a65~2](https://user-images.githubusercontent.com/569991/128957069-530b5993-4435-4eb7-a96e-4fa62daca24a.jpg)
