### ISSUE TITLE
Illegal pawn capture

### ISSUE THREAD

**Issue by jungleskraa** [veloce/lichobile#1799]
**Describe the bug**
In this bullet game move 5 wasnt legal - https://lichess.org/Tot71T8L/white#10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment]
All of the moves in that game appear to be perfectly legal. If you have a particular reason to believe any of them were not, please explain why.

**Comment by fynsta** [comment]
There is a pawn on f4. Lol

**Comment by Notproffesionalcoder** [comment]
Yeah exactly you are 2200+ and this tbh @jungleskraa
