### ISSUE TITLE
Drag config for otb games

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#180]

**Comment by filkaris** [comment]
I could take this on.

From what I understand we just need a "draggable" option added in the "settings" menu that enables/disables draggability regarding ONLY offline games.

Puzzles and online games will remain unaffected by this setting, since you mention only "otb games". 

Is that ok?

**Comment by veloce** [comment]
No sorry I should close this. I was a reminder for me to have a drag config special for otb games, to not shift the piece up during dragging. But it's not important, I won't do it right now.

**Comment by filkaris** [comment]
I see, is there anything else basic you need any help on?
