### ISSUE TITLE
antichess always promotes to queen

### ISSUE THREAD

**Issue by shabbychef** [veloce/lichobile#1802]
**Describe the bug**

When playing antichess against the computer, the computer always promotes a pawn to a queen, even when it is not optimal.

**To Reproduce**
1. Go to board editor
2. Set up the following FEN: `8/6k1/8/8/8/K7/3p4/2R5 b -- 1 2`
3. Continue from here
4. Play offline against Computer
5. Play White in Antichess

Computer promotes pawn to queen, immediately losing. I believe a rook promotion will lead to a draw.

**Expected behavior**
Computer should consider promoting to pieces other than a queen.

**Smartphone (please complete the following information):**
 - Device: Motorola One 5G Ace
 - OS: Android 10
 - Version Lichess v7.11.3

**Comment by shabbychef** [comment]
Exploring a little bit, I have found that the problem is not restricted solely to antichess. In fact, when playing standard variants, it seems the computer always promotes to queen. As an example, use the board editor to enter the following position:

```
[FEN "8/8/8/8/8/2K5/1p5R/2k5 b - - 0 1"]
```

(_cf_ https://chess.stackexchange.com/a/810/13155 )
Play against computer, select standard chess, Stockfish level 8, let the computer play Black. The computer chooses to promote the pawn to queen, immediately losing to `Rh1`. 

So I suspect the problem is not that variant is not passed in, but rather stockfish is doing no thinking upon promotion.

**Comment by jas14** [comment]
Thanks for looking into this more! I can reproduce this - the engine only seems to be willing/able to promote to a queen (even though an analysis board shows the best move as a knight promotion). I believe this is a communication/parsing issue between the Stockfish engine and the app-level state management system.

@shabbychef would you like to tackle this one? `src/ui/ai/engine.ts` is almost certainly the culprit. (If not, no worries, I'm happy to take it.)

**Comment by shabbychef** [comment]
Sure, this will be a good exercise for me. (Cannot promise it quickly, of course.)

**Comment by shabbychef** [comment]
OK, I made some headway, I think. Testing in standard chess, I found that the bestmove received back from stockfish was only capturing the from and to squares (four characters). I fixed that to optionally pull 4 or 5 characters to get the promotion piece. This is then passed to `onEngineMove`, which needed to further pass on the `role`. I do not yet understand how `apiMove` works, but it seems like it needs the promotion piece as well.

WIP commit: https://github.com/shabbychef/lichobile/commit/b5d3d54c4906b7ac9aeaa174599d626cffcf2917

**Comment by shabbychef** [comment]
ok, I think I was passing along the  raw string like `'n'` in as the promotion `Role`, whereas poking around in the code it seems a `Role` has to be something like `'knight', 'queen'`, _etc_. I'll put in an ugly switch statement, though I assume there is a more elegant way to do it.

BTW, I am not sure about the text return stream from Stockfish. When Black promotes, I get back a `bestmove b1b2n`, but would it be capitalized for White? That is, would I have `bestmove b7b8N`?

**Comment by shabbychef** [comment]
OK, duh, found the `charToRole` function which does this.  I have a preliminary fix in place which needs testing. Still not sure I have passed on the proper information, however: it would seem that `apiMove` needs to know about the promotion as well.

**Comment by jas14** [comment]
Thanks @shabbychef , great work so far ! `chessground.apiMove` doesn't need to know about this, there's another `chessground` function, `promote` IIRC, that you can call.

**Comment by shabbychef** [comment]
Thanks for the hints, `uciToProm` indeed was what I was looking for (though it takes a 4-5 character string). Testing from this branch https://github.com/veloce/lichobile/compare/master...shabbychef:fix_promotion works for traditional chess: promotes to Knight in the above puzzle, can promote to a queen, etc. However, antichess has become totally unstable (and not just WRT promotion behavior). Not sure how I broke things so hard. It seems the engine is no longer getting the variant string?

**Comment by shabbychef** [comment]
It seems like other variants work fine, but antichess is still acting weird. Perhaps this is unrelated to my changes. It seems like`setoption name UCI_Variant value antichess` should be `setoption name UCI_Variant value giveaway` in the below:

![image](https://user-images.githubusercontent.com/1456159/131616820-c4057f26-32c0-4cd6-831e-19be718d1f77.png)

**Comment by shabbychef** [comment]
OK, fixed that in `src/stockfish.ts`, I think. Seems to work fine now. Not sure how that broke.
