### ISSUE TITLE
I think ive been hacked

### ISSUE THREAD

**Issue by Jeppeboystiago** [veloce/lichobile#1803]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. samsungA31]
 - OS: [e.g. android 10.1]
 - Browser [e.g. chrome]

**Additional context**
I was playing a chess tournament as I lost three of my games but then noticed I was I first place even though I was losing my friends were saying how well I played and then I left and came back and was unable to join  the game then sent I message to the whatsapp group and the creator of the tournament told me that it was because I was cheating as I played near perfect moves the entire game
I don't know weather it's a glitch or If I'd been hacked but it needs to be fixed because know I being accused of cheating

**Comment by jas14** [comment]
@Jeppeboystiago this is the repository for the source code for the mobile app - we deal with feature requests, bug reports, and other things related to the code of the mobile app itself; we don't handle bans, claims of hacking, or other operational concerns. You may find some helpful tips on securing your account in [this](https://lichess.org/forum/lichess-feedback/account-hacked) or other posts on the Lichess forum.
