### ISSUE TITLE
Fide title display next to username in tournaments

### ISSUE THREAD

**Issue by PanChee00** [veloce/lichobile#1814]
I think that it will be great in mobile app if in tournaments i can see the fide title of a user next to the username.

**Comment by Baikalcadillac** [comment]
Also while searching for a player there’s no title next to the username (website have such feature)

**Comment by jas14** [comment]
For https://lichess.org/tournament/URkPUgGL :

Website:
![Screen Shot 2021-08-22 at 9 45 34 PM](https://user-images.githubusercontent.com/569991/130378979-143dd9e5-f2ce-476b-8189-0d87dea5a6ac.png)

Mobile:
![Screen Shot 2021-08-22 at 9 45 50 PM](https://user-images.githubusercontent.com/569991/130379005-e7ed6ad1-b6ba-4094-8a84-b1f55ca1efdc.png)
