### ISSUE TITLE
OTB soft lock on pawn promotion.

### ISSUE THREAD

**Issue by Kinglink** [veloce/lichobile#182]
Hey guys I'm on the lichess beta. 

A. I love the move confirmation.

B. I was teaching my fiancee chess using the OTB setup.  However on our second game the moves were 
[Event "Casual game"]
[Site "http://lichess.org"]
[Date "2015.07.17"]
[Variant "Standard"]

1. e4 Nf6 2. f3 e5 3. Nc3 d5
4. exd5 Nxd5 5. Nxd5 Qxd5
6. a4 Bb4 7. Ra2 Nc6 8. Ne2 Bf5
9. Nc3 Qxa2 10. Nxa2 Nd4
11. Nxb4 O-O-O 12. Bc4 Nc6
13. Nxc6 bxc6 14. d3 e4
15. dxe4 Rxd1+ 16. Kxd1 Bd7
17. Re1 Rd8 18. a5 Be6+
19. Bd3 Rd5 20. exd5 Bxd5
21. Bf5+ Kb8 22. Re8+ Kb7
23. Bd7 Be6 24. Bc8+ Bxc8
25. Re5 Ka6 26. Be3 Be6
27. f4 Bg4+ 28. Ke1 f6
29. Rc5 Kb7 30. a6+ Kxa6
31. b4 Kb6 32. Rc4+ Kb5
33. Rd4 g5 34. c4+ Kxb4
35. c5+ Kxc5 36. fxg5 fxg5
37. g3 a5 38. Rd3+ Kc4
39. Rd2 a4 40. Rd4+ Kb3
41. Rxg4 a3 42. Bc1 a2 43. Rd4

Now I was going to move a1 and promote to queen.  I move a1 and the game soft locks.  I can't promote and she can't move.  I tried everything, the only thing I can do is take back the move.  

A shame I was about to show her why getting a new Queen spelt her doom.   Oh well.  Hope it's not impossible to reproduce.

**Comment by Kinglink** [comment]
Same situation in vs CPU games

**Comment by veloce** [comment]
Hey @Kinglink 

It was a bug indeed, you can try the new beta I just uploaded. Should be fixed now. Sorry for the inconvenience.
