### ISSUE TITLE
 missing pieces 

### ISSUE THREAD

**Issue by docj3530** [veloce/lichobile#1839]
Many pieces are missing 

![20F9464D-AB5B-4F7D-B9B2-B10E2535DA46](https://user-images.githubusercontent.com/90297642/132438327-1586b30a-cc01-4dcb-a5bd-0ab22f639da2.jpeg)

**Comment by veloce** [comment]
This is the website and not the application, issue should be posted to https://github.com/ornicar/lila instead, thanks.
