### ISSUE TITLE
When creating a tournament, the "Time" selector doesn't scroll

### ISSUE THREAD

**Issue by giordy** [veloce/lichobile#1844]
**Describe the bug**
When creating an Arena tournament, the "Time" selector doesn't scroll.

**To Reproduce**
1. Open the form to create a new tournament
2. Click on 'Time'
3. The list of times doesn't scroll

**Screenshots**
[Video displaying the problem.](https://user-images.githubusercontent.com/6016950/133165198-64052f65-89bd-4828-81db-b0199c742cbf.mp4)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11
 - Lichess App
 - Version 7.11.3

**Comment by jas14** [comment]
Thanks for the video, that's very helpful. Those are indeed the hard-coded supported start times:

https://github.com/veloce/lichobile/blob/8d85fce8e597bd645406de2efd8ee068592affaa/src/settings.ts#L356-L357

I suppose you're expecting to see all the options that the website offers too? (10, 15, 20, 25, 30, 40, 50, 60)? And same with increment? (currently the only supported increments on mobile are 0, 1, 2)

**Comment by giordy** [comment]
Yes, I guess one should have the same values. I was checking the form to simulate creating an arena for rapid have 10+0 and I noticed I couldn't select any value above 7.

About increments I guess it should be possible to have more values like on the website. 

But I don't know if there's a reason to not have the same list as in the website.

**Comment by jas14** [comment]
@veloce any reason you know of not to have the same tournament time options as the website?

**Comment by veloce** [comment]
They probably were the same at the time of implementation, and have changed since. So we should update.
