### ISSUE TITLE
(Android) App crashes when doing endless analysis on study 

### ISSUE THREAD

**Issue by Rerbun** [veloce/lichobile#1849]
**Describe the bug**
App completely shuts down if endless analysis is turned on while looking at a weird board set up, for example in a study.

**To Reproduce**
1. Go to study (for example: https://lichess.org/study/p1pdMu9b)
2. Turn on endless analysis
3. Go to chapter with weird board (for example: https://lichess.org/study/p1pdMu9b/7IXBprr5)
4. App shuts down completely

**Expected behavior**
Analysis should not affect the app if the board has no black pieces or in other weird scenarios while studying.

**Screenshots**
The chapter it crashes on:
![Screenshot_20210918-095510~2](https://user-images.githubusercontent.com/7070542/133881306-2806c4e0-661e-4394-8daa-fd993052241a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Android 11
 - Browser: Chrome (but NA.)
 - Version: 7.11.3

**Comment by veloce** [comment]
You can't run analysis on this position since there is no black piece. This is fixed in the upcoming version (analysis is disabled when the position is not valid).
