### ISSUE TITLE
Consistency is haphazard

### ISSUE THREAD

**Issue by chadparry** [veloce/lichobile#185]
When the network connection is temporarily lost, the game's consistency is no longer guaranteed. The typical way this manifests is that the player makes a move, then the app loses the connection, then regains the connection, and the app reports that no more moves are being made. To the player on the mobile app, it looks like the other player is still moving. Meanwhile, according to the server, the other player has already moved. Eventually, the app shows that the time runs out, and the player thinks that the game is won, when according to the server the game was lost.

I've seen several games on my own phone where an opponent's move was never reported to me. I also saw one game where the board shown on my phone was a board that never existed in the game; the opponent's queen and bishop were shown in places which they never actually occupied at the same time in the real game. These are all manifestations of the same consistency bug.

While the connection is down, a message can be lost. The app does not recover gracefully from a lost message. See https://github.com/veloce/lichobile/blob/2.1.x/project/src/js/StrongSocket.js#L189-L191. The correct protocol should be to have a message that updates the entire board state from the server, including all pieces, the move count, the clock, and other state. Then, that message should be requested whenever there is a gap detected in the message sequence.

Note that the web interface also has the same consistency bug. See http://en.lichess.org/qa/151/my-reconnected-games-dont-show-all-the-moves.

**Comment by veloce** [comment]
Thanks for the report. This issue has already been reported to me, but I couldn't reproduce at the time.
If you can provide steps to reproduce it would help me.
I'll investigate this when I have the time.

**Comment by chadparry** [comment]
I've seen this several times, and the repro seems to only require these steps:
1) Start a game.
2) Make a move.
3) Lose the network connection.
4) The remote opponent makes a move.
5) Restore the network connection.
6) The client doesn't get notified of the opponent's move.

**Comment by veloce** [comment]
Can't reproduce with these steps. The app normaly recovers by itself. In case of very poor network condition the app may have difficulties to resync from the server, even though it says it's connected. There's not much I can do against this.

**Comment by chadparry** [comment]
For the record, the problem is not that the app sometimes has a poor connection. The problem is that when it reconnects, you don't have any code to get the updated state from the server. The client assumes that its current state is close enough, which is not correct. This causes the board to look different on the client compared to the opponent. Also note that these synchronization issues do not reproduce every time, so just because you avoided the issue once does not mean the bug doesn't exist.

Unfortunately, Thibault has a similarly lackadaisical attitude towards consistency. He prefers to leave the bugs in the clients, instead of admit there is an issue, (https://github.com/ornicar/lila/issues/800)! Because of that, it's time for me to leave the site.

**Comment by chadparry** [comment]
Actually, I stand corrected. In the history for https://github.com/ornicar/lila/issues/800, it now shows that Thibault returned to the issue and submitted a fix. Quality in the web client is better than I thought.

**Comment by Unihedro** [comment]
He didn't "return" to the issue. He's been working on it despite how you never give up flaming on him. He never wanted to leave the issue hanging except for how you badgered him over and over again. Your expectation is subpar and that has nothing to do with this issue itself. Try to let it go already, okay?

**Comment by ornicar** [comment]
I applied the fix on serverside, so hopefuly it should improve the mobile app experience as well.

**Comment by veloce** [comment]
@chadparry the server will resync client if it detects a consistency problem between the versions. It sends a 'resync' message to the client which in turn gets the correct current game data by xhr.
See here: https://github.com/veloce/lichobile/blob/2.2.x/project/src/js/ui/round/socketHandler.js#L33

Website and app have the same behavior for resync. The only difference is that on the website you can manually trigger reload by hitting F5. 

What I'm saying is that if you have a poor network you may still receive a 'resync' message but fail to receive the data via xhr. In case of very poor network you shouldn't play a blitz. That being said I could not reproduce your issue with steps you gave above. Maybe those steps didn't fall into the edgecase fixed by aforementioned server side fix.

**Comment by chadparry** [comment]
I'm not sure what the release schedule is for your server-side code. I tried playing a game in the web client just now. Normally I would reopen the ticket and help contribute a fix, but out of respect I will not "badger" your team any more about this.
