### ISSUE TITLE
Display Style of pieces Changed 

### ISSUE THREAD

**Issue by CoJung** [veloce/lichobile#1855]
**Describe the bug**

The Bug: 
Pieces are looking weird. They are missing the black outline and dark and white pieces are nearly the Same schade of darkness ( See Screenshot )

I am not Sure If it is a bug. But since today the pieces are being displayed in a very different Style. I Trier Out all the Styles in the lichess settings but iT seems Like all of them are missing the black outline and the dark pieces are Just displayed was too bright. 

I checked all the settings on my Phone and I am 99% Sure that the slissue is Not my phone's fault. Also i didnt Change anything Form Yesterday when I Player Last Time to today. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2021-09-22-20-15-14-613_org lichess mobileapp](https://user-images.githubusercontent.com/18658816/134399655-03e03f4a-505b-42f1-b631-b08d6b70a574.jpg)
Screenshot of the issue

![Screenshot_2021-09-21-20-44-08-779_org lichess mobileapp](https://user-images.githubusercontent.com/18658816/134399708-96646f47-8260-46e6-9152-b909367a6c91.jpg)
Screenshot of the nicht before

**Smartphone (please complete the following information):**
 - Device: [redmi note 10]
 - OS: [MIUI global 12.5.1]
 - Browser [lichess Android app]
 - Version [na

**Additional context**

**Comment by juguitodeanana** [comment]
Hey, sorry, I have the same problem since a few days ago; I would like to ask you, how did you solve it?

PD: sorry for my english

**Comment by jas14** [comment]
@juguitodeanana this is probably a duplicate of #1859, see that issue - it's affecting only Xiaomi Redmi devices

**Comment by juguitodeanana** [comment]
Thank you! @jas14 @CoJung
