### ISSUE TITLE
All pieces are the same color for both white and black players 

### ISSUE THREAD

**Issue by MilitusInnocent** [veloce/lichobile#1859]
**To Reproduce**
Just when a game is started, all the pieces have the same color. Check attached screenshot 

**Expected behavior**
Should be white pieces and black pieces for players
![Screenshot_2021-09-24-07-39-11-979_org lichess mobileapp](https://user-images.githubusercontent.com/55919005/134630701-aef6c5f3-b807-4830-b24a-046f8017b1b9.jpg)
.

**Smartphone (please complete the following information):**
 - Device: Redmi note 9T
 - OS: Android 
 - Version 

**Additional context**

**Comment by rodrigoq** [comment]
Same happened to me last night, it was on dark mode on the OS. Disabling dark mode fixed it.

Xiaomi Mi 9T
MIUI 12.5.1
Android 11

**Comment by MilitusInnocent** [comment]
> Same happened to me last night, it was on dark mode on the OS. Disabling dark mode fixed it.
> 
> Xiaomi Mi 9T
> MIUI 12.5.1
> Android 11

This wasn't happening before. Can they kindly fix it the way it was because I can't use my phone on light mode cos of my eyes.

**Comment by courtier** [comment]
This started happening to me as well a couple days ago. Xiaomi Redmi Note 10 Pro. I am also using dark mode, switching to light mode fixes it.

**Comment by duhizjame** [comment]
If you choose a different set of figures(ie. merida) white figures will actually be black, and vice-versa on dark mode. I have aborted  two games for not starting because I thought I was black.
Xiaomi Redmi Note 9S

**Comment by jas14** [comment]
Best guess: the Xiaomi / MIUI default webview has a "best effort" dark mode that attempts to invert colors. Opening a "best effort" PR for this now

**Comment by fsaatci** [comment]
Same problem.so i have abort few games then i have banned because of it. 
![Screenshot_2021-09-27-13-31-28-999_org lichess mobileapp](https://user-images.githubusercontent.com/91466736/134893285-20d9ac82-d0f0-4556-8138-93a568c96185.jpg)
![Screenshot_2021-09-27-13-31-55-083_org lichess mobileapp](https://user-images.githubusercontent.com/91466736/134893288-f4b6b64f-4dc5-4f42-902e-777f87fb9db2.jpg)

**Comment by ornicar** [comment]
More reports

https://www.reddit.com/r/chessbeginners/comments/pwd9ll/lichess_update_glitch_how_do_i_fix_this/

![](https://i.redd.it/a9nnyjo9i0q71.jpg)

![](https://media.discordapp.net/attachments/807722604478988348/892333914700521512/Screenshot_2021-09-28-10-23-09-013_org.lichess.mobileapp.jpg)

**Comment by ornicar** [comment]
https://lichess.org/forum/lichess-feedback/all-piece-sets-mostly-invisible-except-pixel?page=1
https://www.reddit.com/r/lichess/comments/pwkmaf/why_is_this_happening_this_has_been_going_on_for/

and reported in many other places and emails
