### ISSUE TITLE
[enhancement] Show game type in game

### ISSUE THREAD

**Issue by losingkeys** [veloce/lichobile#186]
When I open up the lichess app it brings me to a game where it's my turn. This is great! However I always end up tapping the upper left icon that shows all games teice, to see what game on playing, because I'm usually playing a few games at once.

I think it would be useful to have the game type icon somewhere in the page when viewing/playing a game.

**Comment by Unihedro** [comment]
related ornicar/lila#764

**Comment by veloce** [comment]
You have a quick access to the game type, with the bottom left '...' button. On mobile portrait we don't have space to show it. If you try the landscape mode you'll see the game icon and type is always there.

**Comment by losingkeys** [comment]
Ahh, that menu opens a bit smoother, but it's still another tap.

What if the ... menu was the game icon? Then you'd know you're getting the menu for this game, and you could see the game type at a glance.

I can see this being a little not intuitive though if you're not used to it (I'm supposed to tap that?). Maybe it would be clear enough because it's near other buttons and we could make it the same gold outline color?

**Comment by veloce** [comment]
Closing this. Sorry I don't think we can replace the '...' button, it would feel odd.
