### ISSUE TITLE
The colour pieces has got very brighter and I would like to make it normal . Please help me with this bug

### ISSUE THREAD

**Issue by Ajinkya2222** [veloce/lichobile#1861]
![IMG_20210925_184151](https://user-images.githubusercontent.com/91377304/134772795-4fcb671b-b275-428c-b9d7-b2e4fe4152fb.jpg)
Please remove this bug , it has got all pieces getting really light coloured and brighter. I want it to normal

**Comment by jas14** [comment]
@Ajinkya2222 are you in dark mode? What is your operating system platform and version? Please fill out the issue template.

**Comment by Ajinkya2222** [comment]
I am using the dark mode . I am playing on miui 12.0.12 version , and
Android 10.
I am using redmi 9 to play

**Comment by jas14** [comment]
Duplicate of #1859.
