### ISSUE TITLE
Piece sets not rendering properly

### ISSUE THREAD

**Issue by kraktus** [veloce/lichobile#1865]
Several users have reported piece sets not rendering properly since the beginning of the week
![](https://i.ibb.co/sKgz2c7/Screenshot-20210927-181238.png)
> Clearing app cache, Uninstalling, restarting device, logging out and in, did not work.
 The Lichess app is straight from current google play store, but maybe my android version is old?
It is happening on browsers as well as the app.
Phone: xperia l3312
Android: 8.1.0

From: https://lichess.org/forum/lichess-feedback/all-piece-sets-mostly-invisible-except-pixel?page=1

**Comment by ornicar** [comment]
https://www.reddit.com/r/lichess/comments/pwkmaf/why_is_this_happening_this_has_been_going_on_for/

and reported in many other places and emails

**Comment by ornicar** [comment]
probably #1859
