### ISSUE TITLE
Piece rendering is messed up

### ISSUE THREAD

**Issue by bonstio** [veloce/lichobile#1873]
This happens a lot.

https://photos.app.goo.gl/sqifRkQyMkBuudtC8

**Comment by jas14** [comment]
I don't see anything wrong with the piece rendering here. Is the issue that the clock and game info are squished?

**Comment by bonstio** [comment]
Sorry if it's not clear. Check G5 in this screenshot from the video.

![image](https://user-images.githubusercontent.com/294411/135850353-14e2d2c7-761a-44d8-a209-0602eff7a582.png)

I have a bug report taken from the device at this time if that will help.

**Comment by bonstio** [comment]
Although the squished clock is another potential issue, it's less severe.

**Comment by jas14** [comment]
Ah, got it. I thought that link was to a picture, the video didn't load for me. Anyway, this looks like a duplicate of #1866 , so I'm going to consolidate the two - please give that one a thumbs-up
