### ISSUE TITLE
[Minor bug] Board jumps in analysis 'when not from the game' move is played because clock disappears

### ISSUE THREAD

**Issue by baack** [veloce/lichobile#1874]
**Describe the bug**
The board jumps in analysis 'when not from the game' move is played because clock disappears and the position of the board is changed. It's annoying and never should happen (never happens on web-site of course).
Reproducible 100% at least using accont-less mode (not logged in).

**To Reproduce**
1. Play a game (at least using accont-less mode, not logged in)
2. The game is finished, go to analysis.
3. Make any move that was not played in the game.
4. The clock dissappers and the board changes it's position right after piece move.

**Expected behavior**
The board stays on the same place.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 8.1
 - Version: 7.12.0

**Additional context**
This is regression in 7.12.0, caused by fixing this: #1759.

**Comment by jas14** [comment]
Almost certainly caused by #1771 😬
