### ISSUE TITLE
Stockfish version

### ISSUE THREAD

**Issue by GustavoConde22** [veloce/lichobile#1922]
I'm using the new version of lichess that should use stockfish 14.1, but mine is showing stockfish 11, is this a bug? 

version 7.14.0
device samsung A02s
android 11 ![Screenshot_20211122-205434_lichess.jpg](https://user-images.githubusercontent.com/54965992/142952486-fa6ab7ca-90fd-4c8c-a232-d5aa9539bcce.jpg)

**Comment by veloce** [comment]
It means your device doesn't support stockfish 14 (you need a 64bit ARM V8), and stockfish 11 is used as a fallback.
