### ISSUE TITLE
Long tap causes magnifying glass

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1926]
Pressing and holding most of the elements leads to magnifying in and having taptic feedback on iPhone X with iOS 15.1 (doesn't happen on iPhone 6 as it hasn't taptic engine).

**Comment by jas14** [comment]
Looks like we're [not the only ones](https://github.com/leaflet/leaflet/issues/7678) experiencing this issue, but it appears we'll have to wait until the WebKit fix makes it into a new iOS release. We [already have](https://github.com/veloce/lichobile/blob/049e9b7ab03158dac24a3f771d70bdbd727fd36b/src/styl/reset.styl#L41) a `-webkit-user-select: none` directive.

**Comment by Baikalcadillac** [comment]
Ok, then you can close this issue if needed, as it's not critical and can't be fixed without changes to iOS.

**Comment by Baikalcadillac** [comment]
It was fixed in iOS 15.2.
