### ISSUE TITLE
Resign confirmation

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#193]

**Comment by Unihedro** [comment]
You sure? The resign button is obscure enough not to mistakenly hit imo.

**Comment by veloce** [comment]
Well, I wanted to do it for a long time and I saw this is now on the website, so I thought.
I happened once to accidentally resign... it's very annoying but I reckon it's hard to hit it by mistake

**Comment by Unihedro** [comment]
Yeah, no problem, add it!

**Comment by veloce** [comment]
Actually I won't do it :)
