### ISSUE TITLE
Multiple lines don't apply to every move 

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1934]
Not sure if this is intended, but changing multiple lines in analysis board doesn't apply instantly and only after next move is made.

Steps to reproduce: 
1. Open analysis or analyze completed game.
2. Local evaluation and best move arrow should be enabled.
3. By default multiple lines is 1/5, so only one arrow is displayed, but if you change this number it doesn't apply to current position, only after next move.

Happens on iOS 12.5.5 and iOS 15.1 with lichess 7.14

**Comment by jas14** [comment]
This is also the case if you reduce the number of lines. I believe the evaluation cache isn't keyed on the number of lines. I don't think this is intentional.

**Comment by jas14** [comment]
I guess there are sort of two problems here:

1) The one I think you're referring to is that changing the number of lines, or in fact any computer evaluation setting as far as I can tell, doesn't immediately affect evaluation.
2) Another is that changing those settings won't necessarily change the evaluation that's displayed on situations that were previously evaluated. There's layer of caching happens on the move tree, where just one computer evaluation is cached on each move node. The code that updates a move node's evaluation [prefers computer analyses with higher depth](https://github.com/veloce/lichobile/blob/bbeba5e262084b10f209e35a866337c308e51f50/src/ui/analyse/AnalyseCtrl.ts#L670), regardless of the number of lines (`multipv`). Maybe we should expand that cache to key by number of lines.

**Comment by Baikalcadillac** [comment]
Right, I was expected that changing any of these settings would affect the board immediately (as on website) or maybe refresh the analysis board.
I understand that this issue isn't critical and if it's not hard to fix it would be nice.

**Comment by Baikalcadillac** [comment]
Unfortunately nothing has changed for me.
