### ISSUE TITLE
Old Lichess Version without 

### ISSUE THREAD

**Issue by SciFi2017** [veloce/lichobile#1944]
Does anyone know if there is an old version of Li-Chess without Firebase Analytics ?

**Comment by jas14** [comment]
The oldest version I'm aware of without Firebase Analytics is < 7.0, but that may have Google Analytics. No guarantees that such an old app version will even work with the current Lichess server. The TL;DR is that you'll have to compile your own build if you want to remove FCM (push notifications). If you do, submit a pull request for a new build flavor 🙂
