### ISSUE TITLE
Illegat castling with queen in android

### ISSUE THREAD

**Issue by DwarfPorter** [veloce/lichobile#1953]
**Describe the bug**
I can do castling with queen and rook.

**To Reproduce**
1. Play with chess, and move queen to rook
2. Rook jump over queen
Please see the next game
https://lichess.org/M8SgkKYF/black#90

**Expected behavior**
Rook do not jump

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android Xiaomi mi max
 - OS: android 7.0
 

**Additional context**

**Comment by jas14** [comment]
At what move does the illegal castle occur in that game? I don't see any illegal castle.

**Comment by DwarfPorter** [comment]
Sorry, my bad

пт, 17 дек. 2021 г., 9:44 Joe Stein ***@***.***>:

**Comment by jas14** [comment]
@DwarfPorter I'm taking it this issue was opened in error, so I'm closing it - please do comment if that's not the case
