### ISSUE TITLE
Android Zen Mode, Touch not properly aligned with UI.

### ISSUE THREAD

**Issue by shah-xad** [veloce/lichobile#1956]
**Describe the bug**
When I turn on Zen Mode on my mobile app the touch and the UI of the application are miss-aligned, it doesn't touch where it is supposed to be. For example, in the below screenshot if I touch at the red highlighted point of `g1`, it just selects at `g2`

![WhatsApp Image 2021-12-22 at 3 25 12 PM](https://user-images.githubusercontent.com/32363363/147078653-05d5c179-b878-4262-9949-d29d692944f7.jpeg)

**To Reproduce**
 Go to Setting>Game Display and turn on Zen Mode. If now I play any game it's just the worse. But if I turn on the Zen mode from the game menu during the gameplay it works fine. It just makes an issue when I turn it on from the settings. But it's not convenient to turn it on again and again from the game menu.

**Expected behavior**
 The touch and UI should be properly aligned.

**Smartphone (please complete the following information):**
 - Device: Huawei y9 Prime 2019
 - OS: Android 10
 - Mobile Lichess App
 - Version: the latest one from the Playstore

**Comment by Baikalcadillac** [comment]
This happened to me on iOS as well, I hope fix will affect it as well.

**Comment by shah-xad** [comment]
@veloce thanks for the fix, what do we expect about this to be released?

**Comment by shah-xad** [comment]
@veloce when would this update be available on Playstore?
