### ISSUE TITLE
Unresponsive buttons in arena tournaments

### ISSUE THREAD

**Issue by njamund** [veloce/lichobile#1963]
**Describe the bug**
In the Android mobile app, some buttons in arena tournaments often aren't working properly for me. Clicking on a player's name in the standings does nothing, and sometimes even the chat and pause/play buttons also do nothing.

**To Reproduce**
1. Go to Tournaments in the left pane of the mobile app. 
2. Click on a player's name. 
3. Back in the tournament page, click on the chat icon. 

**Expected behavior**
Clicking on the player name should show the player's games in the tournament and stats such as performance rating. Clicking on the chat button should open the chat. 

**Actual behavior**
Clicking on the player name and buttons often does nothing. Sometimes it works for some players but not others. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 11
 - Browser: N/A (mobile app from Google Play Store) 
 - Version: 7.14.0

**Additional context**
I started noticing this issue two or three days ago. It has occurred every time I've tried it since then. Restarting my phone and updating the app didn't fix it.

**Comment by jas14** [comment]
Can reproduce, OnePlus 6 running Android 11

**Comment by veloce** [comment]
Perhaps a BC break from server some time ago, but it'll be fixed anyway in the next version: https://github.com/veloce/lichobile/commit/c047bf37e66a5e1d94199ca86b681da4fe4500eb

**Comment by njamund** [comment]
I installed 7.14.1, and it does appear to be fixed. Thanks!
