### ISSUE TITLE
Announcement message is too wide

### ISSUE THREAD

**Issue by Baikalcadillac** [veloce/lichobile#1970]
One line message definitely don't need that much space. Happened today on iPhone X with zen mode on.

![photo_2022-01-06_18-35-00](https://user-images.githubusercontent.com/67504540/148417135-4113a450-ff25-4c3c-8c1e-48f5c501b4de.jpg)

**Comment by jas14** [comment]
Can reproduce, the `padding env(safe-area-inset-top)` directive is wrong - that should just be `padding-top`. Will open a PR shortly
