### ISSUE TITLE
Ping information showing in wrong language after changing language back in Android app

### ISSUE THREAD

**Issue by wojtekweg** [veloce/lichobile#1986]
**Describe the bug**
After changing the language to a different one, reopening the app and changing language back the ping information (next to the ping label) is showing in wrong language. This happens on an android application.

**To Reproduce**
Steps to reproduce the behaviour:
1 Go to settings -> language
2. Select some language different than english
3. Close and reopen app
4. Change language back to english
5. Go to menu and click the question mark next to ping label

**Expected behaviour**
Displayed information should be in the currently selected language

**Screenshots**
![Screenshot_20220116-000247_lichess](https://user-images.githubusercontent.com/49337058/149675128-e8bf1281-5b13-4f97-ba1b-e482b58773ca.jpeg)

**Smartphone:**
- Device: Samsung S10
- OS: Android 11
- Lichess app of version 7.13.1

**Comment by jas14** [comment]
Line I suspect is to blame:

https://github.com/veloce/lichobile/blob/9f8a65b3d67816cccb803bcdfc87a5471f783d5c/src/ui/menu/menuView.tsx#L20

That constant is evaluated once.
