### ISSUE TITLE
Moving two squares up but counting one step up instead

### ISSUE THREAD

**Issue by AlenToma** [veloce/lichobile#1987]
**Describe the bug**
There is a very series bug in the android app version.

This bug makes people crazy.

But it dose not happen all the time and that is why I am having trouble reporting it.

This is how the bug happen. The user move a solder one step down and I move my solder two step up. This will make sure that the opponents solder will not be able to attack my solder but still he is able to do just that.

On my screen I can see that I moved two step up but for the other side he sees only one step up.

I hop I am making this clear.

I am 100% that other user experience this too.

**To Reproduce**
1. Opponents solder move one step down 
2. And you move two step up so that the opponents solder dose not able to attack you 
3. Then the opponents still able to attack you and kill your solder as if you have moved 1 step up.

**Expected behavior**
When I move two step up it should count as two step up and not one.

**Smartphone (please complete the following information):**
 - Device: Samsung s10 lite 
 - OS: 11

**Comment by jas14** [comment]
This is called en passant and it's a legal move. See https://lichess.org/learn#/15 , https://en.wikipedia.org/wiki/En_passant

**Comment by AlenToma** [comment]
Whaaat really ?? Did not know that :) ok thx
