### ISSUE TITLE
online friends

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#20]

**Comment by frankcalise** [comment]
Is there an API available to retrieve a player's friends?

**Comment by ornicar** [comment]
Yes. https://github.com/ornicar/lila/blob/master/doc/mobile/friends.md

It's a websocket API, because that data is by definition volatile.

**Comment by veloce** [comment]
@frankcalise I'll be on holidays the next two weeks so I won't be able to help you much, but if you're looking to another feature to implement I suggest you #99 (add the clock option to otb games)
It's not API dependant so you can start right away, and it's quite interesting I think ;)

**Comment by veloce** [comment]
Done
