### ISSUE TITLE
Time Odds in the "Clock" tool

### ISSUE THREAD

**Issue by hb20007** [veloce/lichobile#2004]
**Is your feature request related to a problem? Please describe.**
The lichess app can be used as an offline chess clock when playing over the board thanks to the "Clock" tool. The tool allows us to choose an increment system and the starting time, which is common for both players.

**Describe the solution you'd like**
It would be nice to be able to choose a different starting time for each player, so that we can play over-the-board games with time odds using this tool.

**Describe alternatives you've considered**
Right now, to do this, we need to let the time of one player run without making a move, which is not ideal.

**Additional context**
This feature request is somewhat related to https://github.com/ornicar/lila/issues/9814 although it is independent.

**Comment by jas14** [comment]
I believe you're describing the "increment with handicap" option.

![Screenshot_20220124-065216_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/569991/150778364-c4d35064-ae1d-42ad-a135-65455797e05a.jpg)

**Comment by hb20007** [comment]
@jas14 I assumed that was only for having a different increment. Now I see that you are right, it also allows changing the starting time.

What I was looking for is Sudden Death with Handicap but that can be done by setting the increment to 0.
