### ISSUE TITLE
Please add lichessTV for lichess.org/tv/computer

### ISSUE THREAD

**Issue by ddugovic** [veloce/lichobile#203]
As a Stockfish developer, I'd like to watch "tv/computer" on my phone!

**Comment by ornicar** [comment]
Yes! The channel now exists on lichess: http://en.lichess.org/tv/computer

**Comment by Unihedro** [comment]
It's kinda in the title already, by chance are you looking at the wrong repository? :D

**Comment by ornicar** [comment]
yeah nvm

**Comment by niklasf** [comment]
See PR #204.
