### ISSUE TITLE
challenge a friend

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#21]
requires #20

**Comment by frankcalise** [comment]
How should one get to this action? A few ideas that come to mind:

* From online friends, a button in every list item
* Touching a friend's name goes to a profile view with info and a challenge button
* Touching a friend's name opens an actions overlay (similar to share PGN overlay) with a button for challenge

**Comment by veloce** [comment]
Basic functionality done. I may add improvements in other issues
