### ISSUE TITLE
Player names are always upper-case when displayed in the app.

### ISSUE THREAD

**Issue by primehunter326** [veloce/lichobile#210]
Any player name displayed in the app is always in upper-case, regardless of how it was actually entered (i.e CamelCase becomes CAMELCASE).  It would be nice if it didn't do this, as the website doesn't alter the case at all.  Otherwise this is a really slick app (and website).

**Comment by veloce** [comment]
This was part of the original design. I'll give it a thought as I understand case may be significant in a username
