### ISSUE TITLE
Symmetric chess pieces

### ISSUE THREAD

**Issue by Arcticpenguins** [veloce/lichobile#215]
When playing two player over-the-board chess on a mobile phone either each player sees their opponent's pieces upside down or the pieces need to be flipped each turn and you have to look at the board upside down while your opponent is thinking. Lichess has one set ("Shapes") that gets around this by having extra symmetry, but the pieces are abstract and not immediately recognizable without some practice. 

I could not find anything like this online, so I made some traditional looking, symmetric chess pieces. I don't know if there is interest in something like this for the Lichess Mobile app as an option for over-the-board mode, but you are welcome to use them. If not, I'd still love some feedback and if you know of an Android app that allows custom chess pieces that would be very helpful. Here's what I have so far:

![alila](https://cloud.githubusercontent.com/assets/13425948/10830726/82815da0-7e3e-11e5-99f3-f81843cc32ed.PNG)

There's also a version with thinner lines, though I think this one works better on a small screen.

Commentary:
1. The rook is easy!
2. The symmetric pawn looks surprisingly okay.
3. The bishop is rotated 45 degrees because it looked too small when vertical. It's a little non-traditional but it seems to fit with diagonal movement. It could be changed back.
4. The queen is too cluttered with 5 crown points on each side, so I lowered it to 3 each. It seems to work though it looks like a sheriff badge.
5. The king looks a bit like a butterfly...
6. The knight is the hardest to make symmetric, so I compromised. The facial features are symmetric, but the neck is only on one side. However, because the head looks the same upside down, the knight is still easily recognizable when the neck faces away from you (as shown in the snapshots).

I'm open to suggestions for changes to any of the pieces. Although it really works best for mobile, you can try it out on [Stylish here](https://userstyles.org/styles/120187/alila-symmetric-lichess-pieces).

**Comment by veloce** [comment]
That's interesting! I like it. They're all very recognizable to me. If you send me the piece set in svg format (as other pieces of lichess) I'll add it to the app.

**Comment by Arcticpenguins** [comment]
Thanks, I'm glad you like them! I shared the svg files [here on Dropbox](https://www.dropbox.com/sh/yjgzg2cvvl62uk1/AAAbvYgSQ68rgR7MqBMRDD57a?dl=0). Let me know if you want me to make any modifications to the pieces.

**Comment by Arcticpenguins** [comment]
There was a weird svg rendering issue that I only noticed when browsing on Android. All the pieces should be fixed now and are still in the same folder.

**Comment by Arcticpenguins** [comment]
Sorry to bump the topic again, but I made a new version of the pieces with shading and lightness that look even more like the popular Merida pieces.

![alila_shaded](https://cloud.githubusercontent.com/assets/13425948/10861813/48ac160c-7f4b-11e5-9973-a752f2429b80.png)

I think these are better than the unshaded ones, but I'll leave the old ones where they are in case they are preferable. The files for these shaded pieces are in [this Dropbox folder](https://www.dropbox.com/sh/jws5b0hgf71udsf/AAAZCxF4PQ02nkhwPZN3qHxia?dl=0).

**Comment by veloce** [comment]
Excellent! I like it better with the shade too. 
Integrated in https://github.com/veloce/lichobile/commit/fd5db4e12ab355e1f7e6584832a0c5ff6b0efa0d

**Comment by Arcticpenguins** [comment]
Sorry to bother you one last time!

I forgot to mention that since the Knights are not perfectly symmetric they will look better if they have rotated versions for over the board mode. Otherwise instead of looking like the above images the black player will see his/her Knight with the neck facing outward. Will it work if you add partial rotation code like the other sets (except "Shapes") have? Something like:

    #page.white .otb.mode_facing .symmetric .cg-piece.black,
    #page.black .otb.mode_facing .symmetric .cg-piece.white,
    #page.white .otb.mode_flip.turn_black .symmetric .cg-piece,
    #page.black .otb.mode_flip.turn_white .symmetric .cg-piece
	&.pawn
		&.white
		  background-image url('../../images/pieces/symmetric/wP.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bP.svg')
	  &.bishop
		&.white
		  background-image url('../../images/pieces/symmetric/wB.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bB.svg')
	  &.knight
		&.white
		  background-image url('../../images/pieces/symmetric/rotated/wN.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/rotated/bN.svg')
	  &.rook
		&.white
		  background-image url('../../images/pieces/symmetric/wR.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bR.svg')
	  &.queen
		&.white
		  background-image url('../../images/pieces/symmetric/wQ.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bQ.svg')
	  &.king
		&.white
		  background-image url('../../images/pieces/symmetric/wK.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bK.svg')

The Knights rotate but all the other pieces use their original unrotated images so their shading doesn't ever flip sides. If I understand it correctly, when players use over-the-board mode but disable piece flipping, only the black Knight will be rotated so the black Knight neck points towards the black player. (And with piece flipping, if someone prefers that, both Knights' necks will flip to point down on each player's turn).

Here are rotated Knight .svg files:
Rotated black knight: https://www.dropbox.com/s/qivml8fxu09a34o/rotated_bknight.svg?dl=0
Rotated white knight: https://www.dropbox.com/s/krgo1yes3dnv78v/rotated_wknight.svg?dl=0
