### ISSUE TITLE
Flipping knights for symmetric pieces in over-the-board mode

### ISSUE THREAD

**Issue by Arcticpenguins** [veloce/lichobile#216]
In reference to #215, sorry to bother you one last time!

I forgot to mention that since the Knights are not perfectly symmetric they will look better if they have rotated versions for over the board mode. It will work okay this way, but instead of looking like the above images the black player will see his/her Knight with the neck facing outward. Is it possible to add partial rotation code like the other sets (except "Shapes") have? Something like:

    #page.white .otb.mode_facing .symmetric .cg-piece.black,
    #page.black .otb.mode_facing .symmetric .cg-piece.white,
    #page.white .otb.mode_flip.turn_black .symmetric .cg-piece,
    #page.black .otb.mode_flip.turn_white .symmetric .cg-piece
	&.pawn
		&.white
		  background-image url('../../images/pieces/symmetric/wP.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bP.svg')
	  &.bishop
		&.white
		  background-image url('../../images/pieces/symmetric/wB.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bB.svg')
	  &.knight
		&.white
		  background-image url('../../images/pieces/symmetric/rotated/wN.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/rotated/bN.svg')
	  &.rook
		&.white
		  background-image url('../../images/pieces/symmetric/wR.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bR.svg')
	  &.queen
		&.white
		  background-image url('../../images/pieces/symmetric/wQ.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bQ.svg')
	  &.king
		&.white
		  background-image url('../../images/pieces/symmetric/wK.svg')
		&.black
		  background-image url('../../images/pieces/symmetric/bK.svg')

The Knights rotate but all the other pieces use their original unrotated images so their shading doesn't ever flip sides. If I understand it correctly (which I may not!), when players use over-the-board mode but disable piece flipping, only the black Knight will be rotated so the black Knight's neck points towards the black player. And with piece flipping, if someone prefers that, both Knights' necks will flip to point down on each player's turn. 

Alternatively, you could have the Knights' necks always face out even in single player mode. The normal black Knight would actually have the neck up but whenever the player is Black on the bottom the black Knight would be rotated so it has the neck down and the white Knight would be rotated so it has the neck up. That would require different code from all the other sets though, and probably isn't much better than the above proposal.

Here are rotated Knight .svg files:
Rotated black knight: https://www.dropbox.com/s/qivml8fxu09a34o/rotated_bknight.svg?dl=0
Rotated white knight: https://www.dropbox.com/s/krgo1yes3dnv78v/rotated_wknight.svg?dl=0

**Comment by Unihedro** [comment]
```css
transform rotate(45deg)

**Comment by Arcticpenguins** [comment]
Thanks Unihedron! I'm obviously not much of a programmer and was just blindly copying and modifying the code. I was fiddling with the CSS and got the effect I wanted for the opposing player's knight to always be rotated with Stylish using something like:

    .cg-board.orientation-black piece.knight.white {background-image url('../../rotated/wN.svg')}
    .cg-board.orientation-white piece.knight.white {background-image url('../../wN.svg')}
    .cg-board.orientation-black piece.knight.black {background-image url('../../bN.svg')}
    .cg-board.orientation-white piece.knight.black {background-image url('../../rotated/bN.svg')}

Would something like that also work here? Then you wouldn't need to deal with board flips at all as the Knights will always face inward from their starting locations.

**Comment by Unihedro** [comment]
```css
.cg-board piece.knight.white {background-image url('../../wN.svg')}
.cg-board.orientation-black piece.knight.white {transform: rotate(180deg)}
.cg-board piece.knight.black {background-image url('../../bN.svg')}
.cg-board.orientation-white piece.knight.black {transform: rotate(180deg)}

**Comment by veloce** [comment]
rotate doesn't work just like this because we override the `transform` prop during piece translation.
