### ISSUE TITLE
Can't login on to iOS app

### ISSUE THREAD

**Issue by y0ast** [veloce/lichobile#219]
When I try to login to the iOS app it first gives me a "signed in" message, but when I go to my profile it says "undefined". I can see random correspondence games I have never started.

I can then sign out again and it says "anonymous". Is there something wrong because I have a zero (0) in my username?

Device: iPhone 6, iOS 9.1
Username: y0ast
App version: 2.2.0

**Comment by Unihedro** [comment]
weird issue. I've experienced it before on Android, but it fixed itself somehow. Don't remember how it happened though.

**Comment by y0ast** [comment]
Last night I could login fine, but right now it doesn't work. I realized the only thing that's different is that I am now on the office wifi, which might block specific ports (lichess.org works on my desktop though). If I switch to LTE it works fine again.

Are you by any chance failing silently on a specific connection issue?

**Comment by y0ast** [comment]
I just noticed this commit: https://github.com/veloce/lichobile/commit/edfc1d4bfa360713d4ed2115ce09bff01c2d84c6

I hope that solves it :)

**Comment by veloce** [comment]
Well I have serious doubts that will fix the issue... but we never know ;)
The 0 in your name can't be the issue either. You'll tell me when I release a new ios version.

**Comment by veloce** [comment]
The fact it doesn't work on wifi but on 4G (another network) makes me think of the proxy issue. But it only has en effect to websocket. @y0ast your problem is only that you can't login ? Can you play a game as anon or seek a game ?

It's not the first time I hear someone saying it works on mobile browser but not on app... Could be some differences between webviews and browsers. Should investigate.

**Comment by y0ast** [comment]
Well, the problem is that I seem to login successfully but not as my account but as "undefined".

I can play games yes. Let me know if you need more info to debug.

**Comment by veloce** [comment]
I've opened another issue maybe related: #220 

Yes it would be nice to have debug info. The thing is, you can't really do that with prod version. I know it's not that easy for everyone but if you have a mac and are willing to help I can explain you how to send debug info (you'd have to build the app and use iOS simulator within Xcode).
