### ISSUE TITLE
Investigate login issue

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#220]
Several users reported they can't login. Try to find why.

**Comment by y0ast** [comment]
Let me know how I can send you debug info. I got access to a Mac and Xcode.

**Comment by veloce** [comment]
Great! So basically you need to clone the repo and then run the app using the iOS simulator in Xcode.
The README is up-to-date and should help you to setup the project. I can summarize the commands here provided you already installed node:

    npm install -g tarifa
    git clone https://github.com/veloce/lichobile.git
    cd lichobile
    tarifa check --force
    tarifa prepare ios stage

If everything is ok, at this step you have an iOS project and the javascript assets are already built. So you need to open the project in Xcode (open the file: `app/platforms/ios/lichess.xcodeproj`).

Then select an iOS simulator in the list and press 'Run'. You should see the app running. At this point you should have [safari enabled for remote debugging](http://developer.telerik.com/featured/a-concise-guide-to-remote-debugging-on-ios-android-and-windows-phone/#ios) and in "Develop" tab of safari, you should see the simulator entry, which you can click to open dev tools.

Now you just need to test the login and send me any JS or network error you see :)

**Comment by y0ast** [comment]
I have been wanting to test it, but the bug doesn't seem to pop up anymore... Will get back to you whenever I see it again.

**Comment by veloce** [comment]
Ok closing it then.
