### ISSUE TITLE
Back button should not seek a new game

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#223]
The back button on Android seems to act the same as the "New Opponent" button in the browser interface (at least sometimes; other times it takes you back to a previous game that isn't necessarily the last game to finish).  This behavior is quite surprising and counter-intuitive.  Back should never start a new game.
Why not just add a "New Opponent" button to the menu you get when a game ends?

**Comment by mattjacobsen** [comment]
Agreed, this is very annoying. It's the same with with Training and against the AI, so at least it's consistent :-)

**Comment by veloce** [comment]
Can you describe more precisely the steps to reproduce the issues described? (ie: the sequence of screens or actions before hitting the backbutton). This would help me.

**Comment by GrahamJohnson** [comment]
It's not difficult... After a game (online against a human, in case it matters) has finished, while the post game menu dialog is showing (with the rematch, etc. buttons), pressing the back button seeks a new game as though a "New Opponent" button was pressed.  It should not.  For that matter, it would be nice if there were a New Opponent button on that menu.

**Comment by veloce** [comment]
Ok. Thanks!
