### ISSUE TITLE
Share PGN is not longer available

### ISSUE THREAD

**Issue by smat** [veloce/lichobile#225]
I am not able to find the "Share PGN"-button anymore when doing an Over the board game. (see attached screenshot)

![screenshot_20151125-154934](https://cloud.githubusercontent.com/assets/129455/11400330/0d0653be-938d-11e5-9cb1-83f36bdeb583.png)

**Comment by veloce** [comment]
Normal, now it's only available at the end of the game.

**Comment by veloce** [comment]
Is it a problem? I can re-enable it for any game situation.

**Comment by smat** [comment]
I would very much like to have it re-enabled. We are usually a group of three playing live chess. The person not playing records the game on the lichess app while we play, and then we copy the PGN into the analyzer at lichess.org.

It is not always our games last until checkmate, so it would be nice to copy the PGN from the point where one player gives up. Another possibility is to make players able to resign/give up.

**Comment by veloce** [comment]
Yes I didn't think about it at the time I made the modification. Sorry for that, I'll reenable it.

**Comment by smat** [comment]
Thanks for the fast feedback :+1:
