### ISSUE TITLE
Improve names for local AI

### ISSUE THREAD

**Issue by akemn** [veloce/lichobile#228]
Local AI names are currently uninformative.

1. It is unclear that they are an ordered list of difficulty levels, as opposed to just a collection of fun/vanity names.
2. It is unclear that they represent a local javascript AI, as opposed to online AI.
3. They are television pop-culture references that don't mesh well with the timelessness of chess and the crisp, forward-thinking design of lichess.

**Comment by JoelMon** [comment]
```1. It is unclear that they are an ordered list of difficulty levels, as opposed to just a collection of fun/vanity names.```

This is the one that bothers me the most. I'm assuming that Tuco Salamanca is the weakest of all the A.I. yet it's a hard opponent compared to the online A.I. level 1, 2. Basicly if you are a weak player and don't have an internet connection you are doomed to not having a fighting chance. It would be nice to:

* Have a rough estimation of each A.I's strength stated
* Have more variation in A.I's strength

```2. It is unclear that they represent a local javascript AI, as opposed to online AI.```

The "computer" game is listed under "play offline".

**Comment by veloce** [comment]
I have a project to replace current offline AI with stockfish. This would enable same configuration as online AI.

**Comment by ddugovic** [comment]
@veloce FYI I'm continuously tweaking the AI configuration to play more human-like moves.
