### ISSUE TITLE
Use lichobile as a desktop application

### ISSUE THREAD

**Issue by benas** [veloce/lichobile#244]
Hi,

First of all thank you for this amazing project!
I am a huge fan of lichess :smile: 

I was wondering if it's possible to use lichobile as a desktop application?
There are [many GUI clients](http://fics.freechess.org/interfaces.html) to FICS and the idea is to have something similar to lichess.

Those clients are, IMHO, "outdated" and not too sexy as lichobile (which is based on modern web technologies I guess).

I would love to hear your thoughts.
Keep the good work up!
Kind regards

**Comment by Unihedro** [comment]
#164 

tldr DIY or it won't happen

**Comment by benas** [comment]
Ok, the message is pretty clear..
I would love to contribute to such an amazing project!

I was thinking of a cross platform toolkit like [electron](http://electron.atom.io/), Since it uses HTML/CSS/JS, I'm pretty sure most of lichobile resources and assets are reusable for the desktop app, which would be Windows, Linux and OSX compatible, not only windows as requested in #164

Are there some docs on how to make lichobile talk to lichess server?
If not, no problem, I can always dive into the source code :smile:

**Comment by veloce** [comment]
Sure it's a interesting project to make a cross-platform desktop app! lichobile uses html/css/js and it could certainly be used as a basis to such an app. It has already a responsive design for tablet but I reckon it could be improved (I focus more on mobile for now). Except for cordova specific code, most of the codebase could be reused so I guess it could be easy to get started.

You can find some doc regarding mobile API here: https://github.com/ornicar/lila/tree/master/doc/mobile

Not sure it's up to date, but as you said you can always look at the code.

If you start such a project let me know :)

**Comment by SweetLion** [comment]
Sounds very interesting. I just read that Cordova supports Windows 10. But I don't know how to do it.... 
http://blogs.msdn.com/b/visualstudio/archive/2015/07/29/targeting-windows-10-with-your-apache-cordova-app.aspx

**Comment by benas** [comment]
Happy new year to all!

Thank you @veloce , these docs are a good starting point.

As soon as I get a working prototype, I'll will share it with you.

Kind Regards

**Comment by SweetLion** [comment]
Thank you.

**Comment by JoelMon** [comment]
@benas, the PyChess team has an interest in implementing lichess support into their desktop client. https://github.com/pychess/pychess/issues/1332

**Comment by veloce** [comment]
Yep. And as I won't do this in lichobile I'm closing the issue. Feel free to fork lichobile to start a desktop project!

**Comment by benas** [comment]
@JoelMon 

> the PyChess team has an interest in implementing lichess support into their desktop client.

This is a fantastic news!

@veloce You are right, the scope of this issue is bigger than a feature of lichobile, it makes sense to create a fork for a new desktop product.
