### ISSUE TITLE
Can't cancel game search w/ human

### ISSUE THREAD

**Issue by Jimlun** [veloce/lichobile#25]
Button doesn't seem to work at all. (I've found a game once, but it usually never finds)
 
![img_1916](https://cloud.githubusercontent.com/assets/10516146/5724391/82d36036-9b4b-11e4-9bb9-01ecb2082567.jpg)

iPhone 5,2
iOS 7.1.2
beta6

**Comment by veloce** [comment]
Fixed in version beta 1.0.1
