### ISSUE TITLE
Training gives negative points if disconnected in between

### ISSUE THREAD

**Issue by mehdisadeghi** [veloce/lichobile#251]
As I often play chess when I'm on the go, frequently I experience short breaks in my Internet connection. When I am in training mode and have already made a few moves, if I lose coverage, the training will be marked as failed, even when I have solved it correctly!

I will try to fix it myself, but any insight on this problem is welcome.

**Comment by veloce** [comment]
Fixed in https://github.com/veloce/lichobile/commit/6c831d6a5d47f0367cc01d0f1de81245c2e0ba49

**Comment by mehdisadeghi** [comment]
@veloce Thanks for the fix.
