### ISSUE TITLE
support Racing Kings

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#252]
- [Racing Kings on lichess TV](http://en.lichess.org/tv/racingKings)
- [Rules](http://en.lichess.org/racing-kings)

Games are in fact already watchable on the app (like when spectating a player's games). There's nothing too crazy about the variant so full support should be achievable without too much hassle.

What remains to be done:

- [x] CSS board decorations
- [x] TV channel
- [x] game creation
- [x] special board orientation (should always be white)
- [ ] leaderboard
- [x] rating entry in user profile

**Comment by veloce** [comment]
Awesome. I'll take care of this.

**Comment by prevostc** [comment]
+1 !

**Comment by veloce** [comment]
@ornicar leaderboard entry will be added automatically when it is included in `GET /player` JSON response.

**Comment by ornicar** [comment]
holy smokes.
