### ISSUE TITLE
wrong piece being selected in landscape mode

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#253]
It picks the field 3 to the left of the intended position. So when you try to select a piece on position ```D2``` it will pick the piece on ```A2``` instead. This doesn't wrap around so it's not possible to select pieces on the first 3 rows.

This bug may be related to https://github.com/veloce/lichobile/issues/250.

**Comment by pdknsk** [comment]
I just downloaded the latest version fresh and it worked in the first game I played. I closed the app and opened it again to resume the game, and only then did the problem occur, and since.

**Comment by veloce** [comment]
Ok I'll have a look

**Comment by pdknsk** [comment]
Confirmed. Thanks!
