### ISSUE TITLE
Add standalone chess clock

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#254]
The _over the board_ mode is great when you want to play an impromptu game of chess with someone and you don't have a chessboard handy. I would love for a chess clock to be built into lichobile for those days where you have a chess board handy but no chess clock (or your chess clock's batteries die).

A standalone chess clock would compliment lichobile well.

**Comment by ornicar** [comment]
I agree. For now I'm using chess.com clock app, it does the job very well.

**Comment by quinncomendant** [comment]
It wasn't mentioned here, but it seems the over-the-board mode doesn't have any chess clock at all (even when “you don't have a chessboard handy”). Is there a separate feature ticket for that? My GF insists we time our games—I'm that slow. ;)

**Comment by JoelMon** [comment]
That would be an excellent feature as well.

**Comment by veloce** [comment]
That's planned too, maybe soon.

**Comment by JoelMon** [comment]
Wonderful! Thank you for the clock @freefal :)
