### ISSUE TITLE
Ability to read/write game notes & sync with lichess.org

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#255]
Would like to request the ability to read and write notes for the games being played. Having the notes synchronized with the notes written on lichess.org. 

This would be a simple feature that increases the seamlessness of lichess.org and lichobile a great deal. Very handy for when correspondence gameplay moves from the computer to the phone.

**Comment by Unihedro** [comment]
I up this. chess.com supports notes synced from desktop and mobile and is what makes the notes the most useful.

**Comment by JoelMon** [comment]
Status on the HTTP note API: https://github.com/ornicar/lila/issues/1478

**Comment by JoelMon** [comment]
Thank you @veloce for dc8d863. :grinning:
