### ISSUE TITLE
Add more settings

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#257]
Some users are asking for confidentiality settings in the app. For lichess website users there is no problem, but we should do something for app only users.

The simplest way would be to provide a link to lichess settings page but it would not be very integrated since user would have to zoom because page is not adapted to mobile format.

The best would be to have a settings API for mobile, even if it requires more work.

**Comment by ornicar** [comment]
I'm pretty sure you can send POST requests, using lichess website settings form endpoints as an API.

**Comment by veloce** [comment]
Ah of course, using form data.

**Comment by ornicar** [comment]
do you need a GET endpoint to get the current settings of a user?

**Comment by veloce** [comment]
or can you put it in 'GET /account/info' ?

**Comment by ornicar** [comment]
Done (not deployed).

See https://github.com/ornicar/lila/blob/master/modules/pref/src/main/JsonView.scala

And https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala#L103-L280 for the value codes.
