### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by tap52384** [veloce/lichobile#261]
This is crucial for correspondence games.

**Comment by Unihedro** [comment]
It's already there.

**Comment by capnbishop** [comment]
Could push notifications be made to remove the notification if the move is made on the website?  Chess.com actually does this (at least, the Android app does).

**Comment by ornicar** [comment]
The notification isn't sent if you're already looking at the game. Is that what you mean?

**Comment by capnbishop** [comment]
No, I mean *after* the notification has been sent.  So, it's my turn, I get a notification on my phone.  Before I clear the notification on my phone I make my move on the website.  At that point, it would be nice if the notification that I already received would be cleared.  Otherwise, I might later look at my phone and think that I have a move pending, when in fact I had already made it.

**Comment by ornicar** [comment]
how do we achieve that @veloce ?

**Comment by veloce** [comment]
I guess there is a method to clear the notification. I'll look to the doc.

**Comment by veloce** [comment]
Well, there is no such method in the plugin I use: https://github.com/phonegap/phonegap-plugin-push

But really the notification doesn't appear in your drawer if lichess app is in foreground. If it's in background then you see the notif and you tap on it to make it disappear and open the app.

**Comment by tap52384** [comment]
I'm on an iPhone 5 and I don't seem to get push notifications for my classic correspondence games. I'm allowing anonymous statistics; is there anything else I can do to provide diagnostic information?

**Comment by tap52384** [comment]
Also, if I'm logged into the website on a different computer, will that cancel the push notifications?

**Comment by tap52384** [comment]
Also, if I'm logged into the website on a different computer, will that cancel the push notifications?

**Comment by veloce** [comment]
I'm opening another issue for iphone push notifications.
