### ISSUE TITLE
Add crazyhouse variant

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#263]
Spectator mode:
- [x] adapt chessground
- [x] add TV channel
- [x] add crazyhouse in supported variants

Player mode:
- [x] Adapt UI
- [x] add in game creation form
- [x] OTB mode
- [x] analysis board

Maybe we'll start by spectator mode only for now

**Comment by aurimus** [comment]
An idea: instead of adapting the whole piece drop UI, it could be simpler to do a piece select when touching an empty square, so the UI could be adapted from Pawn promotion at the back rank. This could be even faster / easier to use I think.

**Comment by clarkerubber** [comment]
+1 to aurimus' idea. This feels like a good way to keep the UI simple and it's probably easier to use on a mobile interface. The only problem is that this might be a little unintuitive at first, so it might need an explanation for the first time.

**Comment by ornicar** [comment]
I don't think it works, since you need to always see your piece reserve anyway.

**Comment by aurimus** [comment]
You could have the reserve where the captured material (difference) is currently displayed. So you can see what you have there and when you touch (longtouch / 3DTouch?) an empty square you get to select from the pool (so you get displayed only the pieces that you already have)

**Comment by flugsio** [comment]
aurimus nice idea! I also came up with that when thinking about a good solution for predictable piece drop (instead of static piece positions) and did a test implementation, I put it on a shelf because it didn't have an obvious way to display the reserve
http://i.imgur.com/rI4ciwR.png
As usual i got a bit crazy with the testing https://www.youtube.com/watch?v=6ym7mXXa5Q8 (hardcoded to a queen move)

**Comment by aurimus** [comment]
nice! what's with the spinning .. ? lol

**Comment by flugsio** [comment]
I was bored, and wanted to celebrate that the coordinates wasn't hardcoded...

I wan't to contribute something to the app, so I might take a look at this. But need to go through the code a bit first though and play around with things, not sure exactly what is needed.

**Comment by veloce** [comment]
@flugsio that's awesome! if you need any help, let me know
