### ISSUE TITLE
iOS push notifications

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#264]

**Comment by JoelMon** [comment]
Was talking to a friend of mine today who has an iPhone and this was exactly what he wanted. :+1:

**Comment by cjrorvik** [comment]
+1 on this one ;) That would be great when you play a remote chess game with several days potential waiting time.

**Comment by michaelawill** [comment]
I hope you'll prioritize this. It is the only feature left to replace chess.com with lichess.org. Without notifications that it is my turn, correspondence games are almost impossible to reliably finish on my phone.

**Comment by M165437** [comment]
This is definitely missing. +1 Thanks for all the hard work :-)

**Comment by cjrorvik** [comment]
@veloce When do you think this will be ready?

**Comment by zubr93** [comment]
there is option, but not working :c

**Comment by veloce** [comment]
Should be available in next release. No release date yet.

**Comment by eeerlend** [comment]
Still not working for me

**Comment by pcantalupo** [comment]
Hello... I receive a notification on my iPhone when somebody makes a move. However, there is no red circle with the number of games that await my move. Is that intended?
