### ISSUE TITLE
lichobile for Web Runtime

### ISSUE THREAD

**Issue by Symbian9** [veloce/lichobile#266]
Can you make version of app that will support S60v3-S^3 phones using Web Runtime technology or Opera Widget manager, please?
1) http://www.slideshare.net/andreasjakl/basics-of-wrt-web-runtime
2) http://media.opera.com/media/b2b/Opera-Widgets-Product-Sheet.pdf
3) http://www.lghost.ru/docs/opera-widgets-sdk-0.2/

**Comment by veloce** [comment]
No I don't have the time for this. If you want you can fork and do it.
