### ISSUE TITLE
Online indicator is broken

### ISSUE THREAD

**Issue by alexbagirov** [veloce/lichobile#269]
After the last update that was rolled out some days before I don't actually see when the player joins the game. It usually shows that I've left too.

I'm speaking about those green and red icons next to the board in the game. Sometimes they say I'm and my opponent are offline even if we're making moves at this time.

But sometimes it changes to green and then turn offline again. Please fix it!

P.S.: I've added the screenshot of this problem to another issue #270.

**Comment by alexbagirov** [comment]
Some additional screens. Currently I'm playing ans see that we're online.
![screenshot_20160131-181920](https://cloud.githubusercontent.com/assets/6885864/12702320/8d203f3a-c847-11e5-97e2-be06d80aa46a.png)

But after I make a move it shows that we left the game.
![screenshot_20160131-181929](https://cloud.githubusercontent.com/assets/6885864/12702322/a1a13c5c-c847-11e5-984d-0381f98e84a8.png)

**Comment by veloce** [comment]
For this one, I don't have a clue. If you manage to get steps to reproduce, it would help me greatly!

**Comment by alexbagirov** [comment]
@veloce I just enter any game where I am in and make a move. This happens on Nexus 5 and appeared after the last update I suppose (because it was fine before).
