### ISSUE TITLE
disable sleep doesn't seem to work

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#27]
steps to reproduce:
- enable "disable sleep"
- go play a game
- watch the phone go to sleep mode

**Comment by veloce** [comment]
Hmmm it worked for me every time I tested. I'll look but are you sure your phone is not plugged in ?

**Comment by ornicar** [comment]
it's the other way round. Disabling sleep needs a restart.

**Comment by veloce** [comment]
Should be fixed by 5987ffa5e
