### ISSUE TITLE
Horizontal orientation brakes the usernames

### ISSUE THREAD

**Issue by alexbagirov** [veloce/lichobile#270]
See this screenshot:
![screenshot_20160130-212635](https://cloud.githubusercontent.com/assets/6885864/12697550/af63b51c-c7a8-11e5-803a-542cb05180a2.png)

I can't see usernames now, but if I click the place they might be it opens the profile. If I come back then it will show both names.

This also shows you that it tells me I'm oflline while I'm playing (related to #269).

**Comment by veloce** [comment]
Can you describe the steps to reproduce this bug? I can't reproduce it myself.

**Comment by alexbagirov** [comment]
I just turn my Nexus 5 and see this.

**Comment by veloce** [comment]
I think I found the bug.

**Comment by alexbagirov** [comment]
That's great!
