### ISSUE TITLE
Openings training mode support

### ISSUE THREAD

**Issue by njlochner** [veloce/lichobile#275]
Hi, is there planned support for openings training mode? If not, I would be willing to look into implementing this feature and to put in a PR.

Thanks.

**Comment by veloce** [comment]
Hi,

I don't plan to implement this feature right now. Go ahead, fill free to send a PR when you want :)
If you want to ask questions at some point, let me know here.

**Comment by njlochner** [comment]
Thanks! I'll look into it. It probably won't be fast since I am rather busy currently, but I am definitely interested in contributing this.

**Comment by freefal** [comment]
I don't think this exists any more. @ornicar should confirm I guess. 

https://github.com/ornicar/lila/commit/d61a49505c95248da16da6c5028a43cd35aa93f1#commitcomment-20018148

**Comment by ornicar** [comment]
correct https://github.com/ornicar/lila/commit/f0cd74f5e1f7eb2e999262ec07919d7e576034fe

**Comment by veloce** [comment]
Ok, closing.
