### ISSUE TITLE
A workaround is required to view game analysis on a mobile device.

### ISSUE THREAD

**Issue by MattSmiglarski** [veloce/lichobile#277]
_NB: While #129 is a feature request for game analysis in the mobile app, this issue is about the mobile site redirecting to the mobile app when clicking the "Analysis board" button._

It is difficult for a user to view game analysis on a mobile device when the mobile app is installed due to an undesired redirect from the mobile site to the mobile app. The steps which demonstrate this behaviour are:

1. Ensure the mobile app is installed.
2. Visit lichess.org and view a game: User dropdown -> profile -> games played, and select.
3. Click the "Analysis board" button.

The user is redirected to the mobile app, but no analysis board feature is available here. Ideally, the user wouldn't get this redirect until the feature is supported. Fortunately there is a workaround:

1. **Press the 'Back' button on the device.** This presents the user with an uninitialised page in the mobile site containing a blank board with no pieces.
2. **Press 'Refresh' on the browser.** A dialog is presented to the user asking if they wish to redirect to the mobile app.
3. **Press 'Cancel' on the dialog.** The user is now in the game analysis, on the mobile site, where they want to be.

The behaviour was seen on an SGS5 running Android 5.0 with Lichess v2.8.0 and the default Android browser.

**Comment by veloce** [comment]
This should be an issue to ornicar/lila indeed, until the analysis functionnality is shipped in mobile version.
