### ISSUE TITLE
Publish on F-droid

### ISSUE THREAD

**Issue by jsparber** [veloce/lichobile#278]
Great work.
I would love to be able to get the app form F-Droid.

**Comment by Calinou** [comment]
[It already is in F-Droid's submission queue](https://f-droid.org/forums/topic/lichess-mobile-app-lichobile/).

**Comment by ornicar** [comment]
You can get the APK from http://veloce.github.io/lichess-mobile-apk/

**Comment by fazlerabbi37** [comment]
> You can get the APK from http://veloce.github.io/lichess-mobile-apk/

APK from GutHub release is not same as an app published in F-Droid. Just a simple face that the APK's are never updated automatically is a security problem on it's on.

**Comment by fazlerabbi37** [comment]
ah, duplicate of #409. better to keep the discussion on one thread.
