### ISSUE TITLE
Change homescreen to anything reasonable

### ISSUE THREAD

**Issue by aurimus** [veloce/lichobile#279]
I always have the last game played against PC (which could at least be the last game played generally).

Since back button sometimes circles the played games, may it be game history? Seems like all the code should be there already, just the dispay of the list thats lacking.

Lobby of course could be an option.

Even maybe just my profile! Its just annoying to always see that last game against PC

**Comment by veloce** [comment]
Normally if you are online, you'd have the most urgent online game to play. If you have no online game to play at all it'd fallback to offline game.

I agree this is not optimum though. There is no lobby in mobile app so this is not an option. I like your idea of having a list of recently played games. We could add recently played puzzle as well.

To sum up, we could have:
* when *online*, this of recently played games and puzzles
* when *offline*, current offline game, or just starting board of offline game (I don't want to implement offline games history for now)

**Comment by aurimus** [comment]
I see, you are referring to correspondence or other cases where you have a game running. I'm not using the app for correspondence usually so I just see last finished offline game (which since is finished - is completely of no interest to me, especially since it's against the CPU and not human). It actually feels like it's a bug, since that game I played a few months ago and it's still there, first thing I see.

I think a starting board is also useless unless you play a lot of games against the CPU.

Is some info stored in the app, like profile etc. to access offline?

So having all thoughts in mind, including future lobby - create new page / screen that you would call _home_ , if there are any games to play - display the most urgent (as it is now), if there are no games to play - display the homescreen, make homescreen accesible through the menu.

Homescreen could contain some info from profile (may also be recent games in there somewhere), and some shortcuts maybe? .. Like Play: Blitz, Bullet etc. presets for settings that were last used for that variant.

If I only had 2min of development time - I would make the homescreen the same as my profile (if there are no games to play)

**Comment by veloce** [comment]
All profile info, etc. are not stored offline. And I'm not going to implement such offline functionalities right now because it's not the most valuable thing to do. 

At this point I have to leave AI for offline home. When you're online it's different and I'll try to find some home that mix some profile infos with recently played games and maybe a big fat button 'start a new game'.

**Comment by aurimus** [comment]
That would totally make sense. You could leave the open correspondence games there for online too.

Actually I would prefer big fat button for offline also if there are no offline games in progress, that 3 months old **finished** game just doesn't make any sense at all, believe me.

**Comment by aurimus** [comment]
P.S. The sign in button doesn't make sense when offline either (it just signs in automatically once online). I think a suggestion to go online would make more sense in place.

**Comment by veloce** [comment]
I thought about it and we should have a home that is close to lichess.org's one. Here's what we will do:

- [ ] top players of the day
- [ ] featured game
- [ ] puzzle of the day
- [ ] create a game fat button

@ornicar I'm not sure there is the API for "top players of the day", you confirm? I know there isn't for puzzle of the day.
Let me know if I should create a ticket for that in ornicar/lila

**Comment by aurimus** [comment]
>  featured game
>  puzzle of the day

My concern is how would it fit into the screen? Or would it only be a link?

**Comment by veloce** [comment]
it will fit with a mini board

**Comment by aurimus** [comment]
Makes sense, but the main board is already mini ... so that would be micro board then. Not too sure how useful is that.. maybe save your time and put fewer things (?)

**Comment by veloce** [comment]
it's just prettier with a board than just a link... and it's good that a home page of a chess app shows a chessboard, even if small!

**Comment by aurimus** [comment]
Good job! Just updated.. there's a few glitches though:
* No feedback for created game (it only appears after f. ex. clicking the puzzle, then I get the usual Waiting for opponent..).
* Related to above: It would be able to solve puzzles while waiting for opponent.
* The mini boards might as well be centered (no?)

**Comment by aurimus** [comment]
Good job, I just updated.. there's a few glitches though:
* No feedback for created game (it only appears after f. ex. clicking the puzzle, then I get the usual Waiting for opponent..).
* Related to above: It would be able to solve puzzles while waiting for opponent. So the "waiting for opponent" could just be a line of text next to number of players. F. ex. "Waiting for: Rated Blitz 5+4"
* The mini boards might as well be centered (no?)

@veloce

**Comment by veloce** [comment]
Oh yes... I did not test well. Thanks for reporting.

**Comment by aurimus** [comment]
How often do you push updates? I could test this and the #284

**Comment by veloce** [comment]
That is released on android since yesterday. iOS will come a bit later. I plan to push it to the apple store today so I guess in 3-4 days it will be out.

**Comment by aurimus** [comment]
All working now, I creaded a separate issue for the second point #294
