### ISSUE TITLE
Fit to height on square / small screens

### ISSUE THREAD

**Issue by aurimus** [veloce/lichobile#284]
Clock and controls are barely visible, I suggest maybe fitting to height if things dont fit vertically

![lichessonsmallscreen_small](https://cloud.githubusercontent.com/assets/1052992/13204694/22245466-d8df-11e5-8820-34167ace24bc.jpg)

**Comment by veloce** [comment]
What phone is that? I have used the iphone4 as the smallest screen for my tests. Thoses small screen make it hard to adjust the size of everything, but let's see what can be done.

If you can give me the model, and best the screen dimensions that would help. Thanks!

**Comment by Unihedro** [comment]
It says Sony. But it's too small to be Xperia.

**Comment by aurimus** [comment]
That's Sony Xperia, it seems like this one http://www.gsmarena.com/sony_xperia_e-5149.php (320 x 480). My father's phone.

**Comment by aurimus** [comment]
iPhone4 aspect ratio is actually the same as this phone's, the problem then I guess is the size of things (font-size etc.)

**Comment by aurimus** [comment]
Better, but still not perferct. If you put the rating to the right of the name (not forgetting to increase font of it cause it's barely visible), maybe that would do it.

![lichess_still not enough](https://cloud.githubusercontent.com/assets/1052992/13398866/fe59e71e-df08-11e5-996c-a91717f9c2d0.jpg)

**Comment by aurimus** [comment]
Better, but still not perferct. If you put the rating to the right of the name (not forgetting to increase font of it cause it's barely visible), maybe that would do it.

![lichess_still not enough](https://cloud.githubusercontent.com/assets/1052992/13398866/fe59e71e-df08-11e5-996c-a91717f9c2d0.jpg)

@veloce

**Comment by veloce** [comment]
@aurimus then it's not the same dimensions as iphone 4 because I tested it looks good on iphone 4.

Can you send me the dimensions?

**Comment by aurimus** [comment]
I did send it in my first reply, it must be 320x480, iphone4 has double that. If you mean aspect ration though, then it must be the same (but there are other variables - font size might look different for example)

**Comment by aurimus** [comment]
I did send it in my first reply, it must be 320x480, iphone4 has double that. If you mean aspect ration though, then it must be the same (but there are other variables - font size might look different for example)

@veloce (not sure you follow closed issues, so I tag you while it's closed)

**Comment by aurimus** [comment]
My father is no longer in possession of the mobile phone so I can't confirm if the issue still stands or not
