### ISSUE TITLE
Enhance notification of events

### ISSUE THREAD

**Issue by aurimus** [veloce/lichobile#286]
pop up the options dialog on event (optionally)

It would be better to have the dialog popup on any of events automatically (draw offer, takeback offer etc.) since you need to check what's happening anyway. This could be of course optional, and especially useful for someone not paying attention to the three dots at the left corner (it's a bit hard to notice for myself either)

**Comment by ornicar** [comment]
You don't pop up things over a board like that. And one more settings, I don't think so. Imo the currrent setup is good.

**Comment by aurimus** [comment]
I agree it's not optimal, but probably easy / easiest to implement atm. This is not just philosophy, I recommended my father lichess and played with him for a while, he certainly could have used a popup.. he would completely miss draw offers and takeback.

Optimally maybe there should be a line for text somewhere in order not to disturb the playing, but then again on some screens there are no space #284 for that either. So there maybe still popup but not the whole menu, just the relevant question (draw offer, takeback)

The whole menu contains too much info, but if it's opt-in, the user would be aware this would happen. Still yes, this is just quick fix so maybe not optimal

**Comment by veloce** [comment]
No popup. That can't be. The only thing we can add to make the notif more obvious is a sound.

**Comment by aurimus** [comment]
Sound will not be enough for some people, but better than nothing

**Comment by veloce** [comment]
maybe a vibration is better than sound ? @aurimus

**Comment by aurimus** [comment]
Might as well can be both
