### ISSUE TITLE
iOS bug - Freeze when using the chat

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#287]
My friend uses iOS 9.2.1 and he tells me that lichobile (2.9.0) freezes up when I send him a message and he clicks the chat icon. He says after he clicks the chat icon nothing else is clickable. He has to close and reopen lichmobile.

P.S. He really is looking forward to push notifications. He wanted me to tell you guys. haha

**Comment by veloce** [comment]
I am not able to reproduce all the issues, but I will release a new version that will fix them hopefully.

Push notification  will come later :)

**Comment by JoelMon** [comment]
@fetzig is having similar issues with lichobile freezing during game while on the iPhone. https://github.com/ornicar/lila/issues/1645
