### ISSUE TITLE
Mark Cheaters

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#288]
Today I noticed that accounts on lichess.org marked as _This player uses chess computer assistance_ appeare on lichobile as normal accounts, even their rating for each varient is displayed on their profile.

Accounts marked as cheaters should be displayed somehow on lichobile and the same protocal used by lichess.org should be followed, ie hide account's ratings and display a message.

On lichess.org the user can move their mouse over the opponate's username and the  _This player uses chess computer assistance_ is displayed. Perhaps on mobile devices we can have it so that a short message can be displayed next or under the username during play to avoid having to leave the board to check the opponent's profile to see if they cheat.

Below I've posted two mockups to illustrate the idea.

![chess_board_assistance](https://cloud.githubusercontent.com/assets/6587811/13257960/10bec44a-da1f-11e5-80f5-d836dd9a5127.png)

![profile_cheater](https://cloud.githubusercontent.com/assets/6587811/13258190/24e433b4-da20-11e5-8ef3-85e2f53ea1c0.png)

**Comment by veloce** [comment]
Alright, good idea to mark it on game. The notif already exist on user profile page.

**Comment by JoelMon** [comment]
@veloce Do you mean the notification was implemented in a version higher than 2.9.0?

As of 2.9.0 (Android) there's no notification that I can see:

![dnwtx74](https://cloud.githubusercontent.com/assets/6587811/13260681/94deffdc-da2a-11e5-86ea-904780ae009c.png)

**Comment by JoelMon** [comment]
Was looking at the wording just now. _Uses computer assistance_ is shorter and seems more aesthetically pleasing while implying the user uses computer assistance.

**Comment by veloce** [comment]
Ah @JoelMon it used to work... maybe the api has changed. I will take a look, thanks.

**Comment by veloce** [comment]
![capture d ecran_2016-02-23_21-02-03](https://cloud.githubusercontent.com/assets/423393/13264951/d42b295e-da70-11e5-8849-3ea0d72a71a3.png)

**Comment by veloce** [comment]
I will be like that. And a long press on user will show the information (either computer assistance, or artificial increase of rating).

It's much simpler for me to do like that. You can predict the size of the text in various languages that's why. I think it's good compromise.

**Comment by JoelMon** [comment]
Looks good

**Comment by ornicar** [comment]
Thanks for using me as your testing cheater :D :D :D

**Comment by veloce** [comment]
hahaha :D

**Comment by JoelMon** [comment]
Should cheaters be marked on the gameboard even after the game is over? Not sure if that's overkill or not but at the moment after the game is over the (!) isn't displayed and long pressing on the cheater's name doesn't mention anything about computer assistance.One has to look at the profile. (v. 2.10.0)

**Comment by veloce** [comment]
Ha. Ok, that is probably because lichess does not send this data when the game is over. I need to check to be sure.
