### ISSUE TITLE
Allow device's back button to navigate to the last window

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#289]
One of the annoyances when navigating around is that the device's back button doesn't work.

**Scenario**
I want to see a few games played by a friend. I click his username and then click his Games. I click into a game I want to view. I intuitively click the device's back button expecting to go back to the list of games played by my friend. Instead I have to click on his name again and repeat the process.

It would be nice if the device's back button returned you to the last screen.

**Comment by veloce** [comment]
Yep, I will soon release a version with that feature. It is shipped in current iOS release. Actually if you are spectator of any game you will be able to navigate back either with back button of android or the back button in the header of the app.

**Comment by veloce** [comment]
Fixed in 588e838a for iOS. For android it's already working with the back button.
