### ISSUE TITLE
v. 2.10.0 persistent 'No Internet Connection' message

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#290]
Hello,

I just upgraded to v. 2.10.0 via the Android Play Store and lichobile displays _No Internet Connection [...]_ most of the time. Every once in awhile it will connect and function as expected but then for long periods of time it will display the message.

I tried connecting via my house's wifi and the phone's cellular connections with the same outcomes. I tested both wifi and cellular connections and both seems to be fine.

Maybe a problem with the APIs on lichess.org side?

![9xdyryc2](https://cloud.githubusercontent.com/assets/6587811/13333619/df6fd7e0-dbd5-11e5-9ae6-5bbb310a4d6d.png)

**Update**

I think I found the problem. My home internet is coming and going. I have small intervals where the internet drops out and then comes back. When my home's internet did not work, I would turn off the wifi from my phone and used cellular data instead but lichobile would still display No Internet Connection.

After doing a Forced Stop from Settings I opened lichobile and it connected without an issue over cellular and has worked as expected for a good while.

So the problem may be that when there's a loss of connection it takes lichobile a long while to realize there's a connection again if at all. Although it says there's no internet, some features continue working normally such as showing which of my friends are online in real time. A Force Stop seems to fix things.

**Reproducing**

1. Connect via wifi and then pull the plug on the internet
2. Click the new Home button in lichobile until you get No Internet Connection
3. Turn off wifi from phone
4. Click on the new Home button in lichobile
5. The first time you click home it might connect to the server
6. Click on home a few more times. It will show No Internet Connection there after

**Update 2**

There's a bug because while it displays No Internet Connection I just saw my online friend count go from 1 to 2. When I click on the online friends icon I see both of my friends online. I confirmed the information is correct by checking lichess.org

**Comment by JoelMon** [comment]
**Update**
 
I think I found the problem. My home internet is coming and going. I have small intervals where the internet drops out and then comes back. When my home's internet did not work, I would turn off the wifi from my phone and used cellular data instead but lichobile would still display _No Internet Connection_.

After doing a Forced Stop from Settings I opened lichmobile and it connected without an issue and has worked as expected for a good while.

So the problem is that when there's a loss of connection it takes lichobile a long while to realize there's a connection again if at all. A Force Stop seems to fix things.

**Comment by aurimus** [comment]
Can't reproduce.

**Comment by JoelMon** [comment]
I'm using lichobile 2.10.0 on a Nexus 4 running Android 5.1.1. Don't know if that makes a difference.

**Comment by JoelMon** [comment]
Another quork while lichobile claims there's no internet connection: I still receive push notifications.

**Comment by veloce** [comment]
The message 'no internet connection' is too generic. 

This message is only shown when there is an issue with an xhr (it could be a timeout or something else). 

The other kind of connection with lichess is the websocket. The websocket connection doesn't show the 'no internet connection' message. The friend list for instance use websocket.

 The only thing I can do here is to improve error handling and display better messages.

**Comment by JoelMon** [comment]
@veloce might the problem be with commit c4098032e60? The notes says don't try xhr if offline. If the network goes offline then it will never try xhr again? Sorry I don't know java.

**Comment by veloce** [comment]
@JoelMon no it's not that.

Actually I know what it is: websocket events trigger an http request each time the featured game box switches to a new game. That's why you get multiple message if you are having network issues.

To fix this I will simply ignore errors in that case only ;)

**Comment by JoelMon** [comment]
Awesome, sounds good.
