### ISSUE TITLE
iphone app unresponsive

### ISSUE THREAD

**Issue by fetzig** [veloce/lichobile#292]
env: iphone6, ios 9.2.1, lichess 2.10.0 (version number according to ios app store, has been released yesterday)

Simply touch button on top right -> app "freezes".

![2016-02-26 14 10 54](https://cloud.githubusercontent.com/assets/105761/13353430/a3f47b70-dc94-11e5-9129-cf0a97ce3c2f.png)

Previous version had similar issues (button to open User stats in training, or landscape in training resulted in similar problem). Thus I wanted to investigate and add some more info here. 

To debug I built and run the current HEAD on the same iphone -> the button works. But not in the app store version, thus I guess the bug must have been fixed in the last days or so. Maybe even just 2 hours ago: https://github.com/veloce/lichobile/commit/57dbe69fa08a390c9747674f13978c790cbbac04 (thx @veloce)

(Couldn't verify since I couldn't find a v2.10.0 tag in the git repository. Or am I talking about v2.9.0, and the version number from the app store is off by one?)

**Comment by JoelMon** [comment]
The version number was updated with commit b6a360462f9 but there were never a tag made that I can find for 2.10.0.

**Comment by veloce** [comment]
I forgot to tag, that's why. I will tag the 2.10.0 where it was when I release the ios version.

That 'freeze' bug appears to be also in android. I never manage to reproduce it so I would need more info.

Like can you send all the games types (variant) currently being played ?
