### ISSUE TITLE
optional push notification sound

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#293]
from an email:

> Notification seems to be an "all or nothing" feature. I like to keep it turned on (referring to correspondence games, of course) but then if an opponent makes a move at 3 am it tends to wake me up. But it is good to have both visual and sound notifications when I'm awake. I would prefer to be able to turn the sound off and only see the notification bar icon in the morning. Could you create a way to have only visual or only sound (or both) when it comes to notifications?

**Comment by Unihedro** [comment]
or quiet hours

**Comment by veloce** [comment]
I'll investigate. Maybe this is a server side one.

**Comment by veloce** [comment]
https://github.com/phonegap-build/PushPlugin/issues/159
