### ISSUE TITLE
Allow using application while waiting for opponent

### ISSUE THREAD

**Issue by aurimus** [veloce/lichobile#294]
Sometimes the wait is lengthy, it'd be nice to solve puzzles, watch TV, review past games etc. basically use the application while waiting.

For indication that a game has been created it could simply add one in the "games in play" section (the nano board button on top right) or have a css fixed header / footer with f. ex. "Waiting for Blitz, Rated 5+4"

**Comment by veloce** [comment]
That's a good idea. I need to find an icon to notify that a game is 'in waiting'.
