### ISSUE TITLE
'games in play' counter not working

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#297]
You probably noticed this already but it seems lichess made changes to the API and the _games in play_ counter is no longer working.

![5g4a1ba](https://cloud.githubusercontent.com/assets/6587811/13548568/48d3135e-e2c1-11e5-9961-75b55fc0abad.png)

**Comment by alexbagirov** [comment]
+1

**Comment by veloce** [comment]
Yes, there is a server side issue for this: https://github.com/ornicar/lila/issues/1686

**Comment by ornicar** [comment]
I'm going to add BC on the server side, but please update lichobile to use the new behaviour:

lobby pong messages now contain the game count additionally to the player count.

```js
{
  t: 'd', // pong
  d: 8670 // player count
  r: 2874 // game count
}
```

In the new protocol, the `nbr` message is no longer used; but I'm reintroducing it temporarily for mobile BC.

**Comment by ornicar** [comment]
BC fix in production
