### ISSUE TITLE
Reposition accept / decline buttons

### ISSUE THREAD

**Issue by movabo** [veloce/lichobile#304]
Reposition the accept / decline buttons when the oppenent proposes a takeback / offers a draw.
(See the following picture)

![ad](https://cloud.githubusercontent.com/assets/4041740/14079119/97e1dfec-f4fb-11e5-91f0-674fc9a5be19.png)

Normally it looks like this:

![screenshot_2016-03-28-15-30-19](https://cloud.githubusercontent.com/assets/4041740/14079125/a605839e-f4fb-11e5-8cca-cf9bff53eb78.png)

# Why is a repositioning necessary?

__Lets consider the following situation:__ 

The opponent proposes a takeback. 
The accept / decline button will be appended.
You are going to tap on one of the buttons.
Shortly before you tap on the screen the opponent takes the proposition back.
The buttons will disappear and all remaining buttons will reposition themself to the center.
__Now here the problem:__ On the position of the accept / decline buttons is now the resign button (as the next picture shows). This will increase the chances of an accidential resign.

![overlay](https://cloud.githubusercontent.com/assets/4041740/14079212/5192241a-f4fc-11e5-9c0d-2efd58ab3103.png)

**Comment by veloce** [comment]
You're right. I think the resign confirmation is the best solution here.
