### ISSUE TITLE
Inbox messages

### ISSUE THREAD

**Issue by flugsio** [veloce/lichobile#308]
Ability to message friends without an ongoing game, and to receive messages. Push notifications would be extra nice.

**Comment by veloce** [comment]
I'm willing to do it. It needs a confirmation by @ornicar for the server part that is not exposed yet. I believe this is not the most urgent.

**Comment by ornicar** [comment]
a rewrite of lichess messenging is due, mixing chat & mail like on facebook.

**Comment by LichessJoe** [comment]
Me and my friends really want this for the mobile app!
