### ISSUE TITLE
Changing orientation while a piece is grabbed

### ISSUE THREAD

**Issue by makcakaya** [veloce/lichobile#310]
Today I grabbed a rook and at the same time orientation is changed. The rook stuck that way (magnified as if it was grabbed) and I could not move that piece.

To purge this effect I went back a few moves so rook was moved by the application to its previous location and the problem was solved.

**Comment by veloce** [comment]
Thanks for reporting.

**Comment by veloce** [comment]
Never been able to reproduce.
