### ISSUE TITLE
evaluation: landscape board too large

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#317]
Please compare screenshots. The evaluation part is pushed off the screen. You can only just about notice the green progress bar.

![1256](https://cloud.githubusercontent.com/assets/1097609/14782258/7ac02786-0ae8-11e6-940c-5754d9aee8d4.png)
![2256](https://cloud.githubusercontent.com/assets/1097609/14782257/7abfd236-0ae8-11e6-840b-921d6c11c92b.png)

**Comment by veloce** [comment]
Can you give tablet model and screen size plz?

**Comment by pdknsk** [comment]
I guess you already figured out from image size.
