### ISSUE TITLE
evaluation crash prone on android

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#319]
I don't have a clear reproduction, but switching from a game to evaluation, and then interacting with it, more often than not will eventually force-close the app.

I noticed this in the logs.

```
pid: 5527, tid: 6277, name: DedicatedWorker  >>> org.lichess.mobileapp <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x9dd46358
    r0 9f92b044  r1 04005000  r2 0d7f5000  r3 0017c000
    r4 9f92b044  r5 04000000  r6 00000000  r7 00000000
    r8 04005000  r9 9514701c  sl 04000000  fp 9d443470
    ip b6ee3710  sp 9d4433a0  lr 9e3bf5e1  pc 9dd46358  cpsr 88010030
    d0  0000000000000000  d1  0000000000000000
    d2  02191021704142e9  d3  025d221520413246
    d4  e1a0d00be5823003  d5  e28dd008e8bd4800
    d6  e7f001f0e12fff1e  d7  95147060972efb3c
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 0000000000000000  d17 0000000000000fff
    d18 000000000000648a  d19 0000000000000000
    d20 000000000000648a  d21 bf66bd24acae58da
    d22 3f1152fe6142af77  d23 3fc746649aab65dc
    d24 4160000000000000  d25 bfc896800000001b
    d26 4000000000000000  d27 3fc5d527743d6f6b
    d28 3ff0000000000000  d29 3ffd455b11785213
    d30 3f90c68c14bcc493  d31 bf90c68bc95634d9
    scr 62000013

backtrace:
    #00 pc 001e3358  /data/app/org.lichess.mobileapp-1/lib/arm/libxwalkcore.so
    #01 pc 0085c5dd  /data/app/org.lichess.mobileapp-1/lib/arm/libxwalkcore.so
```

**Comment by veloce** [comment]
You don't have a more complete error message? This one is pretty useless.

I am preparing a new version which will use native stockfish (for now it is a stockfish compiled to JS), so this bug will be no more relevant.

**Comment by pdknsk** [comment]
How do I get a complete error message? I'm not familiar with Android debugging. The app closes itself and Android shows a notification stating as much. I think ```ILL_ILLOPC``` signals that the library has been compiled with perhaps some ARM extension or sth. like that the CPU doesn't support.

If the bug will be obsolete soon, I'm OK with closing it.

**Comment by veloce** [comment]
Ok let's close it. The new version with native stockfish will add a huge perf boost to analyse. It will be at least 10x faster. I'm currently testing it a lot because I also don't want it to crash. If you're interested in beta testing I can provide you a link to the beta with stockfish plugin.

Let me know.

**Comment by pdknsk** [comment]
Sure, why not.
