### ISSUE TITLE
Kidmode doesn't work on mobile

### ISSUE THREAD

**Issue by AbAeterno** [veloce/lichobile#320]
If Kidmode is enabled on the desktop site, mobile users can still receive in-game chats. 

From the email:
"Hi I play regularly on your site & app. I would like to make a suggestion. Which is even though you tell others to be polite in the chat. Others still ignore this. I just let my 6 year old niece try it out & someone anonymous came on & started cyberbullying her.

My suggestion is to create an optional toggle chat button which ALLOWS the other person access to know their opponent disabled / muted the chat. [...]"

**Comment by veloce** [comment]
> My suggestion is to create an optional toggle chat button which ALLOWS the other person access to know their opponent disabled / muted the chat. [...]"

Sorry I don't understand your last sentence. A setting to disable chat in a game would be enough or not?

The app already has a setting (in privacy tab) to let or not anonymous players message you. This is a setting from lichess.org and actually I'm not sure it applies to PM and chat, or just PMs. @ornicar can confirm here.

**Comment by AbAeterno** [comment]
I set "Let other players message you" to "Never" on iPhone and I was able to still receive messages.

(Created an anonymous game from computer and played my lichess username from the phone. I was able to receive messages sent from anonymous.)

**Comment by AbAeterno** [comment]
When my "let other players message you" is set to "Never" on iPhone, Anonymous can still message me.

(While signed in to the mobile app, I set a game seek to 4+9 and did the same while signed out on the desktop. When I was paired with myself, I sent in-game chat messages from the desktop and was able to receive them on the mobile).

Also, it would be good that when KidMode = on, Let Other Players Message Me = "Never" by default.

**Comment by veloce** [comment]
Ok it confirms that this setting is just for PM... which does not make sense since mobile app doesn't have PM. I'll see with @ornicar we can make the change so the setting applies to chat messages too.

If not possible, then I'll add an option to disable chat during game.

**Comment by veloce** [comment]
I'll implement kid mode setting in the app

**Comment by veloce** [comment]
@ornicar I'd like to implement kid mode on mobile app but I need some help to choose the best way to do it, as I don't know how it works in the website.
