### ISSUE TITLE
Lichess on Samsung SM J1 Ace 4.4.4 crashing

### ISSUE THREAD

**Issue by AbAeterno** [veloce/lichobile#323]
"I tried to install liChess on my Samsung SM J1 Ace 4.4.4 and it keeps crashing before it opens [...] I noticed that when I turn off mobile data the app opens but when I swith mobile on it crashes again!" from email.

**Comment by veloce** [comment]
Well I can't do nothing against it... I don't have this phone and I don't have the time to test them all. Besides, without a proper bug report this issue is useless.

**Comment by LeoChessNut** [comment]
At least 5 Bug reports were sent via Google reporting! Isn't there somebody there that actually cares or can give a more constructive answer than the useless comment you made!?

**Comment by LeoChessNut** [comment]
This matter isn't "CLOESED" until you actually solve the problem! Its not an mobile from outerspace millions have it!

**Comment by LeoChessNut** [comment]
Sorry, "CLOSED"

**Comment by veloce** [comment]
I will say it again: I'm the only developer of the application. I'm doing it on my free time only and I spend already a lot of time on it. I don't have all the phones of the planet and I can't (don't want to) spend all my time to debug them.
 
So, unless you debug yourself or find someone that has the phone and can debug it, it won't be fixed.

**Comment by LeoChessNut** [comment]
I have no idea to debug, how do I do that?
