### ISSUE TITLE
Fix iOS screen rotation

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#328]

**Comment by llimllib** [comment]
I and another player have been affected by this as well. Just +1ing and happy to help debug.

**Comment by veloce** [comment]
I guess it's happening since a change in ios 9.x. Shouldn't be hard to fix.

**Comment by angborxley** [comment]
I'm the other player - that would make sense @veloce as it appears to have started once I updated ios. I've noticed it on my iPad (Air2) but not on my iPhone (6+)

**Comment by llimllib** [comment]
I can reproduce on both my iPhone 6 and my iPad Mini (version whatever the most recent one is)
