### ISSUE TITLE
iOS app sporadically becomes unresponsive

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#337]
This one is difficult to describe, but I have noticed regularly since upgrading to v3.0.2 on iOS 9.3.1 and 9.3.2 (I updated to Lichess v3 and iOS v9 at the same time, so don't know which or both is to blame). 

Case 1: When initially opening Lichess, and starting an *Over the board* game, everything functions fine. Some hours later, or the next day, open Lichess again and click the *New game* icon (the crossed swords) opens the game choice box, but the *CREATE A GAME* button does nothing. The button changes background color as it knows it is being pressed, but nothing else happens. Tapping the background area closes the dialog. There is no way to begin a new *Over the board* game (selecting *Over the board* from the menu doesn't help). Forcefully quitting Lichess and starting over does allow a new game to be created. Here's a screenshot showing this unresponsive state:

![unresponsive-1](https://cloud.githubusercontent.com/assets/6884276/15522346/66feee66-21d7-11e6-8ebf-89d827969470.jpg)

Case 2: Also when returning to Lichess after leaving it running in the background for some hours or days, to continue a *Over the board* game, moving the pieces is unresponsive. Here is an example, where *white* has moved, but the board is unresponsive to any *black* move (tapping anywhere on the board does nothing). Also, notice the *Flip pieces after move* has not happened: despite white completing its move, the board didn't flip back to black's side. Here is a screenshot of this state:

![unresponsive-5](https://cloud.githubusercontent.com/assets/6884276/15522449/16bf6a74-21d8-11e6-9e55-cc91992195c6.jpg)

Case 3: switching a ‘stuck’ game into analysis mode (the eye icon), similar problems exist: go back a few moves (clicking the move arrows) and white is able to make a move, but black is not. Clicking the elipsis icon and *Start new analysis* resets the board to starting position, but no moves can be made. Also, I noticed a banner, “Premove enabled - Click anywhere to cancel” which doesn't go away by clicking anywhere. Returning to the elipsis menu icon and selecting *Start new analysis* does nothing (tapping the background is required to close the dialog). 

![unresponsive-2](https://cloud.githubusercontent.com/assets/6884276/15522569/08f79bfe-21d9-11e6-9ff6-6aa230010813.jpg)
![unresponsive-4](https://cloud.githubusercontent.com/assets/6884276/15522570/090146ea-21d9-11e6-8ad1-f4afc135abaf.jpg)

In all these cases, forcefully quitting Lichess and re-opening it allows normal game function.

**Comment by veloce** [comment]
Those are maybe mithril bugs; I uploaded today a 4.0 version which might fix some of them, should be available in ~3 days. 

Tell me if you still see those bugs. Anyway thanks for the detailed description. The fact we can't reproduce the bugs all the time make it hard to debug.

**Comment by quinncomendant** [comment]
Yes! In v4.0.1, this problem is gone. 👏
