### ISSUE TITLE
Stockfish not working for android < 4.4

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#341]

**Comment by veloce** [comment]
@srenault I don't see where to change the compiler setting for this. Can you help me?

**Comment by srenault** [comment]
I think I was wrong. It's not in the `build.gradle` file. You have specify the platform like this: https://github.com/cheminotorg/m.cheminot.plugin/blob/master/src/android/jni/Application.mk#L1

**Comment by veloce** [comment]
I tested to change that file, but it didn't seem to work.

**Comment by srenault** [comment]
Weird. I just test by changing `android-16` in `android-14`  in `app/platforms/android/jni/Application.mk` file. I don't have anymore the warning `Android NDK: WARNING: APP_PLATFORM android-16 is larger than android:minSdkVersion 14 in ./AndroidManifest.xml`

**Comment by veloce** [comment]
Ah. So maybe it worked after all :) I just saw a comment on google play saying that the AI were not working but we shouldn't trust too much those comments.

**Comment by srenault** [comment]
Ok. Don't you have any crash traces in the Android developper console ?

**Comment by veloce** [comment]
Not for version 4.0

**Comment by veloce** [comment]
It seems to be the case for version 4.2 too. So I guess this is the case for all android version < 4.4.

Maybe you have another idea @srenault ?

I'll use the stockfish.js polyfill as a workaround for now.
