### ISSUE TITLE
Allow analysis board for puzzles

### ISSUE THREAD

**Issue by cuzox** [veloce/lichobile#344]
This is a feature. It would be great to allow analysis board for puzzles so that it is not necessary to go to the desktop to gain more insight on a certain position. Great work btw you guys.

**Comment by veloce** [comment]
What do you want exactly? To load the position of the puzzle to the analysis board?

I don't know such a feature on the website. But if you want to go to the game after the puzzle is completed to be able to analyse it, then it's perfectly doable.

**Comment by quinncomendant** [comment]
On the website, after you finish, fail, or give up on a puzzle, you can click the analysis board button (microscope icon) to enter analysis mode for that puzzle. It is rather useful to use it to understand why the solution given by the puzzle is the *correct solution*. Often, I will think I'm more clever than the creator of the puzzle, and think I've identified an alternative solution, only to find during analysis mode that my alternative solution was a delusion. ;)

With the current version of the iOS app, after completing a puzzle, there is no way to enter analysis mode. We must go to the URL for the puzzle (e.g., https://en.lichess.org/training/49818) into the website, click "give up," and then enter analysis mode there.

**Comment by cuzox** [comment]
^THIS! 
Could have not said it better.

**Comment by veloce** [comment]
Yes I got it, the app don't lacks those buttons.
