### ISSUE TITLE
Unexpected quit during Analysis in v4.0.1

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#347]
After playing an over-the-board game, I went into Analysis mode, and began skipping backwards through the moves to find the position where my side lost its advantage (the new analysis speed is great BTW). After about 5-7 moves back, the app quit with no message (to the home screen). 

I launched the app again, navigated to Over-the-board, then entered Analysis mode again, and began going back moves. Again it crashed. This repeats.

Here's the PGN of the game:

    0. Ne3 c6 1. d4 d5 2. c3 e5 3. b4 exd4 4. cxd4 Qxb4 5. a3 Qxd4 6. N3c2 Qf6 7. a4 Bf5 8. Ra3 Ne6 9. Nf3 Bd6 10. Re3 Bc5 11. Re5 Nd6 12. Bg5 Qg6 13. Ne3 f6 14. Bxf5 Qh5 15. Rxe6 fxg5 16. g4 Qf7 17. Nxg5 Nxf5 18. Nxf7 Nxe3 19. Qh3 Kxf7 20. Re5 Nd1 21. Rf5+ Kg8 22. Kg2 Nxf2 23. Qf3 Nxh1 24. Kxh1 Re8 25. Qc3 g6 26. Rg5 Bd6 27. h4 Rxe2 28. h5 Re6 29. hxg6 hxg6+ 30. Kg2 Rh2+ 31. Kg1 Ree2 32. Rxg6+ Kf7 33. Qg7+ Ke8 34. Qg8+ Bf8 35. Re6+ Kd7 36. Qf7+ Be7 37. Qxe7+ Kc8 38. Rxe2 Rh8 39. a5 b6 40. a6 c5 41. Qxa7 Rh6 42. Qb7+ Kd8 43. a7 Rc6 *

I tried to import this PGN directly into Analysis mode to test if it also crashed when outside of over-the-board context, but the import never finishes (I'll open a separate ticket for that).

**Comment by veloce** [comment]
Yes I saw a crash as well, with chess960 only, and I believe only on iOS. But this means nothing since I didn't try the same PGN on both platforms. Frankly I have no idea why. My debugger showed that the crash occured in some stockfish code managing variants. That's all I know.

**Comment by veloce** [comment]
Could not reproduce after upgrading stockfish plugin.
