### ISSUE TITLE
evaluation bar transitions backwards

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#350]
It should rather start fresh when switching to a different move. The web version [had the same bug](https://github.com/ornicar/lila/commit/e7fa16b3194fa41d12b1dddd3732a6ce233d433e#diff-994c882e58eb463beaefefa02ad00241R89) once.

**Comment by freefal** [comment]
What's the bug? Can you describe it in more detail? I'm not sure what "evaluation bar transitions backwards" means.

**Comment by pdknsk** [comment]
Sorry, I thought it's obvious from the linked commit. In evaluation mode,
the green bar transitions forward with each ply. Now switch to the next
move, which makes the bar transition backwards. It should rather start
fresh immediately. This is merely a cosmetic bug, which was fixed on the
web version previously.

2016-06-17 21:08 GMT+02:00 Mark Henle <notifications@github.com>:

**Comment by pdknsk** [comment]
Is this supposed to be in _4.9.0_? If so, it's not fixed.
