### ISSUE TITLE
Side Switches Randomly When Playing Offline Computer

### ISSUE THREAD

**Issue by freefal** [veloce/lichobile#357]
As reported here (https://en.lichess.org/forum/lichess-feedback/mobile-app-ai-bug) and in a number of other places. Can't yet reliably reproduce, but have observed.

**Comment by movabo** [comment]
I could replicate this by castling:
![screenshot_20160621-142034](https://cloud.githubusercontent.com/assets/4041740/16229299/4d389d24-37bc-11e6-8a49-d15410c720f9.png)
The important part is how you initiate it:

First click on the king and then click on the rook (not on the field two fields away from the king).

Sometimes after doing this, the computer does nothing, other times it moved with my items.
