### ISSUE TITLE
Analysis board should start from the last move in the position

### ISSUE THREAD

**Issue by apetresc** [veloce/lichobile#358]
When you open a new analysis board (in, say, a correspondence game), it loads up from the first move  and requires the user to make an additional tap to zoom to the end.

Given that 99% of the time, you're analyzing a correspondence game to try to figure out your next move rather than to explore 1.e4, it makes much more sense to have the analysis board default to the most recent move in the position.

Is this okay from a design point of view? Would a pull request that changed this behavior be accepted, or are you philosophically opposed?

**Comment by freefal** [comment]
@veloce is on vacation, but I strongly suspect that if you created a well-written PR for this, it would be accepted.

**Comment by veloce** [comment]
Sure, that would be accepted.
