### ISSUE TITLE
Android: Accessing profile and preferences should not take three  clicks

### ISSUE THREAD

**Issue by dfc** [veloce/lichobile#371]
I access my profile and preferences  much more than any of the things in the default list. Right now I have to:

1. Bring up menu
2. Click drop down
3. Click prefs or profile

Why are these buried? Surely other people want to review their games. Profile and preferences should listed under the 'home' entry.

**Comment by veloce** [comment]
For profile I agree, I'll move it under Home entry like you suggest. Preferences though is not accessed very often so I'll leave it under the drop down menu.
