### ISSUE TITLE
Conditional premoves in corres games

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#374]

**Comment by lightbulbjim** [comment]
+1

**Comment by bak1an** [comment]
I am interesting in having this, will try to create a PR implementing that.

**Comment by c5gaspar** [comment]
> I am interesting in having this, will try to create a PR implementing that.

Any updates on this PR?

**Comment by bak1an** [comment]
@c5gaspar I started working on it back then but had to abandon it due to a lack of free time.

Thanks for pinging, it is a good reminder to dedicate some hours to finishing half-baked PRs.

**Comment by KennethJ-USC** [comment]
Still really interested in this feature. What would you estimate the amount of dev time it would take to finish your implementation @bak1an ?
