### ISSUE TITLE
Can't drop piece in correspondence crazyhouse

### ISSUE THREAD

**Issue by leekaiinthesky** [veloce/lichobile#377]
I'm on iOS playing correspondence crazyhouse.

If I move a piece on the board, it brings up the Submit/Cancel dialog as expected. But if I drop a piece, the menu doesn't appear. (The piece is also displayed both on the board and still in my piece tray, which also seems like a bug.)

A couple other minor things:
- I can drag a piece from my opponent's the tray (but probably shouldn't be able to).
- After I submit a move, my clock should reset but doesn't (this may exist for all correspondence chess, though I haven't played any other correspondence variants yet).

I wasn't sure whether I should create separate issues for these, but they seemed minor enough that I thought I'd just combine them. Thanks, and great work on this app!

**Comment by veloce** [comment]
Thanks for this. I was aware of all the issues except for the corres. piece drop one.

They'll be all fixed by the next release.
