### ISSUE TITLE
Menu buttons become unresponsive

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#38]
Steps to reproduce: Use application a bit by moving back and forwards between menus, sliding the current games tiles, etc...

Device: HTC Incredible S
OS: Android 4.4.4 w/ Cyanogen mod 11-20140919-UNOFFICIAL-vivo

**Comment by veloce** [comment]
Since it's hard to reproduce, we need #35 first to identify this

**Comment by ornicar** [comment]
yeah, happens to me too, when switching between correspondence games

**Comment by veloce** [comment]
Closing since we can't reproduce anymore for sure.

**Comment by ornicar** [comment]
I'm not seeing it anymore.
