### ISSUE TITLE
Sending a rematch invite hides the opponent's presence

### ISSUE THREAD

**Issue by CamilleVictor** [veloce/lichobile#381]
Hello!

Thanks for the good work! Recently I have noticed one thing while playing on the app. Whenever I'm sending a rematch invitation to my opponent, the window becomes bigger and hides if my opponent has left or is still here to see the invitation. It's not a big issue but either the window should be small enough to see that the opponent left or the invitation is automatically cancelled when he leaves.

I play on a Sony xperia btw if the screensize matters.

Thanks!

**Comment by veloce** [comment]
There's too many screen sizes so I suppose the right way to fix it is to cancel the invitation if opponent has left the game.

**Comment by CamilleVictor** [comment]
I know. But you don't know if the opponent has left the game. He can't just not answer the challenge and leaves and you're left hanging with the challenge. Ok it's just a matter of seconds but it's annoying sometimes.

**Comment by veloce** [comment]
But if the opponent leave the game and I cancel the challenge you'll know he's left the game, right?

**Comment by CamilleVictor** [comment]
Only if I cancel I can see if he left. But what if he is still here just wondering if he has time to play another one. He'll just see that I cancelled the challenge and think that I don't want to play after all but instead it was purely to check if he was still here. I know it's not really much but I'm paranoid now as I don't want to waste even 5 seconds wondering if he is gone or not so sometimes I send 1 challenge, wait 2s, cancel and check if he is here, send again if he is still here, wait 2s, cancel again, etc.

**Comment by veloce** [comment]
If I remember correctly the rematch invite you send it from the game menu popup, but then you can close the popup and you'll be redirected when the opponent accepts. So you can watch if he's still there.
Maybe it needs a notification when opponents reject the rematch invite then.
