### ISSUE TITLE
Android analysis interface is cluttered and redundant

### ISSUE THREAD

**Issue by dfc** [veloce/lichobile#383]
I like some of the improvements to the analysis mode. I think the interface is a little cluttered now: 

* The analysis interface prints the game type and timing in the header and in the bottom left above the player names. 

* The outcome listing is also redundant. If white resigns, black is obviously victorious. 

* Why is "standard" a hyperlink to the Wikipedia page for chess? 

* Is printing analysis board in the header bar useful? It seems obvious from the interface you are in analysis mode. 

Side note: i really miss printing the computer recommended move in text notation. Cleaning up either of the first two items would free up space for printing text move.

**Comment by veloce** [comment]
Ok, thanks for the feedback. I also was reluctant to remove the move text notation. 
I did it because I had to make the interface coherent between local and remote eval... but I'll try to find a way to put it back.

**Comment by veloce** [comment]
TODO:

- [ ] eval in text notation
- [ ] add perf icon in title
