### ISSUE TITLE
Impossible move recommendation in Chess960 analysis

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#384]
I was in analysis mode, working backwards through a played Chess960 game, when the move recommendation was for a piece that didn't exist. See screenshot below, arrow is on d5 which doesn't hold a piece.

![2016-07-20 at 11-35-47](https://cloud.githubusercontent.com/assets/6884276/17086601/a52bf342-51c4-11e6-9023-5e38d9b1517a.jpg)

**Comment by veloce** [comment]
Mm. That will be hard to reproduce but thanks for letting me know.

**Comment by kdarkhan** [comment]
Had this problem in Training mode. Might be related to the same issue.
Notice that when rook moves c1-c8, it acts like there is no pawn on c5.
![out](https://cloud.githubusercontent.com/assets/1087493/19023287/3936be62-890d-11e6-9959-adfba6d17efc.gif)
