### ISSUE TITLE
Playing offline

### ISSUE THREAD

**Issue by galuel** [veloce/lichobile#386]
I played with the Lichess mobile app recently, I found two problems in use :

- When playing offline with a friend we have no clock ! (however the reverse chessboard at each move is wonderfull !). This seems very strange since the app proposes us a full screen clock to use it with external chessboard, but no clock to play offline on the mobile...
- When playing online we can propose a challenge but we cannot see the challenges proposed by the others like we can on a classic PC.

**Comment by ornicar** [comment]
1. The app has a clock now, so you could use a second device for the clock.
2. There's too many seeks and they change too fast to be practical on mobile. Autopairing works just as well.

**Comment by galuel** [comment]
1. Yes but when I have only one device ? And when I play online on mobile, I have the clock, so why not offline ?

2. Yes it is ok it works, but it supposes then we only can accept a challenge, and not propose on mobile, so we can only play with PC users who made challenges, so a not all community...

**Comment by ornicar** [comment]
It's the same seeks and community. Autopairing is also in effect on the site, and handles most pairings.

**Comment by galuel** [comment]
Of course ! I'm stupid concerning this point :)
