### ISSUE TITLE
new Drag and Drop is confusing. (iOS)

### ISSUE THREAD

**Issue by asibahi** [veloce/lichobile#388]
Hey,

The newest change to the drag and drop is confusing, especially when I play crazyhouse. I consistently manage to put the piece on the square below the one I intended.

I think the issue is that the piece hovers above my finger, instead of where my finger is. I lost a few pieces several times just because I dropped the piece in the wrong square.

Doesn't help that the CrazyHouse dropping move doesn't allow anything but dragging ....

**Comment by veloce** [comment]
No changes have been made related to drag and drop recently.

You should not look at the piece, rather at the circle target to know where it will drop. Then you can adjust options under settings to enable/disable magnifying while dragging.

**Comment by asibahi** [comment]
@veloce I haven't used the app in a while so this change might not be the most recent.

It is still confusing. I am moving a piece, not a circle. When I start the dragging movement i start by putting my finger on the piece. Expecting me to NOT look at the piece is .. well .. a weird thing to ask. In regular chess it wouldn't be too much of a problem but in CrazyHouse it is detrimental, especially when moving by tapping isn't an option.

**Comment by veloce** [comment]
I don't know what change you're talking about actually. But if you don't like the piece being lift up when you drag it, try to disable magnifying in the options. This way the piece will stay the same size and right under your finger.
