### ISSUE TITLE
[Idea] Lichobile outside of iOS and Android

### ISSUE THREAD

**Issue by marmistrz** [veloce/lichobile#395]
Hi,
Are there any plans for porting Lichobile to platforms other than iOS/Android? For example:
- Ubuntu Touch natively supports Cordova: https://cordova.apache.org/docs/en/latest/guide/platforms/ubuntu/
- SailfishOS has a port of Cordova: https://github.com/lizardK/cordova-sailfish
- there is PhoneGap for Nokia N900 running Maemo5.

I have no idea about the gulp support on these platforms, but Sailfish has `nodejs` 0.10 with `npm`. Maemo5 has `nodejs` 0.8 without `npm`. No idea about Ubuntu Touch. 

The Maemo/Sailfish community is a very active one, especially the Sailfish one nowadays. No idea about Ubuntu Touch.

I may help ;)

**Comment by veloce** [comment]
Since I don't want to maintain other platofrms than android and ios, you can fork lichobile and do such a port. Indeed the main part is the web app, you'll just have to add/change cordova specific stuff.

That would be great!

**Comment by marmistrz** [comment]
I guess I won't be able to do the port myself. Too few time and I'm already working on one lichess-related project (marmistrz/lichify)

Hopefully someone will grab it up.
