### ISSUE TITLE
Please upload lichobile to F-Droid

### ISSUE THREAD

**Issue by marmistrz** [veloce/lichobile#409]
lichobile is Free Software. It's a pity that the only update channel is Google Play.

**Comment by ornicar** [comment]
You can use http://veloce.github.io/lichess-mobile-apk/.

**Comment by marmistrz** [comment]
When using an F-Droid repository or Google Play, the user is notified that an update is available. This is not the case if we're using manually downloaded apks. It's tedious to check whether such apps have an update or not.

F-Droid is an app market which hosts Free Software only (as opposed to Google Play). If you don't want to mess with the F-Droid submission queue, you can create your own repository, [1] especially that you already host previous versions on [2]

[1] https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo
[2] http://veloce.github.io/lichess-mobile-apk/

**Comment by veloce** [comment]
I don't have the time to maintain another store. Any volunteer willing to maintain a lichess app in any store is welcome to do it! The app is open source, it could be in any store.

You can for instance take the apks in http://veloce.github.io/lichess-mobile-apk/ and put them in fdroid.

**Comment by Calinou** [comment]
> You can for instance take the apks in http://veloce.github.io/lichess-mobile-apk/ and put them in fdroid.

F-Droid does not allow that (with rare exceptions), all apps must be built from source. This is to ensure reproduceability.

**Comment by maeslor** [comment]
@veloce @ornicar  There is already a submission request for inclusion on F-Droid, which will take care of the process: <https://gitlab.com/fdroid/rfp/issues/94>

We just need to fulfill the last item of the checklist: "The original app author has been notified (and supports the inclusion)."

**Comment by Kaligule** [comment]
From the [linked thread](https://gitlab.com/fdroid/rfp/issues/94):

> I've had a cursory look at the source code of Lichess and it seems that it depends on OneSignal which has a non free modified MIT license  which prevents use of the code with services other than OneSignal.

> It seems that OneSignal depends on the proprietary Play Services so a fork of Lichess would need to be created that does not use this.

**Comment by marmistrz** [comment]
Btw. if the releases are properly tagged and the app can be built without proprietary deps, then F-Droid can automatically build newer releases without developer's interaction.

**Comment by landry314** [comment]
This link above is dead btw: http://veloce.github.io/lichess-mobile-apk/
