### ISSUE TITLE
Losing wifi momentarily (and switching to data) means you lose the game

### ISSUE THREAD

**Issue by vrasidas** [veloce/lichobile#419]
It takes lichess forever to reconnect even if you get wifi right back (if you wandered to the far side of the house but stepped right back in range afterwards for example) so the opponent gets the notification that you abandoned the game and can claim victory. This is on an lg g4 running android 6.

**Comment by veloce** [comment]
lichess is really trying to reconnect every 1s when the connection is lost. Getting wifi right back doesn't mean you have a stable wifi. Try to switch off wifi to stay on data in that case.

**Comment by veloce** [comment]
Re: I've tested what you described, and it's true: if you loose the wifi, and the connection switches to data then lichess keeps reconnecting for ever. Hard reloading the game works though. 
Getting back to wifi with an established connection through data works too.

Well, it may be an issue with websocket, which may not be reliable in that case. I'll see what I can do.

**Comment by vrasidas** [comment]
Thanks for testing. Best thing about this app other than how good it is, is the speed with which bugs get fixed.

**Comment by veloce** [comment]
Fixed in https://github.com/veloce/lichobile/commit/9f4e8810eeb5eacbb3b19aba7c7f99244a425b91
