### ISSUE TITLE
fresh install on macosx

### ISSUE THREAD

**Issue by peutetre** [veloce/lichobile#42]
With the current master of [tarifa](https://github.com/TarifaTools/tarifa) (0.5.0-dev) what I had to do build the ios app:

* remove android platform folder
* remove `ios` and `android` in `platforms` attribute inside tarifa.json
* remove all plugins from the `tarifa.json`
* re install each plugin (we need to do something about that on tarifa)
* tarifa platform add ios
* tarifa platform add android
* copy https://github.com/veloce/lichobile/blob/master/tarifa.json#L23-L26 into default ios configuration in `tarifa.json`

and then run `tarifa run ios -V`

**Comment by veloce** [comment]
Yes I know this is not ideal... I'll update the readme btw.

I think that adding platforms on repo checkout is not a big deal, but you're right we should be able to install all plugins in tarifa.json with a single command.
