### ISSUE TITLE
[BUG] Impossible move in offline game

### ISSUE THREAD

**Issue by Kcchouette** [veloce/lichobile#420]
Game downloaded through Google Play Store, version of lichess for android is 4.4.1

I played against the computer in offline mode, stockfish level 1, side white, variant standard.

I don't know if this bug is already resolved on the master branch so here steps to reproduce it:

* I play **e2** to **e4**, computer plays **d7** to **d5**<br>
![picture_1](https://cloud.githubusercontent.com/assets/3000936/18329058/1874e790-7552-11e6-977a-3398ec2046ad.png)
* I play **e4** to **d5**, computer plays **g8** to **f6**<br>
![picture_2](https://cloud.githubusercontent.com/assets/3000936/18329254/d05e26be-7552-11e6-99e3-77d2f5d73993.png)
* I play **f1** to **c4**, computer plays **e7** to **e5**<br>
![picture_3](https://cloud.githubusercontent.com/assets/3000936/18329386/6994e55c-7553-11e6-8c8b-f5d5b146070e.png)
* For my next move, I can move **d5** to **e6**… That's normally not allowed! But I do it!
![picture_4](https://cloud.githubusercontent.com/assets/3000936/18329488/f27840c6-7553-11e6-99bc-6bc065a8b18c.png)
* It misses a piece! Where is **e5**? I don't know, it disappear. Computer plays **c8** to **e6**.

It's the bug. If you want more detail, do not hesitate. Thanks!

**Comment by niklasf** [comment]
Thanks for the detailed report. This type of move is called "en passant". You can learn about it here: https://en.lichess.org/learn#/15

**Comment by Kcchouette** [comment]
Here a screenshot of the analysis board + a PNG text of the play:
![analysis_board](https://cloud.githubusercontent.com/assets/3000936/18330016/a498e5ec-7556-11e6-90ff-213e0012f279.png)

```
[Event "Casual Game"]
[Site "http://lichess.org"]
[Date "9/7/2016"]
[White "Anonymous"]
[Black "Anonymous"]
[Result "*"]
[PlyCount "8"]
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]
[Variant "Standard"]
[Termination "?"]

1. e4 d5 2. exd5 Nf6 3. Bc4 e5 4. dxe6 Bxe6 *
```

**Comment by Kcchouette** [comment]
Oh, I don't know, sorry :(
