### ISSUE TITLE
Lichess opens to a blank screen on iOS 10

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#428]
I'm experiencing this new behavior since updating to iOS 10 (I updated from 9.3.5 to 10.0.1). Launching lichess shows blank, black screen (only the phone status icons display at top). If I go back to the iOS home screen and open lichess again it does launch and function correctly. If I force quit lichess, then open it again this repeats: black screen on first launch, but opens correctly on next launch. 

![2016-09-22 at 11-39-49](https://cloud.githubusercontent.com/assets/6884276/18757539/f0fda92c-80b9-11e6-8e65-2acb46a9cb19.jpg)

**Comment by quinncomendant** [comment]
Closed because…?

This issue continues 100%, even after updating now to 10.0.2. You're not able to reproduce it?

**Comment by veloce** [comment]
Closed it's fixed.. to be released soon
