### ISSUE TITLE
Need simple way to list friends

### ISSUE THREAD

**Issue by mellotron** [veloce/lichobile#433]
The mobile app should have a simple way to list friends.

Currently, to start a match with a friend, I have to do the following:
- Right menu
- Players
- Search for the person's exact username
- Click on name
- Challenge to a game

It'd be better if I could go:
- Left menu
- Profile
- View friends # Maybe even have Friends under the Community section?
- Click on friends name
- Challenge to a game

**Comment by mellotron** [comment]
Wow, I just noticed the little arrow next to the server latency which gives access to friends list - it's not very clear what that arrow gives access to however!

**Comment by freefal** [comment]
While the arrow is not perfect, I think this issue can be closed.

**Comment by veloce** [comment]
Yes, and the arrow is more visible now in 4.7.0.
