### ISSUE TITLE
"Play with a friend" should allow friend name selection

### ISSUE THREAD

**Issue by mellotron** [veloce/lichobile#434]
It'd be nice if the "Play with a friend" menu option allowed one to specify the username of the friend to play with.

Currently, it gives one a link, which only seems to work on a desktop browser as on my Android phone, it opens Firefox for Android, then tries to launch the Lichess app, which then freezes.

**Comment by veloce** [comment]
What you ask for actually exists: you can challenge directly a user by going to its profile page.

**Comment by kernc** [comment]
Yeah, but if the user happens to be offline, how many clicks/taps away is that?
