### ISSUE TITLE
better visual cue for completed move evaluation

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#436]
It can be a bit difficult to notice the difference between the last ply still being processed, and it having completed. The difference can be just very few pixels.

I suggest a minor visual cue, like changing color of either the progress bar, the text indicating the best move, or the arrow on the board.

May I also use this opportunity to mention related issue https://github.com/veloce/lichobile/issues/350 which could be fixed *en passant*, I think.

**Comment by pdknsk** [comment]
PS. Should max ply depth be increased further at some point, as it was from 18 to 20, the last step will be even less pixels.

**Comment by veloce** [comment]
Fixed in version 4.7.0 (current depth is shown in text)
