### ISSUE TITLE
Broken on iOS10

### ISSUE THREAD

**Issue by JoshuaMontgomery** [veloce/lichobile#437]
Small set of phenomenology:

+ black screen when opened, never loads (large fraction of attempts to open app end here)

+ if it does load, often loads as anonymous

+ logs in ok, but after apparently making moves in correspondence play the moves revert when app is closed (looks like they never register for other users)

+ while in correspondence play, some features remain offline, in particular features involved in communicating with other player (chat is malformed and text disappears). 

It does appear that rarely these issues don't occur and moves may be made.

**Comment by albertosantini** [comment]
Black screen is fixed with `4.5`. 
See https://github.com/veloce/lichobile/issues/426.

**Comment by veloce** [comment]
Good, closing then.
