### ISSUE TITLE
iOS Push notifications

### ISSUE THREAD

**Issue by cjrorvik** [veloce/lichobile#439]
So nice to see an ios update on iOS notifications! 😄  Doesn't seem to work as expected though 😞 Tried to test it with a correspondance game for 2 days with a friend, but after 20 minutes it still haven't sent a notification for the latest move.

**Comment by veloce** [comment]
It seems that they are working only if you are on iOS 9 for now. There is a subscription issue on iOS 10 that I was unaware of.

**Comment by davidhariri** [comment]
Having this issue as well. On iOS 10.0.2

**Comment by davidhariri** [comment]
@veloce Noticed you closed this issue, is this fixed?

**Comment by veloce** [comment]
New version 4.5.5 is on review, should land within 3-4 days. Note that it fixes push for iOS 10, I upgraded my phone, so I couldn't test on iOS 9.

**Comment by cjrorvik** [comment]
Doesn't seem to work after the update..

**Comment by cjrorvik** [comment]
Nevermind! Works now😉 Thanks for the nice feature!

**Comment by substa** [comment]
Hello,
unfortunately it seems still not working...

After app update, no notifications received, so I delete the app and install it again.
After reinstallation I received the first notification, yeah, but... only for the first time...
Now, again, no notification at all :(

iPhone 6, iOs 10.0.2

**Comment by veloce** [comment]
Make sure you've granted push notifications for lichess mobile app, and make sure you don't have an active tab on the game on lichess.org: server won't send a push if you're currently active.

**Comment by veloce** [comment]
Now I consider this issue fixed, please don't report problem like 'push notifications don't work for me' here.
Only report an issue if it's something new, with a detailed explanation and steps to reproduce the problem, thank you.

**Comment by substa** [comment]
Of course I granted push notifications for lichess mobile app (and I tested many times to select/deselect the option). I'm using exclusively the app, no desktop browser, so not active tab.
Same problem occurs to (at least) a friend of mine. So I think the issue is not fixed.
But thanks anyway :)

**Comment by veloce** [comment]
I'm not saying you don't have an issue. But this is not the right canal to address it. Please send an email to lichess.contact@gmail.com with your user id, your device/os, and we'll try to analyse your problem.
