### ISSUE TITLE
Android toolbar colour

### ISSUE THREAD

**Issue by Happy0** [veloce/lichobile#440]
Do we have any control over the android toolbar color when the app is open?

Somebody pointed out that their android toolbar colour has a dazzling contrast compared with the app colour: https://en.lichess.org/forum/lichess-feedback/android-app-bugs#5

I'm not sure what determines the toolbar colour. The toolbar is black for me on my nexus 6p when the app is open, but another colour with the twitter app open for example.

I will try to investigate this, I guess!

**Comment by veloce** [comment]
https://github.com/apache/cordova-plugin-statusbar

**Comment by fabio656** [comment]
yes, my android toolbar is a very bright blue with lichess app.

**Comment by freefal** [comment]
Did this (https://github.com/veloce/lichobile/blob/master/src/js/main.ts#L71) fix this issue?
