### ISSUE TITLE
Drag&Drop - Old position of the pieces.

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#443]
Hi, i''m ScaccoLento on lichess.org, i report here;
https://en.lichess.org/forum/lichess-feedback/android-app-bugs#9

---

A suggestion for the developers for lichess android App;

It would be very nice to add "the old position of a piece" when i drag my pieces.
i mean, when i tap and drag one of my piece, would be very very usefull to see where this piece was! 
A very good soluction is like the site...with the transparent piece that remain on the starting square.

is very very usefull, because by now, when i drag a pieces, is hard to remember where my piece was (expecially if i want to replace my piece in the same square where it was).

Look this screenshot;
i 'm dragging my queen.....is hard to understand where my queen was, expecially if, during a game, you have problems of time and you are in hurry.
is not intuitive to understand the old position and replace my queen there.

https://drive.google.com/file/d/0B-QYjlrisF60cjM0VndxWVQxWDQ/view?usp=drivesdk

thanks :)

**Comment by freefal** [comment]
ScaccoLento, the easiest way to deal with your problem is to simply drop the piece off the board and it will go back to it's starting square.

**Comment by fabio656** [comment]
yes i know, but is usefull  for a better calculation during the dragging of a pieces.
very often i hold a piece dragged when i think the best square where drop my piece...and to see where this pieces was..is usefull!
In fact, this thing there is on the site, and is perfect :)

**Comment by veloce** [comment]
Will look into it

**Comment by veloce** [comment]
Unless you disabled board highlights, you can know where you piece was by looking at the orange square (selected piece square).

**Comment by fabio656** [comment]
yes is true, but if you use wood board theme, the orange color is too similar to the color of maple wood, and is difficult to see the orange square, you can see this on my shots below

**Comment by fabio656** [comment]
sorry, i meant *my shot above, not below

**Comment by veloce** [comment]
true

**Comment by veloce** [comment]
Done in https://github.com/veloce/lichobile/commit/7b1ebf97fe704acd58db9efa094a92894b44c49f
