### ISSUE TITLE
Notification spam for correspondence games with conditional premoves

### ISSUE THREAD

**Issue by ProgramFOX** [veloce/lichobile#448]
I put some conditional premoves on a game, and all of them were played, but I got this on my phone:
![screenshot_20161014-070338](https://cloud.githubusercontent.com/assets/8034604/19392579/9e6f5910-9231-11e6-8fa4-4f3ee3370f04.png)
I got a notification for each move, but that really wasn't necessary because I had a premove for all of them. Can notifications be avoided if there is a conditionally premoved response?

**Comment by veloce** [comment]
@ornicar is it possible server side to not send a notif when conditional premoves are set ?

**Comment by veloce** [comment]
The fix is server side: https://github.com/ornicar/lila/issues/2439
