### ISSUE TITLE
Badge icon with notification count

### ISSUE THREAD

**Issue by Happy0** [veloce/lichobile#455]
We could perhaps support badge icons with notification counts (or maybe just correspondence games awaiting responses count) using this cordova plugin:

https://github.com/katzer/cordova-plugin-badge

Feature request was from: https://en.lichess.org/forum/lichess-feedback/badge-app-icon-for-lichess-iphone-app

**Comment by Happy0** [comment]
Or maybe that'd annoy some people... I'm not sure!

**Comment by veloce** [comment]
Since it's tied to the notifications we should use this instead: https://github.com/OneSignal/OneSignal-Cordova-SDK

**Comment by lightbulbjim** [comment]
This would be really nice to have.

**Comment by astephensen** [comment]
Agreed this would be great! On iOS you can turn off the badge icon in the app's notification settings so anyone who is annoyed can still turn it off 😄

**Comment by larister** [comment]
Agreed, really want this feature

**Comment by wollkind** [comment]
Another vote for this: correspondence games waiting for moves as a badge would be excellent

**Comment by TaipanRex** [comment]
This is needed!

**Comment by mastro35** [comment]
Yes, it'd be a great feature

**Comment by kristomi** [comment]
+1 On this.
