### ISSUE TITLE
Tablet View issues

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#458]
hi! 
thanks for this great upgrade, now i really better for the tablet !!
But i have some issues with this new upgrade...

1) in portrait mode, the board seems very little compeared to the display and the ratings are cutted off.

2) in landscape mode, the board is too low and appears cutted off to the bottom.

3) in landscape mode the usernames and the rarings are super-cutted off, and unreadable because the fonts are too big.
A possible fix maybe to put the ratings below the usernames.

4) same problem in potrait mode for the analisys, board too little.

give 2 screenshots :)

portrait;
https://drive.google.com/file/d/0B-QYjlrisF60c3BMUldUbHBkX1E/view?usp=drivesdk

landscape;
https://drive.google.com/file/d/0B-QYjlrisF60ZGxOcmtYekRBRkE/view?usp=drivesdk

if you need betatester, i'm here :)

**Comment by fabio656** [comment]
Another little suggestion is to decrease a little bit the fonts, are too big.

**Comment by veloce** [comment]
Thanks for feedback.

The 2 screenshots are the same. 

You're device is a 4:3 screen device right? Then it's not the normal display, I think there is a bug because the media query does not recognize the aspect-ratio. I don't own an android tablet so I can't test in a real device... that's a problem.

Here is how it is supposed to look like in a 4:3 screen tablet:
- landscape: http://imgur.com/a/y96Xe
- portrait: http://imgur.com/a/uWJxb

See, the board size has been reduced to leave place for the rest. That's a shame if media queries don't work the same on all devices.. will look into that issue.

Will decrease font size too, based on your suggestion

**Comment by fabio656** [comment]
i edited my post with the correct images links. :)

my tablet is a new Samsung Tab S2 8" 4G . yes ...it is have a 4:3 display like ALL the new samsung tablets (tab S2 8 and 9,7 inchs, Tab A and others....) 

my suggestion is to increase a little bit the board in portrait mode.

in portrait mode, my tablet i have LARGE black empty spaces.

**Comment by veloce** [comment]
I see, the empty spaces are meant to reduce board size to make place for the rest. 

It it especially useful in analysis board, and board editor. Less useful in game view, but having same size everywhere helps me to maintain the app by simplifying code.

Do you think the black empty space is a big issue? Do you see the benefits in analysis mode, where you need to display the move list and need more space?

I will try to decrease font size by 10%. Is the font also too big in analysis mode?

**Comment by veloce** [comment]
I am aware of the ratings cut off, will push a fix.

**Comment by veloce** [comment]
Does the landscape issue occur in all the screens (game, editor, analysis, etc), or just game?

**Comment by fabio656** [comment]
for me the size of the board in portrait mode are too little, mostly for 8 inches tablet like mine tablet.
8 inches is not a very big display, and the board seems too llittle, for the game, and i'm forced to use landscape mode to play.

**Comment by fabio656** [comment]
now i go to see if the landscape issues are for game only.
waith a minute.

**Comment by fabio656** [comment]
yes, same problems
https://drive.google.com/file/d/0B-QYjlrisF60c3BMUldUbHBkX1E/view?usp=drivesdk

**Comment by veloce** [comment]
Same screenshot

**Comment by fabio656** [comment]
now?
https://drive.google.com/file/d/0B-QYjlrisF60X3RLMUtuZTlYX0U/view?usp=drivesdk

google drive is full of bugs....i click on a screenshot, and give me another image....bha.....

**Comment by fabio656** [comment]
look in the bottom, the icons and the board are cutted off from the screen

**Comment by fabio656** [comment]
i use your kindness for report you the android toolbar colour issue.
if you see my screenshots, you can see that my android toolbar become a "too bright blue" with Lichess app.

thanks, bye :)

**Comment by fabio656** [comment]
hi veloce, there is another issue.
When i play some games or some tactics puzzles, the ststistics in my profile are not update.
for example in this moment my rating in the site is correctly 1948 in tactics....but in the app i am still 1971 like when i started to play tactics half hour ago 🙂

**Comment by veloce** [comment]
About: the blue bar, I'm aware about it. But I don't have a phone that does it and it's not urgent.

About the tactics rating: open a new issue if you want it to be fixed.

**Comment by fabio656** [comment]
Thanks, i have opened a new issue :)

Remaining to this topic...
please, change something to this new version of the app, because, by now, for who have new samsung tablets like me, this version of the app is almost unplayable for many reasons :(

In portrait mode the board is too little for a 8" display....but in landscape mode is cutted off in the bottom...
i cant read the nicknames of the users, and i cant read the ratings of my opponents.
sometime the analisys board remain blocked and i can't do the next move (it seems like if i make a pre-move....and pieces remain blocked)

i have a lot of issues.😨

**Comment by fabio656** [comment]
i edited my post with captured pieces issue

**Comment by fabio656** [comment]
today i want to try the App on my Lenovo 16:9 8" tablet, and i tell you if is ok

**Comment by fabio656** [comment]
thanks for the new release, now is all ok, the size of the board in portrait mode is nice!
2 little suggestions;
1) should be nice if you increase a little bit more the board in landscape mode, now is very little.
2) only for a matter of taste :) would be nice in portrait mode to put the ratings of the players after the nickname, inside the ( ) and in Bold like this;

ScaccoLento (**1790**) 

with the captured pieces under the nicks like landscape mode, just for have the same interface in landscape and portrait mode.

but this last suggestion is only a matter pf taste :)

thanks for the new upgrade.

**Comment by veloce** [comment]
Thanks for the feedback.
The problem in landscape mode with a 4:3 tablet, is that if I increase the board size, there is no more place for the side column right to the board.

I think the current size is a good compromise. If you want a big board: use portrait mode, if you want more info displayed (move list, etc): use landscape with the inconvenient of a smaller board.
