### ISSUE TITLE
Push notifications: what about devices without GMS?

### ISSUE THREAD

**Issue by marmistrz** [veloce/lichobile#470]
In the dot points for mobile app: 
> Push notifications! For PMs and when its your turn to play (much requested by correspondence players)

And what about devices which do not have the proprietary GMS? Will they receive any notifications at all?

**Comment by veloce** [comment]
You can receive them through wifi as well. It is planned to implement the same notification system as lichess.org website. Once it's done it will be an alternative to push notifications, but only when app is in foreground.

**Comment by marmistrz** [comment]
I'm assuming you're using the REST API for this. 

Foreground-only notifications are pretty useless. I think it may be better to keep the relevant piece of code in bg as a service. It's better than no notifications at all.

Alternatively, we could keep an idle connection to the server and await push events from it. This is Google-independent but requires more work. An idle connection doesn't drain battery.
--
Marcin
