### ISSUE TITLE
Possible race condition in playCtrl

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#48]
`this.round` and `this.gameSocket` are initialised at `null` and an asynchronous xhr populates them. But the view depends on those objects.

They should be created before and be `playCtrl` parameters to avoid problems.

It doesn't respect the "model must always be valid" principle.

**Comment by veloce** [comment]
Maybe instead of creating a new instance of StrongSocket for each game we should keep a global one and pass it to each game controller.

**Comment by ornicar** [comment]
But sockets are created for a URL that contains the game ID?

**Comment by veloce** [comment]
We could add the `id` param to `StrongSocket.reset` since we already reset version.
So we'd create 2 instances of StrongSocket one for game, one for lobby, on app init.

What do you think ?

Also playCtrl should be removed completely there's nothing left... all should be done in round

**Comment by ornicar** [comment]
I don't think you can reuse a socket connection for distinct games. A round socket is bound to one game, defined by the round socket URL.

**Comment by ornicar** [comment]
nevermind, there's a confusion between instances of StrongSocket and actual browser WS connection.

**Comment by ornicar** [comment]
Yes reset could have an URL aargument additionally to version, to allow reuse of the StrongSocket instance while changing the underlying connection

**Comment by veloce** [comment]
Yep that's what I meant. I think this is a fair approach to the problem mentioned above. And maybe it'll solve other issues...
