### ISSUE TITLE
LoadLocalJsonFile doesnt  return promise 

### ISSUE THREAD

**Issue by sepiropht** [veloce/lichobile#496]
Maybe this only happen  on my side.
On start, app try to load  local json file , but fail
 ``
 i18n.ts:90Uncaught TypeError: utils_1.loadLocalJsonFile(...).then is not a function
``   
I was able to fix the problem by copy pasting the old version of loadLocalJsonFile which return a promise

**Comment by veloce** [comment]
Thanks for the report: will fix

**Comment by veloce** [comment]
You should do `npm install`, this is due to a dependency change.

**Comment by sepiropht** [comment]
ok thank
