### ISSUE TITLE
Padding above keyboard in iOS

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#497]
![](http://i.imgur.com/LdyK8Zy.jpg)

**Comment by veloce** [comment]
First time I see this: which version of iOS?

**Comment by clarkerubber** [comment]
Version 10.1.1, but I'm pretty sure this isn't the first time I've seen this.

Steps to reproduce:
1. open chat
2. click on text area to bring up keyboard
3. close chat
4. reopen chat and bring up keyboard

Seems to happen every time with google's keyboard installed but not with the native keyboard.

**Comment by spaceships** [comment]
This occurs for me every time with iOS 10.2.1 and system keyboard
