### ISSUE TITLE
Draw showing as defeat in timeline

### ISSUE THREAD

**Issue by JohnMoon94** [veloce/lichobile#508]
If a game ends up being a draw, the mobile timeline will report the game as a defeat for both players. Accessing the full site from a browser, the game is listed correctly as a draw.

To reproduce:
1. Start a game
2. Draw the game
3. Go to the home screen as either player - it will say "Defeat vs. Player X" for both players.

The desired behavior should be for the timeline to show "Draw vs Player X" for both players.

I've tested this with different players on different platforms.

I'm not very experienced with mobile development, but it seems this line may be the culprit?
https://github.com/veloce/lichobile/blob/fb482f2195c454cd6041e0366b569510fc0c8c6e/src/js/ui/timeline.js#L94

**Comment by veloce** [comment]
Already fixed here: https://github.com/veloce/lichobile/commit/336335c23ebed8cebe35c7f9c55e9c05b1052bbc
