### ISSUE TITLE
Analysis board bug when castling from position

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#509]
![screenshot_20161211-223432](https://cloud.githubusercontent.com/assets/12246221/21089096/695af902-bff2-11e6-9d98-d58f6a7afb6e.png)

Bug 1:
If we set a board by ourselves and make it possible to castle for one side, and if we play it in the analysis board and try to castle it, then the bug occurs. The bug is that although we has made a move which is castle, the anaysis board still thinks is our side to move and the board is freezed. Just as the picture shows, white has already moved (castling), but the anaysis board still hints the white move, and the board is freezed and nobody is able to make a move.

This can also happen for the training puzzle where I initially found this bug. I'm using 4.8.0.

The key word for this bug are, from position, anaysis board, castle, then bug.

Bug 2:
It seems there is still something wrong with anaysis board, I encountered two times that the anaysis score keeps calculating no matter how long I wait and no score is shown for a specific position. But I don't know how to reproduce this bug. The following figure shows this bug. Although the best move is shown, the calculation just keeps running.

![screenshot_20161212-043903](https://cloud.githubusercontent.com/assets/12246221/21098353/102a7540-c026-11e6-8fd1-aa5ba163b6eb.png)

**Comment by JuicyRyan** [comment]
I have just uploaded the figure of the second bug I have mentioned. But I still don't know exactly how to reproduce this bug.

**Comment by veloce** [comment]
@JuicyRyan please open another issue for the second bug, it will be easier to track.
