### ISSUE TITLE
Use url scheme to open lichess games in app

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#51]
with this plugin: https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by ornicar** [comment]
v1, really?

**Comment by veloce** [comment]
Not all of the feature actually. But just the ability to load an url should be easy: just install the plugin and listen to an event to route then to 'play/:id'.

Then for a next version we could also add the ability to create such games with url to send to friend easily

**Comment by peutetre** [comment]
I am doing the same on zanimo editor and it's quite cool. Use case:

tweet your current lichess game -> your followers open the link on a twitter mobile client -> if the user has the app, ask to redirect to app -> if redirect, open app and show the game.

example:
* https://twitter.com/Zanimojs/status/440979522276429824
* code https://github.com/peutetre/zanimo-editor/blob/master/project/lib/app.js#L118

in zanimo editor it should work on android and ios.

**Comment by ornicar** [comment]
yep, sounds very good!

**Comment by veloce** [comment]
it's more complicated than 'just install' the plugin, so this is not for v1

**Comment by veloce** [comment]
We need cordova-ios 3.8.0 to do that.

**Comment by peutetre** [comment]
and cordova-ios 3.8.0 is already out! Let add it to tarifa

**Comment by veloce** [comment]
The opening url part is done
