### ISSUE TITLE
vibrate on game start

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#510]
from email:

> I play the game always muted, and thanks for your last change, it's almost perfect, it vibrates when someone moves. But it doesn't when the game starts and I'm with white - so I have to check the display all the time when I'm waiting for a game start. Could you please make it vibrate when the game starts? Thank a lot!

**Comment by veloce** [comment]
Looking at the code, it should work...

**Comment by ornicar** [comment]
tough to try in browser

**Comment by veloce** [comment]
Can't reproduce
