### ISSUE TITLE
Crazyhouse analysis UI bugs

### ISSUE THREAD

**Issue by xivaxy** [veloce/lichobile#511]
Hi!

Great job finally making crazyhouse AI working! However, there are several user interface related bugs in the analysis mode in the latest android version:

- [x]  UI does not allow to drop-interpose a piece against a check that would be a checkmate in standard chess. 

In other words, whenever a standard chess checkmate is on the board, no further moves can be made, even though the position is not a checkmate in crazyhouse (the king can be saved by dropping a piece).  See the first pic, here i am not able to drop a pawn to interpose, as advised by the engine.
<img src="https://cloud.githubusercontent.com/assets/5421101/21152331/9eceacf0-c187-11e6-862e-bc845f232a3e.png" width="50%"/>

- [x]  With local evaluation UI does not show the current evaluated score, depth, and the exact best move, as it does in all the other chess variants. 

I guess in the crazyhouse regime in the current layout there is no space for the little area with this information, but still it would very helpful to see. 

The evaluated score can be seen in the moves list in a very small print, but it is shown only in the main line of the game, and not in the variations, which are the purpose of game analysis (see the second pic).

The best move can be seen as an arrow on the board, but it is ambiguous when the move is pawn promotion to queen vs. knight. See the second pic, the engine properly advises to promote a pawn, but there is no indication that I should promote to a knight.
<img src="https://cloud.githubusercontent.com/assets/5421101/21152620/e4bc7c6e-c188-11e6-94a8-7f94b363cd30.png" width=50%/>

**Comment by veloce** [comment]
Thanks for the report. I will find the place to add evaluation.
To indicate the best promotion is trickier, but I'll see.

**Comment by veloce** [comment]
All fixed. Best move is shown in pgn notation in the eval box, so you have a way to know to which piece promote.

Maybe I'll find a better system later.
