### ISSUE TITLE
New Opponent button no longer appearing

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#517]
The `New Opponent` button has stopped appearing (usually) in the dialog that pops up when a game has finished, and is not there when dialog is reopened via the `...` icon in the bottom left.  I say usually because it occasionally appears where it always used to (I'm not sure under what circumstances it still shows up), but for the most part I am having to click the board icon in the top right to seek a new game where before I just clicked the New Opponent button that used to reliably appear since it was added (at my request, I believe, in https://github.com/veloce/lichobile/issues/223).

I'm wondering if this was somehow caused by the change to Lichess's create game page (adding the default game types), since this stopped working around the time that was added.

**Comment by veloce** [comment]
That's because of the new pool system in lichess. We are aware of this issue, it will be fixed in the next release. Sorry for the inconvenience.
