### ISSUE TITLE
Broken game start behavior

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#518]
Frequently when I cancel the `Waiting for opponent...` dialog, I end up with a new game started anyway.  If I try to re-seek, I get the ugly `You are already playing a game` error message and I have to then click on the board icon in the top right and swipe all the way to the rightmost game board and click on it to join the game that I didn't know had started.  (If I don't try to re-seek, presumably my opponent is waiting for me to make a move in a game I didn't know had started).
Please fix this to be more user-friendly.  At the very least, instead of the ugly error message, a dialog should be shown with a button to join the game instead.

**Comment by veloce** [comment]
The error was due to a websocket connection closed before the canceling message was sent. Should be fixed in the next release.
