### ISSUE TITLE
Correspondence/Unlimited Challenge From Position

### ISSUE THREAD

**Issue by pwwaring** [veloce/lichobile#521]
On the website, a correspondence or unlimited challenge to a specific person using the "From Position" variant can be created by finding the player/friend, selecting challenge to a game, and updating the game parameters, including editing the FEN to set the desired starting position. The challenge is then issued directly to that person.

I'm currently having two, possibly related, issues trying to do the same on the Android app:

1) There appears to be no way to edit the game position directly from the challenge to a game dialog, and going to the board editor appears to provide no way to get back to the previous challenge dialog to issue the challenge to the desired user with the modified FEN. Hitting the Android back button results in an "Oops! Nothing here." message, and hitting the challenge icon to "Continue from here" normally just issues a link to send via text or email instead of directly challenging the desired opponent.

2) At least in the most recent version of the app (v4.8.0) the above steps aren't even providing a link for a new challenge. Instead, all I get is an "Error. Invalid FEN" message. The same is true simply trying to get a new challenge created for a correspondence or unlimited game directly from the "Play with friend" top level menu option. No error if starting from the standard positon, but any path used to start a game using the From Position variant on the app appears to not function correctly for the moment.

Any way to fix this functionality so that Correspondence and Unlimited (haven't tried it with Real Time...) game challenges can be issued using the From Position variant, both in general and when challenging a specific player, similarly to the way it now functions on the website?

**Comment by pwwaring** [comment]
I think this fixed part of it, issuing a From Position challenge that can be manually sent to another player, but still don't see a way to make a challenge to a specific individual work.

For example, go to a specific user's profile and select Challenge to a game, and then Variant = From Position.
![screenshot_20161218-133327](https://cloud.githubusercontent.com/assets/5189782/21295713/164bd6fa-c529-11e6-92f0-6dd421ed2d7b.png)
![screenshot_20161218-133345](https://cloud.githubusercontent.com/assets/5189782/21295715/207f246a-c529-11e6-9372-16421c80d8ac.png)

Now, go to board editor and change to desired starting position. From here, hitting the back button takes you back to the profile screen, not back to the challenge dialog with the board position and FEN in place. From there, going back into the Challenge to a game dialog and then simply hitting challenge to a game results in Error: Invalid FEN.
![screenshot_20161218-135305](https://cloud.githubusercontent.com/assets/5189782/21295732/80a28d50-c529-11e6-8f7b-555f7f160d23.png)
![screenshot_20161218-133535](https://cloud.githubusercontent.com/assets/5189782/21295737/9c4b3c64-c529-11e6-91e6-f7f0a3f9b122.png)
![screenshot_20161218-133646](https://cloud.githubusercontent.com/assets/5189782/21295746/bd40eb3a-c529-11e6-86d6-0bb18593b8ff.png)

But if after going into the board editor and editing the position you then hit the "challenge" icon instead of hitting back to try to go back to the user, you get the Continue from here dialog instead of being able to go back to the original challenge dialog with the user that you're attempting to challenge. Selecting Play with a friend from here brings up the play with a friend challenge dialog, but apparently with no association to the user being challenged. Hitting play with a friend now simply provided the regular challenge URL. 
![screenshot_20161218-133956](https://cloud.githubusercontent.com/assets/5189782/21295753/d73d896c-c529-11e6-82f0-1e7c4109d6ca.png)
![screenshot_20161218-134107](https://cloud.githubusercontent.com/assets/5189782/21295755/dfd07ed6-c529-11e6-9789-d41feb282057.png)
![screenshot_20161218-134243](https://cloud.githubusercontent.com/assets/5189782/21295758/ec80b88a-c529-11e6-8999-9efb958e941f.png)

There appears to be no way to get the challenge specifically to the desired opponent to work from within the app when trying to do it from position rather than standard...

**Comment by veloce** [comment]
indeed
