### ISSUE TITLE
Some little suggestions

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#522]
Hi! 
1) Would be very usefull to have the lichess forum and comunity on the app, so the mobile app can fully replace the site :)
is boring to exit from the lichess app and go to chrome only for read or post something to the community forum.

2) would be nice to have the new patrons icon for patron users

3) would be nice to have Lichess TV on the home page like the site (sometime ago i remember a version of the app with this, why you remove it?).
a good idea is to make an option to turn on/off the lichess tv on homepage, so who want it turn on the option :) for me is very nice to have this, because make the app very alive and not so static :)

4) please, increase the size of the TVs on the friends list...is too little on my tablet, is very hard to click on these TV for see a game of my friend

thanks :)

**Comment by freefal** [comment]
Response to a couple of these:
2. This is coming shortly.
4. I just tried this on my own tablet and had no issues consistently hitting the TV icon.

**Comment by fabio656** [comment]
2) nice :)
4) i know, the tv icons works, but on my hd tablet are too little :)

another 2 nice suggestions may be the number of Spectators would be nice to have this number on the icon of the chat like the numer of online friends, would be very nice :)
and the Elo of the players would be nice, in portrait mode, on the right of the nicknames inside the ( ) using the **Bold** fonts. 
This last suggestion because now the elo rating is under the nickname in tje middle of the pieces captured, and on my hd tablet have a too little size and tiny font.

i know , you prefer to remain with a unique code for phones and tablets, but for me this app need an HD tablet version, for a lot of reasons (size of the fonts, size of a lot of icons, size of the board in landscape mode, analisys page optimizated layouys (now is not some fonts are so little, close to impossible to read), statistics page with very very little fonts, etc etc.....

**Comment by veloce** [comment]
Actually lichobile is a phone app primarily. I added partial support for tablets and it will remain like this unless someone is willing to improve the app for tablets.
