### ISSUE TITLE
The number of unread messages doesn't decrease on Android

### ISSUE THREAD

**Issue by Vinvin20** [veloce/lichobile#523]
The number (and the circle beside the Lichess icon) rise and rise even after I read the messages.
Bug ?

**Comment by veloce** [comment]
I'm not sure to understand: is it about the board icon and its associated number (which is the number of pending moves to play) that you are talking?
If so I've never seen that bug. If could provide a more precise description or steps to reproduce it would help. thanks!

**Comment by Vinvin20** [comment]
It's OK now !
