### ISSUE TITLE
Analysis score keeps calculating if jump directly to the last move in Analysis board

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#530]
Suppose we start an offline game and want to see the analysis score in the middle of the game and we go in to Analysis board. And if we jump to the last move ASAP by keeping pressing the next move button (The last move button is canceled in the latest version), then the score will keep calculating and no score will be shown for this last move (same for the middle moves). An example is shown in Figure 1. But I find if I wait for the score of the first move to come out like Figure 2 then if I jump to the last move or middle moves, the score will show up pretty quick. 

Bref, one has to wait the score of the first move to show up then he can jump to the last or middle moves to see analysis scores. But that is a bug right? We shouldn't need to wait the score of the first move to show up. We should be able to see the score of any move whenever we jump to it.

![figure 1](https://cloud.githubusercontent.com/assets/12246221/21698267/52bda4aa-d353-11e6-890b-7b34c5c8a4da.png)
Figure 1

![figure 2](https://cloud.githubusercontent.com/assets/12246221/21698272/5a7b22c6-d353-11e6-9784-5ea779ddd3f6.png)
Figure 2

**Comment by veloce** [comment]
Fixed now
