### ISSUE TITLE
Sometimes after you write in the chat game doesn't accept input

### ISSUE THREAD

**Issue by vrasidas** [veloce/lichobile#531]
I noticed this a couple of times before but since you could recover by clicking your game icon on the top right and getting back on your current game I did not pay much attention.
Just happened again and I couldn't recover (so I lost a game on time).

Phone is an LG G4, Android 6.

PS. All the buttons work, you just can't move pieces on the board as far as I could tell

**Comment by lakinwecker** [comment]
Yes, this has been happening to me too. I have to go to the home page, then find my game in play again and then I can control the board again.
