### ISSUE TITLE
The custom position will be reset to the initial position if we try to analyze a variant from a custom position of board editor

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#545]
If we edit a custom position in board editor and go to the analysis board, the defaut variant is "standard". But if we want to analyze this custom position in a chess variant by changing the chess variant in analysis board, for example crazyhouse, the board will reset to the initial position and the custom position will be lost. That is the custom position will be reset to the initial position if we try to analyze a variant from a custom position of board editor.

**Comment by veloce** [comment]
yes... it's because currently the board editor doesn't support variants.

But I agree it's confusing, I'll see what I can do about it.
