### ISSUE TITLE
Some suggestions of endgame positions in board editor

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#547]
Some really basic endgame positions are missing in the predefined endgame positions in board editor. 
Examples include but not limited to are one queen, two rooks, one rook, two bishops, one knight one bishop, queen vs rook, rook vs bishop, rook vs knight, lucena position, philidor position etc. 
I know these are very basic end game positions but they are the ones that need to be practiced most. And two bishops, one knight one bishop are actually really hard. 
The current predefined end positions are more like a set of "pawn" positions instead of "endgame" positions since all of current predefined endgame positiosn focus on pawns.

**Comment by veloce** [comment]
I could definitely add some more... but I can't do that alone. I don't know where to find the data. 
If someone can setup another file like this one: https://github.com/veloce/lichobile/blob/master/www/data/endgames.json

and send a PR, I'll merge it for sure!

**Comment by JuicyRyan** [comment]
Ok, I will try to find some new positions with the format like this file.

**Comment by JuicyRyan** [comment]
I just checked the latest json file by pianowow. I think it is wonderful and it includes pretty much all end positions. I think this issue can be closed now once it is added to the release.
