### ISSUE TITLE
analysis display bug on iphone5s

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#548]
https://www.reddit.com/r/chess/comments/5rlyrv/recent_improvements/dd994op/?context=3

![](http://i.imgur.com/Uks0Kvi.jpg)

**Comment by veloce** [comment]
What version of iOS?

**Comment by ornicar** [comment]
I asked.

**Comment by ornicar** [comment]
> Currently 9.3.3, I will try updating to 10.2.1 to see if that resolves the issue.
> edit: It works properly on 10.2.1.

**Comment by veloce** [comment]
ha. Obviously, since I don't test at all on ios 9...

**Comment by ornicar** [comment]
if iOS 9 is not supported, just close.

**Comment by veloce** [comment]
it is... I just take care to not use api/libs not supported. But I didn't test on it recently.
