### ISSUE TITLE
Possibility to use external themes

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#549]
Here there is a lot of fantastic Fritz/chessbase themes;
https://it.lichess.org/forum/general-chess-discussion/my-new-lichess-themes-and-pieces
These themes are amazing!!

Would be wonderful if we can use this themes for the app

Thanks

**Comment by veloce** [comment]
Are they creative commons or free of rights?

**Comment by veloce** [comment]
Thanks for letting me know :)

**Comment by fabio656** [comment]
Yes..i think these are free for lichess.
Please..add them..are wonderful!!!

**Comment by fabio656** [comment]
If younread the topic i linked above...The themes autor...want to make an Apk for use the themes inside Lichess app....is possible ?

**Comment by ornicar** [comment]
We have no info about the licenses. The author didn't answer my message.

**Comment by fabio656** [comment]
I hope that the autor will answer to your messages....because these themes are AMAZING!!

**Comment by veloce** [comment]
it appears as creative commons public domain license
at least here: https://userstyles.org/styles/134586/lichess-pieces-fritz
I didn't check the others

**Comment by veloce** [comment]
I've currently working on a style revamping. I think I'll add custom themes possibility like in lichess website.

**Comment by ornicar** [comment]
the bit of CSS is public. The pieces are copyrighted by Fritz.

**Comment by fabio656** [comment]
Veloce: EXCELLENT!!! :)
Thanks :)

**Comment by veloce** [comment]
Pieces look nice but what I like about those themes are the body backgrounds. Maybe I can use them in the app. Don't know if it's possible to know if they are copyrighted

**Comment by fabio656** [comment]
Yes..background wallpapers is also a good idea!
Are very nice the board textures also!

**Comment by fabio656** [comment]
This theme is beautiful !!
https://drive.google.com/file/d/0B-QYjlrisF60V25BcGRUQmRFRU0/view?usp=drivesdk

So warm...wonderful!
