### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#552]
Hi!
A suggestion, this thing is missing in the app and for me is important;
Would be nice to have the score.. like the score in the bottom of the lichess site when you play.

If a player meet another player more times ...would be nice to have the score on display.

For me would be perfect a simple score inside () on the right of the username

Like this..or similar...as you want :) 

ScaccoLento (4.5)
1755

BOARD

PlayerXXX (2.5)
1680

If 2 players never met before ..a (0.0) should be perfect.

Thanks :)

**Comment by veloce** [comment]
I don't understand what this score is.. sorry. @ornicar ?

**Comment by fabio656** [comment]
The score under the board when you play live in lichess.

I mean the score if 2 players plays more games.

Now i try to find an image

**Comment by fabio656** [comment]
This score 
https://drive.google.com/file/d/0B-QYjlrisF60Uk82SFJ0aVBTX3M/view?usp=drivesdk

Can you see the image?

**Comment by veloce** [comment]
this score is already displayed under the user mini popup: tap on your adversary name, you'll see his name, country, rankings and your score against this player.

**Comment by fabio656** [comment]
Yes i know...but this is only MY score vs a player.

I meant the global score of every player that play against each other.
This is usefull in lichess TV and watch mode.

Very often i see other games....i really like to see other games like a spectator.

For example yesterday i seen Kingscrusher vs an IM ... them played for more than 1 hour....but i could not know the score...and i forced to ask the score in the chat and wait an answer from who was following the games from the site. 

Sorry for my poor english...i hope you understand :)

**Comment by fabio656** [comment]
I not open a new topic for this very minor bug :)
The boards inside the list of our games played...have the Cburnett theme pieces ...but for play i'm using Merida :)
On tablet and on site..the boards have the same theme you choose to play.

Note;
Now i'm playing using a Samsung J7 phone (no more tablet Tab S2 because is broken :( ).....and for the normal phones...the App is AMAZING. :)

**Comment by ornicar** [comment]
I disagree with adding an extra piece of information on the game screen.

- clutter
- most players will have no clue what it means
- clutter!

**Comment by landry314** [comment]
I think this would be very nice to have the score displayed above the game instead of just in the mini popup because it would make it feel more like a tournament and that feels cool. haha.

**Comment by landry314** [comment]
@ornicar, I think most chess players understand "1 - 0" and "0 - 1" or "1.5 - 2.5" as tournament scores...
