### ISSUE TITLE
Analysis board from Training is broken in 4.11.0

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#557]
If you go into Analysis board from Training, we cannot make a move. If we are white, we will have a problem shown in the figure. If we are black, we cannot move at all.
![screenshot_20170219-022409](https://cloud.githubusercontent.com/assets/12246221/23101220/a18e5a1e-f64b-11e6-8164-b89cd40e529b.png)

**Comment by veloce** [comment]
Thanks for report. Going to release 4.11.1 to fix it.
