### ISSUE TITLE
Suggestion for a new Lewis chessmen pieces

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#558]
Can you add a new piece symbol of Lewis chessmen? It will be nice to have it.
![screenshot_20170219-031602](https://cloud.githubusercontent.com/assets/12246221/23101764/7ca5af38-f658-11e6-9bcc-3af4d8582437.png)

**Comment by veloce** [comment]
Not sure it has a free license. For now I won't use any other set than the website has.
