### ISSUE TITLE
Suggestion for setting board, pieces or theme randomly

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#559]
Il will be nice to be able to set board or pieces theme to random so that each time we play or enter the game we see a different board and pieces.

The benefit of this randomness is that we are often used to a particular symbol we see often. If we change the board theme we are often uncomfortable with it. By altering the board theme randomly, we can eventually be used to all the background and piece symbols.

**Comment by veloce** [comment]
No, sorry I won't do that
