### ISSUE TITLE
Importing a concluded OTB game to lichess.org

### ISSUE THREAD

**Issue by arex1337** [veloce/lichobile#562]
After having played a game in the OTB mode in the app, and assuming I'm logged in and online (anon support and offline support could be considered, but not a big priority for me), I would like to easily import/save the game to lichess.org. I can then go to lichess.org to analyze the game later.

Since White and Black does not have usernames in OTB mode, the PGN that is imported into lichess.org should contain (real world) clock time. This will make it easier to identify the game, assuming many games are played and imported in a row.

**Comment by freefal** [comment]
@arex1337 I couldn't easily add the time as our PGN dump currently uses scalachessjs, which only includes a date. If @veloce adds a [Time HH:MM:SS] field to the PGNDump function in scalachessjs (https://github.com/veloce/scalachessjs/blob/master/src/main/scala/scalachessjs/PgnDump.scala)  which Wikipedia says is a common tag (https://en.wikipedia.org/wiki/Portable_Game_Notation), then we'll have the time in the PGN that the app creates.
For the time being, you can manually add it if you wish.

**Comment by veloce** [comment]
I think we'll do better than that. I'll include the date and time (I'll modify scalachessjs). But when importing the PGN to lichess, I was thinking that we could prompt user to write some metadatas that would go along the upload. Not too much and all optional of course. Like:

- black player
- white player
- site

What do you think @arex1337 ?
