### ISSUE TITLE
Board width in analysis mode

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#566]
With a recent update, the width of the board in analysis mode is no longer the full width of the screen. Is that a bug? Is there a good reason why the board isn't full-width?

![2017-02-26 at 12-08-32](https://cloud.githubusercontent.com/assets/6884276/23469621/16e574f6-feca-11e6-87f0-590e092e8c67.jpg)

**Comment by veloce** [comment]
there is a good reason: to have more place to display analysis infos. 

ps: try the button with facing arrows...

**Comment by quinncomendant** [comment]
The button with arrows—bingo! =D

Q
