### ISSUE TITLE
Offline mode for puzzles?

### ISSUE THREAD

**Issue by acegallagher** [veloce/lichobile#570]
It's pretty glaringly painful to have puzzles bork any time there's a connection hickup, especially on mobile connections. I'd also love/kill to be able to play a set of downloaded puzzles offline, places like on an airplane. If I get some time I might try to tackle it but I thought I'd mention it, since several of my friends agree. Best!

**Comment by clarkerubber** [comment]
Going offline would mean: no ratings and no spaced repetition. It would be purely stand-alone, and would not re-sync local progress. Also we're constantly generating new puzzles, so I'm not sure how well that would play.

As long as you're willing to accept those draw-backs, I suppose local puzzles aren't impossible.
