### ISSUE TITLE
Shortcut for turning off sounds

### ISSUE THREAD

**Issue by tsusanka** [veloce/lichobile#575]
I find myself quite often in situations when I turn off sound for a while (public places, buses etc), however I turn it back later on (at home). Doing so in preferences is sometimes rather verbose.

This issue proposes to create an icon to turn on/off the sounds easily. Suggestion:

![selection_015](https://cloud.githubusercontent.com/assets/1835345/24815354/19800c62-1bd5-11e7-86bc-fc4bc831afdc.png)

This is a super minor feature, thanks for the great work you're doing.

**Comment by lightbulbjim** [comment]
One option is to use the hardware volume controls to quickly change the sound level. On Android the volume buttons work as expected; on iOS they currently don't (see https://github.com/veloce/lichobile/issues/520) but the ring/silence switch can be used for quick muting.

**Comment by tsusanka** [comment]
Does that work for you? If I'm in lichess and I press the volume controls I'm adjusting the ring tone sounds, not the "in-game" sounds.

The app has to produce sound to allow me to modify the volume, so you have to press the control exactly in the moment of a chess move. That is also quite uncomfortable, I usually lunch Spotify modify the volume and get back to lichess.
