### ISSUE TITLE
Feature Request: more visible user games dropdown arrow

### ISSUE THREAD

**Issue by igormukhin** [veloce/lichobile#586]
After importing a game and leaving it, you can't go back to it. Please add a screen where imported games are listed.

**Comment by veloce** [comment]
Such a screen already exists: go to your profile -> Games -> select "Imported games" in games dropdown.

Of course if you are anonymous you can't access your imported games since you don't have a profile.

**Comment by igormukhin** [comment]
Thanks for the hint. (Can you make the arrow for that dropdown bigger? It was hard to spot even after you told me that the option is there)

**Comment by veloce** [comment]
I can do that

**Comment by igormukhin** [comment]
Thank you!!!
