### ISSUE TITLE
Feature request: 'Who are streaming' notification.

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#589]
Hi! 
Would be very nice if you add the notification of 'who are streaming in lichess in this moment' in home page of the App (like the site) :)
Would be fantastic if tap on the notification and the app goes on Twitch app on the streamer page.
If it is not possible, no problem, is nice only the simple notification of who are streaming.
So if i want to see the streaming..i open manually Twitch app and i search the streamer.

A nice position should be under the puzzle of the day :)

Thanks, 

Fabio

**Comment by veloce** [comment]
@ornicar are the current streamers information accessible from the app? or does it need an api?

**Comment by ornicar** [comment]
where could it be added? Is there a special API hit on the app home screen?

**Comment by veloce** [comment]
no really special api hit, I request `/player/top/week` and `/training/daily`, that's all

**Comment by ornicar** [comment]
it sounds a bit sad to add a new HTTP request just for that.

Maybe we need /api/homepageStuff to merge it all

**Comment by jas14** [comment]
Closed by https://github.com/veloce/lichobile/commit/b94c347c05bc33e7d4c3122e47c4ab054524d1bd
