### ISSUE TITLE
Create new game "Custom" menu does not allow choosing a side

### ISSUE THREAD

**Issue by markyi370** [veloce/lichobile#592]
On Android 4.4.2 (Lichess app version 4.12.2, the latest) when I click create a game, then Custom, then try to pick which side, the only selectable option is Random side.

I do not have this limitation on the website.

This problem was also present in 4.12.0. I do not recall exactly which one, but there was a version which didn't have the issue.

**Comment by veloce** [comment]
No, it has always been the case that if you choose "Rated", you can only pick "Random" side.
