### ISSUE TITLE
Display rendering / stability issues potentially in Android O

### ISSUE THREAD

**Issue by niklasf** [veloce/lichobile#594]
@ScottBarkman:

> Just installed the dev preview of Android O and looks like there may be some display rendering issues coming. App also crashes when attempting to view the profile menu. Every other app in the developer preview is running locally, so I'm not sure this is related to the Android O preview
>
> (not sure if there is a different repo for android code)

> ![image](https://cloud.githubusercontent.com/assets/402777/26255896/697cee9a-3cbb-11e7-968d-47663ed2fc9b.png)

**Comment by veloce** [comment]
I guess we have to wait for android 0 be officially supported in cordova.

**Comment by freefal** [comment]
I am running Oreo without issue. I think this issue can be closed unless someone is having issues.
