### ISSUE TITLE
Feature request: Lobby

### ISSUE THREAD

**Issue by eduha** [veloce/lichobile#595]
I think it's would be great to join to existing game, same way as on website. 

Please add this feature

**Comment by ornicar** [comment]
We decided against it. Trying to catch a seek among every other one, before it disappears, is already clumsy on desktop. It would only be worse on mobile.

Instead, use "quick game" pools. Or create a seek and lichess will find you an opponent automatically.

**Comment by greg-finley-ck** [comment]
Hey @veloce @ornicar maybe the ship has sailed on this one, but I wanted to share my pain points as a variants player and offer some potential partial solutions.

I prefer to play variants (especially atomic). Variant players aren't nudged into any particular time control (like they are under "quick games"), so it's pretty unlikely that another mobile user will also pick 1+2 or whatever I came up with, shrinking my potential matches. Meanwhile, maybe a 3+0 or 2+2 or 1+1 atomic seeks exists, which I'd be perfectly happy to play, but I can't see it.

I have found myself going to the website on mobile and submitting a seek and watching the lobby for similar games. Once I match, I rush to the app before the game aborts. If I want to seek at a different time control than I did previously, I will first do a seek in the app and then go back and repeat the seek on the site.

Partial fixes, though they are admittedly not perfect:

- Have a toggle for variants within Quick Games.
- Make seek sliders for time controls and rating range toggleable from mobile.

**Comment by landry314** [comment]
Viewing the Lobby as a list and not as a grid would work fine in the mobile app...

You already have Correspondence games viewed this way... why not combine Correspondence and Lobby into one section?

I'd even like to see this on the website. The Lobby already has the Standard "Variant" as an option.

**Comment by landry314** [comment]
I don't think people can see comments on already closed issues, @greg-finley-ck...
