### ISSUE TITLE
homepage timeline before leaderboard

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#596]
In my opinion the timeline is more interesting. It should be above the leaderboards. Like on lichess.org homepage.

**Comment by clarkerubber** [comment]
And dedicate that section on the top left of the homepage to more live events? Like making all of the streams featured.

**Comment by ornicar** [comment]
? this is a mobile app issue

**Comment by clarkerubber** [comment]
Whoops. I thought this was lila. Ignore my comment. I thought we were re-arranging the homepage on lichess.

**Comment by veloce** [comment]
Already done in: https://github.com/veloce/lichobile/commit/1b65401aefbd3144ba63334522c055e81f60bbe3

Planned for next release.
