### ISSUE TITLE
New lag compensation protocol

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#597]
the new way to send lag will be sending the total time the client saw the move, encoded

[10:34] 
the old lag metric will still work until we decide enough people have upgraded the app

[10:36] 
for any given move, the old metric was `{ d: { <move>, l: <lag est> } }`.  The new metric is `{ d: { <move>, s: <client time for move in centiseconds>}`

[10:37] 
it's not live yet but if you want to send both the server will start ignoring the deprecated `l` value when an `s` value is also present (edited)

[10:38] 
this is the reference js impl https://github.com/ornicar/lila/pull/3038/files#diff-7805ce8e49df1b4ecdd04f76163c7edeR72

**Comment by isaacl** [comment]
The app gets to decide how to measure the local time.  From a high level, it should be the time a player got to choose the move, for example:
- start: first screen draw of opponent move
- end: touch up event that leads to move being sent, or more simply local timestamp when move is  being sent.

**Comment by veloce** [comment]
https://github.com/ornicar/lila/pull/3038#event-1110140505

**Comment by veloce** [comment]
@isaacl how is it done on the website? (local time measurement)

**Comment by isaacl** [comment]
This might get refined but initial impl is:
- start, in apiMove() which is the socket receive handler: https://github.com/ornicar/lila/blob/babc478a85709b870b3e665b3a981887cc54b8da/ui/round/src/ctrl.js#L237
- stop, in send move: https://github.com/ornicar/lila/blob/babc478a85709b870b3e665b3a981887cc54b8da/ui/round/src/ctrl.js#L174

**Comment by veloce** [comment]
So it measures the time between opponent move and user move. 

I'd like to see the big picture to understand. Is it an addition to the socket average lag, or is it a replacement? What kind of lag this new protocol is trying to compensate for?

**Comment by isaacl** [comment]
it's a complete replacement to socket lag.  The server uses the client reported time as the official time for the move, as long as it's within the compensation limits.

**Comment by isaacl** [comment]
it's similar to [timeseal](http://www.freechess.org/Help/HelpFiles/timeseal.html) on FICS/ICC.
