### ISSUE TITLE
Studies integration?

### ISSUE THREAD

**Issue by fobos531** [veloce/lichobile#610]
Hello,

was just wondering if the study feature is on the to-do list for lichobile, or are there any technical challenges in regards to implementing this?

**Comment by veloce** [comment]
Maybe it will done later, but it's not on the roadmap yet.

**Comment by fobos531** [comment]
Thanks for the answer, you may close this issue if you feel like it.

**Comment by albertosantini** [comment]
Maybe the first step may be a "read-only" approach.

I mean you can browse the studies and replay the moves: no full integration like edit or creation feature.

**Comment by hammer** [comment]
I love the Study feature of Lichess and primarily use the mobile app. Thanks for keeping this issue open and I hope to see it hit the roadmap some day soon!

**Comment by ornicar** [comment]
I think read-only would be reasonable. Even then, it's a lot of work. Talking dozens of hours here.

**Comment by albertosantini** [comment]
Study feature landed on 6.x version in read-only mode.
Thanks a lot for the effort.

It is in the roadmap the "edit" mode.

@fobos531, @veloce Time to close the issue? :)
