### ISSUE TITLE
Mail notiication

### ISSUE THREAD

**Issue by mrjive** [veloce/lichobile#613]
First of all thank you for the great job!
This is a feature request: I think it would be nice to have notifications, where meaningful, optionally sent by mail. I'm thinking mainly of forum posts, but also opponents' move in correspondence games. Thank you!

**Comment by veloce** [comment]
You already have push notifications for PM and opponent moves in corres games.

Mail notifications are not an option for now.

**Comment by mrjive** [comment]
sorry @veloce I should have opened the issue not for the app but for the main site! Pardonnez moi!
