### ISSUE TITLE
Bug when receiving a call (email bug report)

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#619]
This happens when receiving a call while lichess is open.

Phone: samsung s6 edge. Latest android and latest lichess version

![screenshot_20170707-101359](https://user-images.githubusercontent.com/423393/27952006-172742ea-6307-11e7-9284-0619e778aa1c.png)

**Comment by veloce** [comment]
Cannot reproduce with a Motorola E, android 5.1.

Please reopen if issue persist.

**Comment by ornicar** [comment]
I saw it once. Will try to rep.

**Comment by ornicar** [comment]
likely that's `clientBoundingRect` running without stuff being displayed, resulting in 0 width/height.

**Comment by veloce** [comment]
very likely indeed, and easy to track; will check that
