### ISSUE TITLE
Rematch api update

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#620]
instead of instructing the client to reload XHR when rematch is offered/canceled/declined/accepted, I send `rematchOffer` and `rematchTaken` messages

because it breaks the app (which expects `reload` messages), I used the trick of sending the new messages inside of `reload` messages, as such:

`{t:'reload', d: {t: 'rematchOffer', d: 'white'}}`

so the mobile app still gets the `reload`

and the web (and soon updated mobile app?) executes the reload data instead, i.e. `{t: 'rematchOffer', d: 'white'}`
 
https://github.com/ornicar/lila/blob/master/ui/round/src/socket.js#L17-L18

here's the handlers for the 2 new messages https://github.com/ornicar/lila/blob/master/ui/round/src/socket.js#L66-L75

I will likely proceed to do the same thing for game termination. Send everything through the WS instead of just `reload` then XHR

**Comment by ornicar** [comment]
I added an `endData` event to end games without XHR
lila sends both `endData` (for web) and the old `end` for mobile
