### ISSUE TITLE
Stuck in horde mode

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#621]
https://lichess.org/forum/lichess-feedback/stuck-in-horde-mode

**Comment by veloce** [comment]
Fixed in https://github.com/veloce/lichobile/commit/eb6f4c4ae859d39c91c258650dda7a809e5bc75c

This is a more general bug : otb games are stuck in whatever variant is chosen.

**Comment by maeslor** [comment]
This also happens to me. Then I should wait for the fix on a new mobile release?

**Comment by ornicar** [comment]
A temporary workaround was suggested in the forum: https://lichess.org/forum/lichess-feedback/stuck-in-horde-mode#2
