### ISSUE TITLE
lichess doesn't always send a confirmation email

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#628]
But the mobile app always pretends that it did.

In fact, it's only when you receive `email_confirm: true` https://github.com/ornicar/lila/blob/60cc1dc52da40832ecf81118cbbc274033c6a41c/app/controllers/Auth.scala#L184

if you get the user profile data instead, it means they're logged in, no confirm email was sent.

**Comment by veloce** [comment]
Is there a way to test this (dummy email)?

**Comment by ornicar** [comment]
https://listage.ovh sends emails. You can use your mod privileges to edit your user email, so you can use the email again
