### ISSUE TITLE
Premove on Computer & Mobile Causes Visual Problem

### ISSUE THREAD

**Issue by krcarriere** [veloce/lichobile#631]
![image uploaded from ios 3](https://user-images.githubusercontent.com/11062961/28890937-cccf68f4-7796-11e7-9562-1817eb0743b0.jpg)

iphone 7s 10.3.3

**Comment by veloce** [comment]
I don't see the problem here. Can you precise?

**Comment by krcarriere** [comment]
1. d4 1... h5a5

Set up a game with a friend. You be black. Set a premove on your computer. Open Lichess Mobile. Set a different premove on your phone. Tell your friend to make a move. Your mobile device will display both premoves as made.

**Comment by veloce** [comment]
ha ok. good catch, thanks!

**Comment by veloce** [comment]
I made a single change (more to be on par with the website): https://github.com/veloce/lichobile/commit/1dd5e405f6d44ed674a80e09f609a21ad8f67e96

Since I can't reproduce what seems to be a nasty race condition after this change, I'm closing the issue.
