### ISSUE TITLE
No notification when somebody sends a chat message or sends a "takeback"

### ISSUE THREAD

**Issue by pcantalupo** [veloce/lichobile#632]
Hello,

When I send a chat message or a "takeback" to somebody I'm playing with, my opponent never sees a notification on his iPhone. I inevitably have to follow up with a text message to that person saying that I sent you a chat or a takeback. There should be notifications for this.

Thank you,
Paul

**Comment by pcantalupo** [comment]
> You do have a visual notification when playing. 

I have not tested this when opponent and I were playing.

> Do you mean a notification when app is in background during a correspondence game for instance?
Yes, in background or when app is not running.

**Comment by veloce** [comment]
This is a server issue, I'll open the ticket there. Maybe it's doable, maybe not.

I'll keep you posted here, since I need to do as well a little part on the app for this.

**Comment by veloce** [comment]
So it has been decided to send push notifications for:

- takeback offer
- draw offer

Not for chat: too expensive and potentially invasive. You can send a PM instead.

TODO:

- [ ] add handler on app side for there two events
