### ISSUE TITLE
Integrated game clock is ambiguous when having multiple stages

### ISSUE THREAD

**Issue by baco** [veloce/lichobile#634]
Using the “stage” variant of the chess clock with more than one stage has no indicator whatsoever of which of the stages is transcurring. For example having two stages, one for the first 40 moves and one for the 20 moves after those, when the first stage reaches, say move 22, the stage indicator tells there are 18 moves remaining in the stage but does not tell which stage it is, being either stage possible.

**Comment by jas14** [comment]
@baco #1625 was merged in March and released in v7.10.0. If this resolves your feature request, please close the issue
