### ISSUE TITLE
Over-the-board games stuck in previous mode

### ISSUE THREAD

**Issue by quinncomendant** [veloce/lichobile#642]
Lichess on iOS currently is unable to start a new over-the-board game mode other than the previous mode used. This problem began as a software regression after an update (I think two versions ago). I [reported](https://twitter.com/com/status/878180435368435712) the issue on Twitter in June. My wife has the [same](https://twitter.com/com/status/884046017825431553) problem on her iPhone and iPad.

I had been playing Crazyhouse over-the-board games, and after the update was unable to start a new game in any mode *other* than Crazyhouse. I deleted the app and reinstalled, and then I was unable to create an over-the-board game in any mode other than Classic. The list of other modes is available, but selecting anything other than *classic* has no effect.

I'm surprised there's no issue reported for this bug, nor being fixed, since it began more than two months ago. It seems pretty obvious, I hope it's not just us experiencing it. (I'm not embarrassed to say I check for new Lichess versions almost every day. ;)

**Comment by veloce** [comment]
Yeah, sorry for this issue. It is already fixed in https://github.com/veloce/lichobile/commit/eb6f4c4ae859d39c91c258650dda7a809e5bc75c

Actually the bug is that OTB variant will be whatever is chosen in offline ai game...
Will be fixed in next release.

**Comment by veloce** [comment]
Actually there were two issues here.
