### ISSUE TITLE
Android application wont startup

### ISSUE THREAD

**Issue by eastygh** [veloce/lichobile#646]
After build and run application on android, showing only splash screen and nothing happend after)
In logcat:
 I/chromium: [INFO:CONSOLE(14)] "Uncaught TypeError: Cannot read property 'platformId' of undefined", source: file:///android_asset/www/app.js (14)
D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html) 
and thats all...
what i doing wrong?

**Comment by veloce** [comment]
You should use one of the npm script, like said in the README. For ex. `npm run android-stage`. More generally, look at the scripts to see how to build it
