### ISSUE TITLE
changing language to 1337 freezes app

### ISSUE THREAD

**Issue by cruywulp** [veloce/lichobile#654]
I'm not sure if this is with any other languages, but I've tried EN -> 1337 twice.

S000o 1 ch4n9e th3 l4n9u49e 2 1337, 4nd n0w 1 c4nt 0p3n th3 4pp! 0r st0p t41k1n9 1ik3 th1s!!!
1. change language 2. restart app : the lichess logo loading screen now stays up indefinitely

I had to uninstall and clear my cache to fix.

tested on Android 6.0.1 with armv7 releases 4.14 & 4.15

**Comment by ornicar** [comment]
Woopsies.

The 1337 language has been removed from lichess.org when we moved to crowdin. Better remove it from the app too.
