### ISSUE TITLE
BUG: when watching crazyhouse TV, pawn drops are shown as knight drops in the notation

### ISSUE THREAD

**Issue by mmavova** [veloce/lichobile#657]
I have noticed a really weird thing in the mobile client:
When I watch Lichess TV, it shows pawn drops as knight drops. 

This is on Android, In the corner it shows Lichess version 4.15.0.
Screenshot is attached. See the last move.
![z](https://user-images.githubusercontent.com/20359184/31055139-6f2c19e2-a68d-11e7-8b5b-5f7e8c0f487f.jpg)

**Comment by ornicar** [comment]
From https://github.com/ornicar/lila/blob/0f4325490f1af3ab2c147a2c8b6c5634f70b50c6/ui/round/src/view/replay.ts#L35

`const san = step.san[0] === 'P' ? step.san.slice(1);`
