### ISSUE TITLE
Lichess randomly pops new games when receiving focus (Android)

### ISSUE THREAD

**Issue by thblt** [veloce/lichobile#662]
I haven't found a way to systematically reproduce this, but since the 5.0.0 update, it happens quite often that whenever Lichess gets back focus, a new game appears on front, even when I'm already playing.  This happens when, eg:

 - I start a game against a random opponent (with "create game", 5+0, rated)
 - During the game, I switch to another application, then back to Lichess.
 -  Another game with the same properties pops up on the front.

Same also happens when reopening Lichess after some time: there are often one or two games I never created, all at starting position or first half-move, usually canceled by the opponent, of course.

This is on a Nexus 6P running Oreo 8.0.0, up-to-date.

**Comment by veloce** [comment]
Thanks for this report.

**Comment by thblt** [comment]
Please tell if I can be of any more help.  I also just noticed that when Lichess receives focus while on a game, it behaves as if disconnected, but doesn't try to reconnect --- it doesn't send moves, and the clock keeps running.   Going back to the main screen, then back onto the game and replaying the move solves it.

**Comment by ilikebits** [comment]
This is happening to me as well, and is occurring quite often. When I finish a game, it will also sometimes add me to a new game, as if it's automatically searching for/creating new game requests.

**Comment by veloce** [comment]
@thblt feel free to open a new issue for your other bug. I can't reproduce this one atm. Does it occur often?

**Comment by veloce** [comment]
Actually ignore my last comment. Both bugs were linked, and are fixed in next release.

**Comment by thblt** [comment]
@veloce Thanks!
