### ISSUE TITLE
missing captured piece icons

### ISSUE THREAD

**Issue by poldie** [veloce/lichobile#668]
Just underneath the player's name there was a little list of the pieces that play has taken from the opponent. I have a few games on the go now and there are no captured pieces for either player in some games, but it is working correctly for others (which have fewer captured pieces).

phone hardware: moto g5s plus
phone operating system version: 7.1.1 (stock, unrooted etc)
version of lichess mobile beta: v5.0.1
steps to reproduce:  I've played some chess over the last few days.  i might have briefly lost connectivity from the internet - (there's no `sync` button. it came back by itself after a while) - no idea if this is relevant.
description of the observed behavior: there are no icons under the player's score in some games
description of the expected behavior: all captured pieces should be preset for both players

**Comment by veloce** [comment]
We don't show captured pieces, but piece difference. 

For instance if both players captured a pawn, you won't see anything. If you capture a knight with your bishop, which is taken back in the next move, you'll see a knight under your name, and your opponent a bishop.

**Comment by poldie** [comment]
OK, got it. Thanks.
