### ISSUE TITLE
2 nasty bugs since the latest Android version

### ISSUE THREAD

**Issue by MateMachine** [veloce/lichobile#670]
Hi,

2 new bugs since the latest Android App (v5.0.0)
1) Wrong time
If your opponent gives you extra time, you don't see that.
(The time does not get updated.)
Only if you open the chat, you see he gave you extra time.
Same is of course if you give him time.

2) No reconnect anymore
When opening another app and then switching to Lichess, you stay offline.
Today I lost a game because I acidentally touched the menu button of my Galaxy S5.
It did not matter how often I minimized and opened the app.
That's really frustrating, especially if your opponent doesn't even play anymore,
but wins because you "left the game"

Regards

**Comment by veloce** [comment]
bug n. 2 -> fixed in release 5.0.1

**Comment by MateMachine** [comment]
I downloaded it and made a quick test.
It works!
Good job, veloce.

P.S When was this version released?
