### ISSUE TITLE
Tournament timer gone when spectating

### ISSUE THREAD

**Issue by Apostolique** [veloce/lichobile#671]
Since the latest update, when I spectate someone playing in a tournament, I don't see how much time is left before the end of the tournament anymore.

Currently in version 5.0.1

The timer used to be visible at the top. The top bar was changed in a recent update removing it.

**Comment by veloce** [comment]
Cannot reproduce.
Can you please add steps to reproduce?

**Comment by Apostolique** [comment]
1) Find someone that's currently playing in a tournament.
2) Instead of watching the game from the tournament screen, go to their profile and select "Watch games".
3) At the location where the timer should be, we see the game info instead. For example: "10+0 . Classic . Rated"
