### ISSUE TITLE
No analysis on imported games that are "Playing right now"

### ISSUE THREAD

**Issue by steili** [veloce/lichobile#674]
Hardware: Huawei P9 EVA-L09
OS: Android 7.0
Version: Lichess 5.0.1
Steps to reproduce:
Open an imported game that is listed as "Playing right now" under "Imported Games" in a profile. 

It seems like imported games miss all analysis functions (both the graph, and live SF analysis) if the imported PGN didn't include a final result for the game. Using the website, there's no such limitation. 

Example without analysis (https://lichess.org/yTL9Wrbj):
![image](https://user-images.githubusercontent.com/823397/31558679-38f18e1e-b04e-11e7-8b62-2f35c3d3aa8b.png)

Example with analysis (https://lichess.org/A1IDMd3l): 
![image](https://user-images.githubusercontent.com/823397/31558713-5a64dd26-b04e-11e7-9254-ce5219cdd0f8.png)

I'm sorry if this is already fixed in the beta branch - I don't know how to build/install it.

**Comment by freefal** [comment]
I noticed the same issue when I imported a game that I had played live last Monday, but believe it was fixed on the server side via this commit (https://github.com/ornicar/lila/commit/ed080c9115dca8660dd83c85368b0f60635a61d5).

Can you confirm that it's fixed for you as well?

**Comment by steili** [comment]
Yes, I can confirm that this is fixed for me as well!
