### ISSUE TITLE
Android volume not honored

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#678]
While playing a game, I'm lowering the device volume; it has no effect on game sounds.

lichobile 5.0.1
Android 6.0.1
Motorola g4 play

**Comment by veloce** [comment]
Android has 3 different volumes: ringer, alarm and multimedia content, which is the one used by lichess.

Normally lowering the volume using hardware button will lower the ringer volume. Depending on your android version, you may have a shortcut to access other volumes when you use those buttons, or you may need to go to the settings.
