### ISSUE TITLE
Capture sound sounds twice on new puzzle

### ISSUE THREAD

**Issue by gcp** [veloce/lichobile#683]
In training/puzzle mode, sometimes the capture "klonk" sounds twice upon entering a new problem. It's also possible to get the "tock" "klonk" combination even if the last move is not a capture.

**Comment by veloce** [comment]
Steps to reproduce?

**Comment by gcp** [comment]
I don't know the exact circumstances that trigger this problem, sorry.

**Comment by gcp** [comment]
This seems to be a recent regression though, I cannot remember this happening before.

**Comment by gcp** [comment]
@veloce it seems to happen when you solve the puzzle and click next problem very quickly. I guess it is the sound from the last move that lags a bit and ends up playing together with the sound from the introduction move of the next puzzle.
