### ISSUE TITLE
There is no puzzle solution if the puzzle failed in Anonymous

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#688]
If I play in Anonymous (not logged in) on Android, after I failed a training puzzle (making a bad move), there is no way to see the solution just like Figure 1. I will have to try several times until I find the solution by myself. There is no such problem if logged in just like Figure 2.

![figure 1](https://user-images.githubusercontent.com/12246221/31994887-8b1083b8-b93f-11e7-9f76-d69176bbbc04.png)

![figure 2](https://user-images.githubusercontent.com/12246221/31994892-8ee0525c-b93f-11e7-8e92-e4551e7e3e84.png)

**Comment by veloce** [comment]
app version?

**Comment by JuicyRyan** [comment]
v5.1.1 @veloce

**Comment by veloce** [comment]
Ok. Puzzle section is under a complete refactoring in order to use the latest server API.

This issue will be fixed when it's done.

**Comment by veloce** [comment]
Fixed by #689
