### ISSUE TITLE
Use a white bg w/ cburnett knight as the splash screen

### ISSUE THREAD

**Issue by clarkerubber** [veloce/lichobile#69]
I recall seeing some splash screens with this description added to this repo a while ago, but they don't seem to have made it to build.

**Comment by veloce** [comment]
Since the app has a black bg, why not a black splash screen bg ? If the cburnett knight fit nicely over a black bg of course.

**Comment by ornicar** [comment]
that's appliable on a dark background: [!http://lichess1.org/assets/images/bN-bg.svg](http://lichess1.org/assets/images/bN-bg.svg)

**Comment by veloce** [comment]
Android app logo should have a transparent BG, ios should have a black BG. Can I have the SVG of a knight cburnett for transparent, and one for black @ornicar ?

**Comment by ornicar** [comment]
transparent: http://lichess1.org/assets/piece/cburnett/wN.svg

**Comment by veloce** [comment]
Fixed in beta 1.0.21
