### ISSUE TITLE
Analysis board doesn’t show the participants of the game when in progress

### ISSUE THREAD

**Issue by horazont** [veloce/lichobile#696]
The header in analysis board mode doesn’t show the participants of the game being analysed. Instead, only "Anonymous" is shown.

![screenshot](https://user-images.githubusercontent.com/271710/32136084-93e5116c-bc09-11e7-883f-2a630ea49528.png)

Steps to reproduce: 
1. Open a game in progress.
2. Enter analysis board.

Note that this doesn’t happen with a finished game. I only tested with Correspondence games, if that matters.

EDIT: The header stats of the game seem to be incorrect in general; the game in that screen shot has a time limit of 7 days (not ∞).

**Comment by veloce** [comment]
Seems like a regression. Do you know if it happened with version 5.x?

**Comment by horazont** [comment]
Sorry, I should have specified that this is on version 5.0.1.

I updated to 5.1.2 (didn’t see that this has been released yet), but the issue persists.
