### ISSUE TITLE
can't join a tournament even though i'm perfectly qualified to join it

### ISSUE THREAD

**Issue by tetzki** [veloce/lichobile#703]
![1](https://user-images.githubusercontent.com/24408920/32260154-17eeff96-bf01-11e7-9cd6-178c6d754a87.png)
![2](https://user-images.githubusercontent.com/24408920/32260155-1825c35a-bf01-11e7-9399-d978cb5045c4.PNG)

i have over 10 (even over 100) _rated games_, so i'm not sure why i still can't join the tournament

**Comment by veloce** [comment]
you need > 10 *classical* games (at least 10+0)

**Comment by tetzki** [comment]
atleast make the requirements more specific
