### ISSUE TITLE
Time control not visible when watching tournament games on mobile

### ISSUE THREAD

**Issue by CamilleVictor** [veloce/lichobile#708]
The time control for normal games is usually at the top now, but during tournament game it is replaced by the tournament info without the time control.

**Comment by ornicar** [comment]
That's an issue for veloce/lichobile

**Comment by veloce** [comment]
<img width="384" alt="screen shot 2018-03-22 at 09 13 06" src="https://user-images.githubusercontent.com/423393/37758662-4a3fb0d4-2db1-11e8-91ff-2f50666fa7b9.png">

In a tournament game you see time control of the game at the top, and tournament time at the bottom.
