### ISSUE TITLE
Clicking "Profile Name" in the hamburger menu should open user profile page

### ISSUE THREAD

**Issue by TheCodeArtist** [veloce/lichobile#717]
Currently tapping on the profile username within the hamburger menu does nothing.
![2017-11-27 22 16 02](https://user-images.githubusercontent.com/1897177/33278638-3050b004-d3c2-11e7-92dd-a91a6d675a6c.jpeg)

Could we update it such that tapping on the profile username opens-up the user's profile page?
![2017-11-27 22 17 28](https://user-images.githubusercontent.com/1897177/33278709-67a5cabc-d3c2-11e7-8a3a-0096faf36870.jpeg)

----
Alternately, upon tapping the username,
we could display the current "User Menu" as a expand/drop-down?

I found the "main-menu" <--> "user-menu" confusing.
Its a toggle, with a menu, but not apparent for me for a long time.
It doesn't help discovery as its usage is not obvious and the menu options are split into 2 menus.

I couldn't figure out for a long time on how to open my profile when in "User-Menu",
and so used to rely on "Advanced search" for my own username to land on my profile page. 🤦‍♂️

**Comment by TheCodeArtist** [comment]
i see that the menu text and actions are being referenced at:

`src/ui/menu/menuView.tsx:259`
`www/app.js:42237`

I haven't figured out yet how to update the js/tsx to update the menu though.  
Would this be a **`good first issue`**?

**Comment by veloce** [comment]
Sure go ahead, it's a good first issue.

what do you mean exactly by

> Alternately, upon tapping the username,
> we could display the current "User Menu" as a expand/drop-down?

?

**Comment by TheCodeArtist** [comment]
**To make the entire menu more obvious ,  
one could make each of the top-level menu entry an expandable tree list.**

As i'm new to typescript, i do not know for sure whether the following is possible.
(but i assume it is possible as most websites/apps have such menus)

### Default un-expanded menu for new unregistered user:
```
.:||  Ping stats  (?)
  [ Register/Sign-In ]
► Play Online
► Community
► Play Offline
► Tools
Settings
About
```


### Default un-expanded menu after Register/Sign-In:
```
.:||  Ping stats  (?)
► Username
► Play Online
► Community
► Play Offline
► Tools
Settings
About
```

### Menu with ALL the top-level entries expanded

```
.:l|  Ping stats  (?)
▼ Username
   Profile
   Inbox
   Online friends (0)
   0 following
   0 followers
   Preferences
   Sign Out
▼ Play Online
   0 games in play
   (+) Create a game
   Play with a friend
   Play with the machine
   Correspondence
   Tournament
   Training
▼ Community
   Watch Lichess TV
   Video Library
   Players
   Leaderboard
▼ Play Offline
   Computer
   Over the board
   Clock
▼ Tools
   Analysis board
   Board editor
   Import game
   Advanced search
Settings
About
```

### Details:
* Each sub-menu can be expanded/collapsed by clicking the corresponding top-level menu-item.
* Menu-entries currently in the User-Menu appear under the "User Name"
* Other entires currently in the main-menu conitnue to have the same categorisation.
* New menu entry "**About**" that launches a fullscreen About page with credits to Lichess.org/Github page
* New menu entry "**Video Library**" launches the page https://lichess.org/video

**Comment by TheCodeArtist** [comment]
Another extreme option could be to aim for parity with the menus on the website.
![webpage-menus](https://user-images.githubusercontent.com/1897177/33331535-e0ceaa9c-d487-11e7-9769-d17b32156303.JPG)

We could have the following top-level menus in the hamburger menu of the app.
```
► Username
► Play
► Learn
► Watch
► Community
► Tools
Settings
```

*The website simply combines the **Username** and **Settings** menus as a single Username menu.*

Either ways, i will get started playing around with tsx and try to learn how to update the menu structure.

**Comment by TheCodeArtist** [comment]
Linking the username with their profile page was easier than i thought.  
Submitted PR #718.

_(i still have no idea how to create the expandable/collapsible hierarchial menus in tsx though)_

**Comment by veloce** [comment]
Thanks for the PR :)

For the rest, let's not change the whole menu like that. Users don't like change in general, I'm not sure a collapsible menu is a good idea.

About you other ideas: we can't have the same menu as the website. Menu is app menu, website has a lot more features. We can't put video library as a menu entry too, as we can't put any website page link as a menu entry. The website is not even responsible, and if people want to go to the website they should go to the website by themselves.

When I was talking about ideas to make the menu better, I was meaning small design/style changes that could make this user menu more obvious, leaving the rest of the menu as is. I know the menu could be better, but it's not something you change easily.

**Comment by TheCodeArtist** [comment]
> Users don't like change in general

Very True.


> I know the menu could be better, but it's not something you change easily.

Yeah, i don't even know where to start in `menuView.tsx`.


> small design/style changes that could make this user menu more obvious

**The most obvious one would be to make the user-menu <--> main-menu toggle appear like a toggle.**

How about something like this instead of the ↔ symbol?
`User (●  ) Main` shows the **User Menu** options below.
`User (  ●) Main` displays ther **Main menu** options below.

I am able to create this using standard ascii and unicode characters.
![menu-toggle](https://user-images.githubusercontent.com/1897177/33346321-4f08b9e4-d4b5-11e7-9e2f-65b0bec50759.gif)

Does this look acceptable or can the looks of the "toggle-switch" be further improved?

**Comment by veloce** [comment]
The problem with the toggle is that displaying both "Main menu" and "user menu" takes a long space. It works here in english, but we must take into account other languages, where it could not fit in on line...

But I agree we should find a way to show there is a user menu, bc now it's not obvious.
