### ISSUE TITLE
Support for shield tournaments

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#720]
https://lichess.org/tournament/IKMZgOrd

New font icon char: `5`

**Comment by veloce** [comment]
That's just a new icon to add?

**Comment by ornicar** [comment]
Hmm yes. Also the tournament json has new fields `spotlight.headline` and `spotlight.text`. The `spotlight.text` would be nice to display on the tournament screen. It's the one that says 
```

**Comment by veloce** [comment]
I don't see the `headline` and `text` fields in `spotlight`, only `iconFont`.

**Comment by ornicar** [comment]
Might not be deployed yet; will be in 9h. Sending to stage in the mean time.
