### ISSUE TITLE
Improve UX of User-menu/Main-menu toggle within the hamburger menu

### ISSUE THREAD

**Issue by TheCodeArtist** [veloce/lichobile#721]
Improve UX of user-menu/main-menu as an obvious "toggle".

A rough mock-up:
*(there may be potential issues with using this as-is due to length of the text in other languages)*
![menu-toggle](https://user-images.githubusercontent.com/1897177/33346321-4f08b9e4-d4b5-11e7-9e2f-65b0bec50759.gif)

### Points to consider:
- [ ] Currently rest of the menu items toggle based on the User/Main selection (tap to toggle).
- [ ] Translated menu text will vary in length.
- [ ] [Tree of menus/sub-menus](https://github.com/veloce/lichobile/issues/717#issuecomment-347576711) looks appealing at first.  
  However users may be turned-off by major changes.

**Comment by TheCodeArtist** [comment]
FYI, i noticed that currently there doesn't appear to be translation support for user-menu/main-menu strings.
https://github.com/veloce/lichobile/blob/master/src/ui/menu/menuView.tsx#L259

**Comment by veloce** [comment]
No, translation is a separated project. Server migrated to a translation server, and the app should migrate to use this new system too.
