### ISSUE TITLE
Settings and Search dialogs are broken in the iOS version

### ISSUE THREAD

**Issue by jukey** [veloce/lichobile#737]
All dialogs available when selecting the **settings** menu entry are empty. The same happens when opening the extended search dialog.

## Steps to reproduce
1. Start the app
2. Select **Settings** from the main menu
3. Select the **Language** sub menu item.

## Expected behavior
A dialog that allows choosing the language appears.

## Current behavior
Screen stays empty. Only the main app controls like the back button are shown.

## Additional details
This issue seems to be the same for all of the other sub entries in the settings section as well as for the **Extended Search**.

##Screenshot
![grafik](https://user-images.githubusercontent.com/295928/33872174-08e1de4e-df16-11e7-82fc-7c7698f695ed.png)

**Comment by freefal** [comment]
Having trouble reproducing. What language did you last select?

**Comment by jukey** [comment]
I am using *German* as language setting. I also tried to reinstall the app without any change. Still no settings or extended search.

**Comment by veloce** [comment]
@jukey please send your iOS version too.

**Comment by jukey** [comment]
Indeed: iOS 10.3.3 running on an iPhone 6.

**Comment by knutole** [comment]
Having the same issue with English language, and basically no change of settings (since they never were available).
