### ISSUE TITLE
I've logged out of the app, but am still getting push notifications for messages

### ISSUE THREAD

**Issue by lakinwecker** [veloce/lichobile#738]
I logged out of the app to test something a few weeks back and I haven't bothered logging in again (I don't use my phone much). But I'm still getting push notifications whenever I get a message on lichess.

**Comment by veloce** [comment]
Since all push notification are tied to an user account, I suppose it is indeed unwanted behavior. At least it is not a security issue. Thanks for reporting.

**Comment by lakinwecker** [comment]
If someone uses a shared device, then it does become a privacy issue. 

The 45+45 league uses secret links sent to the lichess user account to verify users on the site. Leaking these is a security issue.

**Comment by lakinwecker** [comment]
It's pretty unlikely to happen though.

**Comment by veloce** [comment]
I see. It should be easy to fix.
