### ISSUE TITLE
Make single taps more tolerant on Android 4.1 & 4.2

### ISSUE THREAD

**Issue by Evropi** [veloce/lichobile#74]
To tap on a piece instead of dragging it to move it is not so easy or intuitive. At the moment, you must hold down or press the destination square very quickly after tapping on your desired piece.

I recommend defaulting to standard lichess behaviour, that is, that one tap means the piece is selected and that a second tap on the same piece deselects it.

As an interim measure (since you want to make a release), you can make single taps leave the piece active for longer, though I strongly recommend (eventually) moving to standard Chessground behaviour.

**Comment by veloce** [comment]
You should have the standard chessground behavior by default.

I suspect you have an older version of Android, like 4.1. Do you confirm?

**Comment by Evropi** [comment]
Yeah, this happens on 4.1. On 4.2 the single tap doesn't work at all!

**Comment by veloce** [comment]
https://developer.android.com/about/dashboards/index.html

Both versions share 20% of android usage. The app is still usable so we won't delay the release but we should definitely fix it. I'll post the issue in chessground.

**Comment by veloce** [comment]
Closing this as I think we won't fix for now. And also this is a chessground issue and should be posted in chessground project.
