### ISSUE TITLE
Add cloud analysis?

### ISSUE THREAD

**Issue by TheSIlentLink** [veloce/lichobile#741]
Is there plans to add cloud analysis? This would be a huge benefit on mobile devices saving battery life as the CPU won’t have to work as hard.

**Comment by TheCodeArtist** [comment]
There is already an option to request analysis for completed online games.
(in the *Analysis Board* screen on mobile devices)

**Comment by TheSIlentLink** [comment]
Yes but not stockfish cloud analysis. Referring to this: https://lichess.org/blog/WN-gLzAAAKlI89Xn/thousands-of-stockfish-analysers

**Comment by TheCodeArtist** [comment]
You mean having a "**Enable Cloud Analysis**" option in this screen, right?
![image](https://user-images.githubusercontent.com/1897177/34154714-826f996a-e4dc-11e7-84eb-58341675c9dc.png)

**Comment by TheSIlentLink** [comment]
Not quite, as you can see here https://lichess.org/HgofdrB0/black#1 move one has the cloud option on desktop and is pulling the stockfish analysis from the server.  
![screen shot 2017-12-19 at 11 28 44](https://user-images.githubusercontent.com/23142496/34155081-e3798aae-e4af-11e7-8a03-35ff122c3450.png) This is the same move on my phone. As you can see from the screenshot it is not pulling the analysis from the server but it calculating it locally using up more battery in the process.
![img_6589](https://user-images.githubusercontent.com/23142496/34155170-30619a00-e4b0-11e7-9980-ee29363a9c21.PNG)
