### ISSUE TITLE
Opening explorer does not show best move on Android

### ISSUE THREAD

**Issue by JuicyRyan** [veloce/lichobile#747]
Title says it. I have enabled local computer evaluation and show computer best move option. But as Figure 1, it does not show computer best move if in opening explorer. However, if not in opening explorer view but in move history view like Figure 2, it will show the best move. I also found if there is a move history of the game, the opening explorer will show the next move in history and that is inconsistent with the website which will always show the computer best move (no matter with or without a move history). A minor problem is that the arrow color is still different in this situation which can be seen if we compare Figure 2 and Figure 3.

Figure 1 No best move in opening explorer view (if no move history)
![figure 1 no best move in opening explorer view](https://user-images.githubusercontent.com/12246221/34539761-253be258-f08f-11e7-96e4-90e7366193cd.png)

Figure 2 It shows best move if in move history view (with or without a move history)
![figure 2 it show best move if in move history view](https://user-images.githubusercontent.com/12246221/34539762-25555238-f08f-11e7-8a72-7aedb3ad18ea.png)

Figure 3 It shows next move in move history in opening explorer view (if there is a move history)
![figure 3 it has next move in history in opening explorer view](https://user-images.githubusercontent.com/12246221/34539763-256f436e-f08f-11e7-9e14-48ed790faf0a.png)

By the way, the arrow color in Figure 2 and Figure 3 is different...

**Comment by veloce** [comment]
The purple arrow color represents the next move played in that game. I found it useful since you don't see the move list when the opening tab is open.

**Comment by veloce** [comment]
Fixed in bab439e8d9af2e0741a27ad851849f6d0a663e07
