### ISSUE TITLE
Lost pieces list is not kept when going back / forward in plays

### ISSUE THREAD

**Issue by 444nonymous** [veloce/lichobile#749]
If you want to review the game and go back to check old plays, the lost pieces list (icons below usernames) is not kept when pressing forward to go back to the current play. Only the last lost piece is shown instead the full list of current lost pieces. 

Also the list is not updated according to the play shown when going back / forward. So it never shows the lost pieces right.

Suggestion: Fix the lost pieces list and you could also show the square of a lost piece in other color that green, used for normal moves. That new color could match the last lost piece in the list (all white except the last one).

Thanks.

**Comment by veloce** [comment]
Sorry, it is maybe not very clear, but what is shown here is not the lost pieces list. 
Is is the pieces difference compared to the opponent. If you take one piece you'll see it below your name because you have one piece more, for instance.
