### ISSUE TITLE
App signs you out when clicking "Playing right now"

### ISSUE THREAD

**Issue by jarannilsen** [veloce/lichobile#75]
After successfully signing in, selecting "playing right now" from the menu results in a toast saying "You have been signed out". This means its not possible to get to the games and play. 

On Nexus 5, Android 5.0.1

**Comment by veloce** [comment]
Fixed in beta 1.0.20

**Comment by jarannilsen** [comment]
That was quick! Well done :)

**Comment by ornicar** [comment]
It required 3 overpaid engineers and several hours of work.
