### ISSUE TITLE
Incorrect formatting at in game option

### ISSUE THREAD

**Issue by gurditsbedi** [veloce/lichobile#752]
The `Threefold repetition` text looks likes its ill formatted.
I also think that `Threefold repetition ✓ Claim a draw` is on one line but due to limited width the text went to the next line.

![li_chess_app](https://user-images.githubusercontent.com/17056684/34651742-1fb96fbc-f3fa-11e7-9e41-c65a9d34a5df.jpg)

**Comment by freefal** [comment]
Thanks for letting us know. Pull request is here: https://github.com/veloce/lichobile/pull/753
