### ISSUE TITLE
Add support for coordinate training in mobile app

### ISSUE THREAD

**Issue by bak1an** [veloce/lichobile#758]
If the feature is acceptable I could work on a PR to implement it.

**Comment by veloce** [comment]
Sure! You can go ahead and implement it. I wasn't planning to do it by lack of time, but this is definitely acceptable.

**Comment by aldokkani** [comment]
@veloce I am working on this and almost done, but I am having issue with "mithril" lib to have the component redraw/rerender when the user clicks. Can I get your help?

**Comment by freefal** [comment]
Hossam,

@veloce is better qualified to help here, but having run into mysterious
mithril issues in the past, make sure that you are adding unique "key"
attributes to any clickable HTML element.

**Comment by aldokkani** [comment]
@freefal I am not sure if this is the problem, since I am using the board and the board should already have a key, shouldn't it?

**Comment by veloce** [comment]
Maybe you miss a `redraw()` call? I know this is something now obvious in mithril (or it's also the way I use mithril), but except for the button handlers (`helper/ontap`) each time an action is performed and you want to redraw, you need an explicit call to `redraw()`.
