### ISSUE TITLE
Proper home page

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#76]
Because start board is not obvious

**Comment by veloce** [comment]
We still have to decide what we do for the home.

**Comment by clarkerubber** [comment]
Create a game/Play against the machine/Play with a friend?

On Fri, Jan 30, 2015 at 6:10 AM, Vincent Velociter <notifications@github.com

**Comment by Evropi** [comment]
I suggest simply showing the sidebar at the start, users want to make sure they're signed in in some way.

I suspect the majority of lichobile users will have registered for the site, so it's important for them to know they're signed in so their games can be tracked on other devices.

**Comment by veloce** [comment]
Problem is: we must make an xhr request to sign user in (to get session data). If network is laggy, or disconnected, the user will stay as disconnected as long as the request is pending.

I'm more in favor of giving a feedback that we're trying to connect, on an empty board, and as soon as we're connected we notify and redirect to the most urgent current game if any.

For those who are anonymous we'll display a message to invite them to play by clicking the 'board logo'.
