### ISSUE TITLE
Change clock position

### ISSUE THREAD

**Issue by borapop** [veloce/lichobile#760]
When I play Lichess on the iPhone I don't see my clocks because my finger always hovering on the board (I play blitz and always ready to make move fast). As soon as I'm very focused and don't see nothing that attract me (or distract) I notice my clocks only then time is getting away (like 40 seconds). So is there a way or any idea to place user's clocks in another place in layout?

**Comment by veloce** [comment]
I can make an option to choose side of clocks: either left or right.

**Comment by borapop** [comment]
Thank you very much! Appreciate that.
