### ISSUE TITLE
AI level 2 gave up in winning position

### ISSUE THREAD

**Issue by BastiTee** [veloce/lichobile#762]
- System: Android 7.1.1 on Nexus 6
- App Lichess with latest updates
- [Played a game as white](https://lichess.org/eaMTfIIarP5b) against AI (random color / level 2 / time 10+0 / standard) 
- After move 146 white promoted to queen thus was even more in a winning position
- On move 151 (with me having seconds on the clock left) AI just resigned the game

**Comment by ornicar** [comment]
a silly result for a silly game

**Comment by BastiTee** [comment]
Wait... what? 
I tried to describe a corner case in the chess engine (or configuration) you're using, it's clearly something even a chess amateur like me wouldn't do in a game and your answer is a rude episode of "How not to encourage people to provide an open-source project with bug/feature reports"?
How about a plain old "Works for me" next time?
Jeez...
