### ISSUE TITLE
Puzzle/training rating graph lags 

### ISSUE THREAD

**Issue by gcp** [veloce/lichobile#766]
Probably as of the last release, the rating graph and displayed rating in the training lags. The rating goes (for example) up if I get a puzzle wrong, and can go down when I get them right.

**Comment by rseegmiller** [comment]
More details about this at: https://lichess.org/forum/lichess-feedback/tactics-stats-bug-in-android-app-v54#2

**Comment by veloce** [comment]
Fixed in https://github.com/veloce/lichobile/commit/005837578e530da3b95a185dbac4a5ae514b50da
