### ISSUE TITLE
Relicense under GPL 3

### ISSUE THREAD

**Issue by niklasf** [veloce/lichobile#771]
Hi fellow lichobile contributors,

like Lichess itself lichobile comes with the promise of remaining free software forever. In October 2016 we made this promise explicit by migrating away from the MIT license (which does not prevent anyone from distributing modified *closed* source versions).

Now we want to do the same with lichobile by migrating to the GNU General Public License v3.

**As a contributor you've got a say in this. Please respond on this issue if you agree with the relicensing. Yay? Nay? Questions?**

Information about the current license, MIT:
https://choosealicense.com/licenses/mit/

Information about the next lichobile license, GNU GPLv3:
https://choosealicense.com/licenses/gpl-3.0/

* [x] @veloce
* [x] @ornicar
* [x] @freefal
* [x] @frankcalise
* [x] @Happy0
* [ ] @Manuelp2 ("see symmetric coordinates" setting: [commits](https://github.com/veloce/lichobile/commits?author=Manuelp2))
* [x] @niklasf
* [x] @srenault
* [x] @peutetre
* [x] @vdebergue (via thumbs up)
* [x] @isaacl
* [x] @bapmrl
* [x] @therealmitchconnors
* [ ] @Duaner (small bugfixes and style tweaks: [commits](https://github.com/veloce/lichobile/commits?author=Duaner))
* [x] @ybr
* [x] @thuo
* [x] @sepiropht
* [x] @flugsio
* [x] @TheLastProject
* [x] @mwhenson
* [x] @BrandonE
* [x] @pianowow
* [x] @christophgysin
* [ ] Jacques (can not be reached, but code has been replaced anyway: 6324831256c137019980d292b995dede0db934bb, 19d0fdeab2003b03008be8bd1892b96a74dbc552, e3d1dcc9813d775fbea0298b8e4d5680f1084284, a5b20048e343409d5c206a86fa7cb0615448ffe4, 05d47f763d9c65701e1130861de25644b5ef7bd2, d3e0f656650c3d5f20c5a68242ab05cd75d8915d)
* [ ] @TheCodeArtist (adding a link: e118e8988f4c6afcd344e8edbb3ac305eb11fe52)
* [ ] @dsjoerg (small documentation improvement: e983f4a03b953330ff7e767859908f07fa0e58ce)
* [ ] Arjun Temurnikar (fixed typos: bfdf6d8aa6b9861a786d59a6545ee0a00ed6cae9 9b297ff40dfe7ee3eeab80ed9d439d0b830c0da3)
* [ ] @palerdot (fixed typo: b2bd1d2b39cacaccdf8abc730340a75f6423ef65)

**Comment by christophgysin** [comment]
Yay!

**Comment by isaacl** [comment]
I support this licensing change. Thanks for spearheading, Niklas.

**Comment by freefal** [comment]
I vote "Yea"

**Comment by sepiropht** [comment]
Ok for me

**Comment by frankcalise** [comment]
Fine with me!

**Comment by TheLastProject** [comment]
I cannot remember contributing to this project, but I fully support this change and give explicit permission to relicense my contributions as such.

**Comment by flugsio** [comment]
Yay!

**Comment by pianowow** [comment]
Vote yes.

**Comment by ornicar** [comment]
Yay!

**Comment by peutetre** [comment]
yes!

**Comment by srenault** [comment]
Yay

Le 22 févr. 2018 09:41, "Paul Panserrieu" <notifications@github.com> a
écrit :

**Comment by thuo** [comment]
Yay!

**Comment by Happy0** [comment]
I haven't contributed anything in a while, so you should weight my vote accordingly :p

That said, I vote yes :).

'would stallman be happy?' is a good principal to stick to when writing software :D

**Comment by BrandonE** [comment]
Yay




---- On Wed, 21 Feb 2018 10:30:31 -0600 Niklas Fiekas &lt;notifications@github.com&gt; wrote ----




Hi fellow lichobile contributors,

like Lichess itself lichobile comes with the promise of remaining free software forever. In October 2016 we made this promise explicit by migrating away from the MIT license (which does not prevent anyone from distributing modified closed source versions).

Now we want to do the same with lichobile by migrating to the GNU General Public License v3.

As a contributor you've got a say in this. Please respond on this issue if you agree with the relicensing? Yay? Nay? Questions?

Information about the current license, MIT:

 https://choosealicense.com/licenses/mit/


Information about the next lichobile license, GNU GPLv3:

 https://choosealicense.com/licenses/gpl-3.0/


@veloce

@ornicar

@freefal

@frankcalise

@Happy0

@Manuelp2

@niklasf

@srenault

@peutetre

@vdebergue

@isaacl

@Duaner

@bapmrl

@thuo

@sepiropht

@ybr

@flugsio

@TheLastProject (also e118e89)

@mwhenson

@palerdot

@BrandonE

@pianowow

@christophgysin

@dsjoerg

@therealmitchconnors

Arjun Temurnikar (bfdf6d8 9b297ff)

Jacques (6324831, 19d0fde, e3d1dcc, a5b2004, 05d47f7, d3e0f65)

**Comment by mwhenson** [comment]
Sure

**Comment by therealmitchconnors** [comment]
Yes!

**Comment by ybr** [comment]
Yay!

**Comment by bapmrl** [comment]
Yes!

**Comment by niklasf** [comment]
Thanks everyone :)
