### ISSUE TITLE
Error in Position change

### ISSUE THREAD

**Issue by niklasf** [veloce/lichobile#778]
@tito-lee (forwarded from ornicar/lila#4082):
>#### Expected behavior
>After my opponents move, the position should look normal for me to make my move.
>
>#### Actual behavior
>After my opponent made his move, the position changed irregularly and look scattered with both Kings wrongly placed.
>
>#### How to reproduce
>Click the backward button to take the position moves back and then the forward button >back to its normal position.
>
>* App: Lichess 5.4.1
>* Operating system: Android 5.1
>
>#### Recording Of The Bug
>![20180301_152100.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519937827/d6bd372ts32o8839h6mq.gif)
>
>    
>
><br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@anonymee/error-in-position-change">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by veloce** [comment]
I have trouble to understand what's going on here from the recording. Can you send the game url?
