### ISSUE TITLE
unable to join an invitation

### ISSUE THREAD

**Issue by niklasf** [veloce/lichobile#785]
@tito-lee (moved from https://github.com/ornicar/lila/issues/4149):
>#### Expected behavior
>When an invitation link is sent and opened, clicking "join game" should take me to the >playing arena
>
>#### Actual behavior
>After opening the invitation link, click on Join game did nothing,it remained the same way. >And it is not a Newtork signal issue, if it was it will show the reconnecting sign.
>
>#### How to reproduce
>To play that same player, simply go to the players profile and challenge.
>
>* Lichess 5.4.1
>* Operating system: Android 5.1
>
>#### Recording Of The Bug
>![20180319_200214.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521503773/xcwyrcipllofciycnzjg.gif)

**Comment by veloce** [comment]
Could not reproduce.
