### ISSUE TITLE
Phone crashes right after making a move

### ISSUE THREAD

**Issue by francois90** [veloce/lichobile#786]
Phone hardware : Motorola G4 Plus
Phone operating system version : LineageOS 14.1-20180219-NIGHTLY-athene (Android 7.1.2)
Version of lichess mobile beta : 5.4.1
Steps to reproduce : Durring a game or while solving a puzzle. It happens seemingly randomly but always right after a move is made, most often by the user but also sometimes by the opponant. I didn't find a systematic way to reproduce the bug, it simply happens from time to time. Approximatively one out of a hundred move will cause this behavior.
Description of the observed behavior : Phone chrashes and reboots itself.
Description of the expected behavior : Phone doesn't crash.

**Comment by veloce** [comment]
I can't really debug this if there is no way to reproduce with some certainty. And I've never seen that bug myself. If you have more elements to help fix this issue, please send them ; if not I'll have to close it.
