### ISSUE TITLE
New opponent button not honoring seek parameters

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#789]
When I "Create a game", I have it set to a certain rating range.  These seek parameters should be reapplied when I click "New opponent" after finishing a game, but this week this stopped happening (on mobile only; web site still honors original parameters).  The result is I am now unexpectedly getting opponents outside (sometimes far outside) my desired rating range.  Please restore the previous behavior.

I am on v5.4.2, suggesting that https://github.com/veloce/lichobile/pull/781/commits/983a5f7b51922fa0a0fe984acf6f158fe2b6e4a9 (merged and tagged with that version) is what broke this behavior.

**Comment by veloce** [comment]
Can you also specify the time control you are using please?

**Comment by GrahamJohnson** [comment]
@veloce Sorry I didn't see this question and haven't been playing non-tournament games on mobile since I posted this issue.  I tried again today with my usual options (3 0 rated, 1900-2200).  The `New opponent` button gave me several 18xx opponents in addition to 19xx opponents.

**Comment by leonty** [comment]
I have the same issue but even worse as it seems to me: the rating range is never respected when seeking a game. The new game dialog shows correct values (minimum is set to a higher value than my own rating), but opponents are selected even with -200 points difference. This happens for 1+0 standard.
Please take a look into this issue, it provokes really trashy games with much weaker opponents.

Android 8.1.0, Nexus 5X, application version 6.1.2

**Comment by veloce** [comment]
Has been fixed now.
