### ISSUE TITLE
Objects in side menu not lining up properly

### ISSUE THREAD

**Issue by netherrod05** [veloce/lichobile#81]
Phone Hardware: Sony Experia
Phone Operating System Version: Android 4.1.2
Version of Lichess Mobile Beta: v1.0.21-beta
Steps to Reproduce: Open lichess mobile beta and press top left button to open side menu/tab
Description of the Observed Behavior: Certain images are overlapping/not lining up with text
Description of the Expected Behavior: All images and text lined up and not overlapping so as to be clear and readable
![screenshot_2015-01-31-16-27-31](https://cloud.githubusercontent.com/assets/3761567/5986702/6b4ab1b8-a969-11e4-8085-e840cb002ad4.png)
Note: You can also see a white line on the left of the screen however I am not sure if this is a related or separate problem.
Note 2: The app looks really nice (apart from the bugs obviously). Keep up the good work!

**Comment by Evropi** [comment]
This happens for me as well. I believe it was diagnosed at the time as being an issue with versions of Android prior to 4.3, which probably means it won't be fixed.

**Comment by GnarlyGoat** [comment]
Yeah I think this is the issue I am having as well, I'm on 4.1.2 so I guess that explains it. Its not really a big deal as I can still use the app just fine but it is a little odd looking sometimes.
