### ISSUE TITLE
[Bug] Display doesn't go off anymore

### ISSUE THREAD

**Issue by MateMachine** [veloce/lichobile#820]
Hi,

Device: Samsung Galaxy S5
Android version: 4.4.2
Lichess version: 5.5.0

Issue:
After a game has finished, the display doesn't go off anymore.
If you don't close the game and click the power button, the display goes off.
If there is any notification (alarm, sms etc.), the display goes on (which is normal).
However, it does not go off anymore because of Lichess.

The same is when you win by time.
It will always stay on.
So the only current solution is that you close the app.

Some versions ago the display went off automatically after the match was over.
Even if you received some sms, it went on but went off some seconds later again.

Can you re-add this function, please?

Best regards

**Comment by MateMachine** [comment]
Are you sure it's solved?
I have v5.6.1 installed and when a match has ended, the display still stays on...
Please re-check the issue!

**Comment by niklasf** [comment]
The fix hasn't made it to a release yet (v5.6.1 is from April 18).
