### ISSUE TITLE
Analysis bug

### ISSUE THREAD

**Issue by Mumbis** [veloce/lichobile#823]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request

# Bug report

**Current behavior:**

After a 960 game when I choose computer analysis it never finishes. The circle just keeps spinning and I never see the final graph. But on the move list I see the computers suggestions AND I can still do the "learn from your mistakes".

**Expected behavior:**

It should show the analysis graph.

**Steps to reproduce:**

Play a 960 game and press computer analysis. Not sure if this bug happens every time but for me very often.

**Environment information**

Lichess v5.6.1
SHIELD Tablet K1 software 5.4(24.29.404.195)
Android 7.0

**Other information:**

**Comment by Mumbis** [comment]
I have found a work around. If I exit the analysis by pressing the arrow on the upper left, and go back to the game, and then back again to analysis THEN the graph shows up.

**Comment by renyhp** [comment]
I am still experiencing the exact same issue with the exact same workaround, by the way on any game (not only 360 games).
Lichess v6.2.0
Huawei P9 lite VNS-L31
Android 7.0
