### ISSUE TITLE
New Icon/Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [veloce/lichobile#824]
Hi Sir @veloce , I am a graphic designer and a chess player also :). I want to contribute to your project by proposing a new design for Icon/Logo as i have observed and notice the existing icon needs an upgrade in my opinion.
With this issue I have come up with these designs which I hope you will like and if you do, I will give and send you the files as a gift for free. 

Here it is Sir:

![idea](https://user-images.githubusercontent.com/36028424/39612913-17494292-4f96-11e8-9011-e5460dcaa40e.png)

![display-01](https://user-images.githubusercontent.com/36028424/39612918-1ec2f87e-4f96-11e8-999b-ce547254dff5.png)

I will also made it an adaptive icon for the Android O compatibility
If you have suggestions or any idea for changes just let me know and i'll edit it.

Thanks and best regards!
-Tobaloidee

**Comment by veloce** [comment]
Hi @Tobaloidee ! Thanks for the logo work! You should open an issue on ornicar/lila instead, which is the lichess main repository. The mobile app and website should have the same logo of course.

**Comment by Tobaloidee** [comment]
Okay Sir @veloce  i will open an issue there.. Do you like the design sir?
