### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by niklasf** [veloce/lichobile#826]
**I'm submitting a ...**
- feature request

# Feature request

Two-factor authentication is deployed on stage. It can be enabled on https://listage.ovh/account/twofactor.

For users with enabled 2FA requests with correct `username` and `password` to `https://listage.ovh/login` will fail with `401 Unauthorized` and response `{global: ["MissingTotpToken"]}`.

The app should detect this particular error and prompt for an *Authentication code*. It should then retry the login with `username`, `password` and `token` (<- the authentication code).

Invalid authentication codes will be rejected with `{global: ["InvalidTotpToken"]}`.

**Comment by pukhrajbal** [comment]
@veloce I'm using 6.1.0 app and it does not allow me to login after I enabled 2fa on website.
Phone - Pixel XL - Android 9.
Is 2FA available on mobile app login?

**Comment by rwuwon** [comment]
lichess v6.1.0 on a 2016 Pixel with Android 9 - I'm getting the same issue after enabling two factor authentication as per the steps below:

1. Use desktop browser to configure lichess to use two factor authentication.
2. As soon as that is enabled, lichess on Android is logged out (when it was previously logged in).
3. Try to sign in again on the app and nothing happens - no prompt for a 2FA code pops up.
4. Disable two factor authentication via desktop browser and login on the app end immediately works again.

I'm not sure whether this needs to be reopened or made as a new issue, but my only current workaround right now is to not use two factor authentication, but only rely on a unique strong password manager-generated passphrase and other general good security practices.

**Comment by niklasf** [comment]
@pukhrajbal Thanks. I tracked down the issue and submitted a fix: https://github.com/ornicar/lila/pull/4672. Once this is deployed we will also remove the `Note that it's not yet supported by the <a href="/mobile">mobile app</a>. We're working on it.` message that I forgot about.

**Comment by pukhrajbal** [comment]
Awesome!... you are the best!

**Comment by ornicar** [comment]
It's deployed.
