### ISSUE TITLE
user report: local AI play, broken after castling [v5.6.1]

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#830]
> When i played offline with stockfish 4 with white pieces and castled, app made a move with my pieces and that's all. i couldn't make another move. i tried several times and result is the same

1) I played with stockfish 4
2) made several moves
3) made castling
4)after that somehow my knight from f3 went to e5
5) I opened analysis and there isn't any my move after castling
6)i closed analysis and can't do anything and stockfish doesn't make any moves
I don't have the same problem on my gf's phone,and it's running Android 7.1
On my phone I have Android 8.1

![](https://i.imgur.com/o6oJTjh.png)
![](https://i.imgur.com/b1OeEeX.jpg)
![](https://i.imgur.com/uSni4ci.jpg)
![](https://i.imgur.com/9O5d7fi.jpg)

**Comment by freefal** [comment]
I tried a couple times to reproduce this and failed.
