### ISSUE TITLE
bug: empty lists top margin

### ISSUE THREAD

**Issue by apunko** [veloce/lichobile#836]
# Bug report

**Current behavior:**
The top margin is absence on empty lists.

![image](https://user-images.githubusercontent.com/10829386/40362225-922cd734-5dd4-11e8-8876-638b7b9d35e5.png)

**Expected behavior:**
Top margin. 'Oops! Nothing here.' under tab titles without interference.

**Steps to reproduce:**
Precondition: Have no challenges
1) Open 'Correspondence' from user menu
2) Challenges tab

The same behavior for Public Games.

**Environment information**
IOS 10.3.1
lichess v5.6.1

I have added https://github.com/veloce/lichobile/pull/837 to fix it.
I really like and enjoy lichess and want to make contributions sometimes.

**Comment by veloce** [comment]
Fixed in master.
