### ISSUE TITLE
iOS excessive storage

### ISSUE THREAD

**Issue by sebastianv89** [veloce/lichobile#839]
# Bug report

**Current behavior:** The application on my iPhone uses an excessive amount of storage data.

**Expected behavior:** The application should not need to take up so much storage on my device.

**Steps to reproduce:** Settings > General > iPhone Storage > lichess > Documents & Data
For example, on my phone the app uses 290.8MB of data.

**Environment information:**

- phone hardware: iPhone SE
- phone operating system version: iOS 11.3.1
- version of lichess mobile: Version 5.6.1

**Other information:** I'm not sure what data is being stored by the application. If it is mainly cached data or something like that, a possible solution would be to have an option to delete all cached data.

**Comment by veloce** [comment]
I won't provide an option to delete cache data. You'll have to delete it yourself. It seems that on iOS the easiest way is to delete the app and reinstall it...
