### ISSUE TITLE
[Bug] Terminating the app messes up the settings

### ISSUE THREAD

**Issue by MateMachine** [veloce/lichobile#842]
Device: Samsung Galaxy S5
OS: Android 4.4.2 (rooted)
Lichess version: v6.0.0

-----------------------------

Hello,

When I hold down my back touch button for about 2 seconds,
the currently active app gets terminated ("killed").
It's not the best thing, I know, but it is very simple and very fast.
(Especially for apps like Whatsapp, which run in background if you close them in a normal way.)

For Lichess this always used to work as well.
You just finished a match and instead of pressing the back touch button several times,
you simply hold it pressed and you'll be instantly on the home screen.
(And the Lichess app will be terminated.)

Since v.6.0.0 has been released, I cannot do this anymore.
Everytime I terminate the app, I cannot launch it again.
It says "Lichess paused" (I don't know how it is in English).
Then I can either press "Report" or "OK".

When I press "OK" and run Lichess again, it works, but the settings are messed up.
Language is set back to German and other settings I made are gone as well.

After setting up everything again and closing the game in a normal way,
it stays saved and the game launches without problems.
I can close it as often as I want, there will never be a problem.

If I terminate the app again, it will start from 0 again.
1. Error message when launching
2. After trying to launch it again, it will start
3. Settings are gone again.

As said, I know terminating an app isn't the way, but since it always used to work
and since it doesn't cause any (noticable) problems to other apps,
I assume it's an issue of Lichess v.6.0.0.

Can you please check this?
Even if you weren't able to terminate apps (because of no root access for example),
I'm sure you knew what could cause this issue.

Regards

**Comment by sick13** [comment]
Got the same problem,but only when i sign in,after that app crashes when i start it again,after that i can start the app but i am signed out and settings are gone

Kitkat 4.4.4

**Comment by veloce** [comment]
That's an android 4.4 issue indeed. I'll see what I can do, in the meantime you can rollback to the previous  release: https://github.com/veloce/lichobile/releases/tag/v5.6.1

**Comment by sick13** [comment]
Yeap,alredy rolled back,thx for looking into it

**Comment by MateMachine** [comment]
Thanks for checking it!
v5.6.1. is a no go for me due to the "permanent screen on" issue.
I'll live with the v.6.0.0 bug with the hope that you'll be able to fix it in the near future.

By the way:
Is it maybe possible that I can modify the default Lichess config file on my device?
(I have root access).
Because if the default config file is as I want, I can live with the 2x times starting the app.
More annoying to me is modifying the settings.

Best regards

**Comment by veloce** [comment]
Fixed: https://github.com/veloce/lichobile/releases/tag/v6.0.1

**Comment by MateMachine** [comment]
Excellent!

Thanks, veloce!
