### ISSUE TITLE
Android app crashes after update to 6.0.0 (Android 4.4.2)

### ISSUE THREAD

**Issue by bamstam** [veloce/lichobile#843]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

Lichess Android app crashes after updating to 6.0.0

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Samsung Galaxy S3
- Android 4.4.2
- Lichess 6.0.0

**Other information:**

# Feature request

**Comment by veloce** [comment]
Fixed here: https://github.com/veloce/lichobile/releases/tag/v6.0.1
