### ISSUE TITLE
App not pairing me with other players

### ISSUE THREAD

**Issue by mandeep** [veloce/lichobile#849]
Tablet: SM-T810
Android version: LineageOS 14.1
Lichess Mobile version: v6.0.1

When trying to play a game, whether a tournament or quick game, the app will not pair me with other players. When playing on the Lichess website everything works fine. I'm unsure how to debug this but if there's anything I can do to help please let me know.

**Comment by mandeep** [comment]
v6.0.3 has caused this issue to resurface.

**Comment by veloce** [comment]
Fixed https://github.com/veloce/lichobile/commit/4f791cade8fa17f45dedd6d26172dc718a9099e2

**Comment by mandeep** [comment]
@veloce is there a planned release that includes this fix?

**Comment by mandeep** [comment]
This problem still exists in v6.1.0.
