### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by nalkpas** [veloce/lichobile#852]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**
As of two days ago, I can't connect to lichess.org on my school network. The mobile app doesn't connect and the browser page doesn't load. I tried both Chrome and Firefox and neither worked. Chrome on my phone can't connect either. 

I'm not sure if the problem is on my school network's end or lichess's, but I figured I should point it out.
I updated my computer OS two days ago as well (I'm on Mac), and there's some chance that's the issue. 

**Expected behavior:**
I can connect to the server and play. Everything was working fine up until very recently. 

**Steps to reproduce:**
This is what the error looks like in my browser: https://imgur.com/a/z94kNvv

If anyone is randomly at Stanford, I'm having the issue on the "Stanford Residences" network. 

**Environment information**

Phone hardware: iPhone 9
Phone OS: latest update
Lichess version: most recent version in the App Store

Computer hardware: 11 inch Macbook Pro (with touchbar)
Computer OS: latest update
Browsers: latest versions of Chrome and Firefox

**Comment by niklasf** [comment]
Hi, what's your (school's) IP address?

**Comment by nalkpas** [comment]
It's 128.12.245.14.

**Comment by niklasf** [comment]
Looks like it triggered detection for too many requests from the same address. I unbanned it for now. Maybe we have to whitelist it, if it happens again.

**Comment by veloce** [comment]
Closing the issue then.
