### ISSUE TITLE
Too easy to press wrong button on tournament end-of-game menu

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#854]
When a game finishes, the menu pops up immediately with several options.  Here are the tournament options:

- Back to tournament
- Pause
- Bookmark this game
- Share game URL
- Share PGN
- Analysis Board

While this menu looks nice, it has a serious usability problem when playing fast games (e.g. hyperbullet) -- it is way too easy to inadvertently press the wrong button when a game suddenly and unexpectedly finishes and this menu pops up where you want to click your next move.  Although I usually manage to click the `Back to tournament` button correctly when I want to, I have unintentionally clicked each of these other options literally hundreds of times while playing tournament games (I currently have 102 bookmarked games I didn't mean to bookmark, for instance, not counting all the times I realized I pressed this and pressed it again to unbookmark).  I have never wanted to share a game URL or PGN, but still see the sharing UI many times a day while playing.  Worst perhaps is accidentally pressing Pause because you can end up withdrawn from a tournament without realizing it, and Analysis Board is also annoying because the way to get back to the tournament from this page is rather counter-intuitive and slow.

I think the post-game UI, especially for tournaments, should be redesigned/restructured so it is much harder to  press the wrong button, perhaps with `Back to tournament` as the only immediate option and the other rarely used options hidden in a `...` option.

The regular end-of-game menu is:

- Bookmark this game
- Share game URL
- Share PGN
- New opponent
- Rematch [if opponent is available]
- Analysis board

Of course, I regularly inadvertantly click `Bookmark this game` instead of `New opponent` because it is inexplicably first in the menu, and because it starts with 'B' so it looks at first glance like the `Back to tournament` first option I am used to clicking in the other menu.  The only options that should be easy to click here are `New Opponent` and `Rematch`.

**Comment by zamirkhan** [comment]
I agree with the above and want to add my 2 cents:

I think one of the most common buttons LiChess players must press is the "new opponent" button after a match. However, I've lost count of how many times I have accidentally hit the "share" button after it has appeared some milliseconds later and vertically displaced the "new opponent" button. Then I must wait for the native share menu to open on my phone, dismiss it, and tap the button I originally intended to. This is obviously just an annoyance, but it happens a lot and it seems solvable.

Without any evidence, I would guess that the "new opponent" button is more popular than the "share" button by orders of magnitude, so obviously having the much less used button negatively affect the widely used one is undesirable. I suggest moving the share button to the end of the list or another location where it won't displace other buttons.
