### ISSUE TITLE
offline vs CPU gets stuck on task switch

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#864]
>>> I've found an annoying bug for version 6.0.3 of Lichess.
While playing offline against the computer, if you switch to the analysis board and then switch back to the game, the computer won't make any more moves. It gets stuck with the hourglass icon at the top of the screen.
Sometimes switching to another game mode, like training, then switching back will fix this, but most of the time doing this just crashes Lichess.

**Comment by sashakirichek** [comment]
Experiencing the same even without changing to analyze. Just using back function.
