### ISSUE TITLE
forever offline

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#865]
0. stop lichobile
1. turn on plane mode (no Internet)
2. start lichobile - it's running offline
3. turn off plane mode (restore Internet connection)

Expected: lichobile is now online
Happening: lichobile remains offline

Only a full stop/restart of the app fixes it.

Galaxy A8, Android 7, lichobile 6.0.4

**Comment by veloce** [comment]
Fixed here: https://github.com/veloce/lichobile/commit/ab9c29aae4adb19fc42fcfda31da77d64df111af
