### ISSUE TITLE
Cannot submit move in correspondence

### ISSUE THREAD

**Issue by mmeyers00** [veloce/lichobile#866]
Bug report:  Whether I'm using move confirmation or direct move it never registers in correpondence. It only shows connectivity dots at the top. I had to revert to older version of app for it to work again.

**Comment by ornicar** [comment]
When you go to the app Home screen, does it say you're offline?

**Comment by mmeyers00** [comment]
Yes it does. I can also watch games.

**Comment by mmeyers00** [comment]
Sorry, made an edit to my comment above.

**Comment by tegularius** [comment]
I am having the same problem, I had to go back to 6.0.2 to make it work again.

LineageOS 14.1 (jfltexx, Android 7.1.1, 20170107, a bit old)

**Comment by veloce** [comment]
Fixed here: https://github.com/veloce/lichobile/commit/4f791cade8fa17f45dedd6d26172dc718a9099e2
