### ISSUE TITLE
App for Android version 6.0.4 doesn't notify when a friend is online.

### ISSUE THREAD

**Issue by joselo89** [veloce/lichobile#867]
Hi there.
I am not sure if it's only me who is experiencing this bug or all of us. I just installed the app (last version 6.0.4) and noticed a bug.

I cannot not see when my friends are online from my app. It doesn't show up that icon that normally pops up on the right up corner when a friend is online.
I attache a picture to illustrate. At that moment I had three friends online, but the app doesn't notify me.

(Click on the link below to see the picture)

https://photos.google.com/share/AF1QipOyW9zkqWAV5fljW-cUCJBTrCLSLST-Yjq4VeTzTk1xPpk8PmPy6lqwODs56yP07w/photo/AF1QipPU0v41hRt9FnYEsez_mzydr62Qna3l0uhLMLFC?key=ZUJhek5NNG9NcUlTamJXd2dUQ3Q2Y2R4MHlUbXBB

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by veloce** [comment]
Fixed here: https://github.com/veloce/lichobile/commit/4f791cade8fa17f45dedd6d26172dc718a9099e2

**Comment by joselo89** [comment]
sorry i don't understand.
I clicked on 4f791ca, but I don't understand what that means...I am not a software developer.

so...what do I have to do to see my friends when they are online?

**Comment by veloce** [comment]
wait for the next release... you can also try to upgrade either chrome or system webview app.

**Comment by joselo89** [comment]
ok. I'll wait. Thank you.

**Comment by joselo89** [comment]
Hi
I just want came here to mention that I updated my system webview app and the problem is fixed.
Thanks for advising me on updating that app.
