### ISSUE TITLE
Game links with /white or /black fail to open

### ISSUE THREAD

**Issue by kufii** [veloce/lichobile#869]
**I'm submitting a ...**  (keep the relevant one):
- bug report

**Current behavior:**

When you open the link on mobile, instead of opening the game it goes to the main screen

**Expected behavior:**

It should open the game from the relevant players perspective. This is the behaviour on the web version.

**Steps to reproduce:**

take any game url, add /black to the end, and try to open it through the mobile app (eg `https://lichess.org/[id]/black`)

**Environment information**
- phone hardware
Pixel 2 XL
- phone operating system version
Android 8.1.0
- version of lichess mobile
6.0.4

**Comment by freefal** [comment]
This PR (https://github.com/veloce/lichobile/pull/895) is an attempt to close this.

**Comment by jeroenmeulenaar** [comment]
I have the same issue. When can this pull request be merged?

**Comment by muisje** [comment]
I had just experienced this issue and my friend too. I'm using the android app. Opening this:

lichess.org/iVEEjKEb/white#121

or

lichess.org/iVEEjKEb/white

opens the home screen.

lichess.org/iVEEjKEb

opens the game.
