### ISSUE TITLE
After checkmate don't immediately pop out a window

### ISSUE THREAD

**Issue by mrwojciech** [veloce/lichobile#872]
**I'm submitting a
- feature request

# Feature request

- Use case: why should this be implemented? Many times when you are surprised you want to see last move so to do this you must first close the pop-up.  It is annoying for me to do thin after each match. 
- If the feature changes current behavior, reasons why your solution is better
--> Because you can see last move. 
As alternative the pop up may appear with some delay. 
Best Regards

**Comment by rolfsimoes** [comment]
* Another reason: why should this be implemented? On Android, after time's up, you just intent to make a move and then you touch on "share game" because the it pops out a menu and go to Android's share screen... it's annoying!
* If the feature changes current behavior, reasons why your solution is better: because you don't want open share screen on Android by touching/clicking by mistake on the suddenly popped up menu.

**Comment by mrwojciech** [comment]
I believe the root cause for that is the 'revenge' options that disappears after some time.  I assume that was the reason to popup immediately.  With that there is this other thing that this 'revange' option disappears (instead of being gray out). 
Maybe some kind of floating button to challenge the opponent again would be a solution?

**Comment by rolfsimoes** [comment]
This happens too. But if you are a bullet chess player and need to play very fast, you will see that the menu that pops up when the game is over (e.g. time up, checkmate) is an annoyance. In bullet chess you play fast at the beginning and the middle game. But at the end games you play insanely fast. You play by making pre-movements. You are totally focused in the game. Then, when time is up, suddenly, a pop up window appear and almost always you click/touch unintentionally in the menu... I think the better solution would be that subtle button that blinks when your opponent proposes a 'draw' or a 'take back last move'. At the end of the game, If you want to access the menu, you should click there. At least this could be an option to the user: "Pops up the menu at the end of the game?".

**Comment by mrwojciech** [comment]
Yeah! :)

**Comment by leonty** [comment]
Also this https://github.com/veloce/lichobile/issues/917
