### ISSUE TITLE
Ultrabullet name is missing on the leaderboard page

### ISSUE THREAD

**Issue by greg-finley-ck** [veloce/lichobile#877]
I'm submitting a bug report

# Bug report

**Current behavior:**

Ultrabullet name is missing from list of variants on Leaderboard page.

**Expected behavior:**

Ultrabullet name should be there.

**Steps to reproduce:**

Hamburger button -> Leaderboard

**Environment information**

iPhones 6s
iOS 11.4.1
v.6.0.0

**Other information:**

![image](https://user-images.githubusercontent.com/28961086/42731027-a8cad2d4-87b9-11e8-8848-66e0af8f2783.png)

**Comment by greg-finley-ck** [comment]
Thanks!

**Comment by freefal** [comment]
Thanks for letting us know about the issue.
