### ISSUE TITLE
option to put a name to a tournament on the app

### ISSUE THREAD

**Issue by joselo89** [veloce/lichobile#883]
Hi there 

would it be possible to have the option to put a name to a tournament on the app?

When we create a tournament (especially private tournament) we don't have the option to name a tournament, so when I create tournament from the app a random name is assignated to it.

It'd be nice to have the option to put a name to the tournament. such as: San Felipe Club arena, etc

Thanks

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by freefal** [comment]
Pull request adding this feature submitted here: https://github.com/veloce/lichobile/pull/889
