### ISSUE TITLE
Keep study tab selection when switching chapters

### ISSUE THREAD

**Issue by cyanfish** [veloce/lichobile#886]
In a study, when you switch chapters, the move list tab is always selected. It doesn't stay on the currently selected tab.

If you switch to another tab (Comments, PGN tags, etc.) it should stay there regardless of chapter changes until the user switches away.

Android Galaxy S9, Lichess v6.0.4

**Comment by freefal** [comment]
Pull request resolving this issue submitted here (https://github.com/veloce/lichobile/pull/892)
