### ISSUE TITLE
CrossTable in the app

### ISSUE THREAD

**Issue by joselo89** [veloce/lichobile#890]
Hi there

When I play a bunch of games against the same opponent on my phone, It's not displayed how many wins I have accomplished nor my opponent's victories.

Would it be possible to display the number of victories when one plays on the app?

The same happens when I watch a top game (for eg two GMs) from my phone...I can't see who is leading.

Thanks

**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by freefal** [comment]
We decided that there is no room for a full crosstable, but just click on your opponent's name above the board and you'll see the overall score between you.

**Comment by joselo89** [comment]
Ok, thank you for responding.
