### ISSUE TITLE
Games in play count does not go over 20

### ISSUE THREAD

**Issue by arawde** [veloce/lichobile#909]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**
I play correspondence, and have a multitude of games going at once. If I open more than 20 games, on the web interface, it displays the correct number, but in the app, it caps out at "20 games in play" in the menu.

**Expected behavior:**
The menu should report a number of games matching the web interface.

**Steps to reproduce:**
To reproduce:
- Open 20 games and observe that 20 games are in play
- Open any number of additional games

**Environment information**
- Phone: Google Pixel 2
- OS version: 9
- Lichess version: 6.1.0

**Comment by veloce** [comment]
https://github.com/ornicar/lila/pull/5328

**Comment by ilovelinux** [comment]
@veloce Why is there a cap?

**Comment by veloce** [comment]
We could remove it in theory, but who plays more than 50 games simultaneously?
