### ISSUE TITLE
Design Proposal for new Piece Set

### ISSUE THREAD

**Issue by philatype** [veloce/lichobile#912]
**I'm submitting a ...**  (keep the relevant one):
- feature request

# Feature request

I have designed a minimalist and contemporary piece set called 'Kosal' and would like for it to be considered as an option in the Lichess app.
I've placed the files and license in my repo.
https://github.com/philatype/kosal/

Here's a preview of the pieces:
![preview](https://user-images.githubusercontent.com/13021834/47335164-e5c21200-d657-11e8-9d76-0ef896341eab.png)

**Comment by dsjoerg** [comment]
Looks great!

**Comment by sick13** [comment]
Very nice... +1 to integrate this set

**Comment by sallyx** [comment]
Nice. It would be also great if you added "blindfold" theme.

**Comment by veloce** [comment]
hello sorry for late response here. @philatype piece themes are sync with the website: I won't add it to the app if it doesn't go to the website first. So ornicar/lila is the repo you want to add an issue to.

**Comment by philatype** [comment]
Hi, it's already on the website: https://github.com/ornicar/lila/issues/4634

**Comment by gbtami** [comment]
@mattbruv PR https://github.com/veloce/lichobile/pull/977

**Comment by jas14** [comment]
Closed by #977.
