### ISSUE TITLE
Move Analysis Button To The In-Game Screen Instead of the Notes Button

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#924]
Feature Request:

In the current version (6.1.0) of the Android lichess app, while you are playing a game you have a few buttons below the board but none of them are the Analysis board. To get to the analysis board you need to tap the menu button then choose Analysis board.

I use the Analysis board in every correspondence game I play but I have never used the Notes.

Can we somehow find out how often each of these features is used? It makes no sense to me personally to have the Analysis board one level deep when it is so useful and the Notes as a quick button when it is so rarely used. Let's swap the two positions of the buttons and move notes to the menu. The Chess.com app has the analysis button right there front and center, btw.

I might be wrong here and everyone is taking notes on their games but not using the Analysis board but I really doubt it. Who agrees with me here that Analysis is so much more useful? Please give a thumbs up to this post if you agree and a thumbs down if you disagree.

Thanks all!

**Comment by landry314** [comment]
who uses notes? i never have in my life...

**Comment by jas14** [comment]
@landry314 As part of conditional premoves (#1490 ), which was released in version 7.8.0, the "Notes" button was replaced with the analysis button. Enjoy!
