### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [veloce/lichobile#927]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by fazlerabbi37** [comment]
Just FYI, this is duplicate of #409. better to keep the discussion on one thread.

**Comment by 532910** [comment]
This issue is closed and not filled, and I'm subscribed for 409

> better to keep the discussion on one thread.

So why do you spread it?
