### ISSUE TITLE
Better UI for sidebar menu

### ISSUE THREAD

**Issue by Evropi** [veloce/lichobile#93]
Currently, the button that brings up the sidebar *moves* after being pressed. It is as if it emulates paper being moved around. However, this is generally considered a UI anti-pattern as such a crucial menu item is shifting position -- especially since it contradicts design guidelines on iOS and Android alike.

Luckily, there is a solution. Here is an extremely rough 1-minute mockup:
http://i.imgur.com/ZdWIOXd.png

The button that opens the menu is always on the top-left. Preferences were moved to the bottom.
The mockup uses the Android convention of attaching the "Preferences" menu to the bottom of the list, regardless of the menu's size.

Note that Android convention dictates an always-visible bar at the top, but I believe we can do without it. If you want to see an app that sticks very closely to Android UI design guidelines *(including the one I just mentioned)*, I highly recommend [Sliding Explorer](https://play.google.com/store/apps/details?id=com.ballerapps.slidingexplorer), which has a very careful implementation of 'material design' (MD has a lot of sound ideas mind you, but certainly isn't all perfect).

**Comment by veloce** [comment]
I'm actually working on a new version of the menu. The main thing is to be able to swipe to open/close it. And it will also come over the screen (instead of shifting the screen as now). So it will look more like Gmail's menu for instance.
I won't follow Android convention to keep the top-bar always visible indeed.

**Comment by veloce** [comment]
@Evropi you can test the new sliding menu with last android beta on hockeyapp. 
I still need to add gestures ;)

**Comment by Evropi** [comment]
I'm very impressed! If you can execute the slide-in on demand, consider making this the normal screen (but show it sliding in on start, so people know how to control the app).

I still reckon the preferences button should be elsewhere and you might want to have a button to close the menu regardless (though that is not necessary). Great job otherwise, keep it up Vinnie.

**Comment by veloce** [comment]
I'll add a separate issue for gestures so closing this.
