### ISSUE TITLE
[feature] click to copy invite URL

### ISSUE THREAD

**Issue by patrickpei** [veloce/lichobile#932]
# Feature request
When creating a link, I'd be nice if the [challenge popup](https://github.com/veloce/lichobile/blob/7fabf3f76ccda8ce67206b2afadbfdfaf5bcef5b/src/ui/challenge/challengeView.tsx) would allow a user to copy the link to clipboard by clicking the grey. Even though share game URL brings up the social sharing dialog, I often find this more cumbersome than just pasting. 

Thanks for the work on this!

![image](https://user-images.githubusercontent.com/14530807/50733204-f8c08a80-114e-11e9-9045-3622bb278aff.png)

**Comment by freefal** [comment]
I don't know what version of Android you are on, but for me one of the "sharing" options is to copy to clipboard (an icon with two intersecting rectangles). Do you see that option and does it solve your issue?

**Comment by patrickpei** [comment]
Ah yeah I see that. I think that clicking the grey to copy would streamline the sharing process a little more, but the functionality is definitely there already.
