### ISSUE TITLE
Chart in computer analysis table is one move ahead

### ISSUE THREAD

**Issue by kf-ryszardseniuta** [veloce/lichobile#935]
**I'm submitting a bug report**

# Bug report

**Current behavior:**

Chart in computer analysis table is one move ahead when playing a tournament game with a starting position where black starts a game.

**Expected behavior:**

**Steps to reproduce:**

https://lichess.org/ua37TkWS
In move 42 stockfish shows -16.8 but on chart it shows white adventage

**Environment information**

- Android 8.1.0
- lichess 6.1.0

**Comment by freefal** [comment]
Addressed in this PR: https://github.com/veloce/lichobile/pull/954
