### ISSUE TITLE
Unable to scroll through games or users in tournaments.

### ISSUE THREAD

**Issue by strike2867** [veloce/lichobile#939]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

Scrolling doesn't work across the board, no pun intended.

**Expected behavior:**

Able to scroll down on home, tournament list of players (impossible to join tournaments now), list of tournaments.

**Steps to reproduce:**

Navigate to any screen and attempt to scroll.

**Environment information**

- phone hardware S7 Edge
- phone operating system version Android 8.0.0
- version of lichess mobile 6.1.0

**Other information:**

The issue started this morning.

**Comment by Nnomii** [comment]
I have the exact same issue. I have tried many things yet I can't fix this its super annoying :(

**Comment by gcp** [comment]
>I'm surprised an external app caused this though.

Chrome powers the system WebView on modern Android. If Google updates Chrome, everything that depends on WebView is at risk of breaking. It's obviously not common but as this bug illustrates, it *is* a risk. It's possible to ship your own web rendering engine to decouple (e.g. Mozilla's GeckoView), but the current mobile app being based on Cordova, it's probably pretty hard to switch at this point.

**Comment by gcp** [comment]
No, it's just that the lichess app is based on common web technologies which has allowed them to have both iOS and Android apps despite having a limited team.

**Comment by dneary** [comment]
Same issue here.

**Comment by veloce** [comment]
I should add to complete what @gcp was saying about the web rendering engine, that lichess app was shipped before with it's own rendering engine. At that time such issue could not happen. But unfortunately, the [open source project](https://crosswalk-project.org/) it was based upon has now been discontinued for more that a year now, and it not maintained anymore.

**Comment by niklasf** [comment]
See https://github.com/veloce/lichobile/issues/874. Fix is coming soon.

**Comment by dneary** [comment]
Chrome 72.0.3626.76 here

**Comment by Spone** [comment]
The latest app update fixed it for me.

**Comment by AitorF** [comment]
Same. Chrome 72.0

**Comment by GruffGemini** [comment]
The latest update fixed the scrolling on the main screen, however scrolling through the notation in the analysis mode is still impossible

**Comment by lasseebert** [comment]
The latest Chrome (72.0.3626.105) solved the issue for me. Can scroll everywhere again.
Using Google Pixel 2.

**Comment by veloce** [comment]
Yes updating chrome should solve all of the scrolling issues. So I'm closing this.
