### ISSUE TITLE
Analysis Board Should Also Maintain Time on Clock At Each Move

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#941]
This is kind of a bug and kind of just a missing feature depending on how you look at it.

The analysis board does not show time remaining on each move as you go back and review the game. This would be quite useful because the time remaining is an essential part of the game. Seeing how much time you took to think can help you learn when to think more and when to move faster. It can also explain why you made a bad move due to not thinking enough or due to time almost being run out...

If the PGN file does not contain time at each move then that would be hard to implement. You would have to add this data somewhere. If it does then it is simply a matter of including it in the analysis board routine.

**Comment by freefal** [comment]
I'm not sure about imported PGN games, but for games played on Lichess, the analysis board does show times just above and under the board on the right (see attached screenshot).
![screenshot from 2019-02-23 22-42-43](https://user-images.githubusercontent.com/954742/53294834-bfa2af00-37bc-11e9-918f-0ee93579ff4a.png)

**Comment by landry314** [comment]
yes, i see the timer is updated in the analysis board now...
