### ISSUE TITLE
Reset to home screen if resized in split-screen mode

### ISSUE THREAD

**Issue by xehpuk** [veloce/lichobile#944]
# Bug report

**Current behavior:**

Use the app inside [Android's split-screen mode](https://developer.android.com/guide/topics/ui/multi-window). Resize it. Whatever you have done before is lost because the app resets to the home screen.

**Expected behavior:**

The app stays in the currently active screen, adjusting the layout to the new size.

**Steps to reproduce:**

Screen capture: https://www.youtube.com/watch?v=LOCwN2vHqLs

**Environment information**

- Huawei Mate 10 Pro (BLA-L29)
- Android 9 / EMUI 9.0.0
- lichess 6.1.1

**Comment by freefal** [comment]
The Lichess app doesn't support split screen mode. If you have time to fix this and submit a patch, that would be great, but this feature isn't a priority for the developers at the moment.

**Comment by wsobasik** [comment]
When you go from split screen directly to the app while playing your app is opened in home screen and then you need to navigate and reopen the game that you play.

**Comment by AmbroiseS** [comment]
It's a shame it was disabled,
I used multiscreen a lot, even though it is a bit buggy (but the bugs are not that bad)
