### ISSUE TITLE
Force portrait mode option

### ISSUE THREAD

**Issue by kehtabp** [veloce/lichobile#950]
# Feature request

Scenario: Playing on the move, can cause unintentional screen rotations to landscape mode which can lead to loss of valuable seconds or making a wrong move.

Current work around is to force your phone in portrait mode system wide, but it's annoying to have to do it every time I play, and I'm confident I never want landscape mode for Lichess on my phone.

**Comment by papb** [comment]
Hi @veloce, was an option added to configure this?
