### ISSUE TITLE
Pressing Profile => Training does not show past puzzles

### ISSUE THREAD

**Issue by jackHedaya** [veloce/lichobile#952]
# Bug report

Pressing Profile => Training shows press markers but does not show past puzzles or training statistics. 

## Environment
iPhone X 
iOS 12.1.4
Lichess v 6.0.0

## Reproduce
Press username on hamburger bar menu. Press training.

**Comment by freefal** [comment]
Fixed here: https://github.com/veloce/lichobile/pull/953
