### ISSUE TITLE
Misinterpreting "standard" as "3n2r1" in analysis URL.

### ISSUE THREAD

**Issue by spxtr** [veloce/lichobile#956]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

My friend generated a position using the board editor on the lichess site, then sent me the analysis link. It looked something like this:

`https://lichess.org/analysis/standard/1k6/5nP1/4bN2/4B3/3R4/2Q5/8/4K3_w_Kk_-`

When I open that link in the mobile app, the FEN it's actually using is `3n2r1/1k6/5nP1/4bN2/4B3/3R4/2Q5/8`. Note that "standard" is being parsed as FEN. When I open it with the lichess site, it opens properly.

**Expected behavior:**

It should not interpret "standard" as "3n2r1". The FEN should have been `1k6/5nP1/4bN2/4B3/3R4/2Q5/8/4K3_w_Kk_-`.

**Steps to reproduce:**

Using the lichess site, go to board editor, copy the URL from the bottom, and open it on a phone with the mobile app.

**Environment information**

- phone hardware: Pixel 2 XL
- phone operating system version: Android 9
- version of lichess mobile: 6.1.1

**Other information:**

Apologies if it's a dupe. Thought it was pretty funny :)

**Comment by freefal** [comment]
Thanks for the clear bug report. Fixed here: https://github.com/veloce/lichobile/pull/964

**Comment by AdnanSlef** [comment]
If fixed, please close.
