### ISSUE TITLE
List seeks

### ISSUE THREAD

**Issue by tobiasvl** [veloce/lichobile#96]
The app should have a list of open seeks that updates in realtime, like the front page of http://lichess.org. Clicking a seek should accept and start the game.

**Comment by nyrk** [comment]
Agree 100%

**Comment by tobiasvl** [comment]
Seeks should probably be displayed on the splash screen of the app; see #102.

**Comment by veloce** [comment]
We have no plan to implement list of real time seeks now. We think more interesting features for mobile are to be developed first. As for now, they are at least: 

* ability to create correspondence seeks (and cancel them)
* training mode (puzzles)

**Comment by veloce** [comment]
Closing since we implemented corresponence seeks and we have no plan for real time seeks for now.
