### ISSUE TITLE
Cannot slide down on analysis screen (Android)

### ISSUE THREAD

**Issue by alexvanacker** [veloce/lichobile#966]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**
When going into analysis mode (on ongoing or done game), I am unable to slide down the moves list (or down to see time per moves once computer analysis is done)

**Expected behavior:**

When sliding down with my finger, I should be able to slide down to the latter/earlier moves of the game.

**Steps to reproduce:**

See current behavior.

**Environment information**

- Lichess version: v6.1.1
- phone hardware: Huawei P10
- phone operating system version: 
  -Android version 8.0.0
  - Build number VTR-L09 8.0.0.365(C530)
 - Kernel version 4.4.23+

**Other information:**

Sliding left or right to switch tabs in analysis mode works.

**Comment by fredericcarron** [comment]
Hello,
I have exactly the same issue since a few days. 

**Environment information**
* Lichess version: v6.1.1
* Phone hardware: Samsung S9
* Phone operating system version:
     * Android version 9
     * Kernel version 4.9.59-15367606
* Chrome 73.03683.90

**Comment by rmehulsoni** [comment]
I also have the same issue Please solve this problem to the earliest..... As I am not able to scroll down and analyse my games....!

**Comment by alexvanacker** [comment]
Fixed in v6.1.2, could not find the issue though on github, but good job anyway!
