### ISSUE TITLE
Scrolling problem in lichess android app. 

### ISSUE THREAD

**Issue by rmehulsoni** [veloce/lichobile#967]
**I'm submitting a ...**  (keep the relevant one):
- bug report
- feature request

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

# Feature request

**Comment by freefal** [comment]
Chrome changed its behavior We're working on a fix.
