### ISSUE TITLE
Opponent's time runs out. I lose. 

### ISSUE THREAD

**Issue by fractionofadot** [veloce/lichobile#968]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**
Often, I will be playing a game and waiting for my opponent to move. There is no indication of any network issues: the moving dots do not appear and everything seems normal. But it turns out that the server believes it is my turn to move and the app has not received the message.

An example game: 
https://lichess.org/0dlO9L3TKLd4

I waited for my opponent to move until their time ran out. I showed as connected with no network problems.  In the end, it was I who lost on time, and had no idea. 

![Screenshot_20190326-161839](https://user-images.githubusercontent.com/12238732/55040391-64472500-4fe5-11e9-92ef-331ec48a6c35.png)

This has happened more often than I (or anyone except the benefactor) would like ;D

**Expected behavior:**

If there are any issues with sending or receiving a move from lichess servers, the app should indicate that there is a problem and not behave as if everything is normal. The servers and app should do a check to make sure the app received/sent the latest moves.

**Steps to reproduce:**

This may be tough to reproduce. It may involve temporarily disconnecting from a network at certain points during, between, or after moving. 

**Environment information**

- phone hardware:  
Pixel 3
- phone operating system version: 
Android Pie
- version of lichess mobile:
v6.1.1

**Other information:**

**Comment by wsobasik** [comment]
Re: there is one:
[https://github.com/veloce/lichobile/issues/936]

**Comment by fractionofadot** [comment]
Similar but is a very different behavior than I have described above (but I wouldn't be surprised if it was related).

- Issue 936 describes that your own time continues to decrease after you have moved. 
- This issue (968) describes a problem where you move and everything seems normal. The problem is that you never receive your opponents move, and so it appears your opponent allows their clock to run down while you wait for them to move. 

These are quite different symptoms.

**Comment by ornicar** [comment]
I think that's a serverside issue.
