### ISSUE TITLE
App not loading from server 

### ISSUE THREAD

**Issue by v-tan** [veloce/lichobile#969]
I'm submitting a bug report.

# Bug report

**Current behavior:**

I tried to build the app after cloning it, using 'npm run android-stage'. I followed the steps suggested before building the app but it still doesn't work.
When the App opens and traverses to the second screen after the splash screen, nothing loads into the app. A single progress bar begins to show and never disappears.

**Expected behavior:**

The app must load the games on the server, no. of users playing, no.of games online, just like the production release app of lichess which we download from Google Play Store.

**Steps to reproduce:**

1. clone the lichess app project onto the system
2. do 'npm install' 
3. add android platform to the cordova app using 'cordova platform add android'
4. build the project using 'cordova build android' and resolve issues regarding build if any.
5. run 'npm run android-stage' 
6. The app builds successfully and runs. After the splash screen, the game screen doesn't load anything and the progress bar keeps on rotating.

**Environment information**

- phone hardware - ASUS Zenfone Max Pro M1, CPU - Qualcomm SDM636, octa core, adreno GPU, SoC - aarch64
- phone operating system version - Android 8.1.0 (Oreo)
- the version of lichess mobile - v6.1.2

**Other information:**

**Comment by freefal** [comment]
Edit env-stage.json to point at lichess.org instead of listage.ovh and rebuild.

**Comment by v-tan** [comment]
Thanks. Its working now.
