### ISSUE TITLE
Feature: Flip pieces in play with friends mode

### ISSUE THREAD

**Issue by arjuntemurnikar** [veloce/lichobile#97]
First off congrats on the release!! :+1: 

I think that the "play offline with a friend" mode is not ideal.

**Why:**
When it is my turn, the upside down opponent pieces really confuse me. I am not able to analyse positions clearly, and its really very odd when playing (for both sides)

**What I propose:**
On change of turn, flip the pieces.

For example, if it is my turn, all pieces face me. When I make a move, all pieces flip 180 degrees so my friend can then see the whole board normally.

**Pros:**
* Less confusion when seeing the board

**Cons:**
* Only useful if playing with ponder=off (i.e. you only think on your turn, not your opponent's turn) as that is when you see the board.

**Some additional points:**
* So when you start the game, the board will be setup normally (as any other lichess game). The pieces will all face the bottom of the screen with white at the bottom. So if you want to be white, you sit with the bottom of the screen facing you. As soon as you make a move, the pieces flip so your friend who is black can then make a move.
* Since everybody may not prefer this approach, it can be set as a setting option... perhaps named something like "flip pieces on turn change".

**Comment by arjuntemurnikar** [comment]
you are awesome

**Comment by ornicar** [comment]
no u
