### ISSUE TITLE
Player information does not flip with the board

### ISSUE THREAD

**Issue by mattbruv** [veloce/lichobile#970]
# Bug report

**Current behavior:**

Flipping the board view does not flip the player's information along with their pieces (name/rating/time remaining). It only flips the pieces. 

**Expected behavior:**

Flipping the board view should flip the player's information so that it will always be shown with the correct perspective.

**Steps to reproduce:**

1. Watch any game in progress
2. Flip the board view
3. Observe that the player's information does not stay with their pieces, but rather stays in place.

**Environment information**

- phone hardware - Not relevant
- phone operating system version - Not relevant
- version of lichess mobile - <= v6.1.2

**Other information:**

**Comment by landry314** [comment]
Yes, absolutely. This is quite annoying.

**Comment by jas14** [comment]
fwiw this is not the case on TV, only watching specific players/games

**Comment by mcu2018** [comment]
Yes this issue still persist.Please resolve it.

Anil
