### ISSUE TITLE
Add the missing piece set "Kosal" which is present on lichess.org

### ISSUE THREAD

**Issue by mattbruv** [veloce/lichobile#974]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**

The [Kosal piece set](https://github.com/ornicar/lila/tree/master/public/piece/kosal) is missing from the mobile app.

**Expected behavior:**

Kosal pieces should be present on the mobile app to keep continuity between lichess.org and lichess.org mobile.

**Steps to reproduce:**

Open the mobile app, change your pieces, and become frustrated that the best piece set isn't on the mobile version.

**Environment information**

- phone hardware: N/A
- phone operating system version: N/A
- version of lichess mobile: <= v6.1.2

**Comment by gbtami** [comment]
I'v created https://github.com/veloce/lichobile/pull/918 to add Leipzig. You can do it with Kosal yourself following that.
