### ISSUE TITLE
Ideas for puzzles

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#98]
In addition to the features of desktop puzzle, here are some ideas for mobile specific usage:

* possibility to download batch of puzzles and then play them offline
* notify daily puzzle (push notification on demand?)
* ...

**Comment by alanmonger** [comment]
👍 would like to just see puzzles make it into the mobile app

**Comment by Suitecake** [comment]
I'd very much like to see this feature as well. 

I don't have much experience with JS or mobile development, but would be happy to learn and contribute!

**Comment by arex1337** [comment]
I want to announce my support for adding tactics/puzzles to the mobile app. I think it is the most important part that is currently missing from the mobile app. I think it is the most important change we could make to get more users interested in the mobile app - both existing lichess users, but more importantly users of other chess apps and websites. I have also seen many comments on lichess.org requesting this feature.

**Comment by veloce** [comment]
Totally agree. This is the next feature planned. The dev has been started by @ornicar , we can try to release a first simple version with offline puzzles only (and maybe the puzzle of the day)

**Comment by veloce** [comment]
[This](https://github.com/phonegap/phonegap-plugin-contentsync) could be used to download batches of puzzles.

**Comment by veloce** [comment]
Todo:

- [ ] new puzzle button always present
- [ ] list of played puzzles when connected
- [ ] long tap handlers for history buttons

**Comment by veloce** [comment]
Not implementing vote for now. Played puzzle has been dropped in favour of sharing puzzle.
