### ISSUE TITLE
Puzzle sequence restarts in mobile app

### ISSUE THREAD

**Issue by techwinder** [veloce/lichobile#981]
**I'm submitting a ...**  bug report

# Bug report

**Current behavior:** After completing a series of puzzles in the desktop app and then switching to Training in the mobile app, the desktop puzzles are forgotten and the series restarts at the last completed puzzle in the mobile app.

**Expected behavior:** When switching to the mobile app, the series of puzzles should continue from where it was left off in the desktop app.

**Steps to reproduce:** As explained above

**Environment information**

- phone hardware : OnePlus 5T
- phone operating system version :  Android 9
- version of lichess mobile : 6.1.2

**Other information:**
- lichess is great

**Comment by veloce** [comment]
This is more a server issue, sorry. You can mitigate this issue by pressing the "refresh" button which will clear offline cache and request another batch of puzzles.
