### ISSUE TITLE
Support timed offline games

### ISSUE THREAD

**Issue by tobiasvl** [veloce/lichobile#99]
It would be great if offline games had the option to have a clock, so you don't have to have a separate clock (or even a separate smartphone with a chess clock app). It should probably have a pause button.

**Comment by garawaa** [comment]
It s good idea. Then upper side players clock should be flipped in over the board game.

**Comment by wei2912** [comment]
Any updates on this issue? I think it's a crucial feature that needs to be added to the app, as nearly all other chess apps allow for OTB timed games.

**Comment by arex1337** [comment]
+1 for this. 

> [22:12]
> i have realized that playing "OTB" on the lichess app is much better than playing OTB with a real board and pieces
> 
> [22:13]  
> it's much more convenient to carry and play on a phone, or preferably a tablet
> 
> [22:15]  
> i played on my tablet with some colleagues the other night, and it was awesome to be able to share the PGN by email with colleagues (and to import it to a study on lichess) (edited)
> 
> [22:18]  
> two things that could be better: 1) we used the lichess app clock functionality on a separate phone. a built-in clock in OTB mode would require 1 less device. we wouldn't have to hit the clock after we move. clock information could also be exported with the game in the future.

**Comment by freefal** [comment]
https://github.com/veloce/lichobile/pull/665
