### ISSUE TITLE
Not option Rapid un advance search

### ISSUE THREAD

**Issue by Tinotin366** [veloce/lichobile#996]
**I'm submitting a 
- bug report

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Aquaris 4.5
- Android 5.0
- 06-06-2019

**Other information:**

# Feature request

**Comment by freefal** [comment]
Thanks for reporting. This pull request (https://github.com/veloce/lichobile/pull/999) should add options for both rapid and ultrabullet.
